### ISSUE TITLE
Error importing survey

### ISSUE THREAD

**Issue by jlopezsi** [ccbogel/QualCoder#100]
I foudn this error trying to imort a survey in csv format in an Ubuntu 16.04 laptop. The same problem with osx 10.14.6:

Traceback (most recent call last):
  File "/usr/share/qualcoder/qualcoder.py", line 572, in import_survey
    ui = DialogImportSurvey(self.app, self.ui.textEdit)

  File "/usr/share/qualcoder/import_survey.py", line 110, in __init__
    self.get_csv_file()

  File "/usr/share/qualcoder/import_survey.py", line 200, in get_csv_file
    set_of_values.add(self.data[row][field])

IndexError: list index out of range

**Comment by ccbogel** [comment]
OK. This can be due to the csv file format.
The problem may be that the quotation format needs to be changed to a different one: ALL , MINIMAL or NONE
Try different formats first and let me know.

If still a problem then:
Are you able to open the csv in a text editor and post the first few rows exactly as appears?
Then I could advise on what to do next.

**Comment by jlopezsi** [comment]
Colin,
After modifying the spreadsheet according to the error messages, I finally
could import the survey. However, it imports it as attributes. In the
survey, I have four open questions with text and 5 closed questions
(factors). I wanted to code the open questions and then explore
differences according to the closed factors (social properties of
individuals).
Is normal this behavior? Could it be possible to use python packages for
reading directly excel files or libreoffice, google sheets, etc.? I've been
looking around and it seems that xlrd package or pandas can do it. I do not
python language so maybe I am saying a nonsense suggestion.
Regards,

*------------------------------------------------------------*

*Jordi López-Sintas, PhD <https://jlopezsi.netlify.com>*
*Catedràtic d'universitat, Comercializació i investigació de mercats (full
professor of marketing and consumer research)**, *Department
d'Empresa, Universitat Autónoma
de Barcelona <http://www.uab.cat>, Spain.

President d'Espacual <https://www.espacual.es>, Asociación Española para el
Avance de la Investigación Cualitativa (2016-2022)

**Comment by ccbogel** [comment]
Hello Jordi,
I did not know about the xlrd package. I can investigate it later to make use of it in QualCoder.
It is good you were able to import. But you said all were as attributes. 
Before pressing the import button, make sure that the qualitative columns are marked 'qualitative'
To do this - right click on the Header section for the column name , and choose 'Change to Qualitative' (see picture).
This will then load the column data into a file - have a look in Manage Files to see it there.
![pic1](https://user-images.githubusercontent.com/5834638/87036762-a625ca00-c22e-11ea-890c-11a4cde54f31.png)

**Comment by ccbogel** [comment]
Hello. I have updated the import survey function - to allow import of Excel.xlsx format documents.
Perhaps test on your machine with a new project. Works OK on Ubuntu,
You must install the openpyxl module
`sudo python3 -m pip install openpyxl`
or
python -m install openpyxl'

**Comment by jlopezsi** [comment]
It works like a charm, perfect. I tried it on OSX 10.14.6. Thanks a lot. I
really appreciate your effort.
Thanks again.
Jordi


*------------------------------------------------------------*

*Jordi López-Sintas, PhD <https://jlopezsi.netlify.com>*
*Catedràtic d'universitat, Comercializació i investigació de mercats (full
professor of marketing and consumer research)**, *Department
d'Empresa, Universitat Autónoma
de Barcelona <http://www.uab.cat>, Spain.

President d'Espacual <https://www.espacual.es>, Asociación Española para el
Avance de la Investigación Cualitativa (2016-2022)
