### ISSUE TITLE
'Coded:' shows one of several codes

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#104]
'Coded:' in Codes displays one of the codes used for the selected text. I am guessing it is the most recently applied code and probably the code to be removed if I unmark that text. That's possibly a holding position, but I am saying, just in case.

**Comment by ccbogel** [comment]
Yes clicking on a coded section of text shows the code at that position.
Yes it would show the overlapped ( last applied) code. I guess I should change this.

**Comment by glocalglocal** [comment]
And showing the colours would also help.

**Comment by ccbogel** [comment]
OK, for now it shows the colour of the last applied code, but it now also shows all the code names in a list. But this may be a problem with not enough space in the label to show all of the wording.

**Comment by ccbogel** [comment]
I hope this sufficently resolves the issue

**Comment by glocalglocal** [comment]
Wouldn't adding a column to the tree dynamically showing with an arrow 
or something the codes applied be easier and solve the space problem? 
Another indicator around there could show the selected code too.

The only limitation I see is that with a super-long tree, an indicator 
showing the second, third etc code applied could be off the screen.

**Comment by ccbogel** [comment]
hmm, not sure about this approach. as if the categories are not expanded you would not see an arrow, and yes, wit ha lot of codes and catgories, some would be off screen.

**Comment by glocalglocal** [comment]
The two methods could co-exist but I don't see how any number of codes with names of any length can be added above the text. An alternative would be an additional pane where codes applied can also be selected for unmarking. Select/unmark can also be done with the tree-based approach I described earlier.

**Comment by ccbogel** [comment]
An alternative would be an additional pane where codes applied can also be selected for unmarking. <= This has been done - if you  you try it - overlap some codes - then try to unmark - you will get a selection pane.

**Comment by glocalglocal** [comment]
I meant a third pane dynamically showing applied codes and offering the option to unmark. The idea is that a coder needs to see applied codes dynamically (hence the tree indicators I suggested earlier).
