### ISSUE TITLE
Reports by selected file and/or project 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#105]
Mindful of mission creep, I am now making the final few, more eclectic suggestions. 

How about generating reports (graph, frequencies etc) by file, selected files and for the whole project? The frequencies has plenty of space to show that. 

I will attempt to import a more substantial project from NVivo. Fingers crossed. I don't know what to expect!

**Comment by ccbogel** [comment]
I might have to get a lot more detail on what is wanted here. Mission creep is OK-ish :) 
However I have decided for the time being to avoid: statistical analysis and text mining.
OK trying the REFI-QDA import - this is really experimental and a challenge to implement. Let me know.

**Comment by glocalglocal** [comment]
The Code Frequencies report could be seamlessly incorporated into the Coding Reports. In the left pane, there could be a column for frequencies per code for the project and another dynamic column for the current file/case/attribute selection. Then, there would be an additional set of buttons for exporting frequencies (or, better, a tick box for export Codings OR Frequencies). Also, as I suggested earlier, the freqs per code could be shown in the Code Text dialogue as an additional column next to the memo column. 

To be honest, I am not sure what View Graph does that Coding Reports doesn't already. The fancy graph is less useful than the tree anyway, esp with lots of codes. 

There -- the opposite of mission creep. Two menu options less. :)

I am not all that keen on statistical analysis either. 'Code and retrieve' done well and reliably is far more important to me at the moment.

**Comment by ccbogel** [comment]
Some people like the graph, I'm also a bit fond of it, so will keep it.
I will keep the frequencies report separate for now - as its already there. I should be able to add a file selector to this.

**Comment by glocalglocal** [comment]
You mean, the freq dialogue could be freqs overall and by coder, for project, file or case (or attribute?). 

I can't help thinking Coding Reports has all this already except the single column for the specific selection (as opposed to the current overall freq) which IMV is missing anyway.

**Comment by ccbogel** [comment]
You mean, the freq dialogue could be freqs overall and by coder, for project, file -  Yes here.
I make use of the tree with the extra columns for each coder - as I can draw from this easily to export files, as well as to view the counts. So these are some reasons why I prefer to keep this separate.

**Comment by ccbogel** [comment]
I think I have covered this. So will close the issue. Create a new one if there is something specific required.
