### ISSUE TITLE
Applying codes: Select text first and then code

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#107]
After some coding I think it is very awkward having to select the code from the tree and then highlight text to apply the code. It disrupts the workflow because then you find something else to code, usually by a different code, and you have to take your eyes off the text, go to the tree first to switch to another code, and then return to your text. The intuitive and common way is to highlight text as you read and then click on the code, which immediately applies the coding. The two methods can co-exist of course.

**Comment by ccbogel** [comment]
good point - I will look at trying to implement this.

**Comment by ccbogel** [comment]
Done. Select the text, then right-click over a code and select the _Assign selected text_ option in the menu - it will be the first option.

**Comment by glocalglocal** [comment]
That's good but out of interest, why right-click + click on the menu instead of just left-click? If I select text and then left-click on a code, what else would you expect or want to happen? Left- and right-click could co-exist of course. 

Also, when you open Code Text and before you select a code, the 'Mark' option on the context menu (when you select text) shouldn't be available. That would make the 'No code was selected' message redundant. 

The tool tip in the tree shows a date and my system ID. Not sure why or what date that is.

**Comment by ccbogel** [comment]
The right click method was easy to implement. Will consider the left click approach.
OK fixed the Mark issue, will upload the fixed file soon.
OK so the tooltip is not useful - it was the codername and date of when the code was created. I could instead add the memo to the tooltip or have none.

**Comment by ccbogel** [comment]
OK left click to assign selected text to a code is now possible

**Comment by glocalglocal** [comment]
I am now getting the error below and I can't go further:

2020/07/11 02:07:22 ERROR __main__.exception_handler Uncaught exception : Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1015, in <module>
    gui()

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1010, in gui
    ex.open_project(path=project_path)

  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 900, in open_project
    shutil.copytree(self.app.project_path, backup)

  File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,

  File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 510, in _copytree
    raise Error(errors)

Error: ...
]

Followed by the path to a document with a very-very long name (172 characters + path) and [Errno 2]. It's the only filename with such a long name.

**Comment by ccbogel** [comment]
Can you put this in a separate issue and explain what happened before this occurred.
To temporarily get around it - suggest turning backups off, as I suspect it is trying to make a backup (ie the copytree business).
You can also edit the .qualcoder/config.ini document, this line :
backup_on_open = False

**Comment by glocalglocal** [comment]
I am creating a separate issue for this.
