### ISSUE TITLE
Add mkv support?

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#11]
My virtualbox died due to some conflict with a kernel update...and I can't use my main machine for testing, so for now I am unable to tinker more with QualCoder.

On the website I noticed this "wav, mp3, mov, mp4, ogg, wmv" though, and I would recommend to support mkv format too.

It is a popular format, it is open and VLC plays it, hence it makes sense to have it supported.

**Comment by ccbogel** [comment]
Thanks for the advice re mkv, I can easily do that. I have begun looking at how to create a flatpak, but I have to admit that it is not that easy to do. First I might try and make a .deb instillation file. I hope you get Lubuntu up an running again soon.

**Comment by WPFilmmaker** [comment]
Thanks!

About .deb file it seems like a good compromise at the least short term (flatpak has the cool characteristic of being distro-agnostic). Until you have different users asking for different packages for different distros I think .deb can do as mint/debian/*buntu use it.

Once you feel QualCoder is stable enough I recommend to get into debian/ubuntu repos, users will get an older version but at the least you can spread around that it exist. AFAIK volounteers just keep packaging new versions, so if there is demand someone will do the job.

**Comment by ccbogel** [comment]
Yes I will investigate adding QualCoder to the Debian and ubuntu repositories. I will close this issue re mkv files as I have loaded and tested an mkv file and it works fine.
