### ISSUE TITLE
coe dialogs

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#112]
restrict to one code dialog at a time.

**Comment by glocalglocal** [comment]
If multiple Code Frequencies, View Graph dialogues from different projects are allowed to be open, the title bar should state the project name.

**Comment by ccbogel** [comment]
No - I would never have multiple projects open at once.

**Comment by glocalglocal** [comment]
So, it's not just code dialogues. At the moment, I can have any number of Code Text, Code Frequencies, View Graph dialogues from different projects open at the same time.

**Comment by ccbogel** [comment]
all those dialogs can be open at the same time. But only within one project.

**Comment by glocalglocal** [comment]
Being able to code two or more texts within the same project could actually be useful and a USP for qualcoder afaik. But that means the 'Code Text' (not the confusing confusing 'Codes') title bar should also display the filename. Similarly, Graph Visuals could show All or selected coding category on the title bar. I must say these windows look very nice with Windows Peek.

**Comment by ccbogel** [comment]
Ok. Will implement the title bar changes. 
What is Windows Peek?

**Comment by glocalglocal** [comment]
Windows Peek is the thumbnail task preview you get when the mouse pointer hovers over the taskbar. Eg [https://www.tenforums.com/tutorials/47266-turn-off-peek-desktop-windows-10-a.html](url)

**Comment by ccbogel** [comment]
Ok thanks. I have a Windows machine,  for work and for testing of this software,  but its not my development or nsin use machine.
