### ISSUE TITLE
Code order in tree and codings report

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#113]
I believe the tree shows codes in the order they were created, which is also used for codings reports. There should be a way for the user to specify a specific order (ideally) or at least get alphabetical sorting within a tree branch. This is important because research design may assume code creation as coding progresses.

**Comment by ccbogel** [comment]
Yes this issue has crossed my mind in the past. Will add it TODO.

**Comment by ccbogel** [comment]
ordered alphabetically

**Comment by glocalglocal** [comment]
Code Text works well, thanks. The codings report doesn't yet work alphabetically.

**Comment by ccbogel** [comment]
It works in coding reports for me - except for the code frequencies report.

**Comment by glocalglocal** [comment]
You right. It works in code text and codings report, but not in the code freqs report. 

Code frequencies still shows IDs although the setting is off. Also, the code labels in the tree are clickable (which changes their colour) for no reason.
