### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#117]
I started the application, I immediately got the error below and had to exit. I bypassed the problem by turning off backups in the .ini file as you suggested. 

2020/07/11 02:07:22 ERROR main.exception_handler Uncaught exception : Traceback (most recent call last):
File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1015, in
gui()

File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1010, in gui
ex.open_project(path=project_path)

File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 900, in open_project
shutil.copytree(self.app.project_path, backup)

File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 554, in copytree
return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,

File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 510, in _copytree
raise Error(errors)

Error: ...
]

Followed by the path to a document with a very-very long name (172 characters + path) and [Errno 2]. It's the only filename with such a long name.

Filename and path were probably over 256 characters long. It was related to the import but the filename was meaningful, given by me. The long "_BACKUP_2020-07-11_02-07-21.qda\documents" in the path made things worse. I should perhaps be able to change the imported filename before qualcoder falls over.

**Comment by ccbogel** [comment]
OK I have shortened the backup suffix now to _BKUP_yyyymmdd_hh.qda
Curious to know what the long name was. It happend as a part of the RQFI-QDA import didnt it.

**Comment by glocalglocal** [comment]
I don't see that. I downloaded the latest update, switched on backups, edit something, closed project, re-open project. The backup was created with the same suffix as before. Not sure why. 

But it didn't freeze even though the files and path are the same as before. Maybe it was not the filename after all? Maybe it only freezes on first run after import, which will make the error more difficult to catch. 

Yes, it was an RQFI-QDA imported project. 

The filename was "Deloitte follow-up proposing software business consultancy [WAC R103-121-2 Microcomputer Software Policy [Deloitte follow-up Proposal for consultancy assistance-Mar86].pdf.txt"

I see now .txt is appended to all filenames, making them longer but I see why pdf.txt is useful. An application can't possibly deal with an unlimited number of characters in path+filename, but somehow it must handle the situation.

**Comment by ccbogel** [comment]
yes. Im not sure how to deal with this issue at the moment.However, that was a really long file name.

**Comment by ccbogel** [comment]
As this seemed to be a one off. Should I close this issue?

**Comment by glocalglocal** [comment]
It won't happen often but if someone uses a really long filename it may come up again. I don't know. Perhaps you can close it for now but I may intentionally push it and see what happens. If there is an issue, ideally, qualcoder would truncate the filename.

**Comment by glocalglocal** [comment]
I imported a .docx with a 256-char filename inc extension. It imported OK, I exited and re-started qualcoder OK. But the filename saved in the documents\ folder was shortened to 210 chars without a warning. No crashes.

**Comment by ccbogel** [comment]
ok thats interesting. if your ran a sql query in the sql dialog, I wonder if it stored the original or shortened name.

select name from source

**Comment by glocalglocal** [comment]
The shortened name is stored.

**Comment by ccbogel** [comment]
ok thats works ok then. I have not put any code in to shorten the name , its something that has happened via windows os or python.

**Comment by glocalglocal** [comment]
It may be the 260 chars default max path length in Windows 10. If that's the case, qualcoder could at least compare length before/after (as stored in sql) and warn the user if there is discrepancy. 

It's extremely unlikely that people would use such a long filename in other circumstances, but in coding docs it's more likely because a filename may contain archive titles, numbers, dates etc. That's how it happened to me anyway. In hindsight, I could have used look-up tables but a descriptive filename is still more efficient.
