### ISSUE TITLE
Sorting files

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#118]
In Code text | View file, the files could be sorted alphabetically. Not sure if other kinds of sorting there would be useful. 

But in Manage Files, sorting by different columns would help (eg date or user-specified attributes). The headings behave as being clickable already.

**Comment by ccbogel** [comment]
code text - view files is now alphabetical.

**Comment by ccbogel** [comment]
done

**Comment by glocalglocal** [comment]
'Coding reports' | File selection doesn't offer alphabetical or other sorting though. 

While I am at it, I open a file in Coding reports, click File Select but then cancel. The file that was earlier open is now closed. Nothing should have changed though.

**Comment by glocalglocal** [comment]
In addition to above, Cases | Add File doesn't do alphabetical sorting.

**Comment by ccbogel** [comment]
'Coding reports' | File selection doesn't offer alphabetical or other sorting though. - Alphabetical now forfile and case selection.
I dont understand this - separate issue, but with more detail please.

**Comment by glocalglocal** [comment]
'I open a file in Coding reports...' - I can't reproduce this either. Sorry.
