### ISSUE TITLE
Search in Code Text

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#119]
Search in Code Text doesn't work anymore. Also, the 'Case' tickbox can be confused with coding cases. I think it should 'Case sensitive'. 

Also the tooltip for 'Case' is 'search case sensitive' but the search input field also has a tooltip 'Case sensitive search'. 

The '0/0' button could be split in the usual '<', '>', x of y match (like in Firefox etc). 

All this applies to Coding reports, I think.

**Comment by ccbogel** [comment]
I made an error with the search text during the week. the latest version fixed that (earlier today).
Case sensitive - yes OK
input tooltip - thanks will fix - (legacy stuff that I had forgotten)
Im happy with the 0/0, prefer not to use words like 'of' Are you saying  I should add '<' and '>' to move forward and backward?

**Comment by glocalglocal** [comment]
I don't like 'of' either :). Yes, I meant forward/backward. 'Whole words' is another possibility.

**Comment by ccbogel** [comment]
ok some of this is updated, slight change to the layout of the dialog now.
The > and < will do later.

**Comment by glocalglocal** [comment]
This works well now.

**Comment by glocalglocal** [comment]
Spoke too soon. When you search, get to say, '3/6' and then open another file through View File, the counter should become 0/new_y (ie as if you just entered the search word but haven't clicked on Search yet).  Currently, it still shows '3/6'. 

And of course an X to delete the search word, enter to initiate and possibly continue search, and a search history would be good for that polish.

**Comment by ccbogel** [comment]
fixed the file change. No need for X , simply delete the word in the lineedit. there are now forward and back buttons to search.
Search History would be hard to imlement - not understanding exactly what you want here.

**Comment by glocalglocal** [comment]
The X and Search History are not essential really. Basically part of the polish and using conventions users recognise immediately. Search History simply remembers previous queries in a pull-down menu so that you don't have to retype them (and possibly get them wrong). 

Similarly, enter typically works as 'next match' and shift+enter as 'previous match'.
