### ISSUE TITLE
Documents, Files, Texts

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#120]
It seems to me that Documents include linked files (as when imported from NVivo) but other texts are only embedded in the .qda file (as when imported from RQDA). I have a project with a few texts and no files in the Documents folder. But then Manage Files and View File treat all these texts (embedded or linked) the same way, and they are not always 'files'. Perhaps, this situation should be clarified and terminology should reflect the distinction.

**Comment by ccbogel** [comment]
OK - so Documents is meant to include all original text import files. But RQDA has the text only stored within the sqlite database. So I can export a copy of this sqlite stored text as a text file in the Documents folder.

The Documents folder is really to keep a back up of original files. As you never know when that may be important to review the originals.
The audio/video/images folders are more important as qualcoder draws from them regularly when doing coding or viewing.

**Comment by ccbogel** [comment]
when importing rqda, save database text as text files in /documents
