### ISSUE TITLE
Manage Files unavailable 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#122]
I open Manage Files and before I click on a file I click on View. The first file is automatically opened. This may be intentional. 

But if I select any file, even the first one, close Manage Files (or even open the file and then close the dialogue) and then select Manage Files again, the dialogue won't open. To make Manage Files available again, I select Manage Cases, select a case, and then go back to Manage Files.

**Comment by ccbogel** [comment]
But if I select any file, even the first one, close Manage Files (or even open the file and then close the dialogue) and then select Manage Files again, the dialogue won't open. To make Manage Files available again, I select Manage Cases, select a case, and then go back to Manage Files.
Yes - this is an issue I have never been able to resolve. the only solution is to open something different and then got back to opening the dialog again.

**Comment by ccbogel** [comment]
ok on further investigation I believe I have fixed this issue.

**Comment by glocalglocal** [comment]
Looks fine here too.
