### ISSUE TITLE
problem with import survey

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#123]
hello !

I import a survey with option Files and case > import survey. I change the characteristic of the colomn, change qualitative to attribute. But, when i look case, the changement is not considered and the importation in same than default values...

Cheers

**Comment by qwertygc** [comment]
OK i have imported with none = error (of course). Delete all case. I have reimport and it's work. May be create architecture of table (empty) before import survey ?

**Comment by qwertygc** [comment]
OK the problem is t put in minimal not in none....

**Comment by ccbogel** [comment]
@qwertygc Are you using the Debian or using the newer qualcoder files from here?
If downloading qualcoder and using the newer files from here, you can import from Excel.
But: you need to install an extra python module:
Linux:
sudo python3 -m pip install openpyxl
Windows:
python -m pip install openpyxl

**Comment by qwertygc** [comment]
I use the .deb.

Oh good feature. We can also import Libreoffice files (.ods) ?

**Comment by ccbogel** [comment]
At the moment only Excel (but you can save ods as Excel)
This feature is not in the Deb. 
I will make another later after the other issues raise here are fixed.
