### ISSUE TITLE
Meta: Consider unit tests 

### ISSUE THREAD

**Issue by jdittrich** [ccbogel/QualCoder#124]
**Story:** As a programmer, I want to know if changes I make to the code do not cause new bugs. 

**Possible Solution:** Consider using a testing library like the python-included [unittest](https://docs.python.org/3/library/unittest.html)

**Comment by ccbogel** [comment]
I am not that familiar with unit tests, but will look in to it. I am not sure how they will work with a lot of Qt objects.

**Comment by jdittrich** [comment]
Some things can be tested by disentangling them from GUI code, for what remains there are PyQT helpers like QTest, which simulates user interactions, so you can check if the results of said interactions are as expected – [tutorial here](http://johnnado.com/pyqt-qtest-example/)

**Comment by ccbogel** [comment]
@jdittrich  I started looking at unittests today.
I have to say I dont really know where or how to start. 
http://johnnado.com/pyqt-qtest-example/
https://www.jetbrains.com/pycharm/guide/tutorials/visual_pytest/hello_test/
https://confluence.jetbrains.com/display/PYH/Creating%20and%20running%20a%20Python%20unit%20test

**Comment by jdittrich** [comment]
I would suggest to start with pythons own unittest and not test the UIs yet. It seems unittest is recognized by pycharm, too – inferring from [pycharm’s documentation on testing](https://www.jetbrains.com/help/pycharm/creating-run-debug-configuration-for-tests.html). 

I am not an expert in python, but it seems that this tutorial is a  [nice intro to unittest](https://www.youtube.com/watch?v=6tNS--WetLI).

The functions and classes in the [qualcoder-folder of the repo](https://github.com/ccbogel/QualCoder/tree/master/qualcoder) will probably a good place to start: When you change something there, try to create a test for the parts of the code you refactor, so you can check if your changes did not break anything. 

Feel free to poke me here or via mail if I can help.
