### ISSUE TITLE
Project properties and rename

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#125]
As there is no 'Save as', there is no way to rename the project without using the file manager. 

Perhaps adding Project Properties could allow renaming and that would also show vital stats (eg number of codes, number of files by type, sizes, saved location, coder names, creation date etc).

**Comment by ccbogel** [comment]
I am ok with renaming a project using the OS file manager. I dont see the need to do this internally via the software.
Yes perhaps show these: number of codes, number of files by type, sizes, saved location, coder names, creation date on opening a project. Qualcoder now presents this information on opening a project.

**Comment by glocalglocal** [comment]
To get this info updated we would then have to close and reopen the project. I think it should be made clear that that is a snapshot. Keeping qualcoder open for days means the info can be very stale.

**Comment by ccbogel** [comment]
I normally close everything at the end of the day and turn off the computers. I dont think it would be a big deal to close and reopen - or would you prefer a File menu option that gives an update?

**Comment by glocalglocal** [comment]
An update option would be good. And date/time stamps for every batch update (eg settings at start-up) in the log that is displayed in the main window would help with possible confusion.

**Comment by ccbogel** [comment]
working on this and the recent project menu as we converse
