### ISSUE TITLE
Manage Files dialogue (memo + multiselect)

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#126]
In Manage Files, clicking in a memo cell switches on 'Yes' even if I never add a memo. No way to remove that Yes once set.

It would be good to be able to select multiple files for Delete, Export, Add Attribute (not sure about the rest of the actions). 

I would expect double-clicking a file to open it for viewing.

**Comment by ccbogel** [comment]
This does not occur for me ?? (either in Windows or Ubuntu). Is the memo completely blank - no text, no spaces?

I have changed 'yes 'to 'Memo'

I have enacted single click on the name to open.

Not sure about the multiple files selection in the table.

**Comment by glocalglocal** [comment]
single click instead of double-click: how can you then select a file and then click on Export / Delete / Add Attribute? 

'Not sure about the multiple files selection in the table.' Do you mean I wasn't clear? I mean with multiple files selection you could delete /export / add attributes to several files at once.

**Comment by ccbogel** [comment]
ok made viewing with double click.
i wasnt sure about implementing multiple row selection in the table. but will consider it.

**Comment by ccbogel** [comment]
multi slect done
