### ISSUE TITLE
Manage cases

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#127]
I add one file to a case. Nothing seems to happen -- the right pane remains blank. The file was actually added because when I try again, qualcoder tells me it was added already. 

It would be good to be able to select multiple files for adding to a case. Also, a column with number of added files next to the memo column in the left pane would be useful, particularly when wondering if I have added a file. 

Clicking in a memo cell and not entering text switches on Yes for that memo and that Yes can't be deleted. 

EDIT: Clicking View Case reveals the texts. I think simply selecting a case should work as View Case.

**Comment by jdittrich** [comment]
Would probably make sense to split this up in three tickets: 
1. Adding already added file to case should give user feedback
2. Select multiple files to be added to case

As for the 3rd one I am not sure that there is an immediate fix. I wonder if the "yes" is actually helpful but should rather be 
"add Memo"-Button (no memo present), "edit memo"-button in case there is a memo, while deleting the memo could be a button in the modal memo window that comes up when the memo is edited.

**Comment by glocalglocal** [comment]
You are right about splitting the ticket. There are just too many tickets and it's tempting to bundle them by area. I'll try to split them. 

I agree that Yes is not very useful.

**Comment by ccbogel** [comment]
this issue - change from Yes to the word Memo - try not to add buttons in the table as its extra complexity
