### ISSUE TITLE
Manage cases -- adding files

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#128]
I add one file to a case. Nothing seems to happen -- the right pane remains blank. The file was actually added because when I try again, qualcoder tells me it was added already.

Then I realised that clicking on View Case reveals the texts for the selected case. I think simply selecting a case could work as View Case. A column could show how many files were added and/or a drop-down menu per case showing the titles of files added.

**Comment by ccbogel** [comment]
think simply selecting a case could work as View Case.  - I dont want to do this - because the right hand text pane is also used for assigning parts of a file to a case.It's dual purpose.
Yes this is a good idea: A column could show how many files were added and/or a drop-down menu per case showing the titles of files added.

**Comment by ccbogel** [comment]
Column showing files count - and right click to see which files.
TODO - select case to view case.

**Comment by glocalglocal** [comment]
'and right click to see which files.' I think you mean left-click. In the dialogue that opens it would be nice to be able to 'remove' multiple files, and possibly select (or double-click) one file to 'Open file to view and assign text to case'.

**Comment by ccbogel** [comment]
Improved functionality. Instructions at bottom of screen
Clicking a case name shows everything associated with the case.
Clicking on the Files count opens a Case File Manager - this is used to assign files to the selected case. - can associate a full file, portions of a file's text, and apply auto text assignment. Files can be removed from a case. Files can be viewed individually.

**Comment by glocalglocal** [comment]
As reported earlier, I click on a blank Memo cell, the dialogue opens, I click cancel. The word 'Memo' appears in the cell.  If I click OK without inserting text instead, the cell correctly remains blank. The ghost memo disappears if I open and close the case file manager.

It would be nice to get a menu with Add case, Add attribute, Delete case when we right-click on a case name. 

In 'case file manager' clicking (or double-clicking) a file name could work as View file. Clicking (or double-clicking) an Assigned cell could work as Add/Remove. 

In 'case file manager' I can select multiple files and click View. Then only the first file is displayed on the right. 

In 'case file manager' I can select File A, click View, then select File B. File B's index number will be made bold. This gives the wrong impression that the text from File A still displayed in the right box is part of File B. Also, more generally, there is no way to tell which file that text is part of.   

Perhaps the red underline could be in some other colour to avoid confusion with the red underline indicating 'coded' elsewhere. 

Should Assigned have three states: no, fully, partially? 

Should the right-click menu in the right pane have a Select All? Should 'unmark' be unavailable when there is nothing to unmark (ie nothing marked or nothing selected)? Also, when no text is selected, should Mark, Unmark, Copy be unavailable?

**Comment by ccbogel** [comment]
Theres a heap of separate isdues here.
Thx giving more detail on tbe gjiist memo issue. 
Double-click file name to view, ok
Select many files view first - yes. I can make it so you can only click one fike at a time.
Red underline is ok i reckon.
Partially,  will consider.
Will try and look at improvement to the right click menu.
