### ISSUE TITLE
.deb package issues

### ISSUE THREAD

**Issue by remram44** [ccbogel/QualCoder#13]
I tried to install QualCoder but ran into issues:

* The .deb package seems to be broken. It puts an executable in the path named `main`, which is probably not what you intended (`/usr/bin/main` should be `/usr/bin/qualcoder` or similar).
* That file is also broken; the shebang reads `#!/usr/bin/python3`, but the contents look like a Bash script, not Python: `python3 qualcoder.py`
* Even if run as Bash, it references a `qualcoder.py` without an absolute path, so it won't work unless running from `/usr/share/QualCoder`

I tried to run from a checkout of this repository instead. I managed to do that, but I had to make a change to qualcoder.py:
```diff
--- a/qualcoder.py
+++ b/qualcoder.py
@@ -589,3 +589,3 @@ def main():
     QtGui.QFontDatabase.addApplicationFont("GUI/NotoSans-hinted/NotoSans-Bold.ttf")
-    with open(path + "/GUI/default.stylesheet", "r") as fh:
+    with open(path + "/QualCoder/GUI/default.stylesheet", "r") as fh:
         app.setStyleSheet(fh.read())
```
I also had to run with `PYTHONPATH=QualCoder python3 qualcoder.py` It seems that it is meant to be run with qualcoder.py inside of `QualCoder/` (like in .deb layout) however in this repo it is at the top level.

**Comment by remram44** [comment]
With those changes it worked great though, I managed to import files and tag them!

**Comment by ccbogel** [comment]
Hello Remi, 
Thanks for looking at the code and trying the deb package. 
Thisis my first time building a deb package and followed this site https://rafael.senties-martinelli.com/articles/debian-packages
Silly mistake with the shebang - fixed
Interesting that the deb package did not work before as I tried the package on two machines and it worked for me. 
I will add the above path change to the qualcoder.py file for the deb package, and the /usr/share/QualCoder path to the main script.
I will also upload the folder that I built the deb from - in case you have time or interest to look at the structure.

**Comment by remram44** [comment]
Oh maybe make sure you are not in the working directory while testing, you might end up hitting those files instead of the installed ones.

**Comment by ccbogel** [comment]
I don't think I was making use of the working directory, as I was using the launcher to open the software after the deb was installed, so presumed that the paths would have related to the installed /usr/share path. Also, I am curious to know why the stylesheet needed the extra path detail that you added (above  "/QualCoder") but that other files images etc do not need that added.

**Comment by ccbogel** [comment]
I will close this for now, as I made some changes mentioned above. Another person, qwertygc, has successfully installed the deb package on Linux Mint.

**Comment by remram44** [comment]
As of 8076e60 ([using dpkg-deb](https://gist.github.com/remram44/dda052944f7f413afe9e2fc88e19c8ba)) the binary in `/usr/bin` is still called `main`.

By running `main` in a terminal, QualCoder opens correctly.

Note that `/usr/bin/main` is not referenced at all, the `qualcoder.desktop` launches `python3 /usr/share/qualcoder/qualcoder.py` directly, so you can probably remove that file completely?

**Comment by ccbogel** [comment]
OK I will try and do that in a future debian package. I am a novice with these, so I have run _lintian_ over the package, and if it tells me to fix an error or even if I can fix a warning I try and sort it out. 

From memory, I think not having a bin exec file was a warning that _lintian_ issued. 

FYI, I have tried using python to deb software such as stdeb, but I have found doing the whole thing manually, structuring the folders and filling in the various extra needs that lintian wants, seems to produce a result that works.

**Comment by remram44** [comment]
I feel you, this is a rabbit hole of standards and file formats. Thanks for providing a package! Simply renaming "main" to "qualcoder" shouldn't trigger any lint.

**Comment by ccbogel** [comment]
Sure, I can do that. ps must be late in your part of the world, it's midday here.

**Comment by ccbogel** [comment]
Cannot add any more to this now. Issue can be reopened if needed .
