### ISSUE TITLE
Blank memos get 'Yes' in memo cell in cases

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#130]
Clicking in a memo cell and not entering text switches on Yes for that memo and that Yes can't be deleted.

**Comment by ccbogel** [comment]
i have replaced Yes with Memo
but this does not occur with me in Windows or Ubuntu ??

**Comment by glocalglocal** [comment]
I see now it doesn't happen every time. I couldn't reproduce it just now, so I tried other things, went back to try again, and it happened. Once it is in the state where it happens, it happens every single time forever until you go away. Same applies to every place where there is a memo column.

**Comment by glocalglocal** [comment]
'Yes' still appears in Cases (Manage Files was updated to show 'Memo')

**Comment by ccbogel** [comment]
oh , sorry, cases dialog, i was looking st the manage files dialog.

**Comment by ccbogel** [comment]
ok. Once it is in the state where it happens, it happens every single time forever until you go away. Same applies to every place where there is a memo column. - this does not occur with me ??

**Comment by glocalglocal** [comment]
'this does not occur with me ??' I reproduce it very easily. All I can add is that 'memo' shows in the cell but it's not recorded apparently. If I close and reopen the dialogue, only the files with an actual memo, show as having a memo. The ghost memos disappear.

**Comment by ccbogel** [comment]
OK - I have added code to do additional checks - hopefully the ghost Memo text will not appear now
