### ISSUE TITLE
Coding Reports: panes output 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#131]
In Coding Reports I select a case, click on Search and get this: The left pane shows the codings that I expected to see in the right pane, replacing the usual codes tree. The right pane shows the codings split into boxes, one box for each codes category.

**Comment by ccbogel** [comment]
Yes, This was intentional. But perhaps confusing. There are actually 3 panes split vertically. On the left hand side will be a little toggle to open the pane with the tree of codes.
I wanted to display - the codings , and then also a coding matrix with codes by case.

**Comment by glocalglocal** [comment]
There is no way I would have guessed there was a toggle there. 

I am not sure why the second pane is necessary. All the search parameters are already displayed (coder, cases selected and selected/highlighted tree codes). 

In the third pane, displaying results by case is useful, but why by codes group horizontally? This is not done for File Selection and reading the table takes a lot of horizontal scrolling.

**Comment by glocalglocal** [comment]
Correction: Actually, there is a hidden third pane in File Selection, only on the right this time but it is always blank. Perhaps it could be used to show the file content for context rather than open a separate window. Ie for File/Case/Attribute selection the panes would show tree/codings/context text with the width for each pane being adjustable or hidden. This assumes a large screen and maximized window probably. Full disclosure: personally, I like three-pane arrangements as long as I can hide a pane.

**Comment by ccbogel** [comment]
Yes this is an idea to implement.

**Comment by ccbogel** [comment]
I have implemented this.
So the third pane will show the text in context, or the case matrix.
If the case matrix is displayed and a coded result heading is clicked on, then it reverts to he text in context.

**Comment by glocalglocal** [comment]
'text in context': nice. It would be better if display scrolled down to the first coding. I doubt the scroll bar can do this, but it is always impressive and very useful when certain applications show markings on the scroll bar to show where a match can be found. 

I can get reports while Coder is blank. Shouldn't a coder be pre-selected? Or is blank the same as 'all coders'?

'Search parameters:' is cluttered. I think when all codes are selected, it could just display 'All Codes'. Or if whole categories are selected, then it could display just the categories. And when codes are listed, they could appear on separate lines without line wrap.  

Cases selected (in the middle pane and above the tree pane) are shown in the order they were clicked on rather than in alphabetical order. 

Shouldn't double-clicking the title bar do a maximize here and everywhere? And shouldn't there be the usual maximize/minimize/restore button set (as well as the keyboard-friendly menu with these options + move/size/close)? Maximize is more important in showing the cases matrix which takes space. Strangely, double-clicking the bottom border correctly does full-height in Windows 10. 

Exported Case reports don't divide codings by categories. The matrix implies this is important info.
