### ISSUE TITLE
Codings Reports: Selecting items without content to show 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#132]
When there are no codings to show for File Y, Case X, or Attribute Z, the selection dialogue could inform the user there is no point in selecting File Y, Case X, or Attribute Z,. They may even be made unavailable. 

In fact, even clicking, say, Case Selection should not be possible if there are no cases defined. Same for Attribute or File.

**Comment by ccbogel** [comment]
This would become too difficult to implement: When there are no codings to show for File Y, Case X, or Attribute Z, the selection dialogue could inform the user there is no point in selecting File Y, Case X, or Attribute Z,. They may even be made unavailable.

But I can do this: In fact, even clicking, say, Case Selection should not be possible if there are no cases defined. Same for Attribute or File.

**Comment by ccbogel** [comment]
done
