### ISSUE TITLE
keyboard navigation and shortcuts

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#134]
Some of that works -- eg tab in Windows moves selection from button to button, pane to pane etc., almost. There could be more consistency and keyboard shortcuts, with main menu items displaying the keyboard shortcut as well. Eg in Windows all menu items are accessible via Alt+key, and pressing Alt causes a character in each menu header to be underlined revealing the key you need to press for that menu. This is an accessibility issue as well.

**Comment by ccbogel** [comment]
yes ok will add in this at some stage.

**Comment by ccbogel** [comment]
done

**Comment by glocalglocal** [comment]
That was fast! I am not expert in UIs so I just checked several application, including LibreOffice, for patterns. I am not sure if they are universal across platforms, so LibreOffice may be useful as cross-platform. Typically, Help: F1, Setting: Alt-F12 or Alt-Enter. Not sure what happens with systems that don't have F keys. Presumably, Ctrl should be Command for Macs. 

It's not a good idea to use Ctrl+A, C, V, X, S, F because many people's brains are hardwired to associate them with Select All, Copy, Paste, Cut, Save, Find. In fact, they (correctly) work as Select All, Copy, Paste, Cut if the focus is in the main log window already.  

When pressing Alt, the focus correctly moves to the menu bar. Then every menu header would typically have an underlined letter we can type on the keyboard to open the menu. Then every menu item has a letter underlined, etc. 

Lists like Recent Files are typically numbered and you can press the number to select (and often there is a 'Clear list' option at the bottom of the list). 

Manage Files and Manage Codes don't have keyboard shortcuts (yet) except Tab and Shift-Tab which don't work properly. 

As I said, I am not sure if these are universal conventions.

**Comment by ccbogel** [comment]
yes I can change the bindings to not cross over with CVSXF. I wont underline the letter in the word, as these may change in other languages.
