### ISSUE TITLE
Rearranging menus

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#135]
I think there are some obvious and easy rearrangements for tidying up. The Project menu could have 'Export' and 'Import' submenus. 'Export' could also get 'export codebook'. Open Recent Project could become a 'Recent Projects' submenu. 

I know these are established conventions in Windows and Linux, but I am not sure about Macs.

**Comment by ccbogel** [comment]
Yes ok will look in to implementing some of this.

**Comment by ccbogel** [comment]
Completed this.
