### ISSUE TITLE
Manage Cases -- all text of cases suddenly appearing in bold

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#138]
I selected a case to view -- all OK. Then I selected another case to view and all text was displayed in bold. Tried a couple of other cases -- all text was displayed in bold. 

I left the dialogue open, worked with other dialogues, returned to the open Cases dialogue, selected another case again and I got the following error: 

2020/07/15 12:41:31 ERROR settings.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\cases.py", line 624, in view
    cur = self.app.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'

EDIT: When I returned to the main window the project was closed. Not sure if somehow I closed it myself (hence causing the Case dialogue error above) -- eg while trying out keyboard shortcuts. Another reason not to use Ctrl+X for Close.

**Comment by ccbogel** [comment]
Yes, I removed Ctrl+X and replace with Alt+X
Yes this is the cause of the error.
Yes I have an html end tag missing - re the bold - so will look in to it.

**Comment by ccbogel** [comment]
bolding appears to be resolved

**Comment by glocalglocal** [comment]
Not sure if this was intentional. Each text in the right pane previously started with a heading in bold. Now it's not bold. I think there should be some sort of divider, even dashes, because it is possible to have a one-line sentence surrounded by line breaks that will look like a heading.

**Comment by ccbogel** [comment]
Ok, will try and add bold back in. And test again.
