### ISSUE TITLE
Menu intgration on Lubuntu 16.04

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#14]
I installed QualCoder however no menu integration happened = no QualCoder in the menu 
I don't know if the same behavior happens on min or debian, but could you make QualCoder into the menu once installed?

**Comment by ccbogel** [comment]
HI, was that through installing the .deb package?
I will have to look a bit more at Lubuntu  ans see what the difference is. I might install virtualbox and Lubuntu to see what is going on.

**Comment by WPFilmmaker** [comment]
Hi!
Yes via .deb

Lubuntu 16.04.3

**Comment by ccbogel** [comment]
See the closed issue #15 Remove the Deb file.  On Lubuntu 16.04.6, the QualCoder icon shows in the Education menu section and when clicked, opens QualCoder.

**Comment by WPFilmmaker** [comment]
@ccbogel unfortunately on my system it does not work :/ I tried 1.2 from the deb file and while it fixes #15, I don't see say Education menu and QualCoder is not in other parts of the menu :/

**Comment by WPFilmmaker** [comment]
Is there any more information I can provide to you so you can try to replicate this in your virtual machine?

**Comment by ccbogel** [comment]
HI. I am at work but am responding on the side. I am not sure if you can use the terminal but can you check some things: to open terminal crtl+alt+t
ls /usr/share
# in the above command qualcoder directory should be present
ls /usr/share/applications
# in the above command the qualcoder.desktop file should be present
ls /usr/share/pixmaps
# in the above command the qualcoder.png icon file should be present

If the above files and directory are present, copy the .desktop file to your desktop and open qualcoder by double-clicking on the desktop icon.  Change YOURUSERNAME to whatever you user name is in Lubuntu. In the terminal do this to copy to the desktop:
cp /usr/share/applications/qualcoder.desktop /home/YOURUSERNAME/Desktop/

**Comment by ccbogel** [comment]
re-opened isse

**Comment by ccbogel** [comment]
Did you follow the above commands? did you manage to make a clickable desktop icon? I would like to know if these instructions helped you.

**Comment by WPFilmmaker** [comment]
As soon as I have access to lubuntu 18.04 I will try there, so far your suggestion seem to be a  good workaround:)

**Comment by WPFilmmaker** [comment]
@ccbogel I installed QualCoder 1.3 via deb file and menu integration works on Lubuntu 18.04. I am closing this.
