### ISSUE TITLE
Help for SQL Statement

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#140]
Hello !

I try to make a table with different elements:
cases.name code_name.name code_text.seltext

I have a try to make a query, but I  have only code_name.name and code_text.seltext, not cases.name. Do you have an idea for get this element ?

```
SELECT name, seltext FROM code_text INNER JOIN code_name ON code_text.cid = code_name.cid
```

Regards

**Comment by ccbogel** [comment]
Willmlook in to this.

**Comment by ccbogel** [comment]
Try this:
select cases.name as casename,  substr(source.fulltext, case_text.pos0, case_text.pos1 -  case_text.pos0 ) as casetext
from cases join case_text on  cases.caseid = case_text.caseid join source on source.id= case_text.fid  
where case_text.pos1 >0

**Comment by ccbogel** [comment]
OK, also try this with the case and coded text together:
I have added this SQL to the dialog SQLs - under the 'joins' section
The -- indicates a comment - so you can remove those 3 lines or you can uncomment and fill in the details of the ids you want

select code_name.name as codename, cases.name as casename, code_text.pos0, code_text.pos1, code_text.fid, seltext as "coded text", code_text.owner  from code_text join code_name on code_name.cid = code_text.cid join (case_text join cases on cases.caseid = case_text.caseid) on code_text.fid = case_text.fid where 
-- code_name.cid in ( code_ids ) -- provide your code ids 
-- and case_text.caseid in ( case_ids ) -- provide your case ids 
-- and 
(code_text.pos0 >= case_text.pos0 and code_text.pos1 <= case_text.pos1)

**Comment by qwertygc** [comment]
Think you it's work !
