### ISSUE TITLE
Small fonts

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#141]
As reported earlier, I get different font sizes in different places, which looks odd but there was a pattern. Now I see that text in a right-click menu (Case File Manager's text box on the right) is displayed is the tiny font, but the text in another right-click menu (Cases' text box on the right) is displayed in the normal font size. Not sure why the tiny size font appears anywhere at all. Not sure what it looks like on small laptop screens. If I increase the font size, what appears normal now, will look very big. 

EDIT: I tried my 14" laptop and the tiny fonts are practically unreadable. I can't imagine what it will be like on 10" ultraportables. Increasing the font size in the settings will make fonts elsewhere far too big, particularly when screen real estate can't be wasted.

**Comment by ccbogel** [comment]
the right click menu - I am not sure I can change the font there, but will look in to it.
The Cases text box on the right is using the computer platform settings. ( I have not added any code for this right-click menu, so have not applied any font choices).

**Comment by glocalglocal** [comment]
To clarify, normal fonts are used in most dialogues and right-click menus. Small fonts appear in the Settings dialogue; in Manage Files, right-click menus; New attribute name, right-click menu; Code Text codes tree and coding right-click menu, etc., Reports / Select files or cases to View; Graph Visualisation / Black and White etc. / SQL top pane right-click menu. Possibly elsewhere.

**Comment by ccbogel** [comment]
I think this is fixed now

**Comment by glocalglocal** [comment]
Yes, Segoe UI 9 looks at it should. Bliss at last :) Only text left out is the SQL top pane right-click menu -- still small fonts.

**Comment by ccbogel** [comment]
LOL, good to know bliss has been achieved. This final font issue has been fixed.

**Comment by glocalglocal** [comment]
One more: saved file confirmations (and possibly similar confirmations) still display in small font. Eg report export.

**Comment by ccbogel** [comment]
ok willconsider, these dialogs look harder to change.
