### ISSUE TITLE
Paragraph spacing in imported files

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#142]
In Word typically a single Return at the end of a paragraph shows a gap between paragraphs. That  spacing below paragraph is the default in Word. When converting imported text to plain text, should there be an option to add a blank line? This is probably an issue with other file formats, including PDF and ODT. At the moment, texts look like there are no paragraphs which is confusing with long texts. 

I am now wondering if I should add a line in the imported texts myself, but I am not sure yet how this will affect existing codings or files.

**Comment by ccbogel** [comment]
Gaps between paragraphs depend on your word paragraph settings. 
Will consider adding the option on import.
You can add a line using the restricted text edit function.

**Comment by glocalglocal** [comment]
'You can add a line using the restricted text edit function.' Not if the file is already coded, which is probably wise. In that case, shouldn't 'Restricted edit' on the title bar say something else? Could there be a way to be able to edit a coded file? Otherwise, I may have to add blank lines to that one file, re-import and re-code it. 

When you say 'restricted' -- what is restricted or restrictive about it?

**Comment by ccbogel** [comment]
The restricted edit in the Manage files : I restricted it to very short sections of text (20 characters). As otherwise the codings/annotations/case assignments etc will be mucked up too easily.

**Comment by ccbogel** [comment]
I will close this issue re line spacing on import - I made it automatic -should work for most if not all file types.

**Comment by glocalglocal** [comment]
It does work! Better still, if there is a blank line there already, import doesn't add one more.

**Comment by glocalglocal** [comment]
> As otherwise the codings/annotations/case assignments etc will be mucked up too easily.

Wouldn't then unlimited editing of uncoded text be safe? The user could of course edit the txt file and import it, but a lot of things can be done manually at the OS level.

**Comment by ccbogel** [comment]
An uncoded/unassigned to case/un-annotated file can be edited as much as you like without problem.

**Comment by glocalglocal** [comment]
How does assigning a file to a case affect its content?

**Comment by ccbogel** [comment]
anything affecting the case character positions is a potential problem.Even a full text file, as it has an end char position. So it is best to do you editing before assigning.
