### ISSUE TITLE
Format in exported ODT files 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#143]
Not sure if there is an issue here, but just in case. I exported a codings report in ODT. I opened the file in Word and LibreOffice and they look different. The font is the same but size in Word is 11 and in Writer it is 12. Spacing after a paragrpah in Word is 8pt, in Writer it is 0. It may be something to do with my defaults in the two applications.

**Comment by ccbogel** [comment]
This is a difference between the applications.
