### ISSUE TITLE
Main window log

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#144]
Being pedantic here but the good news is I am running out of more substantive points. The main window log shows:

For settings: 
Directory: C:/ssfgfg/asgdsfg... [forward slash will confuse some Windows users. Paths could be made clickable too]
Project_path:C:/ssfgfg/asgdsfg... [as above and space missing after colon. Underscore may confuse some]

Date time now:2020... [space missing after colon]
Path: C:/Work/MEGA/Goldsmiths/coding/DTT/DTT.qda [as above and Path different from Project_path]
Directory: C:/ [slash again. Generally, many Windows are not familiar with 'directory' as opposed to 'folder'] 

Should there be a 'Project summary' heading, similar to the 'Settings' heading?

**Comment by ccbogel** [comment]
OK more in alignment with your suggestions. Made a footnote for Windows use for \ or / and Directory(folder). 
I dont think the paths need to be clickable.
