### ISSUE TITLE
Renaming code affects coding

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#145]
I changed the name of code A to correct a typo and the one and only relevant coding was broken into three sections coded like this: (1) code A, (2) code A+B+A [1 character long] (3) code A. Code B is completely irrelevant and appeared out of nowhere. Sections 1 and 3 otherwise behaved correctly (tooltip and combo). 

Section 2 features now overline, and the combo shows the A+B+A codes. The tooltip shows the 3 codes but only the first one has a beginning...end text. 

Selecting code A in the combo or in the tree correctly underlines the whole snipped as originally. Selecting code B underlines the single character (Section 2).

**Comment by ccbogel** [comment]
Hmm interesting, re the B code. if this is removed then the original A code is correct?
I am wondering if the right click context menu was overly sensitive and added the B code inadvertently?
unsure how to resolve this right now.

**Comment by glocalglocal** [comment]
If I removed Code B from that one character, I get A+A, with that one character coded twice as code A (ie there is an overlap of A and A) -- the overline ad combo show that.  

I tried to reproduce it elsewhere in the same text, with overlapping and non-overlapping snippets but I couldn't.

**Comment by ccbogel** [comment]
code renaming wont affect this issue. as the selected text is stored in a different table to the code name. Perhaps an overly sensitive mouse?

**Comment by glocalglocal** [comment]
This mouse is never over-sensitive. I'll keep an eye out, although renaming codes doesn't happen often.

**Comment by ccbogel** [comment]
how about I close this issue for now, and reopen if it occurs again.

**Comment by glocalglocal** [comment]
yes, it makes sense
