### ISSUE TITLE
1x1 cases matrix in codings report is too tight for no reason

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#146]
In Coding reports I select a codes category and one case. It works as expected but the matrix is 1x1 and I get all codings in an unnecessarily small box while there is plenty of spare room in pane 3. Perhaps, boxes should be adjusted depending on x, y of the matrix.

**Comment by ccbogel** [comment]
hmm - challenging. Will look at.

**Comment by ccbogel** [comment]
solved for 1 row or 1 column matrix

**Comment by glocalglocal** [comment]
Just realised, the codings then don't show the filename. Shouldn't each coding by file, case, attribute show all three in its header (file source, codes, attributes)?

**Comment by ccbogel** [comment]
hmm, never thought of that.
