### ISSUE TITLE
ghost memos in Code Text

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#147]
All codes in the tree have 'Memo' in the memo column but I never created a memo and when I open them they are blank. 

Shouldn't single- or double-click on the memo cell open the memo dialogue like elsewhere?

**Comment by ccbogel** [comment]
memo edit - I can really only implement the approach that I have done, using the right-click menu options to open the menu dialog.
I have added extra checking code - so that hopefully now the ghost 'Memo' wording will not occur.

**Comment by glocalglocal** [comment]
ghost 'Memo' wording solved
