### ISSUE TITLE
Closing a project leaves the cases dialogue open 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#148]
This may happen with other dialogues -- I haven't checked. The problem is that when I tried to use the open dialogue to change something I got this error: 

2020/07/18 12:33:00 ERROR memo.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\cases.py", line 416, in cell_selected
    cur = self.app.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by ccbogel** [comment]
yes fixed this now
