### ISSUE TITLE
More (non-essential) ideas

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#149]
I checked NVivo for useful things that may be missing from qualcoder. There are a few pointless things, like Relationships (between concepts, people etc as they emerge from coding) which are nothing more than glorified codes really. Otherwise, not much is missing but here are my observations for reference. 

Nvivo usefully gives the user as much info as possible in different contexts enabling the user to get details without having to go around looking for that info elsewhere. Without overwhelming the user, one way they do that is by cross-linking whenever possible (eg as in qualcoder, clicking on a coding takes you to the context*). Another way is by giving info in columns (eg count in qualcoder). Qualcoder can do more of that easily. Eg

Wherever files or cases are listed, qualcoder could show number of codes used and total codings. Vertically, the columns can show totals for these variables too. The number of files coded with a certain code and the total count across files are two more variables. File sizes should be shown somewhere or wherever relevant. 

On (*) above, Nvivo also shows a % coverage per coding. This is a way to show in the coding report how significant each coding is by volume.  

Another area is sub-folders -- eg sub-codes and sub-cases (with optional children aggregation), and sub-folders for files grouping. File groupings would be very useful. 

Possibly gimmicky -- Nvivo does nicknames for codes and cases. 

An easy win is the many reports Nvivo generates by simply displaying available info in different ways. Eg 

![reports](https://user-images.githubusercontent.com/16408198/87855105-a2b4d180-c905-11ea-929d-54701b22d0fe.jpg)

**Comment by ccbogel** [comment]
I think I need to know the details of what these report do, so I can add missing ones.

**Comment by glocalglocal** [comment]
I would have to re-install nvivo to check but the reports are explained [here](http://help-nv11.qsrinternational.com/desktop/procedures/understand_predefined_reports_and_extracts.htm).

Apparently, you can modify the predefined report parameters or make your own. http://help-nv11.qsrinternational.com/desktop/concepts/about_reports_and_extracts.htm#MiniTOCBookMark3

**Comment by ccbogel** [comment]
OK so I have ideas now of the additional main reports needed.
Source summary
Source classification (make the file attributes exportable, basically)
Case classification (again make the attributes exportable)
Code summary report (lists words coded, number of sources, number of users for each code)
