### ISSUE TITLE
Multiple identical dialogues open

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#150]
I can open multiple identical dialogues for code text etc. I suppose this could be an advantage occasionally but IME it can create all sorts of problems. At times I have more than 4 identical code text dialogues in the background without realising it, and they don't synchronise. Even worse, sometimes I can close the project and the dialogues stay behind leading to errors. 

I think a tabbed approach would be better but this may not be possible.

**Comment by ccbogel** [comment]
I like dialog approach rather than tabbed -as you can see multiple screens at once - if needed.
Yes having multiple dialogs opened at the same time is potentially problematic - I make mention in the manual, but I still feel it is useful in case you need to view another text as the same time.
The close project dialogs should now all be deleted.

**Comment by glocalglocal** [comment]
I can see the usefulness of multiple, say, Code Text dialogues showing different texts. I was referring to **identical** dialogues -- eg opening 2+ Code Text dialogues showing the same text probably because the user didn't realise. These are not synchronised either. You can switch to another task and back to the wrong Code Text dialogue without even realising it, and continue coding another version of the same text. 

Related to this, I select Manage Files while the dialogue was open in the background. The open dialogue didn't come to the foreground.

**Comment by ccbogel** [comment]
Do you think I should limit say a Code Text dialog to one instance only?

**Comment by glocalglocal** [comment]
Ideally, qualcoder would allow opening multiple Code text/audio etc dialogues and would allow to select/open multiple files (a very useful possibility) but it would know which file is already open for coding in another dialogue and would prevent re-opening it (or would automatically switch to the relevant dialogue that is already open). 

If that's hard to implement, I think we would rather lose the advantage of coding multiple files altogether. Otherwise, sooner or later users will run into trouble with conflicts. At some point I had 3-4 identical dialogues in the background without realising it. OK, I was opening/closing lots of files for testing, but I am sure this will happen.

**Comment by ccbogel** [comment]
OK I have reduced these to one of each type
