### ISSUE TITLE
case file manager mods

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#151]
In 'case file manager' I can select multiple files and click View. Then only the first file is displayed on the right.

In 'case file manager' I can select File A, click View, then select File B. File B's index number will be made bold. This gives the wrong impression that the text from File A still displayed in the right box is part of File B. Also, more generally, there is no way to tell which file that text is part of.

Should Assigned have three states: no, fully, partially?

**Comment by ccbogel** [comment]
fixed the above.
Assigned - I feel happy with ow it is for now, but will mull it over.

**Comment by glocalglocal** [comment]
Not sure what has changed here. 

BTW, there is a space missing after 'Displayed file:'

And the right-click menu in the right pane uses the small fonts. And Mark/Unmark/Copy are always available even when they are not applicable.

**Comment by ccbogel** [comment]
what has changed here: well - displayed file for a start. and double click to display a file.
ok fixed the space and font. 
ok will consider doing code for mark/unmark etc, thats more challenging
