### ISSUE TITLE
case file manager additioanl context menu actions

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#152]
Should the right-click menu in the right pane have a Select All? 
Should 'unmark' be unavailable when there is nothing to unmark? 
Also, when no text is selected, should Mark, Unmark, Copy be unavailable?

**Comment by ccbogel** [comment]
all done

**Comment by glocalglocal** [comment]
I select a marked word and 'Mark' is still available. Otherwise it looks OK.
