### ISSUE TITLE
Markdown support 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#155]
I am experimenting with markdown as a way to maintain some richness in the text for emphasis etc that will survive conversions to/from plain text. I use Typora for conversion between .docx and .md and .md editing. The beauty of markdown of course is that the source text is easily readable without rendering, people can or already use it for formatting almost without realising it or after minimal training, and that formatting survives with plain text through almost any conversion. 

This works very well with tools like qualcoder -- Typora even adds blank lines between paragraphs when needed, which qualcoder does now as well, and qualcoder won't add another line on import. 

I am wondering what qualcoder can do to support markdown, or at least not complicate things for markdown. 

Eg initially qualcoder could be easily made to recognise .md files as importable .txt files. Perhaps it could export in .md as well. 

Those special characters that complicated things in importing from RQDA (eg smart quotes, m-dashes) could be optionally converted back to plain quotes and double-dashes -- which is what Typora does as an option). That would be good for qualcoder and how it displays text anyway. 

In the future, you may want to consider rendering markdown as well. This may clash with bold or underline being used to indicate qualcoder features, but there may be ways around that.

**Comment by ccbogel** [comment]
If you were to replace the .md with .txt suffix it would import.
I am not considering rendering markdown - it is really  complex. Particularly when importing from documents such as odt docx for example in which the html tags are used to create the render, and these tags also are characters which in turn affects the text positions.

**Comment by glocalglocal** [comment]
Yes, renaming .md to .txt is what I have been doing, but it would be nice to import files explicitly, (at zero cost), even if qualcoder doesn't render markdown. 

Most markdown editors I've seen use pandoc or another module for conversions in either direction. They don't implement their own conversion. 

These tags add characters but I am not sure why this is problem as long as the characters are there before coding as part of the text to be coded. Despite the advantages it has to offer, I can see how rendering markdown may complicate things in programming. I think I will use markdown (ie get Typora to convert .docx files to .md and then import them as .txt) which qualcoder will simply handle as any other plain text. It will work just fine because markdown is also meant to be readable in plain text anyway. I can see only one area where qualcoder may break something. Suppose a block of text is in bold like this: 

<bold>sentence1.sentence2. sentence3<bold>. (I am not using proper markdown here to avoid github displaying this in bold). 

Then I code sentence2.sentence3<bold> (ie a subset of the above). The coding report will extract and display this without the matching opening <bold>. Qualcoder could perhaps add that to the beginning of the coding so that the text report will still appear properly tagged as bold. I could then open the text file in Typora for further processing. Of course the plain text report will lack the highlight colours. Just a thought.

**Comment by ccbogel** [comment]
ok you can now import.md text files

**Comment by glocalglocal** [comment]
Just realised that the first time I select Manage Files / Import the default folder is the user folder. Shouldn't that be the default project dir?

**Comment by ccbogel** [comment]
fixed import default directory

**Comment by ccbogel** [comment]
I should close this issue if sufficiently resolved. I am not intending to show styles in the text edit pane._

**Comment by glocalglocal** [comment]
OK, just to clarify I was not referring to showing styles. I was wondering if qualcoder could try not to break the pairs of markdown tags when displaying a sub-snippet.

**Comment by ccbogel** [comment]
oh  I get you now. So if you coded some text that contained one or none of the markdown tags - you still want the surrounding tags - when you generate a report. That is complicated.

**Comment by glocalglocal** [comment]
That's what I meant but I see why it takes quite some code to do that.

**Comment by ccbogel** [comment]
I will close this issue, because its not a function I want to spend the time to create.
