### ISSUE TITLE
Special characters in import/export

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#156]
I think that most special characters that complicated codings in imports and plain text exports can be fixed by optionally converting smart quotes to plain single/double quotes, m-dashes to '--', ellipsis to '...', and possibly a few more. 

Eg I exported a report in text and I got this "Itâ€™s" for "It's" and "â€˜wordâ€™" for "word" etc.

**Comment by ccbogel** [comment]
Can you send some short files in the original format so I can import and experiment with. This may not be an easy fix.

**Comment by glocalglocal** [comment]
sample here: 
[special chars.docx](https://github.com/ccbogel/QualCoder/files/4944973/special.chars.docx)

**Comment by ccbogel** [comment]
OK. I imported the docx. All appear to have imported without a problem. Possible exception the double-smart-quotes look the same as single smart quotes.
I used the sql dialog to export as csv. On opening the csv I get the same issue you describe.

**Comment by glocalglocal** [comment]
Oops, I mityped the double-quotes. Here is the file again. 
[special chars.docx](https://github.com/ccbogel/QualCoder/files/4977016/special.chars.docx)

The .txt file I get when exporting the file above contains funny characters. 

Importing from RQDA and Nvivo also produced those characters and that caused codings to shift.

**Comment by ccbogel** [comment]
OK, I have added a different UTF-8 encoding on export from the sql dialog, mange files dialog and code reports (utf-8-sig). This allows other software to recognise the UTF-8 characters.

**Comment by ccbogel** [comment]
I have not looked at RQDA or Nvivo yet.
Thx for the new file.
How are you exporting the file? i.e. what dialog are you using? I need to check that the code I added is there in the right spot.

**Comment by glocalglocal** [comment]
I export it through Manage Files / Export. 

It now exports a docx only but with the correct characters.

**Comment by ccbogel** [comment]
Yes I have changed the export. so it will export (basically copy and move) any original imported files. And also any text files created within qualcoer are exported also. Instead of the two files it did previously.

**Comment by glocalglocal** [comment]
I created the docx and pdf files below with special characters and non-latin to test this. File import/export, view, code, coding report work fine. One issue only (see new issue). 

[test_file.docx](https://github.com/ccbogel/QualCoder/files/4984540/test_file.docx)
[test_file.pdf](https://github.com/ccbogel/QualCoder/files/4984541/test_file.pdf)

**Comment by ccbogel** [comment]
I imported the test RQDA file andit looks ok, I think is this howthe coding looked on yours?
![pic1](https://user-images.githubusercontent.com/5834638/88795648-bdc7f100-d1e3-11ea-86fe-4ad71dfe8347.png)

**Comment by glocalglocal** [comment]
I just re-imported from RQDA and it looks OK in Manage Files, Code, Codings report. No odd characters, no codings shifting. 

When I export a file, the text looks fine in notepad, LibreOffice, Word but there are odd characters in metapad even when set to UTF-8 explicitly. Strange.

**Comment by ccbogel** [comment]
OK. must be a quirk with metapad. Will close this issue.
