### ISSUE TITLE
Superfluous characters in codings reports

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#157]
In coding reports the snippets can start with space or other odd characters. This is typically because the user got it wrong. Qualcoder could perhaps remove superfluous characters as an option.

**Comment by ccbogel** [comment]
I think this is the users responsibility, I hate in Word that it automatically tries to extend selections beyond what I choose.
I could possibly add 2 right click menu options to allow the user to add/subtract characters from the start and end positions in a code, to adjust the originally coded section.

**Comment by glocalglocal** [comment]
'I hate in Word...' This is optional

**Comment by ccbogel** [comment]
is it - ok i did not know

**Comment by glocalglocal** [comment]
![word](https://user-images.githubusercontent.com/16408198/87889680-60cd7d80-ca22-11ea-9d1b-a5de90defa56.jpg)

**Comment by ccbogel** [comment]
ah thanks

**Comment by ccbogel** [comment]
ok, have added right click edit option for changing the code position.

**Comment by glocalglocal** [comment]
The new dialogues have the 'What's this' question-mark
