### ISSUE TITLE
Non-latin encoding of text files 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#159]
I created a Word document containing a sentence in English and another one in Greek. I imported the .docx file into qualcoder and all worked fine. 

Then I used Typora to convert the .docx into .txt and imported that into Qualcoder and got the display below in the different Qualcoder dialogues (Manage File, Code Text, Codings Report): 

![encoding](https://user-images.githubusercontent.com/16408198/87889467-4d6de280-ca21-11ea-881e-5a1b438f4a45.jpg)

Then I got Word to save the file in .txt and followed the advice Word gave me to change the encoding to one of the Greek options (ISO), otherwise it said the portion in Greek wouldn't make it. The .txt opens fine in Typora but when I import it to Qualcoder I get again rubbish characters as before (but very different rubbish characters).

**Comment by ccbogel** [comment]
Python and QualCoder by default use UTF-8 encoding.
Perhaps send me one or both files that are displaying incorrectly. Then I can experiment with encoding detection on import of text files.

**Comment by glocalglocal** [comment]
I followed the same steps as above. I created a docx with special and Greek characters: 
[test_file.docx](https://github.com/ccbogel/QualCoder/files/4984607/test_file.docx)

This is the same file I used a few minutes ago to test import/export, coding and coding report in #156 , which worked fine. 

Then, I used Typora to convert the .docx into .md. Typora is setup to convert smart characters into non-smart (quotes, dashes etc), so ignore them. 

_Notepad correctly displays the file like this:_ 

![notepad](https://user-images.githubusercontent.com/16408198/88595537-adccd780-d052-11ea-8a0d-2afbd9dde359.jpg)

_Metapad (basically, notepad on steroids) messes up Greek (and presumably all non-Latin characters) like this:_

![metapad](https://user-images.githubusercontent.com/16408198/88595676-fe443500-d052-11ea-8899-d62ebceef52b.jpg)

_When I try to import the .md file into qualcoder, I get the warning below and the file isn't imported (in which case, it's more than a warning):_

![cannot import](https://user-images.githubusercontent.com/16408198/88595792-33e91e00-d053-11ea-8186-f15c6cebb949.jpg)

The fact that Typora and notepad display the text correctly, means there is something wrong here. Not sure what Typora does with encoding, but Typora is important in this scenario because only that or a similar application converts from docx to md -- qualcoder doesn't do it.

**Comment by ccbogel** [comment]
OK. So I imported the test_file.docx and it worked fine.
Perhaps you can send me the .md file **after** Typora changes it.
Then I can experiment. I am not confident this is an issue I can resolve, but will have a look.

**Comment by glocalglocal** [comment]
[This ](https://mega.nz/file/kwdF0IzY#MJjHc0v0AxuekNJlysQRMu_dbx9ZfeWH6FIDvVb6DqY) is what Typora produces.

**Comment by ccbogel** [comment]
OK. I can open it without problems with my text editor, and I can import the file without problems - is shows the greek text.

**Comment by ccbogel** [comment]
![pic1](https://user-images.githubusercontent.com/5834638/88801524-33848a80-d1ed-11ea-8565-c6f2fa4ec815.png)

**Comment by glocalglocal** [comment]
I tried to import it again and I get the same Warning message as above. I even downloaded my own file from the link above to avoid confusion.

**Comment by glocalglocal** [comment]
Position 265 in the warning seems to be past the sentence in Greek. I counted character and it looks like it's the '-' character on the last line. I replaced it with 'X' and import works OK. It's not a coincidence that metapad showed specifically that character as rubbish -- the only one in this file. metadata probably is catching what seems to disturb qualcoder's import.

**Comment by ccbogel** [comment]
I tested the import on Ubuntu, I will replicate on Windows
