### ISSUE TITLE
segmentation fault happened

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#16]
I had QualCoder open, system went into suspension and QualCoder segmented. I think it could be related. I tried to reproduce but could not. Terminal shows "Segmentation fault (core dumped)"
where do i find it to post it?

I am on Lubuntu 16.04.3

**Comment by ccbogel** [comment]
It might have been recorded in the qualcoder log file in your home directory.
![picure](https://user-images.githubusercontent.com/5834638/55192686-30444d80-51f9-11e9-81d4-3204ecc38b1a.png)

**Comment by ccbogel** [comment]
I will close this issue for now, hoping it is related to the errors that happened when trying to import the large encrypted arabian nights pdf.  Otherwise make another issue if segmentation fault occurs again.
