### ISSUE TITLE
Attributes: create and edit

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#160]
In Manage Attributes, I can't edit an attribute I created. I can change the name in place or delete the attribute and start all over again.

While creating an attribute, why wouldn't we be presented with a single dialogue with all the options in one place? That would make editing it later easier.

**Comment by ccbogel** [comment]
what do you mean by edit an attribute?
Yes I should do a single dialog for that - just lazy.

**Comment by glocalglocal** [comment]
'Edit' -- ie change case or File, value type (with appropriate warning if that actually messes up attributes linked to files/cases already, which also applies to Delete attribute).

'caseOrFile' and 'valuetype' read like programming variables -- not very user-friendly.

**Comment by ccbogel** [comment]
I have updated the table headings.
I wont be enacting changing from a file to case for the attributes.
