### ISSUE TITLE
Manage Files grid and attributes

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#162]
In Manage Files, I can right-click on an attribute cell, right-click / show this value. This removes all files from the grid except those with the attribute. But then I can't go back. Not even if I close and re-open the dialogue. The only way to get the full list of files is close the the dialogue, open a different dialogue (eg Manage Codes), then go back to Manage Files. 

I can select multiple cells horizontally or vertically but I can't do anything with the selection. Ctrl-C copies only the last selected cell out of multiple selected cells (and there is no Copy on the right-click menu). Similarly, clicking on the column header, all cells are selected vertically but I am not sure why. 

When I select multiple files in Manage Files and click on View only the last selected file is opened -- but all selected files remain selected. 

BTW, in Manage Files there is the option 'File Type order' but there is no column for file type. 

All dialogues following 'Add attribute' use small fonts. 

I can add an attribute, but I can't delete it there.

**Comment by ccbogel** [comment]
To go back - select the date order - but yes -  I should add an option to choose show all - as its not intuitive.
I am not sure if I can do a copy from multiple cells. Is this a needed function? 
Select a column and all highlighted -yes its default behaviour in qt.
select many view one - yes I can add code to make the selection look like the one.
file type order - this is the icons on the left: text, audio, video and image.
Fonts should be correct now.
Yes can add attribute only. its a convenience fn, but in manage attributes can delete.

**Comment by ccbogel** [comment]
added show all rows option
select many view one - fixed the visual of this

**Comment by glocalglocal** [comment]
Font in New Attribute Name still small (eg 'Enter text below:')

copy from multiple cells: not really needed, I think, but it is unexpected behaviour that many cells are selected but one of them is copied. 

Select a column: can't qt do the usual, click on header to sort in ascending/descending order? It is strange that all cells are selected because it encourages you to think you can do do something with them next. Same with multiple selection in any direction/range. 

'Show all rows' is available even when all rows are showing. 

Order by Attribute / View any file produces a blank view box. Texts are available to view again if I order by any other variable. 

Why 'order by *this* attribute' is different from the other variables? Wouldn't 'order by attribute' (showing regardless of where you click) do the same thing?

**Comment by ccbogel** [comment]
font size looks fine now.
changed behaviour to singe cell selection rather than multiple selection.
qt is the graphical display framework - to do things, eg ordering - I have to code that function.
'order by attribute' now
show all - now shows only when needed
view file text fixed

**Comment by glocalglocal** [comment]
single cell selection: the downside is that your can't export or delete multiple files, but I don't an alternative. 

I don't know if it's worth the effort but the appeal of the usual click on the header to sort the column method is that to most people it's natural, and it would make 3-4 menu options redundant.

**Comment by ccbogel** [comment]
i will think about it for later on perhaps. its functional and there are so many other things to implement in the issues
