### ISSUE TITLE
Boolean attributes?

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#163]
Should there be boolean attributes? Of course the user can do that already by setting a number attribute to 0 or 1.

**Comment by ccbogel** [comment]
I based this originally closely on the RQDA file format which had only character and numeric.
There isnt really a boolean type in sqlite, so 1 and 0 will do:
https://www.sqlite.org/datatype3.html

**Comment by glocalglocal** [comment]
Not a problem. I suspect though that the SQLite spec implies that if the developers want Boolean, they can pretend they offer True/ False to the user and handle that as integer 0, 1 behind the scenes without the user realising. The advantage of True/False or Yes/No is that the user can't later input an irrelevant value, like 2. Generally, I think Attributes in many programs can lead to problems because the string is not fixed and can be mistyped, so looking for a match later can miss some hits because someone typed in 'femalle' somewhere. Anyway, free text seems like standard convention. Ideally, on entering, say, gender, an application would remember you used already and suggest 'male', 'female'.
