### ISSUE TITLE
Manage Cases expected interface behaviour 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#166]
In Manage Cases and Case File Manager (and possibly elsewhere) I think a user would expect: 

* single click to show content (now double-click is required in Case File manager)
* right-click on items to offer the relevant options available as buttons + select all items
* right-click on text in the right pain to open menu with at least Copy/Select All. 
* handy info like items selected x/y and possibly more -- eg total files linked. This is relevant to most lists. On several occasions I find I have to count selected/listed files, codes, cases etc to double-check I haven't missed something -- a pain, time consuming and tiring with many files etc.

**Comment by ccbogel** [comment]
Double click is better in the case file manager. single clicks may open other dialogs (eg image, av).
OK- handy info like items selected x/y and possibly more 
OK -  Copy/Select All.

**Comment by ccbogel** [comment]
I think I have implemented the majority of these.

**Comment by glocalglocal** [comment]
Select All in Manages Cases: some very odd happening now. I right-click on text several times and nothing happens. Then scrolling text freezes, then I right-click on text or even outside the textbox, even grabbing the titlebar to move the window, there is a delay and then I get the Copy/Select all menu (in tiny font).   

Strangely, I don't see the rest of the bulleted points implemented.
