### ISSUE TITLE
Manage Journals error

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#168]
I created a journal, closed the Manage Journals dialogue, checked other dialogues, went back to Manage Journals and got the error below:

ERROR add_attribute.exception_handler Uncaught exception:
Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 764, in journals
    d.show()

RuntimeError: wrapped C/C++ object of type DialogJournals has been deleted

**Comment by ccbogel** [comment]
ah, will look into it.

**Comment by ccbogel** [comment]
hmm, that should not have happened, but  I have added an error catch around it

**Comment by ccbogel** [comment]
if this happens again, please open an issue
