### ISSUE TITLE
Coding reports interface improvements 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#169]
In Coding reports, the list of Files/Cases/Attributes Selected can be misleading if the items are not separated clearly. Eg multiple spaces and periods can conceivably be part of a longer filename: "Filename 1.ext Filename 2.ext". Also a x/y files/cases/attributes (and x/y codes) selected would be nice there. 

Pedantry alert: Would Files | Cases | Attributes selection (plural) be better in telling users they can select multiple items?  

Would a frame around Selections and Search inform users they are part of the same process? Would Retrieve (as is 'code and retrieve') be better than Search which can also be confused with 'search text'?

For decluttering, could the 3 selection buttons be merged into a button + menu? Ie Select scope... > Files | Case Attribute. Similarly, Export... > html, ODT, text, csv (btw, why is ODT (the only one) capitalised?)

**Comment by ccbogel** [comment]
HI. I'm not sure what you mean by the x/y comment. - perhaps put a new issue up for this
Now using a semi-colon for separation of names.
I like seeing the 3 selection buttons - have renamed them.
Have moved exports into a combobox.
changed the wording from Search text to Text limiter.

**Comment by glocalglocal** [comment]
> Now using a semi-colon for separation of names.

semicolon can also be part of a filename as in "Filename 1.ext; Filename 2.ext" (an odd filename but possible). How about '|' which is an illegal character?
