### ISSUE TITLE
Uncaught Exception while importing  PDF

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#17]
I get this:

Traceback (most recent call last):
  File "/usr/share/QualCoder/manage_files.py", line 392, in import_files
    self.load_file_text(f)

  File "/usr/share/QualCoder/manage_files.py", line 469, in load_file_text
    doc.initialize('')

  File "/usr/share/QualCoder/pdfminer/pdfparser.py", line 455, in initialize
    raise PDFEncryptionError('Unknown filter: param=%r' % param)

PDFEncryptionError: Unknown filter: param={}

While trying to import a PDF for testing on Lubuntu 16.04 (QualCoder 1.0).

Edit: seems that other PDFs works ok, but I am always able to reproduce this if I try to import: http://www.24grammata.com/wp-content/uploads/2013/05/arabian_nights-24grammata.com_.pdf

It is a freely available version of arabian nights.

Could the PDF be too big for QualCoder? (it is 255 pages).

**Comment by ccbogel** [comment]
HI, no the pdf is not too big. The pdf is encrypted and pdfminer cannot uncrypt it. I will use another tool called qpdf to uncrypt this on import. It will not work on password protected pdfs though. Will upload a code update for this soon.

**Comment by ccbogel** [comment]
The Arabian Nights pdf now loads. It takes 10+ seconds, so you need to wait a bit. This fix currently only works for Linux, I warn users of non-linux OSes to decrypt using qpdf first if they get an encryption error.
