### ISSUE TITLE
OK / Cancel buttons

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#170]
Manage Files / Add Attribute: There is no Cancel button. You can of course delete the text and click OK to achieve Cancel. I think the same happens elsewhere . 

Manage Files / View: OK and Cancel do the same thing when you haven't edited the text. Again, I think the same happens elsewhere.

**Comment by ccbogel** [comment]
added cancel to Add Atribute

**Comment by ccbogel** [comment]
OK I fixed those in Manage files View. Raise another issue if it is elsewhere.

**Comment by glocalglocal** [comment]
> OK I fixed those in Manage files View

I don't see the difference. There are still OK and Cancel available and they do the same thing.

**Comment by ccbogel** [comment]
Cancel does not record any changes made to a text file.

**Comment by glocalglocal** [comment]
Not sure about this but should both cancel and OK be available if there are no changes?

**Comment by ccbogel** [comment]
Its a default set of buttons, that  I would be best not to change.
