### ISSUE TITLE
Manage Files / View file: there is no Select all/copy in menu

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#171]
The right-click menu lacks the usual Select All/Copy.

**Comment by ccbogel** [comment]
this is a bit of extra work - is it needed?

**Comment by ccbogel** [comment]
just tested this. should be fine now

**Comment by glocalglocal** [comment]
I don't see this either. I am wondering if I don't have the right update.

**Comment by ccbogel** [comment]
I notices i had to right ckick on text for it to work, rather than blank space

**Comment by glocalglocal** [comment]
Just tried it again and it doesn't work here.

**Comment by ccbogel** [comment]
fixed now
