### ISSUE TITLE
Manage Files/Restricted edit

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#172]
I think I can by-pass the restrictions by editing repeatedly in small 20-char blocks. If this is true, is it safe?

**Comment by ccbogel** [comment]
It should be safe, but I don't want to guarantee it - especially of you have lots of important work. As I did a lot of testing of this functionality some time ago, as a feature recommended to be added by another user. I much prefer all edits are performed before doing any coding etc.

**Comment by glocalglocal** [comment]
> I much prefer all edits are performed before doing any coding etc.

Well, yes, I am just stress testing. It would be good to be able to edit texts any time, but I can see why this is bad.

**Comment by ccbogel** [comment]
Yes, thanks for your thoroughness. Even tho it gives me I am guessing a lot of work ahead. this is why some issues have not been addressed yet. I start with the easier ones first.
