### ISSUE TITLE
Deb files and zip files for linux install are labelled 1.9 but install 1.8

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#176]
Thank you for a great an much needed tool! Looking forward to next major version and would be happy to beta test it.

The deb files you offer as well as the zip files for the manual linux install version

QualCoder 1.8 2020 March 11

even though the downloaded files are labelled 1.9 .....1.8 is behind the latest 1.9 version in the releases so I am unsure if errors are due to the older version. Please make 1.9 available for download and installatoin on linux as both deb and zip

**Comment by ccbogel** [comment]
That is the 1.9 version, I forgot to update the About information from 1.8 to 1.9.
I will do a 2.0 version once the majority of the issues that are listed are updated.
I am happy that you like QualCoder.
