### ISSUE TITLE
RQDA project import does not work

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#178]
RQDA files are not seen by the RQDA project import file browser. Even renaming them to qda to match the only file type listed in the file browser does not make them show up.

This would be a crucial feature - for interoperability with R it would also be great if Qualcoder files cold be imported into R for quantitative analysis of codes.

Once again - thanks for a great project

**Comment by glocalglocal** [comment]
This may be a version issue. I have tested importing from RQDA extensively, and after some fixing, this now works well on Windows 10. It is looking for .rqda files. Are you sure you are not confusing the first dialogue that opens (Enter project name) with the dialogue where you input the rqda file? I made this mistake several times (and again, just now).

**Comment by ccbogel** [comment]
HI. I will add an extra information dialog that described the two steps involved to reduce confusion about the process.
I would need a lot of information about exactly what would be needed for import int R. Perhaps think about this and post s separate issue.
