### ISSUE TITLE
Key feature "Show coded text and Media" does not work

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#179]
Edit: I now found the codes underneath the about text. I am leaving this here for documentation purposes - and because I still hope that it will get fixed. Since the text is there its not a show stooping bug but user experience, focus on context and ability to copy code text would be better if there was immediate access to the coded text.

original issue:

I have installed qualcoder on different versions of Ubuntu in an attempt to get rid of this bug - unfortunately it persists and renders qualcoder barely usable: When clicking on "Show coded text and media" a window with the correct title but the  contents of the about qualcoder window opens. The correct code color is displayed in snippets that overlay the contents of about window. What i believe to be code positions is also displayed:

File: Transcript FG7.txt, Coder: default , 1133 - 1144File: Transcript FG7.txt, Coder: default , 1479 - 1885

Whats missing is a compilation of the actual coded text snippets as displayed eg in RQDA and many other qualitative coding software when using a comparable option. 

Am I misunderstanding the option or is this an error? I believe this is a key feature, browsing coded text in that way is important for analysis and creation of categories.

**Comment by ccbogel** [comment]
Is this from the Debian file, or from the latest zip download here?
There was an error -in that the coder name needs to be selected to show the coded text. otherwise nothing is seen.
Go to Settings and select a codername from the drop down box.
In the latest zip from here (not the Debian) this issue is resolved, as qualcoder sets a coder name from the RQDA file.

**Comment by ccbogel** [comment]
@menelic OK I have put out a new release. It was a lot quicker than I thought. Let me know how it works for you.
