### ISSUE TITLE
Add epub support

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#18]
I got this idea by looking at taguette's website. Epub is an open format and there is plenty of material available in that format. Therefore I think it would be useful to being able to handle epub files in QualCoder.

**Comment by ccbogel** [comment]
Thats a good idea. I will look into it.

**Comment by ccbogel** [comment]
I have added the ebooklib library from: https://github.com/aerkalov/ebooklib
and with a couple of modifications it to imports ebooks. I have only tried one epub book which  I have added to the examples folder.
