### ISSUE TITLE
Slightly dIfferent coding instance between Win 10 and Mint

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#180]
I opened a coded file in Code Text on Linux Mint and it looked slightly different from my Win 10 setup. The coding was: Coding 1+Coding 2+Coding 3 (three differently coded sentences back-to-back) and the whole paragraph containing these was coded with Code 4. On Windows it looked OK. On Mint there was a single space between coding 1 and 2, so there was no overlap there -- ie it was only coded with Code 4 (the one for the whole paragraph). I spotted it immediately because it was a single space in a different colour from the sentences just before and after. Strange and may suggest there is an issue.

**Comment by ccbogel** [comment]
Interesting and potentially an issue.

**Comment by WPFilmmaker** [comment]
@glocalglocal any update on this? I am going to work with QualCoder in a mixed environment Lubuntu/Windows 10, should I worry?

**Comment by glocalglocal** [comment]
@WPFilmmaker I replaced that Mint setup with Debian and then the HD died! I will fix it one day, but in the meanwhile I just tried Qualcoder 2.1 on Raspberry Pi OS (a Debian derivative) for you and I don't see the issue. I will probably try later with another Mint setup I have. My guess is codings occasionally shifted one or two places because of the different way Windows and Linux probably represented special characters if any where present (ie depending on the setup, certain characters take 2-3 characters to be represented). I seem to remember Colin did something about that which may have fixed this one. I think you could go ahead and report back if you encounter the issue again.

**Comment by ccbogel** [comment]
I make an adjustment to importing text files. It might have fixed this issue. But i have no good way of testing for it.

**Comment by ccbogel** [comment]
I cant resolve the issue, but have acknowledged it in the manual.
