### ISSUE TITLE
Linux Mint on underpowered machine impressions 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#181]
Experimenting with Linux Mint 19.3 xfce I noticed: 
* The menus don't have a frame and blend into the background. 
* The minimize/maximize etc window menu is on the left like on Ubuntu, which clashes with the rest of the environment. 
* 'Are you sure you want to exit?' -- The default is 'No' unlike Windows. 

This is a very underpowered machine and qualcoder worked amazingly fast. With a screen resolution of 1024x800 the system is a good test bed for clutter and screen real estate efficiency. When you see qualcoder in that screen you realise how much space can/should be saved, esp in the vertical.

**Comment by ccbogel** [comment]
Ok interesting to note. May of the visual differences will depend on how the Qt framework is implemented on different OS's. Definitely out of my scope.
Good to know it is fast enough on an older machine.
