### ISSUE TITLE
Interoperability with R 

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#182]
QualCoder is a great RQDA replacement and already has more functionality such as coding audio and video. However, for multi-method analysis eg of surveys with quantitative and qualitative items it would be crucial to be able to enhance interoperability with R. igraph based visualization of codes, code categories and their relationships, correlating codings with quantitative items and other functions are what made RQDA such a handy tool.

As a first step, maybe you could offer RQDA export as well - I assume its easy to implement since you are already ofering RQDA import.

Maybe an integration of  qcoder which strives to be a RQDA replacement that implements some REFI-QDAstandards as an R package could be anothe rpath to  interoperability https://github.com/ropenscilabs/qcoder (repo looks a bit stale but they will resume work this summer https://github.com/ropenscilabs/qcoder/issues/195) cogmapr is a fork or qcoder that adds some functionality https://frdvnw.gitlab.io/cogmapr/

**Comment by ccbogel** [comment]
This is not a high priority for me at the moment.
I am not keen on doing an RQDA export, particularly as RQDA is not being currently developed.
I do need to know a of detail about the data that you want exported for use. I would anticipate a csv file that can then be imported into an R dataframe.

**Comment by ccbogel** [comment]
@menelic Actually, I thought to mention that the sql dialog can export tables of data to import into R. Also the core data is stored in data.qda a sqlite3 file, which you could directly access using R sqlite functions.

**Comment by menelic** [comment]
@ccbogel thanks for this - yes we are already exploring this possibility. We hope to be able to leverage QualCoder codings for visual analysislike this https://lucidmanager.org/data-science/discourse-network-analysis-literature-review/ - not for literature reviews but other analytical use cases.

**Comment by menelic** [comment]
@ccbogel another reason why I still believe R interoperability could be attractive for QualCoder is that it could improve the visualisation of codes and code relationships without having to implement al functionality n QualCoder. That said, I believe QualCoder would gain from implementing the interactive aspects of Graph visualisation that RQDA offered. I believe RQDA achieved this with igraph, which is available as a python package: https://igraph.org/python/ and  i believe partly with D3, so maybe https://github.com/altair-viz/altair/issues would provide a (semi-)pluggable solution with python. 

I am unsure to what extent the RQDA relation function determines RQDA visualisation of code relations.

**Comment by ccbogel** [comment]
@menelic I looked at the lucidmanager site. I see that they use a RQDA function called getCodingTable() 
This function returns cid, fid, codename, filename, CodingLength, index1, index2 
According to this: [https://rdrr.io/rforge/RQDA/man/getCodingTable.html](https://rdrr.io/rforge/RQDA/man/getCodingTable.html)
I have replicated this function in the SQL Dialog - under the joins section, so you can export the table and import it into R to redo some of the R code that is shown on the website:
![sql](https://user-images.githubusercontent.com/5834638/97292598-8d095d80-189f-11eb-84a7-dcf7840a4a1e.png)

**Comment by ccbogel** [comment]
I previously had another software developer use igraph for python, but it did not install on all systems. So I avoided it, however  I might look at it again, it might need a minimum python version for it to work.

**Comment by Emily-2000** [comment]
Hi
I imported my previous RQDA project into QualCoder 2.2. It says:

=========
Data import unsuccessful from ....FileName.rqda.
Project memo: 
Files: 65
Cases: 7
Code categories: 14
Codes: 203
Attributes: 0
Journals: 1
=========

It has imported all 65 files, but only 2 of them seem to have codings. 63 files are text only, no colours, no codings.
Where have all my codings gone? How can I save the tremendous work I have done for my PhD research?
Can anyone pls help?
Shall I upload here the original rqda file? Or send it to anybody who is willing to help?  

Thank you in advance for any positive reply.

**Comment by ccbogel** [comment]
Thsnks for emailing the file Emily.  The latest improvements now account for duplicated codings which rqda allowed. Before the fix it caused a sqlite integrity error .

**Comment by ccbogel** [comment]
Closing this issue now as I cannot do any more to make it work with python. As mentioned above, QualCoder can export csv files which you can import into R for further use.
