### ISSUE TITLE
Coding reports x/y info

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#185]
Clarifying earlier point, in Coding reports, Files/Cases/Attributes selected could also show x/y (ie 2 out of a total of y) in addition to the list of files/cases/attributes. Eg 'Files Selected (2/10): File1 | File2' 

or '2/10 files selected: ...' 

I think generally, every time such info can be made available, it should. It improves the workflow considerably at no cost. Eg it makes a big difference when an OS file manager shows number and aggregate filesize of selected files out of the total number of files and size for the folder. It is a pain having to count items when you are in the middle of something. 

BTW, in 'Files Selected:File' there is currently a space missing after the colon.

**Comment by ccbogel** [comment]
Totals are now in Files, Cases, Journals, Attributes Case File manager. Selected counts are in those where multiple selection is available.

**Comment by glocalglocal** [comment]
I don't see the total in Manage Journals but I see the 'Journals:' text. 

I don't see the x/y in Coding Reports.

**Comment by ccbogel** [comment]
Forgot to upload the Journals.py file. fixed this. working on coding reports.

**Comment by ccbogel** [comment]
completed
