### ISSUE TITLE
Suggestion: Code freq report export file in importable format

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#188]
I think it would be useful to make the exported file a .csv or otherwise importable. 

IMV, the project frequencies could be displayed alongside the current code freqs in Code File, making the separate report redundant, but if the separate report remains and exports a file, it could be made importable for further analysis.

**Comment by ccbogel** [comment]
I will see if  I can add a sql that develops this for export in the sql dialog.

**Comment by ccbogel** [comment]
ok export csv button and method is done
