### ISSUE TITLE
If a file is not support QualCoder should show warn users

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#19]
I tried to import an epub file and QualCoder did not warn me such format is not supported. Nothing happened. I think it makes sense to warn the user if a file is not supported, either via popup or in the qda file log (maybe both?).

**Comment by ccbogel** [comment]
Yes I know why this happened. When importing - it recognises a few file types - so tries to import docx as docx , odt as odt, pdf as pdf, png for png etc but for everything else, I have it default to presuming a text file and try to import as plain text. For example on Linux you can have any or no file ending to denote the file type and these can often be text. OK so if zero bytes gets imported as a presumed plain text file, I will warn the user.

**Comment by ccbogel** [comment]
I have added a warning dialog which states an unknown file type which is not imported.
