### ISSUE TITLE
Meta: Setup feature templates

### ISSUE THREAD

**Issue by jdittrich** [ccbogel/QualCoder#197]
**Story:** As a user or contributor I want to write useful issues
**Story:** As a contributor I want to manage issues easily.

**Problem:** Issues might easily contain multiple issues, lack instructions to contribute or make it hard to distinguish between bugs and feature requests.

**Possible Solution**:  Github provides issue templates. They setup is described in [configuring issue templates for your repository](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository).

**Comment by ccbogel** [comment]
OK thanks. I have added a Bug template and a FEatures template. I am not sure how they are used at this stage.
