### ISSUE TITLE
Manage Files/Export produces 2 files

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#199]
I select a file.md and click on Export and get a message that looks like it's asking me to confirm I want to export the file but it's not entirely clear. I click OK but I get two files created and a confirmation listing them: file.md and file.md.txt.

**Comment by ccbogel** [comment]
Yes thats correct. All exports will do 2 files, one is a transfer of the original (whatever its format) and the second is an export of the text stored in the sqlite database.

**Comment by glocalglocal** [comment]
I think it is very rare users will need both of these (and may be confused when they get file.txt.txt) . The first 'Export files' could ask if the user wants one, the other, or both.

**Comment by ccbogel** [comment]
Changed this to export any imported files only.
Text files created separately within the sqlite database area also exported.

**Comment by glocalglocal** [comment]
I still get the same two files.

**Comment by ccbogel** [comment]
tryit gain.it should only export 1 now.

**Comment by glocalglocal** [comment]
It now exports the file I imported only -- without the txt version. This .docx is unchanged, the file I imported, right? I am guessing that if there is no imported file, but the file was created within qualcoder, then the text is taken from the database.

**Comment by ccbogel** [comment]
Yes thats correct.
