### ISSUE TITLE
logs are too big + questions

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#20]
I was trying to attach a log #16 and#17, and realized that  logs in QualCoder.log are humongous. They are 16mb (for a text file!) and over 200.000 lines...I don't think it is normal.. it is too big for pastebin.com and if I try to paste it here github throws a 405 error...

Also does QualCoder.log get overwritten every time QC crashes? Because I suspect logs for 16 got overwritten by the one for 17. It would be useful (IMHO) being able to produce different logs for different errors.

I am on Lubuntu 16.04.3 QualCoder 1.0

**Comment by ccbogel** [comment]
HI, the log gets appended and never over-written. I will change that so that on opening QualCoder the log file is cleared. When you imported the arabian knights - i think all the pdf errors got sent to the log too, which would have made it huge. (I was looking at my log file).

**Comment by ccbogel** [comment]
OK log file is cleared on first opening, so that file sizes are not massive.
