### ISSUE TITLE
Suggestion: Manage Files/Export default folder 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#200]
I think when we change folder to export a file and then try to export another one, qualcoder should remember the folder selected earlier at least for that open dialogue, rather than revert to the default folder every time. I think this is the convention and may apply to other dialogues too.

**Comment by ccbogel** [comment]
OK I think I can implement this

**Comment by ccbogel** [comment]
I think this is now implemented in all spots
