### ISSUE TITLE
Bug: Manage Cases: View shows files of last case selected out of several selected

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#202]
In Manage Cases I can select 2+ cases. Cases: x/y looks OK but the text in the right pane only shows the files linked to the case I select last. Yet, the multiple selected cases in the left pane remain selected.

**Comment by ccbogel** [comment]
fixed

**Comment by glocalglocal** [comment]
This persists. I would expect to see all files for the selected cases to be displayed.

**Comment by ccbogel** [comment]
What I did was to display no files where multiple rows (cases) are selected. 
And only show one case's files where a case is selected. Otherise it would get confusing.

**Comment by glocalglocal** [comment]
It makes sense but I select 2+ cases and get the files linked to the case selected last as before.

**Comment by ccbogel** [comment]
ah, I see now. I used mouse and clicked and dragged to multiple cases- it works in this situation, but not if I use ctrl and select various cases.

**Comment by ccbogel** [comment]
fixed now
