### ISSUE TITLE
Req: Foregrounding obscured dialogues 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#204]
I open a dialogue, eg Manage Files. I switch tasks and the dialogue is lost behind other applications. I forget about the dialogue being open and click on Manage Files. Nothing happens because the dialogue is already open. It happened on several occasions and I thought the dialogue didn't open because of a bug. Can open dialogues be brought to the foreground in these circumstances?  

This is particularly annoying when an error message is displayed somewhere in the background, or when the only way to get to a dialogue is to minimize another application when/if you realise what is going on.

**Comment by ccbogel** [comment]
OK I have tested an implementation of this.
Manage files, cases, journals only open one window. (although they are non-modal)
For these,if opened, now they should appear at the front.
Let me know if it works for you

**Comment by glocalglocal** [comment]
It does work for those top-level dialogues but not second-level dialogues like Manage Files / View File -- and I get a beep when I click on the wrong app window while one of those second-level dialogues is open.

**Comment by ccbogel** [comment]
I am not sure I can resolve this. One approach is to limit how many dialogs of one type are opened. eg only have one view file dialog opened at a time. what do you think?

**Comment by glocalglocal** [comment]
The beep/obscured window problem is surprisingly common and very annoying but I think we can live with this if we must for the advantage of being able to work with multiple files concurrently. However, as discussed in #150 , I think avoiding clashes is essential. Eg I can open two instances of the same media file for transcribing. Not sure what happens with the .transcribed file -- something bad I am sure.

**Comment by ccbogel** [comment]
Yes, I have made changes to reduce the number of dialogs that can be opened.
So all coding dialogs for example - you can only open one of each type at one time. As mentioned - this will also avoid clashes too.

**Comment by ccbogel** [comment]
OK so I have limited the number of dialogs that can open at a time.
In Mange files, you can only have one dialog open at a time. tying to do more than this will get a beep, as you need to close the opened viewing dialog first.

**Comment by glocalglocal** [comment]
There is a problem with this. When you work with an open dialogue eg open a media file, you can't access the main window at all (eg settings, project summary, reports, temp notes).

**Comment by ccbogel** [comment]
Yes. I made these modal dialogs - so that they are the only ones you can interact with. 
OK so  Iwill chagne the approach here.
