### ISSUE TITLE
Bug: Error when I selected a recent project to open

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#205]
It happens with a specific project. It opens when I open another project first. Then I open another one and try this one again, and I get the error again.  

ERROR manage_files.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 595, in project5
    self.open_project(self.recent_projects[6])

IndexError: list index out of range

**Comment by ccbogel** [comment]
I cant recreate this error yet, but  I have added some code that hopefully mitigates it.

**Comment by ccbogel** [comment]
i found an error in my coding.fixed now
