### ISSUE TITLE
Bug? 17 BKUP folders

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#206]
and 11 for another project. I am not sure up to how many backups qualcoder is set to keep, but 17 sounds a lot.

**Comment by ccbogel** [comment]
I have not set it to keep a certain number of backups.
I have tried to implement - no backup made if no changes are made. 
I have changed the backup frequency by only storing the date and hour in the backup name. So a second backup within the hour would not occur as an existing backup with that date and hour would be present.

**Comment by glocalglocal** [comment]
This way you can get any number of backups over time which means the user is expected to delete backups manually through the file manager. I think this is a problem with RQDA too.

**Comment by ccbogel** [comment]
I could try and delete older backups, but I run the risk of deleting an important backup, say if you did some substantial change 8 backups ago?

**Comment by glocalglocal** [comment]
The same applies to all backups and restore points, but there is typically a limit. You could put the number of backups in the settings and let the user take responsibility/control.

**Comment by ccbogel** [comment]
OK for a start. I have made it so that Qualcoder keeps the 6 most recent backups and deletes the older ones.

**Comment by glocalglocal** [comment]
It doesn't seem to reduce the number of older backups to 6. And while switching between projects to test, I got the error below, displayed in very big font in a dialogue: 

ERROR __main__.exception_handler Uncaught exception : Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 613, in project5
    self.open_project(self.recent_projects[6])

IndexError: list index out of range

**Comment by ccbogel** [comment]
the error is fixed now.

**Comment by ccbogel** [comment]
ok I had a lot of backups, now it deletes all the older ones, keeps 6 most recent
