### ISSUE TITLE
Bug? qualcoder.log not trimmed

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#207]
I think the plan was to trim qualcoder.log Currently, mine goes back to 2020/07/08. I doubt it has ever been trimmed. Just checking.

**Comment by ccbogel** [comment]
It should roll over after filled with 4000 bytes into two backup logs. This is how I have set up the logger and it works for me.

handler = RotatingFileHandler(logfile, maxBytes=4000, backupCount=2)

**Comment by glocalglocal** [comment]
I have only one file, QualCoder.log 41kb, first entry 2020/07/08. It seems to grow unrestricted.

**Comment by ccbogel** [comment]
OK, if you open the qualcoder.py file around line 80 - it should show that line with the rotating file handler.
I wonder if there is an error on Windows around its implementation?
You can delete the log file.

**Comment by glocalglocal** [comment]
I see the line in qualcoder.py and I don't see anything wrong with it. I don't see people complaining about RotatingFileHandler() not working. I deleted the logfile to see if it works when it is recreated from scratch.

**Comment by ccbogel** [comment]
ok. will see what happens i guess.

**Comment by ccbogel** [comment]
this issue should be resolved. It is at my end. can you let me know on your end please.

**Comment by glocalglocal** [comment]
I will check when it grows a bit more and let you know.

**Comment by glocalglocal** [comment]
Started from scratch, currently 6,221 bytes and growing. I'll keep monitoring this.

**Comment by ccbogel** [comment]
hmm. it works fine for me on Ubuntu. I googled, and see that can sometimes be error on Windows. I might have to add a note to the Manual to tell people using Windows to delete the log file once in a while when it gets too big.
Or, on opening qualcoder, automatically delete it if it is very large?
I cant find another solution to it.

**Comment by glocalglocal** [comment]
Would TimedRotatingFileHandler perhaps be more reliable?

**Comment by ccbogel** [comment]
actually, I am getting a PermissionError in the console on Windows. The process cannot access the file because it is being used by another process.

**Comment by glocalglocal** [comment]
Can't qualcoder read the file (a) when it starts or (b) every time an entry is added to the log, and if length is greater than, say, 10kb replace the file with a subset, say 8kb? Only possible problem I can imagine is that (a) won't be very reliable if the user never restarts qualcoder.

**Comment by ccbogel** [comment]
Yes implemented this. keeps last 1000 characters

**Comment by glocalglocal** [comment]
The latest error logged here is 691 characters long. Is 1000 chars long enough as the min?

**Comment by ccbogel** [comment]
I can make it 2000 chars easily

**Comment by glocalglocal** [comment]
My log file is 14kB. First entry is dated 2020/07/27 (when I deleted the log file to start from scratch with the new trimming algorithm).

**Comment by ccbogel** [comment]
@glocalglocal aother Uploaded another attempt at resolving this issue

**Comment by glocalglocal** [comment]
On start I received the error below and then qc exited. This is the whole of the log file content. 

> Added window sizings to config.ini
> 2020/10/01 13:46:42 INFO __main__.check_and_add_additional_settings Added window sizings to config.ini
> Uncaught exception : Traceback (most recent call last):
>   File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1585, in <module>
>     gui()
> 
>   File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1580, in gui
>     ex.open_project(path=proj_path)
> 
>   File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1289, in open_project
>     self.project_summary_report()
> 
>   File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1403, in project_summary_report
>     msg += "\nText Bookmark: " + self.app.settings['bookmark_file_id']
> 
> TypeError: can only concatenate str (not "int") to str
> 2020/10/01 13:46:44 ERROR __main__.exception_handler Uncaught exception : Traceback (most recent call last):
>   File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1585, in <module>
>     gui()
> 
>   File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1580, in gui
>     ex.open_project(path=proj_path)
> 
>   File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1289, in open_project
>     self.project_summary_report()
> 
>   File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 1403, in project_summary_report
>     msg += "\nText Bookmark: " + self.app.settings['bookmark_file_id']
> 
> TypeError: can only concatenate str (not "int") to str

**Comment by ccbogel** [comment]
Ah thanks. Funny how different machines sometimes ignore this error (mine!).
Fixed now.

**Comment by glocalglocal** [comment]
qc working now although the log shows: 

> 2020/10/02 12:41:12 ERROR __main__.clean_dialog_refs wrapped C/C++ object of type DialogCodeText has been deleted

I filled it the file with multiple copies of its content to make it 7kb. I restarted/exited qc and the file remained unchanged -- 7kb.

**Comment by ccbogel** [comment]
Goof. That error is not a major issue. Will try n catch it.
