### ISSUE TITLE
Req: Python/VLC 32/64bit compatibility 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#209]
I know both VLC and python installations will have to be 32 or 64 bit. Is there a way around this at all? Many users will find themselves in a similar situation as me, with VLC 64bit and Python 32bit installed because these are the default versions you get without even being asked. 

I may use the audio transcribing/coding feature with real interviews for the first time, and I may have to replace and reconfigure my version of VLC.

**Comment by ccbogel** [comment]
the bit architecture has to match for any connectivity to occur.You have to replace or reconfigure one or the other.
Even then, sometimes VLC is not detected - which is an issue  I struggle to resolve

**Comment by ccbogel** [comment]
ok, I did some searching and found some extra code that helps to locate the libvlc.dll file
Hoping it will work for you now, it works on my work Win 10 machine.
Re the tiny font issue - this one I cannot resolve due to the error-handler being outside of any classes that use the font settings.

**Comment by glocalglocal** [comment]
The Media Coding dialogue opened now. I also get the pythonw black window (with a 'What's this' question mark). I don't see its purpose so far. Can it be suppressed?

**Comment by ccbogel** [comment]
The whats this - yes I have to remember to remove that. Its a default thing.
Otherwise - thats great you have two windows open - the black window will show the video, when you load it up

**Comment by glocalglocal** [comment]
The titlebar also shows the X (close window) greyed-out. It doesn't do anything and perhaps it should be removed. The titlebar could be removed completely, if there is another way to grab that window to move it. That 'pythonw' confuses things.

**Comment by ccbogel** [comment]
The x- does not show on Ubuntu.  will look at it on Win.
The title bar is needed for moving the window. I dont know what 'pythonw' is. 
Again on Ubuntu it shows either 'qualcoder.py' or when a video is loaded, the video name. But will see if I can replace the title when no video is loaded.

**Comment by glocalglocal** [comment]
Apparently, 'pythonw.exe' does what 'pyw.exe' does -- suppressing the console window. I didn't know [that](https://stackoverflow.com/questions/9705982/pythonw-exe-or-python-exe#30313091). I run qualcoder with pyw.exe. 

pythonw is replaced with the media name when loaded. 

Sometimes you can grab a head-less window from any point, including the middle, to move it. I suppose you meant that was not possible.

**Comment by ccbogel** [comment]
I like the title bar, I dont think i can remove the greyed out x
