### ISSUE TITLE
Uncaught Exception when renaming a category

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#21]
1 add a category
2 name it
3 rename it and press enter to apply renaming
4 results in:

Traceback (most recent call last):
  File "/usr/share/QualCoder/code_text.py", line 347, in tree_menu
    self.rename_category_or_code(selected)

  File "/usr/share/QualCoder/code_text.py", line 675, in rename_category_or_code
    + self.codes[found]['name'] + " to: " + new_name)

IndexError: list index out of range

If you click "ok" the renaming works fine.

IndexError: list index out of range

I am on Lubuntu 16.04.3 QualCoder 1.0

**Comment by ccbogel** [comment]
Thanks - a programming error. Now fixed.
