### ISSUE TITLE
Bug: tiny font in VLC not being recognised error dialogue

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#210]
I tried to code audio/video and get this:

A/V Coding 
'name 'vls' is not defined

This is probably what you meant that vlc may not be recognised, so you know about this already. (I just installed Python x64 and I had VLC x64, so I can't do much about this). 

But this issue is about the tiny font in the message.

**Comment by ccbogel** [comment]
hmm. would like to look into that further. is there a more detailed log entry?

**Comment by glocalglocal** [comment]
The full content of the new log (after I deleted the file) is below. Oddly, it doesn't start with the date.  

name 'vlc' is not defined
2020/07/27 02:30:32 DEBUG __main__.av_coding name 'vlc' is not defined
name 'vlc' is not defined
2020/07/27 02:30:55 DEBUG __main__.av_coding name 'vlc' is not defined

**Comment by ccbogel** [comment]
Actually I cannot fix this instance of the tiny font.
I have added extra code to show a message box with hopefully more information.
there is a file on your system called vlc.dll - it would be good to know where it is located, as the program is looking for this.

**Comment by ccbogel** [comment]
see other comment - I added code to help locate the lobvlc.dll file
I may not be able to resolve the tiny font.

**Comment by glocalglocal** [comment]
Code audio/video opens now (together with the pythonw window).

**Comment by ccbogel** [comment]
I will close this now. 
Perhaps import a small video file and view it.
