### ISSUE TITLE
How to be notify a release ?

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#211]
**Is your feature request related to a problem? Please describe.**
Hello ! Now, we have a problem with QualCoder : we don't know, if we don't get to the github page, if we have a relase of qualcoder.

**Describe the solution you'd like**
A clean solution it's to create a repository. We have already the .deb. [We have an example with Zotero](https://github.com/retorquere/zotero-deb).

**Describe alternatives you've considered**
A other solution it's to act like Zettlr : a modal window to notify a release.

**Additional context**

**Comment by ccbogel** [comment]
A good issue to raise.
I will put a release (and Debian) here: https://github.com/ccbogel/QualCoder/releases
I will get QualCoder to check and display the latest release version on opening.

Once I fix/update/add some of the current issues raised, I will also put a new debian in the [https://github.com/ccbogel/QualCoder-Debians](https://github.com/ccbogel/QualCoder-Debians).

**Comment by qwertygc** [comment]
OK : the update is manually (like Zettlr) or use a repository (like zotero) ?

**Comment by ccbogel** [comment]
OK i get qualcoder to check the releases part of github. It will highlight in red if a newer release is avaiable
