### ISSUE TITLE
Bug: Video playback and slider

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#214]
Video playback: it's working but...

I start playback, I drag the slider to a new position, it jumps back to where it was, and then to the new position. I would expect it to stay where I left it. This stopped happening after a while. 

While the video is playing, if I click somewhere on the timeline, the slider doesn't jump there. It 'shakes' and returns where it was. Playback is uninterrupted. 

When the video is paused, if I click on the timeline, the slider moves to the next stop in the direction of where I clicked. When I unpause, it jumps back to where it was when I paused. This also happens when the video is stopped, the same thing happens but the starting point is the beginning of the video.

**Comment by ccbogel** [comment]
yes. that is an issue that I have not delved into yet.

**Comment by ccbogel** [comment]
Yes, sliders are a bit special. You have to click and hold on the slider handle to move it to a new position. Just clicking (left of right) of the current spot does nothing (apart from the little temporary jump).
The stop button, yes,I made it reset to the start. but it is not needed, as the play/pause button does the job. so best if I remove that Stop button.

**Comment by ccbogel** [comment]
I have removed the stop button, whichwas not needed. but to make the slider work dragging it is the only way.

**Comment by glocalglocal** [comment]
If ctrl+s stood for start/stop, shouldn't that now be ctrl+p for play/pause?

**Comment by ccbogel** [comment]
good point. can adjust this. or have both.

**Comment by ccbogel** [comment]
implemented
