### ISSUE TITLE
Bug: while viewing video, volume resets to max 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#215]
While stopping, pausing, starting etc to test the slider, the volume reset to max from 50%. I think the last thing I did was stop/play (ie from start). 

Then I moved the slider while the video was playing and volume maxed out again but the volume slider didn't move -- it remained at 50%. I continued playing with the slider, pause etc. and the volume slider remained at 50%. When I move it to 100% the volume didn't change -- it was already maxed out anyway.

**Comment by ccbogel** [comment]
I think like the other controller issues, I found this hard to manage.

**Comment by ccbogel** [comment]
I have tested this on Ubuntu. (after some other changes made). So far this is not happening. Will check on Windows also.

**Comment by ccbogel** [comment]
This seems ok on Windows also. If you dont report any further problems,  I will close this issue.

**Comment by glocalglocal** [comment]
Looks OK so far.
