### ISSUE TITLE
Req: Media playback controls

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#216]
In transcribing, it is hugely important for efficient workflow to have full control of the media without having to use the mouse for efficient workflow. IME, it really makes all the difference when transcribing hours of material.  
a. There should be (user configured) keyboard shortcuts for at least pause/unpause (with skip back, skip back/forward x seconds)
b. Ideally, for pro work, qualcoder would be able to read [foot pedals](https://www.altoedge.com/pedals/index.html) connected to the USB like [Express Scribe](https://www.nch.com.au/scribe/index.html) and others do. From what I found out a while back, there are generic foot pedals and known ways to map the USB interface. 
c. a complete set of buttons for clicking with the mouse (inc skip forward/back)

EDIT: The shortcuts in the manual don't work at all.

**Comment by ccbogel** [comment]
Yes some of this is already there.
In manage files, view file. open the video.
This is before any coding is done:
The transcription text pane must have focus, in there you can use the ctrl functions below:
ctrl + s to stop/start
ctrl+r to rewind 3 seconds
ctrl + t to enter a time stamp
ctrl + n to enter a new speakers name
ctrl + 1 -8 to enter the selected name into the text

**Comment by glocalglocal** [comment]
I added the 'EDIT' above too late. The shortcuts don't work. 

Aha, so the names are defined with ctrl+n. Nice. I hope they can be changed later and the names will be replaced in the transcription.

**Comment by ccbogel** [comment]
Experiment with it. I am no expert with video qual analysis. But did what I could to make this aspect work. I am sure you will let me know. Controlling VLC via python is not ideal - so some of the controllers (sliders etc) may not be possible to improve a great deal. But will try. OK must be off, its late here.

**Comment by glocalglocal** [comment]
> Experiment with it. I am no expert with video qual analysis. 

I meant literally they don't work. Nothing happens when I press ctrl+t, r, etc. I am not into video qual analysis either. Personally, I am interested in transcribing interviews. Video researchers may comment once the improved version is out and adopted by more users.

**Comment by ccbogel** [comment]
OK sorted this. Windows uses a different number for the ctrl key.

**Comment by glocalglocal** [comment]
Still not working.

**Comment by ccbogel** [comment]
Are you in the transcription text pane?
As these controls will only work when in there.

**Comment by glocalglocal** [comment]
Yes.

**Comment by ccbogel** [comment]
These controls also only work in the Manage File > Open File (the video file) 
They do not work in the Coding dialog
They work fine on my Windows

**Comment by glocalglocal** [comment]
I am definitely in the Play video/audio dialogue, in the transcription pane. 
![vid](https://user-images.githubusercontent.com/16408198/89090616-8730d880-d393-11ea-9b4c-cc5fa67986ec.jpg)

If there is a way I can capture what qualcoder gets from my keyboard, I can check.

**Comment by ccbogel** [comment]
OK. I have uploaded another view_av.py file. this will print the key numbers (as KEY and MOD) whee mod  the ctrl key.
The output will be in the terminal window. 
ps I might not be able to work much more on this today.

**Comment by glocalglocal** [comment]
KEY  84 MODS  2 for ctrl+t

**Comment by glocalglocal** [comment]
While testing this I saw the following errors in the terminal which may be useful. I don't see them normally because I run qualcoder with pyw.exe to suppress the terminal. 

> name 'file' is not defined
> [WinError 183] Cannot create a file when that file already exists: 'C:/xxxxxx/coding/test/test_BKUP_20200801_02.qda'
> There is already a backup with this name
> --- Logging error ---
> Traceback (most recent call last):
>   File "C:\Users\MKlon\.qualcoder\qualcoder\qualcoder.py", line 1191, in open_project
>     shutil.copytree(self.app.project_path, backup)
>   File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 554, in copytree
>     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
>   File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 455, in _copytree
>     os.makedirs(dst, exist_ok=dirs_exist_ok)
>   File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38\lib\os.py", line 223, in makedirs
>     mkdir(name, mode)
> FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:/xxxxxxxxxx/coding/test/test_BKUP_20200801_02.qda'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38\lib\logging\handlers.py", line 70, in emit
>     self.doRollover()
>   File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38\lib\logging\handlers.py", line 171, in doRollover
>     self.rotate(self.baseFilename, dfn)
>   File "C:\Users\MKlon\AppData\Local\Programs\Python\Python38\lib\logging\handlers.py", line 111, in rotate
>     os.rename(source, dest)
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\MKlon\\.qualcoder\\QualCoder.log' -> 'C:\\Users\\MKlon\\.qualcoder\\QualCoder.log.1'
> Call stack:
>   File "C:\Users\MKlon\.qualcoder\qualcoder\qualcoder.py", line 1428, in <module>
>     gui()
>   File "C:\Users\MKlon\.qualcoder\qualcoder\qualcoder.py", line 1423, in gui
>     ex.open_project(path=project_path)
>   File "C:\Users\MKlon\.qualcoder\qualcoder\qualcoder.py", line 1195, in open_project
>     logger.warning(_(msg) + "\n" + str(e))
> Message: "There is already a backup with this name\n[WinError 183] Cannot create a file when that file already exists: 'C:/xxxxxxxxx/coding/test/test_BKUP_20200801_02.qda'"
> Arguments: ()
> [000002649c2ef630] mmdevice audio output error: cannot initialize COM (error 0x80010106)
> [000002649c2feac0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
> [000002649c7a6350] avcodec decoder: Using D3D11VA (Intel(R) HD Graphics 5500, vendor 8086(Intel), device 1616, revision 9) for hardware decoding

**Comment by ccbogel** [comment]
You can ignore those errors. They dont affect performance. One relates to the rotating file handler. Others relate to how I have set up backups now, with trying yo over-write giles. The final errors relate to the use of vlc and can be ignored.

**Comment by ccbogel** [comment]
Intersting quirk: the ctrl key number is different on different devices:
2 on your Windows
544 on my Windows 10
20 on Ubuntu
This is why the ctrl plus key commands do not work for you. Will fix on Monday.

**Comment by glocalglocal** [comment]
Possibly something to with languages setup? I hope that there won't be tens of different arrangements out there. There must be a definitive list somewhere. Applications somehow don't have a problem reading the key codes.

**Comment by ccbogel** [comment]
OK I have changed the way the control key is detected slightly, using Qt enums rather than checking for the key integer. _Should_ work ok now.

**Comment by glocalglocal** [comment]
Almost. The actions are triggered even if you don't press ctrl. 't' and ctrl-t do the same thing. Same for the other keys.

**Comment by ccbogel** [comment]
OK should be fixed now.
