### ISSUE TITLE
Req: '[ ]' not good for markdown

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#217]
Can you optionally use other characters instead of '[ ]' for timestamps -- eg '{ }'? The current ones are special in markdown and have to be escaped. 

BTW, where do the speaker names come from?

**Comment by ccbogel** [comment]
There are some other commonly used timestamp formats -so could make an option for these.
speaker names - while you are in the transcription pane. type ctrl + n to enter a new speakers name. this will then be entered into the text as [speakername] on subsequently pressing ctrl + 1

**Comment by ccbogel** [comment]
OK in Settings you can choose the format for these characters.

**Comment by glocalglocal** [comment]
Great. For consistency, there is {hh.mm.ss} but not {mm.ss}. My personal favourite would be {hh:mm:ss} but this is perfectly fine.
