### ISSUE TITLE
Req: Separate player window not always necessary

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#218]
When working with audio files, that extra window is black and only wastes space. 

Ideally, video could be optionally incorporated into the controls dialogue for when a bigger window is not needed.

**Comment by ccbogel** [comment]
Yes true. but the window needs to be there to contain the VLC instance. It could be reduced in size for audio, I guess.
I initially tried incorporating the a/v window with the controls, but the events and signals overrode everything and I could not get the controls to work. This is why they were separated.

**Comment by glocalglocal** [comment]
> I have made it now so that the window is 1x1 pixel size for an audio clip.

Are you sure this is 1x1? 
![1x1](https://user-images.githubusercontent.com/16408198/88698186-42881180-d0f5-11ea-8883-c23f3fe8b4de.jpg)

I made it smaller manually: 
![smaller](https://user-images.githubusercontent.com/16408198/88698216-4e73d380-d0f5-11ea-8075-406925efab77.jpg)

It looks odd but there isn't much that can be done about it.
