### ISSUE TITLE
Req: Timeline and time codes in media playback

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#219]
The time code should be shown when the mouse pointer hovers over the timeline. 

The timeline could also have notches with time codes (as in Audacity) or no notches at all. The current one with the notches and downward pointing slider doesn't seem to serve a purpose as it is.

**Comment by ccbogel** [comment]
I think I can remove the notches. A hover with time code - I am not sure if I can implement it, will look in to it.

**Comment by ccbogel** [comment]
notches removed. time tooltip added

**Comment by glocalglocal** [comment]
That's great. If time in the tooltip or next to play is updated as you drag the  slider, it would be good. Otherwise, you don't know where you are moving the slider until you release it.

**Comment by ccbogel** [comment]
ha, now you are asking too much. thats difficult

**Comment by glocalglocal** [comment]
lol. I suppose this means you don't get feedback until dragging is finished. It also means we may have to slide in steps. Not a problem. Just a thought, navigation may be assisted by adding any or all of these:
(a) adding notches with times (or percentages) for 25, 50, 75, 100% points.
(b) percentage for current time next to the current 'Time', eg Time: 14.32 (53%) 
(c) a 'go to time/percentage' option (as in audacity)
