### ISSUE TITLE
Ideas for text mining and visualization

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#22]
In case you decide to add text mining options and more visualization options, if you have not already, I recommend to give a look at the gallery of khcoder: https://photos.google.com/share/AF1QipMFtorNU6AogCbL6E6s2z2j4Npm7lkyh19uZdh7-KZI026PjTV6Sk82MnlOXGp2Qw?key=ZUhtZUlhMV9qTTJIZUtGZXlhTzZvWG1NQW5WR3lR

Some of those visualizations are just amazing and very intuitive :O

**Comment by ccbogel** [comment]
Thanks for the suggestion. I will incorporate some of these in the future, and also a word cloud option. Some graphs look more impressive than practical, so will have to identify the most useful first.

**Comment by WPFilmmaker** [comment]
@ccbogel Hello Colin, I just thought I could help you making things a bit easier by proposing (from a user point of view) the way to visualize data which make sense to me and why. Such visualizations would be useful not only for text mining but also for qualitative analysis.

**Bar charts**: https://datascienceplus.com/wp-content/uploads/2017/10/plot-1.png simple way to show the most used words, IMHO it is a basic feature to visualize data.

**Word clouds**: https://datascienceplus.com/wp-content/uploads/2017/10/plot.png This is very effective to display results to people who do not have a scientific background and can be added to slides or articles. R can do such visualization and afaik RQDA too.

More to come...

**Comment by ccbogel** [comment]
Thanks for these - yes word count bar chart and word cloud might be the next thing to look at.
These options will require more python-module imports. More imports means potentially more problems for some to import these.

**Comment by WPFilmmaker** [comment]
Indeed as the project gets more features it requires more dependencies which potentially means more problem yes, but I think it is inevitable as all software tend to grow in complexity. What could mitigate this is try to distribute it in a way that the user has not to interact with installing them, like flatpak.

Just for the records,
you might be interested in Google Summer of Code to attract students working on QualCoder once/if the software becomes more complex. You would be surprised by how many people are interested in participating.

**Comment by ccbogel** [comment]
Yes good ideas.

**Comment by ccbogel** [comment]
Apart from the charts. I am looking inyo pyinstaller to make Windows executables and more.

**Comment by WPFilmmaker** [comment]
@WPFilmmaker That's great! I don't have a Windows machine so I am unable to test, but I think Windows support is good. I also saw the first publication using QualCoder, so congratulations! This project is evolving :D

**Comment by COOA-software** [comment]
Hi, thanks for doing this great job. I wonder if autocoding functionality could be extended to code larger blocks of text than words. In R(QDA) there is a function codingBySearch("", fid=getFileIds(), cid = , seperator = "[.!?]") that makes it possible to mark all sentences containing the searched string. 
Martin

**Comment by ccbogel** [comment]
Hi Martin,
That is a good idea. I will have to think of a way to implement it.
I guess having cut-off points of periods (full stops) could be implemented. I'm a not sure if that would work in other non-latin style languages, but I will put it on a to do list.
with regards Colin


________________________________

**Comment by ccbogel** [comment]
i dont think  I will do visualizations and word clouds or text mining

**Comment by WPFilmmaker** [comment]
@ccbogel I am sure you have your reasons for not wanting implement these time-consuming features, but I hope in the future qualcoder will have them to reduce the need for other software (like khcoder).

**Comment by ccbogel** [comment]
I have found it really challenging to think it through. I can reopen and keep the tread alive until a time that I might work on it.
How have you been going with it?

**Comment by WPFilmmaker** [comment]
@ccbogel Indeed these are not easy to implement features (I can understand it even as a non-developer). I am glad another user joined with feedbacks! Qualcoder is improving a lot! I am planning on using it for the methodological part of my dissertation. By the way I also did a brief presentation about it to students, where I presented it as a free alternative to Nvivo :D

**Comment by ccbogel** [comment]
I wont continue with thesis ideas. There are so many other issues I have to manage.
