### ISSUE TITLE
Lines in graph visualization (list view) should start from the corner of the square

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#220]
Right now some don't, I don't know if it is a bug or it is just the qay QC functions, but look,

this is with font 10:
https://i.imgur.com/zOXa7uK.png

This is with font 14:
https://i.imgur.com/ghoJQb7.png

With font 14 line cross and gets ugly, and the larger the font the uglier.

Qualcoder 1.9 Lubtuntu 18.04.

Edit: same issue happens in normal view, it seems that in some square lines start correctly from the corners, in others they don't:

https://i.imgur.com/wM49dZv.png

**Comment by ccbogel** [comment]
OK I have fixed this for the list graph. It wont be in a Debian until I make a new one soon.
