### ISSUE TITLE
Bug: I can run 2 instances of qualcoders handling the same project

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#221]
Opening multiple instances of qualcoder handling different projects could be an advantage. But opening the same project 2 or more times is pointless and will lead to clashes.

**Comment by ccbogel** [comment]
There's nothing I can do to prevent this happening.

**Comment by ccbogel** [comment]
out of curiosity, how do you start qualcoder?

**Comment by glocalglocal** [comment]
C:\Windows\pyw.exe "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py"

from the Windows Start menu

**Comment by ccbogel** [comment]
Ishould probably close this issue, as I can see no solution, but the end user really should only open the program once at a time. It would be unusual for multiple ones being opened.
