### ISSUE TITLE
Bug: Error while opening a recent project

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#222]
The error below was also displayed in tiny font. 

ERROR memo.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 613, in project5
    self.open_project(self.recent_projects[6])

IndexError: list index out of range

EDIT: It happens with one in every five attempts to open different projects but it's a different project that won't every time. 

EDIT2: the path above is actually displayed with forward slashes in the dialogue. I think qualcoder should display the path here and elsewhere in the OS specific format, otherwise some Windows users will be confused or will think it's a bug.

**Comment by ccbogel** [comment]
thanks - i made a stupid coding error. Fixed now!

I really cant change the python standard way of using forward slashes.
The end user just has to be aware of this convention.
This is the same in R for example.

**Comment by glocalglocal** [comment]
> I really cant change the python standard way of using forward slashes.

Of course, but surely the string can be converted before it is displayed for the user. Doesn't `os.path` do that for different OSes?

**Comment by ccbogel** [comment]
os.path interprets but does not display that way. No I wont implement that Windows backslash for path display - it means adding extra lines of code to so many places for a minor display tweak.
