### ISSUE TITLE
Bug: inconsistent blank lines in imported files

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#224]
Continuing from #156 I imported the same text as docx and pdf:
[test_file.pdf](https://github.com/ccbogel/QualCoder/files/4991417/test_file.pdf)
[test_file.docx](https://github.com/ccbogel/QualCoder/files/4991418/test_file.docx)

You will observe in both files there is a single blank line -- line 3. 

In Manage files/View, the imported docx file has lost the blank line, while the imported pdf file now has 5 blank lines instead of one:

![docx_view](https://user-images.githubusercontent.com/16408198/88727668-927bce00-d11f-11ea-969a-0c32ec88a8ad.jpg)

![pdf_view](https://user-images.githubusercontent.com/16408198/88727665-91e33780-d11f-11ea-88d2-4d4c01b83be6.jpg)

**Comment by ccbogel** [comment]
There are no easy fixes for these. The best I can do regards the 5 blank lines is run some code after the text is extracted from the pdf to remove multiple line endings.

**Comment by ccbogel** [comment]
have you checked this out. There should be less inconsistency. Then will close this issue.

**Comment by glocalglocal** [comment]
Now the pdf looks OK:
![pdf](https://user-images.githubusercontent.com/16408198/89351605-e2b7da80-d6a1-11ea-9f3a-4dd581a0081e.jpg)

but the docx skips the blank line completely: 
![docx](https://user-images.githubusercontent.com/16408198/89351635-ef3c3300-d6a1-11ea-8b3c-ec8276950833.jpg)

**Comment by ccbogel** [comment]
Yes. Its really hard to get this right. I have mitigated the pdf issue, but I really cant do more.
