### ISSUE TITLE
Bug: I can move the cursor and edit text in the main window 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#228]
This also means I can probably mess up the display of the next print by moving the cursor. I think this happened but I can't reproduce it.

**Comment by ccbogel** [comment]
yes you can edit the text in the main window.
I like it in case you want to add notes of any sort there.

**Comment by glocalglocal** [comment]
I like the scratchpad idea but I think it should be in a separate pane. Notes and qualcoder output can interfere with each other too easily. A note can be easily lost as it is now.

**Comment by ccbogel** [comment]
resolved
