### ISSUE TITLE
Bug: Project / Export / REFI-QDA does nothing

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#229]
Both REFI-QDA options are ignored completely -- not even a warning. 'Export Codebook' (non-REFI-QDA) works fine.

**Comment by ccbogel** [comment]
when I export on Ubuntu it exports to the working directory folder as a zipped .qdpx folder and gives a dialog telling the user. Will test on Windows.

**Comment by glocalglocal** [comment]
here it doesn't add anything to the main window log either

**Comment by ccbogel** [comment]
OK. on my Windows both export options 'work'.
The refi-qda codebook is exported.
The project export - goes through the motions, but had a character encoding issue. It also had a path not found error.

**Comment by glocalglocal** [comment]
This is very strange. Here I click on the option, the menu closes and then the click appears to be completely ignored. Nothing happens at all.

**Comment by ccbogel** [comment]
If there is anything in the your error log, it would be good to know.

**Comment by glocalglocal** [comment]
Oops, there is! I had assumed that without an error message nothing would be logged silently. 

ERROR refi.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 925, in REFI_project_export
    Refi_export(self.app, self.ui.textEdit, "project")

  File "C:\Other programs\QualCoder-master\qualcoder\refi.py", line 979, in __init__
    self.project_xml()

  File "C:\Other programs\QualCoder-master\qualcoder\refi.py", line 1141, in project_xml
    self.xml += self.sources_xml()

  File "C:\Other programs\QualCoder-master\qualcoder\refi.py", line 1393, in sources_xml
    xml += '<Description>' + s['memo'] + '</Description>\n'

TypeError: can only concatenate str (not "NoneType") to str

**Comment by ccbogel** [comment]
Great thanks. I have uploaded a fix for that.
