### ISSUE TITLE
Translate software

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#23]
Hello !
First, think for this software, i have search during lot of months a good sofware in linux. It's intuitive and it's work.

I have a suggest, it's translate software. I can translate in French if you want :-)

Regards

**Comment by ccbogel** [comment]
Bonjour, Thank you for liking qualcoder! 
Yes that would be really good. Where to start? the manual?

**Comment by qwertygc** [comment]
I use linux mint with the deb. I can translate the software.

**Comment by qwertygc** [comment]
For the manual, i am surprising, it's not in Markdown and after convert with pandoc ?

**Comment by ccbogel** [comment]
Hello again, yes software translations would be good also, thank you very much. I will need to enable QTranslator for the French translations within the software, but that hopefully will not be too hard.
The manual was written in LibreOffice as filetype odt. I have added it to the repository, it is called QualCoder_Manual.odt

**Comment by WPFilmmaker** [comment]
@ccbogel, you may also want to try some online platforms popular for translations (crowdin,transifex very popular in he FLOSS community).

**Comment by ccbogel** [comment]
Thanks WPF I have had a bit of a look and I'm unsure how to proceed with them at the moment. I will wait for @qwertygc for translation of the manual into French. I have made some preparations for automatic translations of buttons and some other parts of the software. During the week I will use google translate to translate short texts and words for some of the buttons and labels that are in the widgets.

**Comment by qwertygc** [comment]
Hmm, probably you modify the manual no? Best solution is use wiki option in Github, it's more easier for me for translate.

**Comment by ccbogel** [comment]
yes ok I will do this.

**Comment by ccbogel** [comment]
OK I have made some wiki pages.

**Comment by ccbogel** [comment]
@qwertygc 
I have also added some translations into the software itself. You change the language in the Settings. Then close and open Qualcoder for the change to be shown. 
The translations are mainly from using Goggle Translate, so might need some fixing.

**Comment by qwertygc** [comment]
Oh yeah. How to fix the translation?

**Comment by ccbogel** [comment]
The human readable translation files are in the locale directory:
QualCoder/qualcoder/locale/fr/LC_MESSAGES/fr.po
and:
QualCoder/qualcoder/locale/fr/app_fr.ts

The fr.po file translates wording that I use in most of the software into french.
The fr.po file can be opened and edited with poedit. On save the machine-readable fr.mo is created.

The app_fr.tm file is read by the Qt framework and affects the dialog files shown in the Qualcoder/qualcoder/GUI folder. So this fills in the language on most of the widgets (labels, buttons, window titles, etc). Unless it is overridden.
The app_fr.ts is opened using Qt's Linguist software (or by text editor). It is converted to app_fr.tm - a machine readable version using  lrelease. (lrelease is in Linguist and also a command line tool.)

These changes would need to be pulled and uploaded into the github repository.

fr.po and app_fr.ts can also be edited using a text editor.

Alternatively, posting fixed translations here with clear details about where the translation goes, and I could work through and upload changes.

**Comment by qwertygc** [comment]
OK, i review the translation, but, what is a « case » ?

**Comment by ccbogel** [comment]
Thank you.  A case is a collection of variables about something. Usually, a case is a person and the case contains details about that person (name, gender, age, interests ... ).

**Comment by ccbogel** [comment]
Closing this issue as no further work conducted.
