### ISSUE TITLE
Req: solitary carriage returns in exports

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#230]
'Export Codebook' is another case of export producing those solitary carriage returns metapad complains about and removes. Not generally a problem as other text editors don't complain but there may be a problem in that they translate these CRs translate into blank lines -- too many IMV, In codebook.txt they affect readability.  

Notepad describes the format as Macintosh (CR), ANSI.

**Comment by ccbogel** [comment]
should be fine now

**Comment by glocalglocal** [comment]
indeed!
