### ISSUE TITLE
Req: Video slider position could be remembered between sessions

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#231]
Not essential, but nice to have and can save the user some effort.

**Comment by ccbogel** [comment]
I dont think I will do this. It is a minor thing, and it requires a bit of extra coding, including recording the files that was opened at the time. confounded by multiple things opened.

**Comment by glocalglocal** [comment]
Not a deal-breaker, for sure. 

>  including recording the files that was opened at the time. confounded by multiple things opened.

As per #204 , if the only way to prevent clashes is to block opening multiple dialogues of the same kind, this may not be an issue.
