### ISSUE TITLE
Bug: Project / Export / REFI-QDA error

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#232]
I am getting these errors which may be unrelated. 

> 2020/08/01 01:26:39 WARNING __main__.open_project There is already a backup with this name
> [WinError 183] Cannot create a file when that file already exists: 'C:/xxxxxxxxxx/coding/test/test_BKUP_20200801_01.qda'
> 2020/08/01 01:26:56 ERROR refi.export_project Project export error  .qualcoder preperatory path not found

Also getting this error message (in tiny font): 
![error](https://user-images.githubusercontent.com/16408198/89089769-7d58a680-d38e-11ea-85f9-2f0648cee885.jpg)

**Comment by ccbogel** [comment]
Thanks, yes I am getting these errors also. I will have to test more frequently on Windows.

**Comment by ccbogel** [comment]
The backup warning can be ignored.
The encoding issue is resolved.
I am getting a FileExisits erros, which is unusual s the file did not exist.
However, the project export worked.

**Comment by glocalglocal** [comment]
I tried another project and the logfile recorded: 

> ERROR refi.export_project Project export error  .qualcoder preperatory path not found

but export worked. So, apparently there is an issue with certain files in a project.  

BTW, 'preperatory' above is misspelled.

**Comment by ccbogel** [comment]
LOL, yes, goodness me, normally my spelling is fine.

**Comment by ccbogel** [comment]
actually that was not an error, it was an acknowledgement of of a file / directory existing. Changed so this does not display.
