### ISSUE TITLE
bug: very narrow video window

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#233]
I opened an audio file to transcribe. I closed it and opened a video file. The video window was very very narrow and very tall. I think it inherited the width from the dummy audio window earlier.

**Comment by ccbogel** [comment]
I have added code to reduce this problem. Still can have a fairly small window 100x80 pixels.

**Comment by glocalglocal** [comment]
Below is what I get. All that y doesn't look right. 
![video1](https://user-images.githubusercontent.com/16408198/89124096-d24a0900-d4c3-11ea-98cd-063ea63b18d8.jpg)

**Comment by ccbogel** [comment]
ok, try again. I have further edited the cod around this.

**Comment by glocalglocal** [comment]
Same narrow video window.

**Comment by ccbogel** [comment]
ok, even more code on this.

**Comment by glocalglocal** [comment]
no change.

**Comment by ccbogel** [comment]
OK. Well the code I implemented works on Ubuntu and my Windows 10. I really dont know what else to do.

**Comment by ccbogel** [comment]
The previous code worked ok on my Windows. I have added more logic to try and catch this issue.

**Comment by glocalglocal** [comment]
What seems to happen is that playing audio makes the window very small (and could be smaller). This window size is then remembered when I play video. If I stretch it, the new dimensions are remembered until I play audio at which point the window is made small again. I think qualcoder could remember two sets of sizes/positions: one for audio and one for video. 

Related to this, the video frame aspect ratio could be locked. There is no point in having black vertical or horizontal bands.

**Comment by ccbogel** [comment]
Appreciate it, but I wont do aspect locking. 
OK, I am really stupid. I found the solution to the window sizing. try again. this time , no window will show for the audio, but it still works. So I dont have to resize anything, specially for it.

**Comment by glocalglocal** [comment]
yeap, it's working now!

**Comment by ccbogel** [comment]
YAY
