### ISSUE TITLE
Req: video/audio playback ctrl keys outside transcription area

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#235]
In case it is impossible, it would be useful if ctrl-key worked outside the transcription area. It is very frustrating if you click elsewhere in the dialogue, the focus shifts there, and then you press, say, ctrl-r several times and nothing happens. Same for the rest of the actions. Even if you realise why, it is still frustrating (and rewind currently is not even available as a button).

**Comment by ccbogel** [comment]
OK I have enacted this.
