### ISSUE TITLE
Req: backtrack for unpause 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#236]
It is common for transcription software to optionally rewind by a few seconds when unpausing. Personally, I find this is essential so that I reconnect with context and get the whole sentence. I suppose we can perform ctrl-s + ctrl-r every time, although unpause backtrack is typically shorter than rewind. Perhaps unpause+backtrack could work with ctrl+shft+s -- or ctrl-s for unpause+backtrack and ctrl+shift+s for plain rewind.

**Comment by ccbogel** [comment]
ok  I have enacted a1 second rewind automatically when pressing play

**Comment by glocalglocal** [comment]
I am sure users may have different preferences or different material requires different settings (eg fast paced, scripted talk vs interview). Perhaps these settings could be user selected. In real conditions, personally I find that backtracking should be 3-5 secs because interviewees often pause, say err, emm etc, and rewind would be 5-10 secs.

**Comment by ccbogel** [comment]
For now, I will do 2 secs for play and 5 for rewind.
