### ISSUE TITLE
Req: variable speed playback

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#237]
Many transcription applications offer playback at variable speed (say, 50%-150% speed). Crucially, this is done while pitch remains unaffected. Would VLC do that for qualcoder? 

See [Express Scribe](https://www.nch.com.au/scribe/screenshots.html) for this and other options.

**Comment by ccbogel** [comment]
I might be able to do variable rate. I could not implement unaffected pitch.

**Comment by glocalglocal** [comment]
VLC does both variable rate and unaffected pitch of course, but I don't know how you interface it so fingers crossed.

**Comment by ccbogel** [comment]
i could not see a method in the vlc file to manage pitch. I'm currently looking at the metadata for A/V and trying to fix bugs, as I feel I should put out a new release, once  I update the manual and edit the translations. As there have been a lot of changes. Then look at further bugs and requests for later.

**Comment by glocalglocal** [comment]
> As there have been a lot of changes.

Yes, I was thinking more people will use and benefit from qualcoder when the new version is out and promoted.

**Comment by ccbogel** [comment]
Added key controls to change play rate:
Shift + > to increase up to 4 times
Shift + <   to decrease to 1/4 play rate
Rate options are:
1/4, 1/2, 1, 2, 4

**Comment by glocalglocal** [comment]
It's working as expected but: 
(a) the steps are too big. For transcription I would guess that most people would need something between 1/2 and 1 -- even 1/2 is too slow. Ideally, it could be made a continuos scale. 
(b) the key combinations may actually be needed in typing. Alt-Shift may be better.

**Comment by ccbogel** [comment]
I have made changes to key controls:
Ctrl + Shift + < or >
The steps up and down are now 0.1 for a rate range of 0.1 ... 2.0
I have added a label showing rate changes.
I have added these to the develop branch, as I am working on the RQDA relation code crossover function and reporting

**Comment by glocalglocal** [comment]
That's great and the pitch is unaffected. Two issues: (a) The keys work only when the cursor is in the text box. Otherwise, the volume goes up/down instead; (b) With rates lower than 1, when I click Play there is a very long delay before it starts playing.

**Comment by ccbogel** [comment]
(a) I only tested on Ubuntu. The keys worked even outside of the textbox. Will try on Windows later to confirm.
(b) Yes I noticed this - I think something to do with VLC and out of my control.

**Comment by ccbogel** [comment]
@glocalglocal I checked this on my Windows 10. The keys worked as expected., even when the text area was out of focus. The volume did not change.

**Comment by glocalglocal** [comment]
Working fine now and remarkably well too. Not sure what it was but I can't reproduce the problem.

**Comment by ccbogel** [comment]
Good. Closing this issue
