### ISSUE TITLE
Req: media playback transcription ctrl-t scrolling

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#239]
In media playback transcription, ctrl-t hits enter. I think it should also add a blank line. This is consistent with using a blank line as paragraph separator when importing docx files. 

Also, ctrl-t doesn't cause the transcription window to scroll down when you reach the bottom or the cursor is past the bottom (eg if you hit ctrl+t many times).

**Comment by ccbogel** [comment]
ok both suggestions enacted

**Comment by glocalglocal** [comment]
I forgot to add, a space after the time stamp would be good. 

Not sure if that is good for everyone, but that extra line could be omited if there is a blank line already.

**Comment by ccbogel** [comment]
It wil l be getting hard to work that out, re the blank line, but I can add a space.

**Comment by glocalglocal** [comment]
Not a big problem. The issue here is that I am guessing most people would hit enter and then ctrl-t which would produce two blank lines, but I suppose muscle memory may sort this out. Users can edit the text later.
