### ISSUE TITLE
Put files in .qualcoder directory

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#24]
Hello
Just a suggest in linux, it's put QualCoder.log and QualCoder_settings.txt in the .qualcoder directory. It's just for make a more clean /home

regards

**Comment by ccbogel** [comment]
Thanks, I have updated this in the files (but not in the deb package yet)

**Comment by qwertygc** [comment]
OK. How to build the deb package ?

**Comment by ccbogel** [comment]
I will create and load a new deb package. It took some time to learn how to build it, using debian and other websites.
