### ISSUE TITLE
Req: date/time format following OS settings

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#240]
Can date/time displayed follow the OS settings? Eg time on my system is displayed as 23:45:14 (colon rather than the dots used in media playback). I would expect dates in Manage Files to look like dates in Explorer (eg here 15/09/2020). This means sorting by date would involve some internal conversion, as sorting strings (if that's how it's done now) wouldn't work.

**Comment by ccbogel** [comment]
Yes have implemented the colon. it is an iso standard.
The dates as is - yes its much easier to sort. I will leave it as is. This is how they are stored in sqlite. If I begin changing dates to suit locales, I would have to add others - eg US 09/15/2020.

**Comment by glocalglocal** [comment]
I was hoping Python could get the OS locale and then you could pass it to a function for formatting. Otherwise, indeed, there must by lots of locales to support case-by-case.  

I don't see how to produce {hh:mm:ss} -- only [hh:mm:ss]. Would it be easier if the brackets were selected separately, like the brackets for speaker?

**Comment by ccbogel** [comment]
I am not that familiar with time and number locales,so have avoided it, really.

I don't see how to produce {hh:mm:ss} -- only [hh:mm:ss]. - This is in Settings for choosing a format for the time stamp when adding timestamps to the transcript.

**Comment by glocalglocal** [comment]
> This is in Settings

That's what I mean. It isn't there. The only curly brackets option is {hh.mm.ss} (no colons). That's why I say selecting the style of brackets separately will cover all combinations.

**Comment by glocalglocal** [comment]
> This is in Settings

That's what I mean. It isn't there. The only curly brackets option is {hh.mm.ss} (no colons). That's why I say selecting the style of brackets separately will cover all combinations.

**Comment by ccbogel** [comment]
Oh I get you now. I will change it from .  To :  tomorrow

**Comment by ccbogel** [comment]
done

**Comment by glocalglocal** [comment]
Now it's {hh:mm:ss} in Settings but comes out as {hh.mm.ss} when I press ctrl-t.

**Comment by ccbogel** [comment]
thanks I missed on spot of that, will upload a file in a minute
