### ISSUE TITLE
Bug: Formatted text in the transcription area

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#242]
In the transcription area, if I paste formatted text, the format is preserved and then it is applied to text entered subsequently. 

![font](https://user-images.githubusercontent.com/16408198/89350727-17c32d80-d6a0-11ea-92cf-5a6700dd1f33.jpg)

**Comment by ccbogel** [comment]
Interesting. I might not be able to fix this, but will look in to it. On reopening the transcript, it will revert to the original formatting.

**Comment by glocalglocal** [comment]
No problem but just out of interest, if there is no other way to lose the formatting stored in the clipboard, won't something like pasting or moving its text content into memory and copying it back into the clipboard strip the formatting? Ie the computational equivalent of pasting formatted text into notepad, to copy it back into clipboard before pasting it to the final destination (something I do sometimes).

**Comment by glocalglocal** [comment]
In addition to above, I notice ctrl+shift+V is ignored. That would remove formatting, which should be unnecessary in the first place.
