### ISSUE TITLE
Bug: Add speaker dialogue re-opens

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#243]
In transcribing media, if I press ctrl-n to add a speaker and then click on Cancel without inserting a name, the 'add speaker' dialogue closes and reopens. If I click cancel/OK second time, it goes away.

**Comment by ccbogel** [comment]
fixed

**Comment by glocalglocal** [comment]
Yes, but now if I hit ctrl-n, Cancel several times, there are several times ctrl-n won't open the 'add speaker' dialogue at all.

**Comment by ccbogel** [comment]
This should be improved now

**Comment by glocalglocal** [comment]
Still there. I can see the focus is where it should be but ctrl-n is ignored.

**Comment by ccbogel** [comment]
Hmm? It is not happening to me.

**Comment by glocalglocal** [comment]
I think I found something. Is there a way to set sensitivity? I noticed that I press ctrl-n firmly (specifically press ctrl firmly), it is always picked up. I mean press and hold imperceptibly longer than usual -- the difference between using both hands or one hand. Otherwise, several attempts can fail. Just in case, I tested this on my usual wireless keyboard and the laptop keyboard -- no difference. It's the ctrl key that makes the difference.

**Comment by ccbogel** [comment]
There is no way to set sensitivity. pressing ctrl+n either sends a signal or it doesnt

**Comment by glocalglocal** [comment]
That's what I thought but then I can't explain why it only happens in qualcoder. Never noticed this with my setup in another application, or with, say, ctrl-V in qualcoder. It's as if there is some delay in picking up ctrl in ctrl-n, ctrl+1-8, ctrl+d, ctrl+s, ctrl-t -- yes, all of them, as I discovered now, which is now a workflow problem. Could it be how often the code checks for a ctrl keypress?
