### ISSUE TITLE
Req: no way to delete/replace speaker names for ctrl-n

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#245]
In media transcribing. Perhaps ctrl+alt+n would show a dialogue for delete/replace the speaker name (or assign a name to a preferred n if it is not used already). This is essential if you run out of n and you have speakers you can delete to make room.

**Comment by ccbogel** [comment]
functionality added

**Comment by glocalglocal** [comment]
Like ctrl-n, ctrl-d is sometimes ignored even through the focus is on the transcription area (orange frame). 

Could we select multiple names to delete? 

The 'select name' dialogue is far too wide and tall for up to 8 names.

BTW, why ctrl+1-8 instead of 1-9 or 0-9?

**Comment by ccbogel** [comment]
OK if sometimes ignores. hopefully can live with it. I can implement multiple name delete. The dialog is a default one I use for item selections, so cant it really.
ctrl 1-8 is so that the names can display reasonably within the small label area for displaying this.

**Comment by glocalglocal** [comment]
> OK if sometimes ignores. hopefully can live with it. 

Of course we can live with this. Fine with me but just two thoughts: (a) this may be down to the same reason causing ctrl-n to be ignored. (b) it may be just me, but I think even tiny issues can undermine user confidence in the stability of an application -- even unconsciously. This is why sometimes I point out seemingly silly issues, like a space missing after a colon, inconsistencies (like the path '/') etc.

**Comment by ccbogel** [comment]
Yes you are right re the usability and confidence.
Adding a space is easy. Solving event driven processes can be hard.
