### ISSUE TITLE
Bug: Error when clicking on Code Text

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#246]
... and displayed in very big font:

ERROR code_text.exception_handler Uncaught exception:
Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 906, in text_coding
    d.activateWindow()

RuntimeError: wrapped C/C++ object of type DialogCodeText has been deleted

**Comment by ccbogel** [comment]
I have added code to mitigate this
