### ISSUE TITLE
Bug: Recent Projects doesn't list the most recent projects

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#247]
Recent projects lists recent projects but not the **most** recent ones. Eg I open recent1, I open recent2, recent1 closes automatically. I check the Recent Projects list and recent1 is not one of the listed ones. Instead, there are projects listed there that I haven't opened for a while.

**Comment by ccbogel** [comment]
Yes.  I am finding this a real challenge to resolve.

**Comment by glocalglocal** [comment]
I also notice that recent projects are not sorted by last opened date. Doing so would be good, but also perhaps the discipline in sorting them, would resolve the issue above.

**Comment by ccbogel** [comment]
I have put a bit of time into this today.
The recent project files now shows the datetime|projectpath
I have added abit of code to keep the most recent projects on top (without duplicate entries)
And to remove non-existing entries

**Comment by glocalglocal** [comment]
Do you mean the submenu under Open Recent Project should show datetime as well? It doesn't here. But I see now several spaces before C:/....
Recent_projects.txt looks the same (and with the familiar solitary carriage returns that notepad displays as blank lines).

**Comment by ccbogel** [comment]
Perhaps delete your recent projects file and continue your work/testing. It should populate with that date and name
