### ISSUE TITLE
Bug: Manage Files shows files of previous project

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#248]
I imported from a .qdpx, played with the files in qualcoder, opened another project from Recent. The new project name appears on the titlebar but when I open Manage Files the files of the previous project are still listed. 

I opened/closed Manage Files several times but nothing changed. I selected another Recent Project and eventually Manage Files was updated.

**Comment by ccbogel** [comment]
Thanks a good pick up. I am guessing as I re-created this, that you had the manage files dialog opened with the imported project, and then opened the recent project.

**Comment by ccbogel** [comment]
failry sure I have fixed this now. I have tested it a bit.
