### ISSUE TITLE
Import CSV?

### ISSUE THREAD

**Issue by bennettscience** [ccbogel/QualCoder#25]
I noticed you have a couple CSV files in the examples directory, but when I try to load one of them to play with QualCoder, it throws an error for an unknown file type. I'm running on Mac, and I know you don't officially support that right now (sidebar: I'd be happy to submit a Wiki page or readme update for Mac install if you'd like.) but does CSV import work at all right now?

**Comment by bennettscience** [comment]
Closing. I didn't read the manual far enough. I successfully imported a CSV from the `Survey` menu.

**Comment by ccbogel** [comment]
Hi, I am glad the manual did help you to understand the purpose of the csv files. I have to admit writing a manual was a challenge in itself. I am glad qualcoder appears to be working OK on a Mac, I only have Ubuntu, Linux Mint and at work, a Windows 10 desktop to test on. Its unlikely that I will also purchase a Mac, this is a personal project that has grown into a hobby, that now seems to be garnering some interest from around the world. 
Yes, if you feel this project is useful and deserves more attention, then I would appreciate a wikipage or readme update. Also, even any feedback to say whether the functionality (at present) works without errors on a Mac.
