### ISSUE TITLE
Bug: .mp3 in text filename confused Manage Files

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#250]
One of the text files I imported from nvivo is called blah.mp3. qualcoder Manage Files/Open correctly opens it as text and shows existing codings, but Manage Files shows the microphone icon, presumably because .mp3 looks like a file extension.

**Comment by ccbogel** [comment]
yes that would be the reason.

**Comment by glocalglocal** [comment]
If your code opens these files correctly as txt, can't it tell it should be listed as text in Manage Files? Presumably, similar confusion occurs if the imported file has a video file called video.txt etc.

**Comment by ccbogel** [comment]
this is fixed now
