### ISSUE TITLE
Bug: Error when I selected the Coding menu

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#251]
I changed coder name in settings and clicked on Coding/coding text. It happens every time and couldn't get into coding until I selected a random report from the menu and then went back to Coding/coding text.

ERROR settings.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 903, in text_coding
    d.activateWindow()

RuntimeError: wrapped C/C++ object of type DialogCodeText has been deleted

**Comment by ccbogel** [comment]
I added code to catch this error earlier today. Are you using an older version?
I cant prevent the error happening, but I can hide it from the user, so that clicking on code text once or twice should work.

**Comment by glocalglocal** [comment]
I downloaded my version nearly 3 hours ago. I'll get the latest now but I am not sure I can reproduce the error if the bug is there.

**Comment by ccbogel** [comment]
has this bur re-occured over the last month? if not, will close the issue.

**Comment by glocalglocal** [comment]
OK , I will create a new one if it re-occurs.

**Comment by ccbogel** [comment]
Ok thanks. Sorry, i havent had much time lately to work on any further requirements and updates.
