### ISSUE TITLE
Bug? Different resolutions/size between screens

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#252]
My laptop screen and big external monitor show text and dialogues in very different resolutions and sizes. Such differences across machines probably explain why you and I apparently see different things sometimes, which means that display may be completely wrong on other machines. Eg see how my monitor and my laptop display the 'Select name' dialogue (note how the OK, Cancel buttons are truncated on the laptop screen, and how much white space there is on the monitor. This happens with some applications, particularly when I switch between built-in and external screens in a session. Not sure if it can be fixed. Just letting you know. I still think the 'Select name' dialogue looks too big for up to 8 names. 

External monitor:
![monitor](https://user-images.githubusercontent.com/16408198/89534539-9d4ff600-d7e4-11ea-8ec6-10b8d614209a.jpg)
Laptop screen:
![laptop](https://user-images.githubusercontent.com/16408198/89534547-a2ad4080-d7e4-11ea-8e94-738a70c1a968.jpg)

**Comment by ccbogel** [comment]
OK I have reduced the size of this dialog, and applied a grid layout to it. so resizing will flow better.
