### ISSUE TITLE
Req: Media transcription buttons

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#253]
Personally, I prefer keyboard shortcuts but I think there should be buttons for Ctrl-r, Ctrl-n, Ctrl-d. Perhaps Ctrl-n and Ctrl-d could be part of the same dialogue (possibly with a 'change name' option, eg if you mistyped a name). There could also be a Ctrl-f for skip forward functionality (with a button too) to complement Ctrl+r. 

For completeness, there could be a long-skip back/forward (eg 30 secs) -- Ctrl+Alt+R, Ctrl+Alt+F with buttons. 

If there are are Play/Pause, REW, FF, Long skip back/forward -- should the words be replaced with icons, as in practically every media player? 

Wasn't Ctrl-S going to become Ctrl-P for play/pause? 

Pedantic mode: I think the standard form is Ctrl+R etc (note capitals) https://en.wikipedia.org/wiki/Control_key

**Comment by ccbogel** [comment]
yes crtl S/P do the same thing now. Added 30 sec forwards and reverse using alt F and alt R.
May/may not add buttons.

**Comment by ccbogel** [comment]
I have added a tooltip to the Play button to detail the keyboard shortcuts.
