### ISSUE TITLE
Req: Please release current state of dev't as 2.0

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#256]
**Is your feature request related to a problem? Please describe.**
You have added great functionality and fixed many bugs since the last release - but these improvements are not yet available in a current release. 

**Describe the solution you'd like**
Please release the current version as 1.9.1 - though I d say the many improvements and fixes may warrant a 2.0 release. In addition, a list of milestones would be great so its possible to see what you plan on adding/fixing for the next releases. It would also be great to know if development could be helped along by paying bounties for the implementation of specific requests or fixes. 

**Additional context**
For use in a research / production environment, working with current development snapshots is not ideal - that's why a release would be great.

**Comment by ccbogel** [comment]
Thank you, yes. I am planning to do a 2.0 release very soon. This will include all the current issues found. The newer function requests I will not include in this release. (These will take a lot of time and effort).
Currently, I am updating the manual. Then  I will look at adding in missing translations for FR, ES, DE using google translate. Then I will release the new release. - Yes I agree using the current development snapshots is not ideal.
I do not know if paid bounties will help. I work full time.

**Comment by WPFilmmaker** [comment]
Bounties can be useful to attract external develers, but they would have to be in the orders of hundreds of dollars to be attractive I think. Given the niche base of the software I think it would take months to reach such goal, unless there are very generous donors (I am not familiar with academics but usually donors put 5-10 dollars each).

Maybe a pinned message could be put listing the available bounties, but i wouldn't expect them to attract devs in a few days (unless they are promoted on social medias?)

For next year I would suggest Colin to try to apply to GSOC and have ideas which he has no time to work on (like text mining) and let students paid by Google develop them. This of course requires Colin to have the time to respond to students if they need help with the software, and maybe find another user willing to mentor another student.

**Comment by menelic** [comment]
The milestone lists September 15th as release date - but there are no issues for the translations you list. It seems you are not using transifex which would enable other contributors to translate QualCoder and would enable you to easily and automatically pull translations back into this repository, see here https://github.com/apps/transifex-integration. This would allow contributors with no coding ability to assist with translation and free your time up for coding and documentation. If you want to translate yourself and manually, I highly recommend using  www.deepl.com/translator instead of google translate. Its free to use and vastly superior.

Please consider another point release now so that users can benefit from the changes even if translations and docs are not 100% complete - I believe this was the case for he last point release and is preferable to a longer wait time, esp for those of us who know about the many improvements.  A point release would also enable contributors to more easily contribute to updating the documentation. 

Again, thanks for the swift response and for providing such a valuable tool. I second the GSOC idea and would even go further: If some of the license fees research institutions invest in proprietary coding solutions could be rerouted to QualCoder, this would have the potential to create a sustainable model for continuous development of the core QualCoder ap and possible plug-ins for specific use cases. Sch an architecture could also prevent the bloat commercial solutions suffer from. 

Given increasing mandates for open science in research funding and the fact that several companies run profitable businesses selling licenses for hundreds of dollars per license, I would not consider this software 'niche', especially in connection with the REFI standard I see a real possibility to create a sustainable development model.

**Comment by WPFilmmaker** [comment]
+1 for transifex

**Comment by ccbogel** [comment]
OK so I have uploaded the Qt .ts files to transifex. I was not able to upload the .po files.

**Comment by ccbogel** [comment]
@menelic thanks, glad you like the software. Also thanks re deepl.com I have used it and like it. The manual is updated and most translations are done (even if imperfect). Yes @WPFilmmaker mentioned GSOC previously, I will have another look there. Yes, i will likely release a lot sooner than the milestone.
I have no clear plan of future improvements,  although a few of you have made good suggestions. The other thing that I should do is try and make unit tests, which will take some time.

**Comment by ccbogel** [comment]
@menelic OK It is done, a new release is available. Please confirm the debian file works on your system. It installed fine on mine (Ubuntu 20.04). Before installing it, ensure you have openpyxl installed.

**Comment by menelic** [comment]
> @menelic OK It is done, a new release is available. Please confirm the debian file works on your system. It installed fine on mine (Ubuntu 20.04). Before installing it, ensure you have openpyxl installed.

thank you, I can confirm that it works on Ubuntu 16.04 and 18.04. Thank you for a great 2.0 release with many usability imrovements!

**Comment by menelic** [comment]
@ccbogel please accept my (and possibly other) transifex request to join the translation team - collaborative  translation can only begin only after you have accepted join requests.

**Comment by ccbogel** [comment]
OK thanks re feedback with the Debian. I am not familiar with Transifex:
![pic1](https://user-images.githubusercontent.com/5834638/90450640-88049100-e12d-11ea-8723-1732eda1dec8.png)

**Comment by menelic** [comment]
@ccbogel I suggest you just translate one string or even just one word to get over this hurdle so we can assist you and free you up for further development of QualCoder.

**Comment by ccbogel** [comment]
@menelic  Seriously, I do not know what I am doing with transifex. privately I could give you my login details as my password is unique for this site.

**Comment by menelic** [comment]
@ccbogel here is a step by step guide - I have contributed to but not managed transifex based translations before but it seems pretty straightforward. Its also pretty "set it once and forget it" - do let me know if I should try and assist further

https://docs.transifex.com/transifex-github-integrations/github-tx-ui

**Comment by ccbogel** [comment]
I will close this issue for now - related to development status. As mentioned I am having difficulties with transifex .
