### ISSUE TITLE
ValueError when selecting segment in audio coding window

### ISSUE THREAD

**Issue by forsakendaemon** [ccbogel/QualCoder#259]
**Describe the bug**
When attempting to select a segment during audio coding, a ValueError is thrown:

```
QualCoder-master/qualcoder/view_av.py", line 865, in create_or_clear_segment
    if float(self.segment['start']) > float(self.segment['end']):

ValueError: could not convert string to float: '0:13'
```

**To Reproduce**
Create a new project and import an mp3 file. Open the 'Code audio/video' window. Start playing the media. Select Start segment. Select End segment.

**Expected behavior**
Segment is set.

**Desktop (please complete the following information):**
- OS: macOS 10.15.6
- Version 2.0
- python 3.7.8

**Comment by ccbogel** [comment]
thanks i missed that
