### ISSUE TITLE
Glitches in text (2.0)

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#260]
In settings the options for the backup are not divided by a space thus they result had to read:
https://i.imgur.com/b1QdE3p.png

They should be divided. Also if you notice some letters are truncated.

In graphic view, the text overlaps:
https://i.imgur.com/L0w6VGc.png

Qualcoder 2.0, Lubuntu 18.04, font size 14 (default).

Edit: it seems that this version has issues with rendering text, at the least on my system. Has some lib been upgraded? After exporting coder frequencies the text looks like: https://i.imgur.com/hlMelb8.png

**Comment by ccbogel** [comment]
I have uploaded some changes to allow for a bigger size 14 font. 
No problem with font rendering, but I had reduced the size of the box that displayed the text.
I have uploaded improvements, but wont do another deb release for a while yet.
