### ISSUE TITLE
An interactive data explorer feature

### ISSUE THREAD

**Issue by jlopezsi** [ccbogel/QualCoder#261]
**This feature request is for making easy the analysis of qualitative data**
I am thinking in an interative window similar to the Report/Coding reports but in which in the left we have all files, cases, attributes, and codes, that you can select and deselect just clicking on them, and on the right, you have all files you have selected with the codes selected highlighted but if you click on the window of files, you can select viewing only the segments coded with the codes selected. Like a switch.  it is interactive because if you select another file, attribute or case, the window showing the segments is updated.

**Describe the solution you'd like**
I see two soluctions: 1) add a new menu Data Explorer or 2) modify the coding feature so that it works in the way i've explained. The second solution has the disavantage that the coding menus are specific to the kind of data: text, AV, image. It would be nice to have a data explorer that works with all kind of data al the same time

**Additional context**
<img width="425" alt="image" src="https://user-images.githubusercontent.com/4014875/91468910-f1557400-e892-11ea-973a-5ddd45b12276.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/4014875/91469036-25c93000-e893-11ea-8cdf-f0aca8f81e6f.png">

**Comment by ccbogel** [comment]
@jlopezsi thanks - a lot of work :) 
I will look into this when I have more free time

**Comment by ccbogel** [comment]
@jlopezsi OK. So to clarify this, otherwise it will get messy.
1. You would only select ONE file (or case) at a time and only ONE code at a time to view the selection in the right hand side?
2. What is done if ONE code it in MULTIPLE places in the selected file (or case)? How will this be displayed?

**Comment by ccbogel** [comment]
I have started with the code text window. and added a file explorer.

**Comment by jlopezsi** [comment]
1. You would only select ONE file (or case) at a time and only ONE code
   at a time to view the selection in the right hand side?
   2. What is done if ONE code it in MULTIPLE places in the selected file
   (or case)? How will this be displayed?

The idea is to be able to select one or various codes (you will see whether
one follows the other, or they appear concurrently, etc), and then
select cases or files, and attributes of cases or files and explore the
pattern. I see that it is difficult when you have texts, pictures, and
video files, but if all have transcripts, and codes are liked to
transcripts, then it is possible, I think. This is a previous step to
conduct a query.
By the way, today I've explored importing a REFI project from Nvivo but it
seems that codes are not linked to texts, you have all texts and codes, but
not the linked to the segments of texts. Today I'll try to import a REFI
project from maxqda.
Thanks,
Jordi


*------------------------------------------------------------*

*Jordi López-Sintas, PhD <https://jlopezsi.netlify.com>*
*Catedràtic d'universitat, Comercializació i investigació de mercats (full
professor of marketing and consumer research)**, *Department
d'Empresa, Universitat Autónoma
de Barcelona <http://www.uab.cat>, Spain.

President d'Espacual <https://www.espacual.es>, Asociación Española para el
Avance de la Investigación Cualitativa (2016-2022)

**Comment by jlopezsi** [comment]
Colin,
Sorry, importing the REFI project from nvivo worked well.
J
*------------------------------------------------------------*

*Jordi López-Sintas, PhD <https://jlopezsi.netlify.com>*
*Catedràtic d'universitat, Comercializació i investigació de mercats (full
professor of marketing and consumer research)**, *Department
d'Empresa, Universitat Autónoma
de Barcelona <http://www.uab.cat>, Spain.

President d'Espacual <https://www.espacual.es>, Asociación Española para el
Avance de la Investigación Cualitativa (2016-2022)

**Comment by ccbogel** [comment]
@jlopezsi Good that Nvivo import worked well for text files. Thanks for the feedback. Yes - it might be that you need to change the coder name in the Settings to a name used in the Nvivo project, and the same issue again when using MAXQDA.

_The idea is to be able to select one or various codes (you will see whether one follows the other, or they appear concurrently, etc), and then select cases or files, and attributes of cases or files and explore the pattern_
Yes OK  -  I will look into this - only for text files.

**Comment by ccbogel** [comment]
I will close this issue. It is something  I have not been able to implement. I find it too challenging.
