### ISSUE TITLE
Bug: Adding many files moves report window outside visible area

### ISSUE THREAD

**Issue by AmbientComplexity** [ccbogel/QualCoder#262]
I'm running on windows. If you batch add or remove files and the list is longer than can be displayed on the screen, the accept dialogue button is outside the visible area. Solution: Maybe truncate the list of added files after a certain amount?

**Comment by ccbogel** [comment]
@AmbientComplexity  ok thanks _I have been busy but will look at this soon.

**Comment by ccbogel** [comment]
@AmbientComplexity How do you batch add or remove files?
In the file manager 'Files' dialog you can only select one file at a time to delete, and to add files, no window is displayed showing the files to be imported?

**Comment by AmbientComplexity** [comment]
Hi, thanks taking time to look at my issues. I just shift click. See the image attached: 
![qualcoder-addfile](https://user-images.githubusercontent.com/49981549/92590113-f0addc00-f29b-11ea-978e-d489a0ccafc4.PNG)

**Comment by ccbogel** [comment]
@AmbientComplexity OK I understand this exactly where the problem is occurring now. Yes shift or ctrl click is normal for multiple file selection here.
The Import file window is a part of the Qt framework and I cannot change this behaviour if the Open button moves off screen on Windows.

**Comment by ccbogel** [comment]
this i cannot resolve
