### ISSUE TITLE
Req: Better handling of projects with many files

### ISSUE THREAD

**Issue by AmbientComplexity** [ccbogel/QualCoder#263]
Hi,

first of, thanks for providing this great tool. I'm currently doing research on alot of .txt files. My project contains around 2000 of them. Currently the major feature I'm missing to use QualCoder efficiently, is better handling of file selection. Right now, to switch documents, I have to click "View File" and then scroll to the required file. If you have alot of files, this becomes unwieldy at some point.

Possible solutions:

- The File Viewer dialogue remembers its last spot / jumps to the currently open file
- Add a "next file" function
- Narrow down the file selection dialogue on a per case basis

Any of these features would help me immensly.

**Comment by ccbogel** [comment]
@AmbientComplexity ok will look at implementing some of these options.

**Comment by ccbogel** [comment]
@AmbientComplexity I have added a context (right click) menu to the button. 
So you can go to the next file or go to most recent coded file.
