### ISSUE TITLE
Bug: Big fonts and buttons on Debian 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#268]
I installed qualcoder on Debian 10 i386 with Lxqt and Openbox. The good news is it works fine so far. The problem is everything looks huge, to the point qc is not usable on my setup. This screenshot shows qualcoder maximized at 1024x600. To make the most of the small screen, I have set up my Openbox window manager to maximize and undecorate all windows, and the panel to hide. Everything looks very big and the filename column takes up the whole of the width and more. I haven't seen another application doing this, so it must be fixable. 

(tempted to install it on Raspberry Pi for fun)

![qc_debian](https://user-images.githubusercontent.com/16408198/94921132-2fa00d80-04a7-11eb-8535-82160cf74376.png)

**Comment by ccbogel** [comment]
That file name is very long. But gives me ideas of how to wrap n display long names. 
The font can be reduced in size via settings.
Is the screen resolution on your computer 1024x600. Can you change the screen resolution to improve the display.
I might have to state some limitations for minimum screen size.

**Comment by glocalglocal** [comment]
OK, making the font smaller did it. That's the resolution of that screen -- it's an old netbook and it works fine. 1024x600 should be more than sufficient for such operations, but going for lower resolutions may be an issue. I made that filename intentionally long to push it a bit.

**Comment by ccbogel** [comment]
Ok. Good to know. I will add a recommendation re minimum screen size. And wrap text for long file names.

**Comment by glocalglocal** [comment]
I think 1024x600 is just about the smallest screen you can get, and qc looks fine with it. Another possibility for the long names is to truncate with '...' and a tooltip, like what Windows Explorer does. I think wrapping has the advantage of enabling the user to see at  glance the characters at the end of longfilename1, longfilename2, longfilename_date.

**Comment by glocalglocal** [comment]
> (tempted to install it on Raspberry Pi for fun)

Yeap, possibly the first QualCoder installation on Raspberry Pi in the world. :) 

![rpi](https://user-images.githubusercontent.com/16408198/94996880-c39cd280-0596-11eb-9ac0-93b568cf9c46.png)

Headless Raspberry Pi 4A, 4MB, running Raspberry Pi OS v10.6 32bit

**Comment by ccbogel** [comment]
Very nice! Hope it was straight forward.

**Comment by glocalglocal** [comment]
Very straight forward. I followed the instruction for Debian. Raspberry Pi OS is based on Debian anyway.

**Comment by ccbogel** [comment]
The long file name I have done this: truncated with '...' and a tooltip.
Also I have added a sentence in the manual about minimum screen size.

**Comment by glocalglocal** [comment]
>  truncated with '...' and a tooltip.

Not what I see here:

![longfn](https://user-images.githubusercontent.com/16408198/95081841-afc5ad80-0709-11eb-8a22-d75d316d72c9.png)

**Comment by ccbogel** [comment]
@glocalglocal thats interesting.  There must be some slight differences in qt on different platforms.  On Ubuntu 20.04 it used the  '...' without vertically widening the row.
