### ISSUE TITLE
Usability: Make it easier to understand connections between the different data types (documents, codes…)

### ISSUE THREAD

**Issue by jdittrich** [ccbogel/QualCoder#270]
Several features need users to setup. E.g. before one can code a text, the text needs to be added as file. I often find myself wanting to use a function, then to see that it requires setup somewhere else. It is not hard to find out, but it is not beginner friendly, either. 

_Possible solutions:_
* The most simple would be recognizing if there are zero items that are required for using the function and then display a hint, possibly even with a link allowing to open the dialog needed for setting up the missing data. 
* In addition and as a more long-term-y solution one could consider moving to a more document centric interface, in which the UI relies less on calling up several windows (thus making it easier to navigate). This could possibly be done using QT dock widgets ([class](https://doc.qt.io/qt-5/qdockwidget.html), [example](https://doc.qt.io/qt-5/qtwidgets-mainwindows-dockwidgets-example.html)), resulting in a similar UI than MaxQDA or f4Analysis.

In either way I could help with mockups and possibly some QT code (I'm a UX designer, so programming mileage varies)

**Comment by ccbogel** [comment]
I like the most simple solution (eg grey out code image if no images are in the project).
OK dock widgets, might be a summer holiday (for me) project.

**Comment by ccbogel** [comment]
@jdittrich I have restricted the coding choices depending on the source files that are a part of the project

**Comment by ccbogel** [comment]
I have had a play with qdockwidgets. I am not sure that they are quite what  I need, but I can add the QDialogs to as a tabbed widget, so have one tab as a coding area, and maybe another as a journals area, replacing the temporary notes tab.

**Comment by jdittrich** [comment]
In case you want feedbach: Is there a branch to check out?

**Comment by ccbogel** [comment]
No branch yet. I sm still experimenting. I will put a develop branch out, maybe today.
It was actually quite easy, as the QDialogs that were existing can be placed as objects directly into each tabbed page.

**Comment by ccbogel** [comment]
will close now, as the tabbed version works quite well
