### ISSUE TITLE
Dragging codes and categories

### ISSUE THREAD

**Issue by mirren** [ccbogel/QualCoder#271]
**Describe the bug**
It is not possible to drag codes and categories in order to rearrange them. 

**To Reproduce**
Try to drag codes and categories while in the Code Text or Reports windows. 
Codes and categories cannot be dragged 

**Expected behavior**
Codes and categories can be dragged to create a tree structure as described in the manual

**Screenshots**

**Desktop (please complete the following information):**
 - OSX Catalina 10.15.6, Python 3.9

**Additional context**

**Comment by ccbogel** [comment]
OK. You are not able to drag codes and categories in the Reports window, only in the coding windows.
You can only drag them to:
- add a code to category
- add a category as a sub-category of another category
- drag a code or category onto empty space (below the tree) to remove from a category
- merge a code into another code

Are none of these functions working? If definitely not, then I could add a right-click menu function to enact these actions.

PS I am not able to reproduce your OS and am still developing on python 3.8

**Comment by mirren** [comment]
It seems as if dragging does not work at all. 
There is no way to move a code by clicking on it and dragging. 
I will look into trying it out with 3.8, not sure what is causing this....

**Comment by mirren** [comment]
Same behaviour with 3.8

**Comment by ccbogel** [comment]
Hmm, might be something quirky with the Qt version on mac. I will Google,  and also add right click menu options

**Comment by mirren** [comment]
I was tinkering with re-installing things and it seems that it is working now. May also have been related to the screen setup. 
Is there a recommendation about whether the program should be invoked from qualcoder or QualCoder directories?
By the way, I cannot find the .qualcoder directory or the qualcoder.log file

**Comment by ccbogel** [comment]
@mirren Thats great that it is working for you. As I was having trouble working out a solution.
Is there a recommendation about whether the program should be invoked from qualcoder or QualCoder directories - I am not sure what you mean.
I think on a Mac you have to run it from the terminal - is that correct?
It should not matter which directory you run it from as long as you have the path correct that goes to the qualcoder.py file
As qualcoder.py is where it all starts from.

The .qualcoder folder is in your Home folder
On Mac your Home folder is here: /Users/<username> 
the .qualcoder folder has a dot at the start, maybe this is hidden - perhaps in your Mac settings https://setapp.com/how-to/show-hidden-files-on-mac

**Comment by mirren** [comment]
Yes I use the terminal to start qualcoder. Good to know it does not matter where it is invoked from. 

Here is the log file for the record. There are some entries but I do not know if they are related to the issue. 
[QualCoder.log](https://github.com/ccbogel/QualCoder/files/5389686/QualCoder.log)

Thanks for helping out!

**Comment by ccbogel** [comment]
@mirren Thats ok glad to help.
Those errors listed are not important. Most of them have to do with getting access to the Github releases so that when opening
QualCoder it can check if the code you are running is the latest release in the github relreases.
Occasionally there is a wrapped object deleted. again, not major issue - this is to do with when a dialog window is closed an then not found
