### ISSUE TITLE
Uncaught Exception: Cannot remove code from double coded text segment without error and QC closing

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#275]
When trying to remove one code from a double-coded text segment, the following error occurrs:

![QualCoder uncaught exception](https://user-images.githubusercontent.com/5934115/96510359-b3a31500-125d-11eb-9584-11cd93018737.png)

This is a new error, I have removed many codes without problem. After some hasty clicks (i believe in the code tree where an unsuccessful drag and drop had led to the wrong attribution of a code) this error is now persistent.
 

This error window blocks the context window in which codes are offered for removal.Clicking ok simply leads to the same error window popping up again.  The only way to get out of this is to hit enter at great speed unti QualCoder closes.

Ubuntu 16.04

**Comment by ccbogel** [comment]
Thanks - looking at this right now

**Comment by ccbogel** [comment]
Yes - a little while ago I did do a change with the 'select_items.py' file
This is working for me perfectly. It also give a specific warning on a no name error.
Perhaps download the qualcoder zip again - As I dont know how long ago you downloaded it, and so some variations may have occurred
