### ISSUE TITLE
pyw to hide the DOS box on Windows 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#278]
Under Windows, running the .py files opens a redundant DOS box. To stop this I have been executing this:

C:\Windows\pyw.exe "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py"

Perhaps something like this can be incorporated as standard for Windows setups, as in [here](https://stackoverflow.com/questions/34739315/pyw-files-in-python-program#34739687).

**Comment by ccbogel** [comment]
@glocalglocal For now,  I have added your terminal command in the Read Me.

**Comment by ccbogel** [comment]
when I get around to playing with pyinstaller again, I will use this also
