### ISSUE TITLE
Provide old versions of deb files?

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#28]
I saw you removed 1.0 and 1.1 deb files and it make sense as 1.2 is out, however what if the user needs to downgrade (because the new version breaks something or to compare the two versions)? 

With .deb you can easily uni stall the problematic version but where does one find the older version?

I think it makes sense to leave the older versions available if user need them (perhaps in a folder?) and warn that they should not be used, unless there are specific cases, are old version not supported. This is what Firefox addons do and I think it can be useful.

**Comment by ccbogel** [comment]
HI, yes you are right. What I will do is make another repository with the older deb versions.

**Comment by ccbogel** [comment]
I have made a repository for the older Debian packages.
