### ISSUE TITLE
Bug: About info not updated and dialogue not re-opening

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#282]
Installed 2.1 but on Windows About still refers to 2.0 and the Action log states: 

```
This version: QualCoder 2.0
Newer release available: QualCoder 2.1
https://github.com/ccbogel/QualCoder/releases/tag/2.1
```

On both Windows and Linux, I open About, close it, and try to re-open it but it doesn't open again until I restart the application.

**Comment by ccbogel** [comment]
Damn i thought i had updated the 2.0 to 2.1.
The open close, yeah, its a tricky issue for me yo fix. Will try different code. But if you open a different dialog window and then re-open information it will work.

**Comment by ccbogel** [comment]
OK fixed this silly error on part: Installed 2.1 but on Windows About still refers to 2.0.

**Comment by glocalglocal** [comment]
Just re-installed on Linux and I am getting again: 
```

This version: QualCoder 2.1
Newer release available: 
https://github.com/ccbogel/QualCoder/releases/tag/2.1
```

**Comment by ccbogel** [comment]
Ok. Well an improvement over the previous error. Will look in to it again.

**Comment by ccbogel** [comment]
now fixed with better parsing for the version number
