### ISSUE TITLE
CAnnot re-open same dialog twice

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#283]
@Glocalglocal 
On both Windows and Linux, I open About dialog, close it, and try to re-open it but it doesn't open again until I restart the application.

**Expected behavior**
Dialog to re-open

**Comment by ccbogel** [comment]
@glocalglocal OK I have added some code that appears to fix this issue. For the next release at some stage.

**Comment by glocalglocal** [comment]
Not sure if this is incorporated in the current update, but on Windows the problem persists.

**Comment by ccbogel** [comment]
Its a difficult issue to fix. I have been aware of it for a long time. The attempted fix is not in the release.

**Comment by ccbogel** [comment]
OK I made the About dialog modal, so i will always open when the option clicked.

**Comment by glocalglocal** [comment]
Is there a difference between OK and Cancel?

**Comment by ccbogel** [comment]
not in that dialog

**Comment by glocalglocal** [comment]
So why not keep OK only?

**Comment by ccbogel** [comment]
I new you wer going to say that. Ah more work. ok.

**Comment by ccbogel** [comment]
oops and bad spelling
