### ISSUE TITLE
Add manual to the deb file?

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#29]
I noticed that when using the deb file no manual is present in any folder, unlike when you download from the green clone button where the manual is present. I think it makes sense to have it shipped in the deb file too.

**Comment by ccbogel** [comment]
I am only a beginner at making deb packages, I am finding it complicated. I do not think it is possible to have the pdf manual inside the deb package, because when the deb is installed, where would the manual go. However, when you open qualcoder, there is a help option, and in here  I have put help information.

**Comment by ccbogel** [comment]
The manual is already there when you unzip qualcoder-master from github: QualCoder_Manual.pdf or QualCoder_manual.odt

**Comment by WPFilmmaker** [comment]
Yes indeed, sorry for my english, i meant the manual could be added to the deb file folder like you do for the 
 qualcoder-master folder.

**Comment by ccbogel** [comment]
Yes I understand now what you mean. I don't think this is a good idea, as the deb is used to install software, rather than a general repository of files. The pdf manual would then end up in the /usr/share/qualcoder location along with all the software files.

**Comment by WPFilmmaker** [comment]
Yes it would, it would also increase the file size, I think it is acceptable but you may disagree with that, what I would be sure is that there is a way for the user to have access to the manual (that’s why I proposed to open the pdf from the software), because when QualCoder will be in debian repo user won't see the manual download next to the deb file as it happens now on github.

**Comment by WPFilmmaker** [comment]
Alternatively you could add the manual as html to open within the browser (I saw this in quite a few projects) but of course html is not as pretty as pdf for rendering complex things like a manual.

**Comment by ccbogel** [comment]
Hi WPF, actually this already occurs within the software, if you go to Help and then Contents in the top menu. It is already there as an html file. The exact same html file can be viewed in a browser.
