### ISSUE TITLE
Timestamp insertion not working (2.1)

### ISSUE THREAD

**Issue by taobao-kba** [ccbogel/QualCoder#290]
**Describe the bug**
Failure to insert timestamp in transcription both when playing and when paused. Below prompt shows on pressing of ctrl+T

**To Reproduce**
Press ctrl+T when transcribing

**Expected behavior**
Insertion of timestamp

**Screenshots**
![image](https://user-images.githubusercontent.com/74268289/98727553-fbfeb000-238f-11eb-84b5-6b64c23fd83e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version QualCoder 2.1

**Comment by ccbogel** [comment]
Thanks for this. I forgot to add code for timestamps like '0.13' unlike '0:13'
Download the files here, not the release, the fix will be uploaded in the next release.

os how did you find out about qualcoder and do you like it generally?
