### ISSUE TITLE
Code or Auto-Code whole paragraph

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#291]
**Is your feature request related to a problem? Please describe.**
Coding or Auto-coding a whole paragraph can be helpful for various use cases, not least among them analysis and visualisation of codes and categories by respondent. In the context of group interviews, focus groups or coding by person across files this can yield additional insights, especially if combined with the analytical possibilities unlocked by the implementation of #182   https://github.com/ccbogel/QualCoder/issues/182#issuecomment-717161532 

**Describe the solution you'd like**
Enable coding by paragraph and auto-coding of all paragraphs, for example those following a [speaker] with a corresponding code. Most transcripts or texts are pre-formatted in ways that allow for an implementation of this feature simply by paragraph or by [speaker] 

**Describe alternatives you've considered**
It is of course possible to do this manually, but this task would be made easier by the implementation suggested above.

**Comment by glocalglocal** [comment]
Coming to this from a different angle, this would be great for autocoding twitter, Facebook etc content. Typically, software collecting such content stores each message and its metadata one message per line (eg JSON or CSV). The user can use tools (even Excel) to extract 1000s of messages (possibly in the format ID <tab> message <new line>) into a single file. Qualcoder could autocode lines (ie messages) based on search queries, ideally supporting regex. Qualcoder would then produce its usual reports. If coded messages can be exported in a usable form, users can import them to other applications for further computational analysis and visualisations (eg gephi). The ID will still refer to the original message as delivered by the platform API. I think that would be an excellent feature. I believe some researchers currently use KH Coder for something like that.

**Comment by ccbogel** [comment]
coding whole paragraphs is a challenge. The ideas about coding other source - this is a separate issue. A future possibility.
Defining backspace n for an end fragment - I can experiment further with this but currently it did not work when I tried it. Which is why I avoided it.

**Comment by menelic** [comment]
thanks for the swift reply and the explanation - I was indeed hoping that \n or \r\n ASCII encoding for NEWLINE could be used to identify the end of a paragraph. If that proves difficult, maybe an approximation would be a selection dialogue where one could tell QualCoder how many sentences (defined as until the next full stop) should be coded.

**Comment by ccbogel** [comment]
OK. I have resolved this.
There is an additional button in code text to use start and end marks.
The coded text include the start mark but stops before the end mark.
You can use the new line symbol by typing \n
