### ISSUE TITLE
Easy way to install QualCoder on Windows

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#292]
**Is your feature request related to a problem? Please describe.**
An issue I encounter all the time when I propose QualCoder as alternatives to proprietary software is the installation. My colleagues usually use Windows and are not into programming, and while for me (on linux) typing commands on terminal is no an issue, having to tell people use command line, install this and that, it discourages them. Also in case of issues I have no idea how to help them as I don't use windows.

**Describe the solution you'd like**
An easy way to install QualCoder with a few clicks. Either an exe file or have QualCoder into windows store

**Additional context**

**Comment by ccbogel** [comment]
I have looked at using pyinstaller. But I had lots of problems making it work well. If anyone has the skills to do this I would appreciate their help.

**Comment by AndrzejWawa** [comment]
Hey,

Do you have any secific problems with this? - Maybe, I would ask someone.

**Comment by ccbogel** [comment]
@AndrzejWawa @WPFilmmaker I have managed to create an exe for Windows 10 on 64bit Windows. I have added it to the 2.7 releases. Translation files may not work. So I added some code so that translation files e.g. de.mo and app_de.qm are placed in the home/.qualcoder folder it should be able to read them. e.g. .qualcoder/app_de.qm  and .qualcoder/de/LC_MESSAGES/de.mo

**Comment by AndrzejWawa** [comment]
Hmm, very nice! It works for me too at Windows 7 :) Only some antivirus allerts appeared. So, is it mean that there is no need for having Python and modules installed at the computer?

It is possible to chage the icon into qual coder icon?

**Comment by ccbogel** [comment]
HI thanks. Good that it works on Windows 7.
I wonder if you could change the language to Deutsch in the settings. then reopen. I wanted to see if it loaded the 2 translation files. It does not load those files for me. So I had to add a workaround by storing the files in the .qualcoder folder.

The icon,  Iam not sure if I can fix this, I will have a look , minor issue.

**Comment by AndrzejWawa** [comment]
Hi,

No, I also have the problem with changing the language.

**Comment by ccbogel** [comment]
I have fixed this language issue. Try the new exe (I replaced the old exe with the same name).
