### ISSUE TITLE
Bug: Ctrl+ and Shift+click in Auto code 'select files to code' 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#293]
In the Auto code 'Select files to code' dialogue, Shift+click behaves like Ctrl+click. If I Shift+click item 2 and 4, items 2, 3, 4 should be selected. Currently, item 3 is not. If I Shift+click item 2, 4, 6, all items 2-6 should be selected. 

The same applies when de-selecting.

**Comment by ccbogel** [comment]
Fixed. I used the wrong selection mode: changed MultiItemSelection to ExtendedItemSelection
