### ISSUE TITLE
Bug: report and View inconsistencies after autocoding 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#294]
I autocoded 3 test files with node1 using the search terms 'python' and then 'test'. The result looks OK but the report (a) doesn't show the coded text with surrounding text for context (b) shows an entry (2nd) that doesn't contain a coding. Viewing the file shows a lot of stuff is coded, including whole sentences that don't contain one of the terms and the '.' before certain paragraphs.    

![auto](https://user-images.githubusercontent.com/16408198/98880406-938efc00-247f-11eb-9ef8-d6e46cd2e112.jpg)

![auto2](https://user-images.githubusercontent.com/16408198/98880413-9ab60a00-247f-11eb-8c70-0e5f63ec0a89.jpg)

Incidentally, the button reads 'Auto code'. The dialogue reads 'autocode' (no space) :)

**Comment by ccbogel** [comment]
@glocalglocal There is too much here to unpack.
But re text in context, in the report itself, I dont show this, but there is a tooltip that say click - when clicked the second picture below is shown wit hthe text in context: 

Tooltip:
![pic1](https://user-images.githubusercontent.com/5834638/98881338-dc759d80-24dd-11eb-85fe-f1c065c4c721.png)

After click a side window with text in context is shown:
![pic3](https://user-images.githubusercontent.com/5834638/98881533-573eb880-24de-11eb-85bc-af020a81971e.png)

The restricted edit window underlines anywhere where any codes or any case assignments are located for that text.

This:
 (2nd) that doesn't contain a coding. Viewing the file shows a lot of stuff is coded, including whole sentences that don't contain one of the terms and the '.' before certain paragraphs.
To check was this a newly created project  - and so the node1 assignment to the MichaelK document did not occur at previous time - to end up in this report?

**Comment by glocalglocal** [comment]
My bad. I had forgotten about the third pane and I didn't realise there were two coders. It may be just me, but I often confuse the coders. I am wondering if there should be a forced single-coder mode. If nothing else, you will get fewer bug reports from people like me.

**Comment by ccbogel** [comment]
@glocalglocal, thats ok. no I wont enact single coder mode. So close issue?

**Comment by glocalglocal** [comment]
Yes, I am closing the issue. I don't have the time to make a video, but maybe later.

**Comment by ccbogel** [comment]
No worries.  I was just hopeful.  One day I may have the time for doing that.
________________________________
