### ISSUE TITLE
Req: Undo Autocoding

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#295]
Autocode can mess a lot of things very quickly. Eg with the default '. ' (note space) as end of fragment, nearly all of my test file was autocoded because most sentences ended in '.\n' or ':\n'. Undo Autocoding would help. 

There are of course the backup files, but that's a bit drastic. If we must stick with the backup files, perhaps qualcoder could save a 'restore point' (ie a backup) every time autocode is used. That 'restore point' could be used for undo manually or as a proper undo from within qualcoder.

**Comment by ccbogel** [comment]
Yes a good point -  I will have to consider an approach for this.

**Comment by menelic** [comment]
Ideally there would be multi-step undo and redo for all coding operations, maybe this could first be implemented with a simple undo and redo option (which could be in the right click context menue for now, as long as there are separate windows) and then enhances with a listed history that names the operations. Undo and redo could be bound to shortcuts such as the fairly standard cttl + z for undo and ctrl +y for redo.

**Comment by ccbogel** [comment]
I dont think there is a need for undo for all coding operations. As you can easily uncode something you have coded. But the autocode function does need an undo as it has a broad impact.

**Comment by ccbogel** [comment]
implemented

**Comment by glocalglocal** [comment]
I can't find how it works.

**Comment by ccbogel** [comment]
I will add to the manual soon. Right click on the auto code button for a menu option to undo.
The option is only available after any auto coding has been done during a current session of use.

**Comment by glocalglocal** [comment]
> The option is only available after any auto coding has been done during a current session of use.

And when no coding has been done, the menu option is not available (OK-ish) but then I get the pop-up below, even if I change my mind and simply want to forget about the right-click. I think following convention the Undo option should always be on the right-click menu, but greyed-out when not applicable. 

Also, the pop-up title is truncated. 

![autocode](https://user-images.githubusercontent.com/16408198/99392384-89338e80-28d3-11eb-8884-9c6926d283da.jpg)

**Comment by ccbogel** [comment]
OK
