### ISSUE TITLE
Doesn't work with Linux Mint 20

### ISSUE THREAD

**Issue by janesakoh** [ccbogel/QualCoder#296]
Thank you for the great effort!

I made 2 attempts: (1) installed the Debian package for version 2.1, (2) install from git. Installation when smoothly, no error message. Folder was created in the right place. But when I clicked on the icon shortcut, there was no response whatsoever...

**Comment by ccbogel** [comment]
Ok. Firstly you also need to run the commands in the terminal to install all the python modules that are required. 
Secondly,  you could try looking in your home folder for the .qualcoder folder. Inside there is an error log. This may give insight into problems.
Thirdly,  you could start the program uding the terminal.  You need to cd to where qualcoder.py is and run: python3 qualcoder.py 
Any errors will show in the terminal.

**Comment by janesakoh** [comment]
I managed to start and run the program from the terminal. Error messages are indeed shown in the terminal. There is no .qualcoder folder hidden or otherwise in the home directory. Looks like what it needs is only to get the launcher shortcut to work.

**Comment by ccbogel** [comment]
Great that you started the program. I am unsure why the shortcut did not work.
The home folder should definitely have a .qualcoder folder
It should be located like this:
/home/username/.qualcoder

You might have to unhide folders - as there could be a setting on your mint that hides folders that begin with a dot.

I guess you are ok with the error messages, as you did not detail them.

**Comment by janesakoh** [comment]
I unhid the folders. I could see all the other hidden folder that begin with a dot, but not .qualcoder. 

There is only 2 error messages in the terminal:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[0000000002905be0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused

They do not seem to affect the running of the program.

**Comment by ccbogel** [comment]
yes those errors do not affect running. 
The lack of the .qualcoder folder is strange - as in here is stored a configuration file: config.ini  This file contains many settings, such as the default coder name, font sizes and language.

**Comment by ccbogel** [comment]
So to clarify. QualCoder does work with Linux Mint. But the Quick start Launcher does not.

**Comment by ccbogel** [comment]
@janesakoh The debian install is fixed now.
