### ISSUE TITLE
Bug: narrow popup and '?' in title

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#299]
This pop-up in Code Text is not wide enough for the title, and there is the usual Windows '?'. I am sure there is at least one more such pop-up but I can't remember where. 

![window](https://user-images.githubusercontent.com/16408198/99272277-837c7100-281f-11eb-92c7-f9df88b72756.jpg)

EDIT: Here is another narrow one: 

![2](https://user-images.githubusercontent.com/16408198/99276787-ed4b4980-2824-11eb-8871-fb5c3a0f8efc.jpg)

**Comment by ccbogel** [comment]
ok these should be better now.

**Comment by glocalglocal** [comment]
Better but see:
'?' still there:
![change](https://user-images.githubusercontent.com/16408198/99392888-5dfd6f00-28d4-11eb-8309-7b851027e6fc.png)

![show](https://user-images.githubusercontent.com/16408198/99392908-68b80400-28d4-11eb-9277-e55d71774dc5.jpg)

![truncate](https://user-images.githubusercontent.com/16408198/99392919-6e154e80-28d4-11eb-9883-ed1148bb11f1.jpg)

**Comment by ccbogel** [comment]
I have done what I can here. The code is correct but the 'whats this' question mark remains. 
I also tried to add text to the 'whats this' but that does not display.
As its more a visual nuisance than anything else, will close this issue.
