### ISSUE TITLE
More visibility for QualCoder

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#3]
To find this project I had to search on github by using specific keywords. If one googles "opensource qualitivative analysis software" QualCoder does not come up.

To give more visibility (=more users = more likely to get feedbacks and attract contributors) I would suggest to make a post about QualCoder on reddit /r/opensource/ and /r/freesoftware/.

Once you feel the project is stable enough You could also ask to have QualCoder added to: https://guides.library.illinois.edu/c.php?g=348074&p=2346107 which is one of the first results that show up.

**Comment by ccbogel** [comment]
Thanks very much for your advice. I have posted to those sections of reddit now.

**Comment by WPFilmmaker** [comment]
Great! I also thought about something else (actually copied from http://khcoder.net/en/bib.html?year=2018&lang=English&key= ), you could ask if those who use your software for their work are kind enough to send you the name of their papers and you can add it to your website. It would be a good way for advertising your free software. Khcoder (for text mining) does it and I think helps spreading the word about QualCoder.

**Comment by ccbogel** [comment]
Thanks again, you have lots of good ideas.
The KH coder site also has lots of intersting visualisations too - more coding, perhaps for the future.
regards CC

________________________________

**Comment by WPFilmmaker** [comment]
Thanks to you for developing QualCoder!

Yes KH Coder is pretty cool but as far as I know it does not work with photos or videos.

If you don't know I also suggest to give a look at Aquad, I found it impossible to use but it seems the most complete for FLOSS qualitative analysis.

Best Regards

**Comment by arthurhjorth** [comment]
FWIW I found this by googling for open source qualitative coding software, and finding the r/opensource post. So at least it's working now :)

**Comment by ccbogel** [comment]
Thanks Arthur

**Comment by ccbogel** [comment]
It would be nice if someone could set up a separate page in Wikipedia for QualCoder. I am not allowed to do so according to Wikipedia policies about conflict of interest.

**Comment by WPFilmmaker** [comment]
Qualcoder is included here: https://en.wikipedia.org/wiki/Computer-assisted_qualitative_data_analysis_software

but it does not have a page yet, @ccbogel, could you provide some cool screenshot? for the page?

**Comment by ccbogel** [comment]
I will try, I don't know about a 'cool' screenshot, but this picture shows the various coding possibilities.

![qualcoder_screenshot2](https://user-images.githubusercontent.com/5834638/62342670-0db99c80-b52b-11e9-83f4-0fd0ba81c160.png)
.

**Comment by WPFilmmaker** [comment]
That looks good! I never uploaded stuff to Wikipedia but afaik you need to chose a creative commons license in order to have the material not removed. 

For example: https://en.wikipedia.org/wiki/File:Lancaster_Gate_tube.jpg (look at the licensing part).

**Comment by ccbogel** [comment]
Under Wikimedia Commons it says:
    _Is your file a media file?
    Is it likely to be useful to a Wikimedia Foundation project? For example, can you point to a Wikipedia article that would benefit from this file's inclusion?
If you don't answer YES to both questions, maybe your file does not belong here._ 
There is no wikipedia article at present.

**Comment by ccbogel** [comment]
no more development in this pace, so closing issue
