### ISSUE TITLE
Implement automatic backups?

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#30]
From the manual: 

"QualCoder does not automatically create backups. So I recommend that you make a backup copy of the qda folder each time you plan to work on a qda project. Also make a backup before doing any
substantial changes, such as reorganising codes and categories."

Do you have plans to implement automatic backups? I think it could be useful provided you can find an easy way to implement it and that it does not bloat the software (maybe create a backup and replace it with a newer one every X time or maybe create more versions?). What do you think?

I think you are familiar with Nvivo, does it have backups?

**Comment by ccbogel** [comment]
Yes a good idea. I am being lazy, I could set it up so that on opening a project folder a backup with date and time is created. I have not used Nvivo for a couple of years, it might have auto backups.

**Comment by ccbogel** [comment]
OK I have made it so that when you open a project, a copy of the project folder is made with a date  and time added. While this won't make backups every X time, it at least provides a backup for some reassurance. (Not in the latest deb - will do another of those later)

**Comment by ccbogel** [comment]
I will close this issue as I have implemented this change.
