### ISSUE TITLE
Req: Bookmark function unclear 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#300]
Can you have multiple bookmarks? Probably not, if Go to Bookmark can point to one bookmark only. 
How do you remove a bookmark? Do you just forget about until a new one displaces it? Is there an indication of where a bookmark is?

**Comment by ccbogel** [comment]
There is only one bookmark. And its stored in the config file. This is a temporary solution for now. As ideally it should be stored in a project's database.
Can't remove it but can ignore it. No indication of where it is, at the moment.

**Comment by ccbogel** [comment]
I have uploaded a change in where the bookmark is stored -it is now in the project database itself. There is no visual indication of where the bookmark is. No sure how to resolve that - or even if its essential, but When project is opened it can show project details and display the bookmark file and location.

**Comment by glocalglocal** [comment]
Without a marginal indicator, changing the font colour, the font set, or something like that, I can't see how bookmark indicators can be improved tbh. Doing bookmarks properly would require supporting multiple bookmarks with management (editable names, ability to delete etc)  and visible indicators. This sounds like a lot of work for little gain compared to other issues (Windows installer being top priority imv).

**Comment by ccbogel** [comment]
I have implemented one bookmark only. This is sufficient for someone to pickup from where they left off.
The bookmark highlights one character when you go to the bookmark. So a temporary visual clue. I cannot add blinking cursors, as this is a read only document.

**Comment by ccbogel** [comment]
I will update the manual, and then close this issue.
