### ISSUE TITLE
Req: Clone a project (possibly as part of Manage Project)

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#303]
Ability to manage a project would be useful. Eg rename, delete. 

More importantly, duplicate a project. This would make using an existing project as a template much, much easier. This way I could create a duplicate project, not having to export/import codes, cases, files etc. I could use the cloned project as starting point, delete whatever is not relevant and continue from there. We can do that manually of course at OS level but it's not very user-friendly.

**Comment by ccbogel** [comment]
I don't think this is necessary. Use  the OS to copy the qda folder and rename it. Its easy and user friendly.
