### ISSUE TITLE
Req: Windows paths/directories in Action Log

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#304]
I think the directories should be displayed in the Action log in a Windows compatible format (backward slashes). I know you didn't like the idea a few months ago but there are two good reasons. 

Currently, I can't just copy the path and paste it into Windows Explorer to go to that folder. I have to replace a number of forward slashes. The alternative would be a clickable button that would open that folder in Windows Explorer.

The second reason is that it looks very odd to a Windows user. Together with that weird 'directory' instead if 'folder' and the absence of a Windows installer, Windows users don't feel at home.

**Comment by ccbogel** [comment]
Currently, I can't just copy the path and paste it into Windows Explorer to go to that folder.
Actually, you should be able to do it, with forward slashes.I tested and this works fine on my Windows 10 work computer.
forward slashes might look odd, and the 'directory' wording might be odd for some users but I wont change these, its a lot of work for little gain, I feel.
The Installer, yes - a challenge to do installer on any platform - so any assistance form someone knowledgeable would be helpful.

**Comment by glocalglocal** [comment]
> Actually, you should be able to do it, with forward slashes.

It works! You learn something new every day!

> The Installer, yes - a challenge to do installer on any platform - so any assistance form someone knowledgeable would be helpful.

I wish I could help with coding, but I simply don't have the skills. Sorry! I would second a point a fellow contributor made earlier. The Windows installer missing is the one thing that prevents mass adoption among Windows users who are often terrified at the thought of the DOS box. Personally, I would still prefer not having to download all those dependencies, and I'd rather stick with the manual method.

**Comment by ccbogel** [comment]
Yes sure. I will close this for mow.
ps, glad you learned something new :)
