### ISSUE TITLE
Bug: tiny fonts 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#305]
More tiny fonts in popups:

![Clipboard01](https://user-images.githubusercontent.com/16408198/99398307-2692c080-28dc-11eb-9fb5-1428b4f4080f.jpg)

![dupl](https://user-images.githubusercontent.com/16408198/99401014-95bde400-28df-11eb-883c-48e982208886.jpg)

There was another one 'Can't open project' I think. 

That's a Windows-only issue I suspect.

**Comment by ccbogel** [comment]
OK, I will gradually implement another way of displaying these messages, so that messages will be bigger font (ie font that matches the user settings)

**Comment by ccbogel** [comment]
The above ones should be fine now.
