### ISSUE TITLE
Req: reflections on amending project

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#306]
Not a specific feature request. More of a reflection on the workflow. I tried to re-create an existing project, only this time with the docs linked rather than imported. 
* I had to use Windows Explorer to clone the project folder as a folder with a new name because qualcoder doesn't do cloning and I didn't want to do all that export/import (files, codes, attributes, cases etc). 
* I opened the new project, and tried to link the first file. It failed because the file was already imported and the filename was the same. Probably a good idea. 
* I had to delete all imported files one-by-one because I can't select multiple files for deletion. 
* I could select multiple files for linking (good!). Ideally, we could also drag'n'drop files from Windows Explorer. 
* It's not immediately obvious which files were linked or imported and I had to be extra careful not to miss any. That path with forward slashes in the tooltip looks weird (a bug even!) to a Windows user.  
* One of the imported files is already coded. If I remove it to replace it with a linked file, presumably the coding will be lost. So, I am stuck with one imported file out of the whole set. Should there be a replace linked file with an imported one (easy) and vice versa (less easy)? 
* I changed the OS filename of one of the linked files thinking qualcoder would see that as a broken link. 'Manage bad link to files' remained greyed out. I could even open the file in Manage Files (so presumably the text is on data.qda, in which case I am not sure what a bad link is.

**Comment by ccbogel** [comment]
- _Added imagery to the icons to show a linked file vs imported._ 
- **Multi-file delete - yes - to implement**. 
- Dont think I can implement drag n drop from the desktop.
- Replace linked with imported and vice versa. Good point - will consider this.
- Changed OS filename of one of the linked files thinking qualcoder would see that as a broken link. Yes it will recognise a broken link but only when a project is opened. As I would not want to regularly run the method to test whether a link is broken. However, if a picture or a/v is broken-linked QC will inform the user, when trying to use that file.

**Comment by glocalglocal** [comment]
> In Manage Files: Multi-file delete - _now implemented._

I can't select more than one file at a time. 

> Replace linked with imported and vice versa. _Can now import a linked file._

Will we also be able to replace an imported file with a linked one without losing the codings that already exist? I am presuming that importing linked files doesn't affect the codings either.

**Comment by ccbogel** [comment]
Yes, can do replace imported with linked. Soon.
For deleting multiple files, use the delete button. (Im To add instructions to the manual)
