### ISSUE TITLE
Improving the ergonomics of Qualcoder

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#309]
Hello,

I have been using QualCoder for some time and I find it very good. I have had it tested by my colleagues (PhD students in a social science laboratory, mainly using qualitative methods), and from a functional point of view, it "does the job". But a recurrent criticism is the graphical interface which is too "cluttered" and unclear. I know that the software is developed by a volunteer on his free time. Nevertheless, ergonomics seems to me an essential point to make it pleasant to use. Can we carry out a collective reflection (with QualCoder users) to find a more pleasant ergonomics?

Wishing you a good day,
Qwerty

**Comment by qwertygc** [comment]
CONCERNING THE TEXT CODING INTERFACE  (especially the left pane)

Example of others UX CAQDAS (text coding interface)
![MaxQDA](https://user-images.githubusercontent.com/4261986/99823107-46ccb480-2b54-11eb-86ec-7dd8b7931c0b.png)
![Atlas.ti](https://user-images.githubusercontent.com/4261986/99823153-551ad080-2b54-11eb-9d88-322882de043e.png)
![qda miner lite](https://user-images.githubusercontent.com/4261986/99823734-04f03e00-2b55-11eb-801f-ee4fab7cfb56.png)

For the three software programs, the left pane is divided into two: on one side a case/file explorer (in the form of a tree structure) and on the other the codebook. In QualCoder, the case/file explorer is located in a specific window, and it is necessary to click on a button to access it. In QDA Miner, there is also a pane to view the variables.

SUGGESTION 1: Add a pane in the form of a tree structure showing the cases/files, instead of a specific window. We can add a section to display the variables associated with our text. When we click on the case/file name, it will load in the interface.

**Comment by glocalglocal** [comment]
Nvivo pretty much follows the same approach. Ergonomics as well as consistency and attention to detail are hugely important for so many reasons, including inspiring confidence and reducing the time users spent looking for ways to do things. We discussed such matters before but we all appreciate that it's very difficult for one person doing all the coding in his spare time to solve the many problems coming up as the project branches out. It is amazing how much Colin has done, esp since May. I think it is down to him not losing sight of the point of diminishing returns, keeping things simple and prioritising.  

Having said all this, I wish ergonomics in certain areas could improve but that may involve a lot of effort and certainly more dependencies. 

I know this is not going to happen any time soon, but for example, I think a major functionality issue is the absence of rich text in documents (a standard feature in all these applications listed above). There are of course good reasons developers like plain text, but, say, italics can signify emphasis in an interview -- an important feature in certain types of interviews. Or a highlight can be used as aide memoir. For that reason, I proposed markdown as a workaround (and that's what I use). Let's not forget that people use coding software in their lit review too, and texts can come with emphasis or other rich text features. Double-underline could replace the odd-looking overline too. But I can see how complex this would be. 

A UI designer could help with iconified toolbars too. I wish I could help with any of this, but I can't I am afraid.

**Comment by ccbogel** [comment]
Good points raised thanks.
Others have also raise this type of issue also: #270 #261
"cluttered" and unclear. - perhaps expand on this. to give more details on what needs to change for improved UI. (e.g. are icons with tooltips preferable to buttons with text?) Msybe @qwertygc you could do a short survey of the UI features needed among the PhD students - and feedback to me.

Low on my list: rich text - this is a really hard thing to implement IMO. The overline might look odd, but does work. There is no double underline in the Qt framework.

**Comment by qwertygc** [comment]
I take the liberty of going back up "as I go along" the returns that are made to me. It is up to you to see what is possible/feasible to improve this.
Remarks are identical to #270 and #261. Maybe we could merge these different issues into a single issue to find our way around?
CODE TEXT : 
It is possible to simplify the "code text" window with clear icons and tooltips, such as maxqda or nvivo. I can offer this mockup for this window. It is possible to imagine an identical organisation for the image and audio/video windows.
![image](https://user-images.githubusercontent.com/4261986/99901997-d68c7300-2cba-11eb-8c49-0f9e2d65763d.png)
![image](https://user-images.githubusercontent.com/4261986/99902294-03418a00-2cbd-11eb-93cb-0eacd66185de.png)

**Comment by qwertygc** [comment]
In the document, it is written :

> This file will have the same name as the audio or video file, but have a '.transcribed' suffix, shown in the image below. Initially, this text transcription will be empty. You can transcribe the file your self or get the file professionally transcribed and copy and paste the text into this file.

But how do I edit the .transcribed file? Via the software interface, by modifying a file, etc?

**Comment by ccbogel** [comment]
I will have to add to the manusl, instructions.
Open the audio or video file in Manage Files. The text area below is where you can type in and edit the file. At the same time as watching the video or audio.
Alternatively,  you can just open the transcribed file in Manage Files and edit there.  
Note: do the typing/editing before assigning to a case or coding.

**Comment by ccbogel** [comment]
@qwertygc I have started. In the code text window, I have removed the view file button. I have added a files list.

**Comment by qwertygc** [comment]
Oh yes, thanks ! Can't wait to see the results!

@glocalglocal : For rich text, perhaps imagine using Markdown? Qt implements [this functionality](https://doc.qt.io/qt-5/qtwebengine-webenginewidgets-markdowneditor-example.html).

**Comment by glocalglocal** [comment]
@ccbogel the files list has already improved efficiency in the workflow! As discussed before, it would be good to provide the user with quick info when possible. Eg file size, memo, number of codings etc in the same file list pane or on a status bar. 

@qwertygc currently, I use raw markdown in qualcoder and if I want I use Typora to view markdown as HTML, or convert .docx to .md and back. IMV, qualcoder fully supporting rich text/markdown would raise the game dramatically. The advantage of markdown is that the format survives plain text manipulation and makes sense to the reader even without rich text rendering, which was the whole point of markdown of course.

**Comment by ccbogel** [comment]
Rich text display. Re the markdown (or HTML - which is what markdown is converted to) These involve the use of extra characters in a text file. This is the issue that makes defining coding positions in the text extra hard, as  I would need to keep track of these extra characters throughout the document in some way.

**Comment by qwertygc** [comment]
The new UI for code text it's perfect ! But I don't have the impression that the translation has been updated?

**Comment by ccbogel** [comment]
Ok regards translations: the fr.po file is converted to fr.mo which i did and put in the locale directory. The po file is only for translations of strings within the python code. Everytime code is changed, this needs to be updated.
There is a second file of translations: app_fr.ts in the GUI folder. This is used for all the Qt framework widgets: button, label,,tooltips, window headings text. This is also converted to app_fr.qm for use. To edit the .ts file you need to install qt linguist.or if careful, directly edit the xml file.

**Comment by qwertygc** [comment]
All right. So I have to regularly update fr.mo and app_fr.ts? You do on your side the conversion in qm and po so that it is interpreted by the software then ?

**Comment by ccbogel** [comment]
Yes, correct.

**Comment by qwertygc** [comment]
OK. I proposed pull requests to correct some translation errors. I will look later at how this is translated in other software to homogenise the translation and not lose the users.

**Comment by ccbogel** [comment]
OK I have pulled the requests, and will convert and upload the converedted files. I have also changed wiki permissions so you can edit.

**Comment by qwertygc** [comment]
Thanks !
Ergonomics suggestion :

List all the files in the left window (audio/video, text, image), as on the interface for the text code. When you click, it opens the appropriate window. But that might be difficult to implement, right?

**Comment by ccbogel** [comment]
It is a good idea, but at the moment yes, difficult to implement.

**Comment by glocalglocal** [comment]
> File size and codings per file - are these really necessary when looking for a file to code? how do they benefit the coding process? ( I ask in part coz it will take a lot more work to implement)

Oops, missed this one. Emails notifications truncate replies apparently, or leave edits out. 

@ccbogel, eg codings per file immediately tells you which ones you haven't started working with. The user may even be able to sort by that variable. My premise is that some projects may involve 100s or 1000s of files. Also, I think that saving people having to stop what they are doing to go to another place to get that (or any) info that could be at their fingertips could improve workflow efficiency dramatically. A good example is how showing the list of files itself in the Code Text window and being able to jump from file to file with a single click accelerated work considerably. It did for me anyway.

**Comment by ccbogel** [comment]
@qwertygc @glocalglocal Download and have a play with the Develop branch.  I have added Icons.

**Comment by glocalglocal** [comment]
It's a good start but (a) the layout could be improved. Eg the file-related buttons could be below the files list. This way it's obvious what the arrows do and why its function is different from next/previous in Search. Similarly, the Show codings buttons could be below the codes tree. 
(b) is there a way to open this up for UI designers to contribute alternative button designs or possibly help with the layout? I am saying this because I've seen how a professional designer completely transformed other open source applications beyond recognition.

**Comment by ccbogel** [comment]
Eg the file-related buttons could be below the files list. This way it's obvious what the arrows do and why its function is different from next/previous in Search. Similarly, the Show codings buttons could be below the codes tree.
Yes enacted this suggestion.

Yes designers can contribute - where are they? 

@jdittrich is one who can help with layouts, Im not sure if he does graphic design work though.

**Comment by jdittrich** [comment]
> @jdittrich is one who can help with layouts, I’m not sure if he does graphic design work though.

That’s right. Some of my peers at [opensourcedesign.net](https://opensourcedesign.net) are excellent at designing icons, you could [create a job](https://opensourcedesign.net/jobs/). It often is helpful to describe the target users and/or the style you aim for. You can also reach out on the [forum](https://discourse.opensourcedesign.net/t/introductions-come-in-say-hi/), if you like.

**Comment by glocalglocal** [comment]
> Yes enacted this suggestion.

The files list + toolbar are there, but the codes tree is invisible until I pull it up from the bottom. The 'Show codings' buttons are missing completely. My arrangement is reset every time I close the window and have to do it all over again next time. 

But it already looks much more ergonomically designed, although to be fair I am sure a pro designer would do miracles.

**Comment by jdittrich** [comment]
> e.g. are icons with tooltips preferable to buttons with text? [source](https://github.com/ccbogel/QualCoder/issues/309#issuecomment-731440132)

No, usually not. Icons are great if: 
* They have a standardized meaning (e.g. folder for open, disk for save, clipboard for paste… specific application genres might have their own established 
* they refer to something inherently visual (think of the icons for italic and bold, or left/center/right-aligned or text color in a word processor)

For most other cases, one is usually better off with a text label, particularly if one can't do many usability tests on how well the icons work. It might look a bit boring _but_ it works better than self-cooked icons that have symbols unknown to the user.

**Comment by ccbogel** [comment]
@glocalglocal I think you grabbed a version before I uploaded all the buttons to the develop branch - a few minutes ago.
RE icon design. Even the professional software has 'quirky' icons that are not immediately obvious. I have tried to use mostly a standard set, so things like delete, import and export etc look like that. I did edit some for the unique aspects - eg autocoding and file linking.

**Comment by glocalglocal** [comment]
@ccbogel I download the new one. Yes, working fine. There is a lot of white (well, grey) space now where the buttons were previously, but that's something probably for later.
