### ISSUE TITLE
Graph view

### ISSUE THREAD

**Issue by bennettscience** [ccbogel/QualCoder#31]
I'm trying to understand how the graph is drawn. I've looked through the source and I'm trying to understand how the angles and lengths of segments are drawn. Can you give a quick primer here (or in a future manual update) about how the graph is created?

**Comment by ccbogel** [comment]
OK I will try. It was a matter of a lot of experimentation, and likely there are other solutions:

1 Identify the top level items (categories and codes with no super-category)
2 Arrange these equidistant around a circle with a radius of 180px. (Actually the circle is an oval, as screens are wider than high - this is the reason for the rx_expander)
3 Then recursively look at each of these items. For each item arrange the sub-items in a circle (as in step 2 above), but reduce the radius length by dividing by the depth of the item. This is the code on lines 207 & 208 in the view_graph.py: (m['depth'] + 2).  So if the item had a depth of 0, the radius would be halved, a 1 the n radius reduced by 1/3 etc.
4 Each of the resulting x, y coords are for the top left text box, which positions the box.
Note the above approach might not be ideal for a deeply layered set of categories and codes (e.g. 4 deep or more), but you do have the option of selecting any category and doing a node graph on that.

5. In the class LinkGraphicsItem a line is drawn between the category and sub-category(or code). 
6. Each text box position and size (eg all corners) are looked at for both items, the 2 closest corners are identified and used as the x,y, coords for drawing the line.

7. I don't make any adjustments for overlaps of text boxes. This was complex enough to do as is. However, you can drag the boxes around by left-clicking near the box margin and dragging.

**Comment by ccbogel** [comment]
I hope that was sufficient info for you.
