### ISSUE TITLE
Registering case attributes does not work.

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#311]
Hello,
I noticed a bug in qualcoder. I was able to create case attributes. However, when I want to assign an attribute value to my cases, it remains empty.No line is saved in the database (`attribute` table).

Yours sincerely

**Comment by qwertygc** [comment]
OK i have recreate a new project and it's work...

**Comment by qwertygc** [comment]
Non... Quand je referme/réouvre, ça disparaît à nouveau. Étrange.

**Comment by ccbogel** [comment]
Thsnkd. One of tjose tricky hard to detect bugs. Will look at as a priority.

**Comment by ccbogel** [comment]
I have edited the Add Attribute dialog to be more clear about when the OK or Cancel button is pressed.
However I cannot recreate this bug.
If I add a case after attributes are made, the attributes table does fill with placeholders for the attributes for that case. I can enter attribute values in the cases table for that case, and they are stored.

**Comment by qwertygc** [comment]
> Thanks. One of those tricky hard to detect bugs. Will look at as a priority.
> "When I close/reopen, it disappears again." - not sure what you mean - close and open the Cases Dialog?

The software. When it's just the window, the data is retained. Which is strange by the way.

Process :
1) Creation of 3 cases in the case management interface
2) Creation of attributes in the specific window
3) Enter in the cells the attribute values of my cases
4) creation of a 4th case. Fill in the attribute
5) restart the software

**Comment by ccbogel** [comment]
@qwertygc I have made some changes. so when entering the attribute value the attributes are re-loaded.
I have also added a warning when entering text into a numeric attribute.
I also found an error when entering new attributes, character attributes were made numeric.
You may have to change some attributes from numeric to character in Manage attributes. 
I think this fixes the issue - as  I have tested it a bit. Please confirm.

**Comment by qwertygc** [comment]
Hello,

I tried again, and the bug still exists. Surprisingly, it only removes the attributes of even cases.

**Comment by ccbogel** [comment]
What do you mean by even cases? The caseid?
How many cases did you add after you created attributes ?
Hoe nnany attributes did you add?
I have to match exactly what you did.

**Comment by qwertygc** [comment]
Yes, the caseid. I have add 3 cases and 2 attributes. 

I have create attributes, add 3 cases. I have filled the table. I have join files in cases.  --> I have content
I have look content of files  --> Content are missing.

**Comment by ccbogel** [comment]
I have tested again. I cannot create the error of missing attributes that is happening for you.
There must be something different that you are doing that I am not aware of.

**Comment by qwertygc** [comment]
OK i have delete the atribute and recreate and it's OK... Thanks.
