### ISSUE TITLE
Create a translation guide

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#314]
Hello,

I am currently translating QualCoder. I have difficulty translating some technical terms (codebook, journal, etc.), because they are specific terms. Perhaps it would be interesting to list the software's technical terms and see how it is translated in other CAQDAS, in order to find terminology that does not disturb new users? 

This could take the form of a page in the wiki, for example, which would be contributory.

I can start a recession of technical terms if necessary, to help clear the work.

Sincerly

**Comment by ccbogel** [comment]
Yes sure. I could add a text file of terms in the QualCoder-Master folder.

**Comment by ccbogel** [comment]
p.s. is the new file selection much better?

**Comment by qwertygc** [comment]
I download for test :-)

**Comment by qwertygc** [comment]
I don't have permission for create a new page but  started to make a table of equivalence of terms. I'll look at the different software later.

| QualCoder        | Aquad | Atlas.ti | MaxQDA | Nvivo | QDA Miner (lite) | Sonal | REFI-QDA |
|------------------|-------|----------|--------|-------|------------------|-------|----------|
| Code             |       |          |        |       |                  |       |          |
| Coder            |       |          |        |       |                  |       |          |
| Auto code        |       |          |        |       |                  |       |          |
| Code text        |       |          |        |       |                  |       |          |
| Code image       |       |          |        |       |                  |       |          |
| Code Audio/Vidéo |       |          |        |       |                  |       |          |
| Category         |       |          |        |       |                  |       |          |
| Reports          |       |          |        |       |                  |       |          |
| Journal          |       |          |        |       |                  |       |          |
| CodeBook         |       |          |        |       |                  |       |          |
| Cases            |       |          |        |       |                  |       |          |
| Memo             |       |          |        |       |                  |       |          |
| Project          |       |          |        |       |                  |       |          |
| Survey           |       |          |        |       |                  |       |          |
| Attribute        |       |          |        |       |                  |       |          |

**Comment by ccbogel** [comment]
@qwertygc I have changed wiki permissions

**Comment by qwertygc** [comment]
Thanks !
