### ISSUE TITLE
Coding notes from RQDA not imported

### ISSUE THREAD

**Issue by FLuser1** [ccbogel/QualCoder#318]
Hi.  Are “coding notes” retained when a project is imported from RQDA?  I am talking about notes that you can attach to a coded text segment in RQDA.  I tried importing, but the notes seem to get lost.  Actually, there is no coding notes function in Qual Coder?  The closest thing is annotation function?  I have notes for every coded segment, and they are the most important component of my RQDA project files.  So it is one thing that is preventing me from switching from RQDA to Qual Coder.  I would appreciate any help.  Thank you for sharing cool software!

**Comment by ccbogel** [comment]
@FLuser1 thanks for this. I do need to make this function in qualcoder. Should be easy to do. 
The coding notes are probably imported already from rqda. To check, open the sql dialog in the reports menu then run a sql command:

select memo from code_text

This should display your coding notes. If it does, i then need to add a bit more functionality to qualcoder so you can use this easily. 

Apart from this issue,  i hope you find the software was easy enough to install snd to use.

**Comment by FLuser1** [comment]
Thank you very much for your response.  Unfortunately, the SQL command did not work—I got a message for syntax error.  It might be because I am not using the command correctly.  Anyhow, it would be great to be able to see coding memos in the “Code Text” window as we can do in RQDA.  Thanks for considering it.

**Comment by ccbogel** [comment]
This is a work in progress.
You should now see the memos on mouse hovering.
You can right click on a coded text area and add or edit a memo.

**Comment by FLuser1** [comment]
Thanks for being so responsive.  When I move the cursor over the coded text, what I see in the popup window is the code attached to text and the start and end of the coded text, instead of coding notes content.  And when I right click the coded text, I see options for changing the start/end, etc, but nothing about memo or notes.  I could be doing it incorrectly, however.  I appreciate all the effort you are putting into the cool program!

**Comment by ccbogel** [comment]
Have you downloaded the latest code from github? 
Not from the releases.

There is an option in tbe right click menu underneath _unmark_ to enter a memo for coded text.

**Comment by FLuser1** [comment]
When I downloaded the latest code, I was able to see the memos!   Thank you very much for your help!
