### ISSUE TITLE
Provide a changelog?

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#32]
I know it must be a pain for a dev, but it would be useful for users to know what has changed in QualCoder from one version to another. Right now users just see a new deb without what's new. I suggest either to implement a popup the first time you open the software (after a new update) with a changelog or to use github's 'release' section to provide a changelog or to add a changelog file here on github.

**Comment by ccbogel** [comment]
Not really a pain being a dev, particularly as it is a hobby. But there's a lot to learn and this is a really good idea. I had not even noticed the 'releases' tag before.
