### ISSUE TITLE
Req: 'Show codings for this code' in situ

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#320]
Here is the scenario: I have very-very long lit review documents with headings dividing them by source like this. 
Source1
my notes
Source2
my notes
...

Currently, I can code them and in the Code Text window I can ask qualcoder to show me all codings for a selected code. This works well for a single-source document (eg an interview) but in the above scenario, the report won't show which source (ie sub-section) the coding is part of. An elegant way to solve this is an additional 'show codings for this code' which will temporarily remove al highlights from the text except for the ones relating to the selected code. Then Next/Previous would skip from highlight to highlight. This would retain all of the context. A 'collate these codings' button could then produce the report the current 'show coded text' produces. 

Alternatively, the well-organised user could have a separate document for each source and treat them like separate interviews. Often this is not practical, hence my suggestion above. Eg imagine you have a very long public enquiry report quoting oral or written contributions from different people. It would take ages to split the document into separate contributions, one per file. The report itself could be coded as a whole instead.

**Comment by ccbogel** [comment]
show codings for this code' which will temporarily remove al highlights from the text except for the ones relating to the selected code. Then Next/Previous would skip from highlight to highlight
OK I have enacted this in the Develop branch for now.

**Comment by glocalglocal** [comment]
If I am not mistaken, to switch this on you have to click on next/previous. How about making the 'Show all codings' button an on/off toggle? 

Overlines are shown for overlapping codings that don't involve the selected code. I don't see why but if qualcoder is meant to show other codings, why wouldn't it show non-overlapping codings as well? 

I am not sure why one of the codings is highlighted in grey. 

I am getting 'This segment has already been coded with this code by XY' a lot. I know what it does, but I think that's because when I am in this mode, one of the codings is automatically selected (possibly the grey snippet above?).

**Comment by ccbogel** [comment]
Re this: I am not sure why one of the codings is highlighted in grey. I am getting 'This segment has already been coded with this code by XY' a lot. I know what it does, but I think that's because when I am in this mode, one of the codings is automatically selected (possibly the grey snippet above?)
Yes I am selecting the coded text as you move forward and back - I can switch this off - as its causing issues.

Yes will hide overlines.

Show all codings as a toggle - ok -so perhaps I can change the wording from show all codings to toggle with show this code. and change the forward back buttons to green to show this  'one code highlighting' is enacted currently.

**Comment by glocalglocal** [comment]
> Yes I am selecting the coded text as you move forward and back - I can switch this off - as its causing issues.

How about changing Previous/Next coding to Previous/Next codings page? This way the invisibly selected coding becomes irrelevant and you don't have to click several times (once for each currently visible coding) wondering why nothing is happening before it scrolls down. 

> Show all codings as a toggle 

not done yet I believe

> and change the forward back buttons to green to show this 'one code highlighting' is enacted currently.

nice touch

**Comment by ccbogel** [comment]
I have kept the buttons as it. The forward back buttons take on the colour of the currently selected code - as a visual aid. 
I have moved aay from the toggle idea because of the above.
The currently visible coded section is now highlighted with over and underlines.

**Comment by glocalglocal** [comment]
> I have moved away from the toggle idea because of the above.

It's just that it's not obvious that you have to click on an arrow to reveal the codings. 

Also, if I click on a colour1 code while colour2 codings are showing, the buttons remain in colour2 until I click on them. And colour2 won't be replaced by colour1 if I have reached the bottom of the text and click on Next. Perhaps Next causing a jump to the top if you are at the bottom would solve this. Same for Previous/top of course.

**Comment by glocalglocal** [comment]
If I have codings for code1 showing and select code2, codings for code1 remain as they are (correct) but at the same time codings for code2 appear dashed underlined.

**Comment by ccbogel** [comment]
If I click on a colour1 code while colour2 codings are showing, the buttons remain in colour2 until I click on them.
OK, I will work on this.

**Comment by ccbogel** [comment]
I think fixed now

**Comment by glocalglocal** [comment]
related issue: if I don't select a file and click on a 'show codings' arrow, nothing happens (of course). Should there be a message?
