### ISSUE TITLE
Importing refi-qda codebook from lin to win results in categories being added to codes

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#321]
**Describe the bug**
Importing refi-qda codebook from linux (lubtuntu 18.04) to windows (10) results in categories being treated as codes and added under the same category (screenshot: https://i.imgur.com/xUIhMv5.jpeg ). It is not a big thing but it shouldn't happen as one has to manually delete them.

**To Reproduce**
Export codebook made on Lubtuntu 18.04 and open it on windows 10 (QualCoder versions are latest available)

**Expected behavior**
Everything works fine

**Additional context**
Colors,codes and categories work well and me and my colleague were able to exchange the codebook without issues apart from this bug. Unfortunately in his terminal nothing shown up so we only have a screenshot.

**Comment by ccbogel** [comment]
I think this is because of the feedback and change i made to import regi-qda from MAXQDA.  I think codebook export from QC sets categories as codable, wgrn they should be set as non-codable.  Should be eady to fix.

**Comment by ccbogel** [comment]
Should be fixed now.

**Comment by WPFilmmaker** [comment]
@ccbogel Thanks! Once we update QualCoder I will report results ;)
