### ISSUE TITLE
Infinite popup errors when importing a refi-qda codebook (exported from windows 10 and imported on lubuntu)

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#322]
**Describe the bug**
My colleague on Windows 10 created a project and added categories and codes. She exported the codebook in refi-qda so that I could load it, but when I try I get a pop-up about the codes/categories already existing and an "OK" button. If you click "OK" or press enter it tells you about another code/category and it cycles indefinitely.

If my colleagues closes QualCoder and tries to import the codebook she gets the same result. 
I get the same issue.

note: this afternoon after clicking "ok" X times the codebook was imported correctly (as I mentioned in the ticked with the categories being merged into codes"), where X was the number of codes/categories in the codebook.

**Comment by ccbogel** [comment]
OK I have hidden that warning message. So many pop-ups will no occur,

**Comment by WPFilmmaker** [comment]
Thanks! I forgot to mention that the only way to fix this was to kill QualCoder from terminal.

**Comment by ccbogel** [comment]
Please check it works fine for you then I will close the issue.

**Comment by WPFilmmaker** [comment]
@ccbogel As soon as my colleague can update QualCoder he will test this. As for me I would rather wait for a next deb file as I am not very tech savvy to build from source.

**Comment by ccbogel** [comment]
I have created a new release, with a deb file. It will look a different as it uses icons in the buttons.

**Comment by ccbogel** [comment]
@WPFilmmaker I just realised something. You are exchanging codebooks. If you are both working on the same project,  it would be much much better to exchange the full project,  e.g. zip and email the project to each other.  That way both your codings will be contained within the same project. If you are not doing this, The problem will be, how will you merge your independent work on the project.

**Comment by WPFilmmaker** [comment]
@ccbogel Good suggestion Colin! This week I should be able to update QualCoder and do the testing for this issue and the others I reported.

**Comment by ccbogel** [comment]
closing as no response for a long time

**Comment by WPFilmmaker** [comment]
@ccbogel sorry been busy, will let you know if we have issues ;)
