### ISSUE TITLE
[question] how to update on windows 10?

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#323]
I know it is a silly question but how do you update QualCoder on Windows 10?
With linux I am used to wait for your deb files, but on windows?
From the manual I read 

"Download the latest QualCoder from GitHub: https://github.com/ccbogel/QualCoder. Unzip the
folder. The main program code is in the QualCoder folder." but I suppose this refers to linux right?

What About Windows? Is there a stable release for it as well or my colleague can just get the most recent 'bleeding-edge' version from github?

Thank you a lot Colin for your patience and help!

**Comment by ccbogel** [comment]
The main program code is in the QualCoder folder." but I suppose this refers to linux right? - No, this is on all operating systems.
So the zip folder in the releases is used on WIndows (or Linux or Mac). 
https://github.com/ccbogel/QualCoder/releases
On Windows unzip, then double-click on the qualcoder.py file. You can make a shortcut to it for easy use. The qualcoder .py file is located here: QualCoder-2.1/qualcoder/qualcoder.py

The 'bleeding edge' is here:  
https://github.com/ccbogel/QualCoder

**Comment by WPFilmmaker** [comment]
@ccbogel Thanks Colin I will let my colleague know, if there will be issues I will report them here
