### ISSUE TITLE
Bug: Error with 'Move file to externally linked file'

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#324]
In Files, I right-clicked one of the coded .md files and selected 'Move file to externally linked file'. I selected a folder and got this error. 

![error](https://user-images.githubusercontent.com/16408198/100627491-fb1dc600-331e-11eb-8ccd-63b5081947d0.jpg)

I am slightly confused (again) over how to replace an embedded coded file with a linked file safely. The original .md file I imported earlier exists in a folder. I imported it and coded. Now I am trying to dis-embed the file and replace it with a link to the original .md file still in the original folder. My concern is that if I remove the embedded file temporarily from Qualcoder, qualcoder may forget the codings before I create the replacement link. I am guessing that 'Move file...' (when it works) is meant to create a new copy of the original file in the original or other folder, replacing the original file. I think this qualcoder's safe way to switch from imported to linked file without messing up the codings database. Is this correct?

**Comment by ccbogel** [comment]
Thanks - I forgot to test export of text files. Fixed now.
Because it is a text file, the full imported text will be stored and coded against within the sqlite database.
The export as a linked file: this only affects the location of the original file from which the text was drawn. For text files it is not really that important as the text is imported into the database, but for other media, it is vital to have a link to the original file.

**Comment by glocalglocal** [comment]
The error disappeared and linking worked as expected. Codings remained intact of course.

**Comment by glocalglocal** [comment]
> For text files it is not really that important as the text is imported into the database, but for other media, it is vital to have a link to the original file.

This reminds me, how do we remove a text and associated codings from data.qda? Eg I may want to replace it, delete it to save space, or wipe it for privacy purposes when sharing the project data. Also, we should be able to remove all codings from a text (eg by selecting all text and clicking on Unmark -- currently unavailable, or by clicking on an 'Unmark file' from the right-click menu on the files list).

**Comment by ccbogel** [comment]
Deleting a text is easy. Delete the file.
You can remove all codings from a text using the sql dialog.  But i wouldn't add it as a regular function as its a risky thing to do.

**Comment by glocalglocal** [comment]
Sorry to dwell on this. When I delete a text file from Manage Files, do its content and metadata disappear completely from all qualcoder's data files without leaving a trace, not even codings? This is very important for confidentiality when researchers are increasingly expected to put their data online. BTW, this last part could be stated as a selling point for qualocder as the transparent solution.  

Having to use the sql dialogue to do anything is probably beyond what most users can do. An 'Enable Advanced Settings' option in Settings, with suitable warnings may be better for this and some other options.
