### ISSUE TITLE
Bug: linked MP3s don't open (only imported MP3s do)

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#325]
Linked .mp3 files don't open, although the .mp3.transcribed file is automatically created when I link one. The .mp3 files open only after I import them.

**Comment by ccbogel** [comment]
That is odd. I have tried this (on Ubuntu so far) and there is no issue with playing a linked mp3 file. Is there something in the log file that might give an idea?  And secondly, is the mp3 file on your drive somewhere - not on removable media.

**Comment by glocalglocal** [comment]
I tried again with the latest version I just downloaded. Linked MP3 files don't open. The log file shows nothing new but the tooltip says: 
```
Cannot locate media. C. 
Externally linked file: 
audio:C:/<correct path>
```
I suspect that 'C' relates to the 'C' in the title bar in #327. 

Shouldn't there be a space after 'audio:', 'docs:' etc?

**Comment by ccbogel** [comment]
fixed this issue

**Comment by glocalglocal** [comment]
Fixed but this is still there: 
```
Cannot locate media. C. 
Externally linked file: 
audio:C:/<correct path>
```
