### ISSUE TITLE
Bug: Manage Files grid spacing

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#326]
In Manage Files, I set the window width to its narrowest while keeping the buttons visible. There is quite some space after the third column that is not utilised, and the name is wrapped unnecessarily. The name column could be stretched to make the most of the wasted space.

**Comment by ccbogel** [comment]
I can try and resolve, a bit tricky. Previously you posted an issue regards long filenames, so I restricted the maximum name width to 450px.

**Comment by glocalglocal** [comment]
I would expect to see just enough space for Memo, Date, other attribute, and all the rest of the available width given to Name (with wordwrap when necessary). I would also expect buttons to take as little space as possible, or even be replaced by icons. Generally, screen space is too valuable to be wasted. 

Another example is Settings where about 1/3 of the window is blank. 

Or in Code Text, the size of the file list pane is fixed (and reset every time I open the window), so space can be wasted at the expense of the codes pane below. Chances are the user will want to prioritise codes over files for long periods of time. Ideally, the size of these panes would be remembered and the user should be able to minimize, massively reduce and/or close/open selected panes.

**Comment by ccbogel** [comment]
sure - updated the code text splitter, setting dialog size. and as mentioned, above, hopefully the file name width is better - in Manage files.

**Comment by glocalglocal** [comment]
I don't see anything different in Manage Files or Settings The files list pane in Code Text is now remembered when I reopen the dialogue.  

(I think we discussed this before, but just in case. I open Code Text, close it. It takes two clicks on the menu to reopen Code Text.)

**Comment by ccbogel** [comment]
Settings is re-sized - smaller.
Yes clicking twice to open the same dialog that was just closed - is how it is - I am not able to fix that.
I changed code so that the filename would extend further - perhaps more to do?

**Comment by glocalglocal** [comment]
Certainly not a functionality issue but just in case these look different on Windows, I find odd that this space is just blank. Eg I would expect the grid to self-adjust to fill up all space available. But as I said, not a functionality issue unless the extra space interferes with how many things fit on a small screen. 

![manage](https://user-images.githubusercontent.com/16408198/100930496-159f9d00-34e1-11eb-8a3d-2c0dbb6e4fb6.jpg)
![settings](https://user-images.githubusercontent.com/16408198/100930499-16383380-34e1-11eb-9b66-454d35b26710.jpg)

**Comment by ccbogel** [comment]
re the table - it wont self adjust to fill the space. it is sized by contents.
