### ISSUE TITLE
Bug: Title bar for mp3 file in Manage Files 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#327]
In Manage Files, I open an imported .mp3 file. The window opens OK but displays 'C' as the only text in the title bar. 

I think the following are probably non-issues, so I didn't create separate issues for them.  
I think this was not possible to change but just in case, before I Play the file I can't move the slider to a position other than the start. 

Does the Audio drop-down menu in this dialogue refer to multiple tracks?

**Comment by ccbogel** [comment]
I think this was not possible to change but just in case, before I Play the file I can't move the slider to a position other than the start. - Correct
Does the Audio drop-down menu in this dialogue refer to multiple tracks?  Correct  and it can only detect multiple (or single) tracks once a media file has started to play.

**Comment by glocalglocal** [comment]
> What I could potentially do is to begin to play the media automatically for a couple of milisecs. Then I can get the what is needed for you to be able to then slide the slider.

My thought exactly :)

**Comment by ccbogel** [comment]
fixed the opening issue

**Comment by glocalglocal** [comment]
The titlebar is fixed and the MP3 opens OK but the tooltip for the MP3 file in Manage Files still says:  `Cannot locate media. C`
