### ISSUE TITLE
Req: misaligned date/time in Manage Files grid

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#329]
In Manage Files, see misalignment: 

![dates](https://user-images.githubusercontent.com/16408198/100676630-304b0800-3361-11eb-8a89-77b8819d2e0c.jpg)

The only unusual think about the file associate with that '5:41:08' is that it's the only one coded in RQDA and imported.

**Comment by ccbogel** [comment]
What does the original date string look like - directly from RQDA ?

**Comment by glocalglocal** [comment]
aha. I opened the .rqda file as text to have a quick look. There is this string there 'Tue Oct 29 15:41:08 2019'. So, it's not a '0' that is missing.

**Comment by ccbogel** [comment]
This should be better: but as I no longer have a good rqda file can you check one thing for me?
If the date was small e.g. Tues Oct 2 is it stored as:
Tues Oct 2 
OR
Tues Oct 02
?

**Comment by glocalglocal** [comment]
That '5:41:08' looks the same. No change here. 

I checked my sample rqda files and, amazingly, I can't find a date at the start of the month. I don't have a working RQDA any more, so can't create a test file. An RQDA may be able to help.

**Comment by ccbogel** [comment]
Ok, back to the drawing board, I will split the rqda date in a different way.

**Comment by ccbogel** [comment]
I have imported another persons RQDA project which had times before 12. The leading zero is added. Will close this now.
