### ISSUE TITLE
Req: '...' on buttons to indicate more steps

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#330]
In Manage Files, should that 'Delete files' be 'Delete files...' to indicate that there is another step following the click? Instinctively, every time I have to click on the button, I fear that something will be  immediately deleted, as would happen in most interfaces. In fact, for consistency with standards, most buttons in qualcoder should have the '...'.

**Comment by ccbogel** [comment]
I have added a tooltip to state 'select files to delete'

**Comment by glocalglocal** [comment]
I don't see the tooltip. 
Should it be 'select files and delete' or some other wording? 'select files and delete' may be read as select files first and then click the button to delete -- which is very common.

**Comment by ccbogel** [comment]
changed to 'select files for deletion'

**Comment by glocalglocal** [comment]
OK, I see the tooltip and I see the button moved closer to the others and I can make the window narrower. 

But Export shows a blank tooltip.

**Comment by ccbogel** [comment]
done
