### ISSUE TITLE
Req: AV slider movement and audio tracks

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#331]
**Req**
Before I play the A/V file I cannot move the slider to a position other than the start.

Audio drop-down menu. Only needed for multiple tracks.

**Describe the solution you'd like**
make slider movable even before playing media. 
and hide audio tracks option if only one audio track is available for the media.

**Comment by ccbogel** [comment]
fixed

**Comment by glocalglocal** [comment]
Almost. (a) The quick play/stop produces a noise (b) when I move the slider, it starts playing rather than stay paused (c) and Play doesn't change to Pause when (b) happens -- if I click on Play, it pauses and the button still reads Play (correctly this time).

**Comment by ccbogel** [comment]
ok its virtually all fixed.
You can move the slider when playing or when paused.
In Manage_files > View  Moving the slider the first time, when loaded and it is paused - it resets to the start. Cant resolve this yet. Otherwise it works fine. And the play/pause button appears correctly

**Comment by glocalglocal** [comment]
(a) above is still there. It sounds like wooosh.

**Comment by ccbogel** [comment]
Yes. It would very brief though. I can shrink it from 200 to 100msecs.

**Comment by glocalglocal** [comment]
Why not 50 or 10msecs? How about turning volume down and up discreetly?

**Comment by ccbogel** [comment]
Yes, i will do the volume
