### ISSUE TITLE
More colors for codes

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#332]
**Is your feature request related to a problem? Please describe.**
Right now me and my colleague are trying to use QualCoder to code data, we have 14 categories and something like 70 codes. With such volume of codes we almost run out of shades of colors, and some shades are quite similar. I was wondering if it would be possible adding more colors.

**Describe the solution you'd like**
I thought about a colorwheel to being able to select colors. But I also like the current approach with several colors and their shades. so maybe keep this approach and add a wheel to pick more colors?

QualCoder 2.1 Lubuntu 18.04/Windows 10.

**Comment by ccbogel** [comment]
How about extending the current approach, easier for me. Here are some colour charts:
https://htmlcolorcodes.com/color-chart/
https://html-color-codes.info/
https://www.rapidtables.com/web/color/html-color-codes.html

If you could pick TEN colours at a time and I can add to the rows in the colour picker.
They need to be in hex format, e.g.: black is  #000000
They also need to be light enough that the black text can be clearly visible.

**Comment by WPFilmmaker** [comment]
@ccbogel that sounds like a good approach!
The first one seems a standard for many programs, is it something you could add easily?
I think the final results with 10 colors would look similar to the third link right?An extension of the existing one (which I think is very functional), thank you!

**Comment by ccbogel** [comment]
Select 10 from there and post it here.

**Comment by WPFilmmaker** [comment]
#0d47a1
#311b92
#4a148c
#880e4f
#b71c1c
#bf360c 
#e65100
#ff6f00 
#33691e
#1b5e20

**Comment by ccbogel** [comment]
@WPFilmmaker thanks for this. I have uploaded the changes. Lots of good colours there.
The only thing for me on my screen is the 2 purple colours are quite dark and for me, hard to see the black text.

**Comment by WPFilmmaker** [comment]
@ccbogel you mean  #4a148c ?
would grey  #626567  be a good replacement? (a lighter one is available but basically half of the shades are white..)

**Comment by ccbogel** [comment]
I have updated these now.
