### ISSUE TITLE
Add total number of codes

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#333]
**Is your feature request related to a problem? Please describe.**
When you work with others and you have many codes/categories, ideally you would just share them, however this is not always possible, and two coders might have to make their own codebooks from scratch. It would be helpful showing the number of total categories and codes in your codebook, so that it would be easy to compare your codebook with someone else's.

I don't see this feature at the moment, if there is a way you can close this ticket, otherwise I would appreciate such feature.

(there is an 'id' feature but at the least on my system it doesn't seem to make sense because I can't order ids from 1to100 or vice versa, otherwise this could be used instead of my feature request).

**Comment by ccbogel** [comment]
@WPFilmmaker The ids are identifiers used behind the scenes in the database. These can be useful to view, if you are doing any SQL queries.
The easiest way is to open the project and view the project summary that is shown:
![pic1](https://user-images.githubusercontent.com/5834638/100942305-39013100-354f-11eb-88f4-626606426416.png)
