### ISSUE TITLE
Bug: Greek translation 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#335]
I am guessing the translation was done with Google Translate or similar. There are far too many mistakes, some quite amusing. I would help with that, but I didn't volunteer because although I am native in Greek, I am not sure about many technical and standardised UI terms. That's because I never worked with a UI in Greek. When I find a bit more time, I will try to look at similar applications and literature -- not as easy as it sounds, because I am not aware of a big CAQDAS application supporting Greek (another possible first for Qualcoder).

**Comment by ccbogel** [comment]
Yes sure. I am not surprised. I added Greek using Google Translate, because on wordpress there was a lot of interest from Greece recently: https://qdas.uom.gr/
Someone might edit the gr.po and app_gr.ts files

**Comment by glocalglocal** [comment]
That link helps. The author published a paper on RQDA in Greek, and that solves some standardisation issues. To my surprise, screenshots show RQDA is half-localised. Not great. Is it acceptable to leave some of the terms in English for later?

**Comment by ccbogel** [comment]
Is it acceptable to leave some of the terms in English for later? Sure.
Are you able to edit the .po and the .ts files?
You can edit the xml directly on github. But it is better and safer to use poedit to edit the .po file and QtLinguist to edit the .ts file.

**Comment by glocalglocal** [comment]
I will look into how to edit these files when I get a bit more time. Never done it before but it should be fine.

**Comment by ccbogel** [comment]
I will have to update them. As every change - even one line of English in a message in the code or in the ui files, will be missed. I am also investigating how to enact the icons. So perhaps wait a little first. (i.e. a few weeks).
ps if you know anyone interested in editing the Spanish or Japanese - that would be great :)
pps I am guessing its very late where you are, Im about to have a work meeting soon.

**Comment by ccbogel** [comment]
This is how it looks to use poedit:
![pic1](https://user-images.githubusercontent.com/5834638/100961271-29491300-3576-11eb-8da4-a3fb3d4c944d.png)

**Comment by ccbogel** [comment]
This is how it looks in QtLinguist:
I am not sure how you install Qt Creator on Windows but this is their site:
https://www.qt.io/developers

![pic1](https://user-images.githubusercontent.com/5834638/100961499-a2486a80-3576-11eb-9849-32c0327ce10e.png)

**Comment by glocalglocal** [comment]
OK, I'll wait. DO we have to edit both the .po and the .ts file? Excuse my ignorance, but what is the difference?

**Comment by ccbogel** [comment]
Yes both need editing. The ts file is for the Qt widgets: dialogs, buttons, 
Labels etc these are the python files in the GUI folder.
The po file is for text generated in all the other python code.

**Comment by ccbogel** [comment]
@glocalglocal I thought I would mention that the el.po and app_el.ts files have been updated and can be reviewed now.

**Comment by ccbogel** [comment]
@glocalglocal perhaps do nothing for now, I have had interest from Prof. Koutsoupias of the University of Macedonia, Greece and his staff and students to translate the files.

**Comment by glocalglocal** [comment]
That would be good. I am currently snowed under work.
