### ISSUE TITLE
Uncaught exception on windows 10

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#336]
**Describe the bug**
When launching QualCoder (github-master) on windows 10 an uncaught exception happens. My colleague said it also happened with "stable" version, which he installed following the guide on the main page of github, since yesterday.

**To Reproduce**
Just open QualCoder 

**Expected behavior**
That it opens correctly

**Screenshots**

https://i.imgur.com/zzaVb9g.jpg
and terminal: https://imgur.com/a/gd864jM

**Desktop (please complete the following information):**
 Windows 10, Python 3.7 64bit, QualCoder from github master

**Comment by ccbogel** [comment]
Thanks this issue occurred after fixing an earlier codenames issue. Particularly if no project was open.
It now opens correctly.

**Comment by WPFilmmaker** [comment]
@ccbogel Thanks! This means it is fixed and I can close this right?

**Comment by ccbogel** [comment]
yes. I left it open - in case you wanted to double check and confirm.

**Comment by WPFilmmaker** [comment]
@ccbogel Thanks! Tomorrow my colleague will try and I will close or comment if necessary ;)

**Comment by WPFilmmaker** [comment]
@ccbogel Colin my colleague reports he is having the same issue despite downloading again QualCoder from github.

Message: 'Uncaught exception : Traceback (most recent call last):\n  File "C:\\Program Files\\QualCoder-master\\qualcoder\\qualcoder.py", line 1679, in <module>\n    gui()\n\n  File "C:\\Program Files\\QualCoder-master\\qualcoder\\qualcoder.py", line 1674, in gui\n    ex.open_project(path=proj_path)\n\n  File "C:\\Program Files\\QualCoder-master\\qualcoder\\qualcoder.py", line 1393, in open_project\n    cur.execute("ALTER TABLE code_text ADD avid integer;")\n\nOperationalError: no such table: code_text'

OperationalError: no such table: code_text

Is there more info we can provide you?

**Comment by ccbogel** [comment]
I want to clarify - this occurs when qualcoder is first opened AND there is no project that it is trying to open or the project it is trying to open is not present?
I have added some additional exception catching in the code to get around this issue.

**Comment by WPFilmmaker** [comment]
@ccbogel my colleague deteled all previous folders related to QualCoder to be sure the installation was clean. He is trying to open QualCoader to open our project (which I sent him), but QualCoder throws such exception. As far as I know no project has been loaded before. I will edit if I know more details.

**Comment by ccbogel** [comment]
OK, that's good to know. It means QualCoder is trying to open a project that is not there - which is what I thought. I presume the program still works even though this exception occurs.
The changes I have uploaded should hide this exception now.

**Comment by WPFilmmaker** [comment]
@ccbogel I will ask my colleague to try again tomorrow and let you know :) Thanks for the assistance!

**Comment by WPFilmmaker** [comment]
@ccbogel Colleague said it is working fine!
