### ISSUE TITLE
txt files require '.txt' to be present in the name

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#338]
I thought saving a file as .txt would be enough to load it in qualcoder, however it turns out the file has to contain .txt in the name or qualcoder will show "Unknown file type for import:". I have several txt files without .txt in the name :( 

I think it would make sense that for QualCoder it wouldn't matter whether the file name has or not .txt because the file is always a txt...I haven't tried with other file formats, does it happen the same?

Would it be difficult to make QualCoder load such file even without .txt in the name?

I am using QualCoder from master on Lubuntu 18.04

**Comment by ccbogel** [comment]
I did this for Windows users in particular. Would it be easy enough for you to add .txt to the end of the file name?

**Comment by WPFilmmaker** [comment]
@ccbogel I added manually, not an issue :)
But when I saw they wouldn't load I worried it might be a bug...then I thought it could be because of that..
so I would put somewhere that file names must contain the format (maybe in the manual or in the software the first time an user tries to import files
Does this apply to all formats?-

**Comment by ccbogel** [comment]
Yes it applies to all formats. It is in the manual, but not clear enough. Will fix.

**Comment by ccbogel** [comment]
Im going to get qualcoder to try animport as text, files that it does not recognise
