### ISSUE TITLE
Question about alphabetic order of file

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#339]
After loading my files I wanted to reorder them according to the alphabetical order. I tried by date and it worked, however by alphabetical order it does not (or maybe I got it wrong): https://imgur.com/a/akQGVOA

As you can see the order of numbers is like: 
1
2
3
4
5

So we have 1, but then we have 10, 11, 12, (because they start with 1), and only then 3,4 etc.

I would have expected: 1,2,3,4,5,6,7,8,9,10,11,12

Am I mistaken and  alphabetic order QualCoder is using wrong, or vice versa?

Info:
Qualcoder from master, Lubuntu 18.04, all files are .txt files.

**Comment by ccbogel** [comment]
That is the correct ordering for numbers when they are ordered alphabetically. The only way to overcome this is to add leading zeros. and you would need to add another leading zero of you are going into hundreds of files.
e.g. 01.txt,  not 1.txt
or 001.txt ... 345.txt
