### ISSUE TITLE
Bug: cross-linked codings between texts in 'Show coded text'

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#340]
'Show coded text and media' for any code X in any file Y shows also codings for code X from another specific text file Z. The codings from the wrong file Z are always appended to the codings list for file Y. 

The only special thing about file Z is that it's the only one imported directly from RQDA -- ie there is no separate file in the data directory for this. 

When looking at the coding box for file Y there is no sign of the extraneous codings. They only appear in 'Show coded text and media'. 

This applies to Master and Develop.

**Comment by ccbogel** [comment]
This is a deliberate function. Someone in the past wanted to see all the codings for a particular code across all file. SO enacted this using the right click menu on a code.
I could rename 'show coded text and media' to 'show coded text and media across all files'

**Comment by glocalglocal** [comment]
Or more simply, show only for this file/coder, and when the dialogue opens there can be a tickbox for 'show for all'.

**Comment by glocalglocal** [comment]
Incidentally, sometimes the 'show codings' dialogue shows a blank line between codings, sometimes not. I suppose it's because of how the user coded the text, but that extra line serves no purpose in the dialogue and could be removed.

**Comment by ccbogel** [comment]
I have changed it to: for THIS coder only

**Comment by glocalglocal** [comment]
> sometimes the 'show codings' dialogue shows a blank line...

This is still the case.
