### ISSUE TITLE
Bug: arrow buttons looking wrong

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#343]
qualcoder 2.2
On Raspberry Pi OS (left) the arrows look different from Windows (right), like they are aligned right and something is missing. Only these three buttons look different. 

![debian_left](https://user-images.githubusercontent.com/16408198/101803490-7e51cf80-3b08-11eb-99e6-f4f09318b5d3.jpg)

**Comment by ccbogel** [comment]
Yes I see. I think this is going to remain as a bug for Raspberians. The Qt widgets are being rendered slightly differently in Pi compared to Ubuntu and Windows. It will take a lot of coding to fix a slight issue for specifics Oses, so you will have to live with it.
Its not that they are aligned right, its that the buttons need to be even bigger to render the full icon as a background image on Pi. I have made those buttons 28x28px and the icon inside is 24x24. This looks good everywhere else. I cant make the buttons bigger everywhere or the 24x24 image will start to tile inside the button - which then will make it look bad elsewhere.

**Comment by glocalglocal** [comment]
Not a problem of course but I should add that Raspberry Pi OS is essentially Debian LXQt. I suspect this may be a lot more widespread than it sounds.

**Comment by ccbogel** [comment]
I have made those buttons 1 px bigger width and height - in the code text dialog only. Let me know if it improves the images slightly. If I make it 2 px bigger then tiling starts.

**Comment by glocalglocal** [comment]
I installed yesterday's 2.2 and it looks the same but I think I know why it looks different. The icons look wrong until I hover over the button. When I do, the icon is raised and more centred. Now I notice the same happens with the other buttons (and the icons appear misaligned and chopped), except the Search-related buttons. The raised button effect doesn't work in Windows and the icons appear centred.

**Comment by ccbogel** [comment]
In the Develop branch I have tried a different way of putting pictures into the buttons and labels. They look a bit smaller, and so should overcome this issue.

**Comment by glocalglocal** [comment]
I can tell already these look so much better in Windows. Is it my impression, or are the search button still big? That 'T' is really big.

**Comment by ccbogel** [comment]
The search button?
The t is big  im not going to change the image immediately . If you can find a small b&w icon that has something like a T and t or similar to denote case sensitivity,  let me know.

**Comment by glocalglocal** [comment]
I thought if you did with T and other buttons around there what you did with the arrow buttons they would look smaller. I didn't realise you needed different images.

**Comment by ccbogel** [comment]
they are presented differently. the T is inside a label as a pixmap, the arrows are icons made from pixmaps, and set within buttons.

**Comment by ccbogel** [comment]
Are the buttons looking better on Pi? o I can close this issue

**Comment by glocalglocal** [comment]
Here is what I see. RPi on the left, Windows on the right:
![arrows](https://user-images.githubusercontent.com/16408198/102149077-9194d000-3e65-11eb-89a4-aab13d3e72bc.jpg)

The buttons on the RPi are now static and centred, so the problem is solved, but they look bigger than in Windows, therefore they don't look as nice.

**Comment by ccbogel** [comment]
OK thanks for letting me know that it is solved. I cant further refine to make adjustments for quirks of Qt implementation on different systems - thats an endless rabbit hole.
