### ISSUE TITLE
Bug: Toolbars in Code Text remain visible when the panes are made invisible 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#344]
In Code Text I can shrink the files list to the point it disappears but the Next File etc toolbar remain visible. Similarly, I can reduce the codes list to nothing but the Previous Coding etc toolbar remains visible.

**Comment by ccbogel** [comment]
That's normal behaviour. You can shrink the button bars to nothing also by dragging with the mouse on the point where the widgets meet.

**Comment by glocalglocal** [comment]
In my view, a button bar should automatically disappear when the pane collapses. Ideally, there would also be the usual 'handle' informing the user there is actually a collapsed pane there. 

> I can set the splitter behaviour so that nothing is fully collapsible.

IMV, this is not great because I tend to get things out of the way but it solves the issue of a user looking for a missing pane.

**Comment by ccbogel** [comment]
I tried to change the GUI to match your recommendation, but ended up wrecking it. So will have to put this in the too hard basket for the time being.

**Comment by glocalglocal** [comment]
I downloaded the latest Master and now only one file in listed in Code Text. I tried different projects and it's always one file listed. And it won't open either. Could the above have broken something?

**Comment by ccbogel** [comment]
Yes the above did break things. Now fixed to show all files, by reverting to previous code. So I wont be continuing down this path.
