### ISSUE TITLE
[Question] How do I add shades of a color?

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#345]
I installed version 2.2 and improvements look good! I saw you also added new colors, however I am unable to find a way to add shades, I only see new colors (1 tone) so the colors choice remains limited. How do I find them? Is there any way you can add the shades of new colors as you do for the previous one? Thanks.

**Comment by ccbogel** [comment]
The best way is to give me the list and  I can add them to the color selector. However I dont want to add many more colours, there is quite enough to select from.
Another way means to add colours is using the SQL statements in the Reports menu using the following command:
update code_name set color = "#123456" where name ="mycode"
mycode can be replaced with the name of your code, 123456 can be replaced with the hex value of a colour you like.

**Comment by glocalglocal** [comment]
Out of interest, can people actually tell the difference between more than 4 shades of a colour when they see it in the text? That's shades that are light enough to work with black fonts. I wish I could.

**Comment by ccbogel** [comment]
I feel there's many colours already available within qualcoder. Adding more dilutes the differences too much. I think some quality software only has 8 colour options.

**Comment by WPFilmmaker** [comment]
@ccbogel actually you are right..checking better only the first 4 shades of a color (including the stronger one) are distinguishable...

@ccbogel Sorry for my poor description of how I imagined the new colors. I am attaching a badly made sketch to visualize my idea: https://imgur.com/a/3EcvzuY

The new colors would have shades like the rest. Could a compromise be removing the whitest shade (which is indistinguishable from the next one on the right) but add shades to the new added colors?

Right now we have 12 colors + shades. If you really think 12 is too much maybe (check the photo) the grey below the dark green and the lilly purple newly added (since it is quite similar to the pastel lily already included) could be removed. So we would have 10 colors in total + 3 shades of each color.

I can check the hex code for them if needed.

**Comment by ccbogel** [comment]
ok i understand now, if you can add the hex values for the shades ad the main strong colour. in order. that would be brilliant.

**Comment by WPFilmmaker** [comment]
Super! will do that but will take a while as this week I am pretty busy.

**Comment by ccbogel** [comment]
OK I had time, I did what you asked and added colours and shades. Will close this now.
