### ISSUE TITLE
[Question] How to import QualCoder codebook

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#346]
Me and my colleague (me on Lubuntu 18.04 and him on Windows 10) have been attempted several times to share codebooks and projects, this results in a few bugs that were fixed with the new version. 

We are now trying again to share a codebook (I made it and exported it and he is trying to open), however we have one question, how do we open qualcoder's codebook?

I checked the manual however it only mentions refi-qda exports, what about the plain qualcoder codebook text file? How do you load that in an open project? Since we have two options we would like to try both formats to see which one works better for us.

Thank you.

Edit: I realized the question might sound silly..should we just import the codebook txt file as a normal txt file and use the codes from there? If yes I suppose that txt file cannot be deleted from the files list.

**Comment by ccbogel** [comment]
Hi. You can only import the codebook using refi-qda. 
The codebook txt file is only for viewing, not for importing.
