### ISSUE TITLE
Empty buttons on Windows 10

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#347]
My colleague was trying to import my codebook and after updating he noticed that new buttons are empty:

 https://postimg.cc/XpGq3Dhj  and https://postimg.cc/S21QbWfY

Terminal: I don't know if terminal mentioned something atm, when I know I will add anything meaninful here.

Qualcoder 2.2, Windows 10

**Comment by ccbogel** [comment]
Hmm, thats a problem.  Mine and another's Windows 10 have no issues with this. I have a technical suggestion, but best to email you directly to try it.

**Comment by WPFilmmaker** [comment]
@ccbogel I emailed you at the hotmail email on your profile here on github ;)

**Comment by ccbogel** [comment]
OK. I sent you a test file for manage_files.py to see if the icons will now show. The thing was I commented out lines 85 and 86.  I will also have to look at a different way of showing icons on buttons.

**Comment by WPFilmmaker** [comment]
@ccbogel Thanks for the suggestions, we have a few deadline this week, so no time to work on QualCoder and to try your  suggestion. But if in the meanwhile you change something in the way buttons are displayed could you let me know? I will ask my colleague to try using the dev version and report if this work.

**Comment by ccbogel** [comment]
it is changed now, ready to try.

**Comment by WPFilmmaker** [comment]
thanks! will let you know when he tried ;)

**Comment by ccbogel** [comment]
@WPFilmmaker I merged it into the Master branch.

**Comment by WPFilmmaker** [comment]
@ccbogel closing this as my colleague said it is solved.
