### ISSUE TITLE
Improvements to the 'why use QualCoder' section

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#349]
Right now the 'why use QualCoder' section is quite rushed I feel, which is a pity because there are a lot of reasons to use QualCoder (imho).

I propose replacing the current paragraph with: 

Qualcoder is free of charge: unlike other qualitative analysis software require expensive one-time fees or monthly subscriptions. Not everyone can afford expensive fees, especially in developing countries.

You can modify and adapt QualCoder to your needs, or if you do not how you ask someone to do it for you, as long as you release your changes to everyone. This also means you can copy it and give it to your colleagues or students free of charge.

QualCoder is easy to use: it has all you need to perform qualitative analysis without the complicated interfaces of closed-sources alternatives.

QualCoder is not tied to a computer: If you change workplace you don’t have to worry about being tied to your former workplace’s license or to buy a new license. QualCoder license allows you to use it regardless of where you work or on what computer it is installed on.

QualCoder is multiplatform, it runs on Linux, Windows and Mac, this means that you do not have to worry if you have a Linux laptop, and it also means you can collaborate with colleagues on different platforms.

QualCoder works offline: Internet is not always available and QualCoder does not require internet to work.

QualCoder relies on the community: if you find a bug or have a feature request or a feedback write it on QualCoder’s page on github (https://github.com/ccbogel/QualCoder).

QualCoder is always improving: QualCoder is actively developed meaning that newer versions are released often with improvements. 

QualCoder supports open standards: unlike closed-sources software, QualCoder supports REFI-QDA open standard. You can exchange files with your colleagues even if they do not use QualCoder, as long as the software they use supports REFI-QDA. It also means that you do not risk your data being unavailable in a few years because a company decides so, in order you to buy their new version.

**Comment by ccbogel** [comment]
Thank you, I will update this in the manual. With some slight wording changes - especially with REFI-QDA as I feel this is still experimental.
