### ISSUE TITLE
Add a spreadsheet export ?

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#35]
Hello,

An idea, is to export in a spreadsheet (csv, xls, ods... what you want) contents. In Y files and X codes.

Regards

**Comment by ccbogel** [comment]
OK thanks for the idea. So do you mean from after a report is run - have the columns of codes and the coded text in rows?

**Comment by qwertygc** [comment]
Yes, exactly. It's a good format for sharing results in a working document.

**Comment by ccbogel** [comment]
I have added a csv export option with the header row containing the codes and the coded data underneath in relevant columns.
