### ISSUE TITLE
Improve the moving of codes

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#352]
Right now if you have several codes/categories you get a menu to scroll down. However If I want to move a code to another category right now I need to close with the drop down menu all the categories so that the category I want to move the code to, appears and then reopen them all afterwards.

A better solution would be:

1 being able to grab the code with the mouse and pull it down to the desired category (so the scroll menu would scroll while you drag the code)

OR

2 have a right click function 'send code to category X"

I have no preference so if you decide to implement this you can go for the easier for you.

**Comment by ccbogel** [comment]
I will add a right-click function to do this.

**Comment by ccbogel** [comment]
I have enacted this now - using right-click on the code. Then choose 'move code to'
