### ISSUE TITLE
Req: new tab interface

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#356]
With the new tabbed interface, in Coding Reports two of the three panes on the left should not be hidden first time we open the tab, or there should be a clear indication they are hidden. Many users won't know they are even there. 

It would be good to have a description for each of these panes. Ideally, that wouldn't take up vertical space somehow. 

There is no indication (in the titlebar or elsewhere) of which report you are looking at. 

I return from that tab to Coding, and the text file that was showing previously was closed. This doesn't happen every time and can't reproduce it. The state (inc scroll position) shouldn't be reset.   

Opening a file in Manage opens a window. The file is not displayed in a tab. Same for View Graph. 

Opening/closing settings switches to the Action Log tab.

**Comment by ccbogel** [comment]
OK I have tried to improve the hidden panes situation. The report has wording in it, but not on the title bar - have added extra wording in some reports for this, 
Return to tab coding issue - unsure how to replicate or deal with that.
yes opening a file in manage files is in a separate window, I prefer this. View graph, yes, for now, will not change this.
settings - yes - draws attention to the changes made.
