### ISSUE TITLE
Bug: Show codings buttons

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#357]
In Code Text, I select a code, click on the right arrow several times until I reach the last coding. I click on Show all Codings and the arrow buttons correctly become B&W etc. If I click on the right arrow, the buttons don't become colourful again and the function is not activated (presumably because I had reached the last coding earlier). I would expect something to happen (eg at least the function to be switched on again). I am guessing none of the b&w arrows would do anything if there was only one coding, because I would have reached the first and last coding. 

As above, if I click on the Show all Codings button nothing happens. I would expect this to work as a toggle. 

More generally, could the arrows be coloured only if there is a coding to move to up or down? So, if the cursor is at the top-most coding, only the right arrow would be coloured. And when you reach the bottom, only the left arrow would 'light up'. 

I find it confusing that the codes menu reads 'Show coded text and media' -- meaning codings across all texts and media. I keep reading this as showing codings in the current file. Would something like 'Show codings across files' be clearer? 

BTW, I am guessing that if the colour for a code is the same as the grey background in the buttons, then when the buttons 'light up', they won't change.

**Comment by ccbogel** [comment]
OK I have improved this to cycle around when reaching the last coding. this also assists when toggling off and on.
Coded text and media is now Coded files. 
Yes gray on gray would be too hard to interpret , but just a limitation
