### ISSUE TITLE
Case Matrix - using codes within categories

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#359]
1. When you are selecting codes to be displayed in the cases matrix, you can only select codes which are not in the category. If the codes are in the category, you can only click on category and select ALL the codes in the category, not only selected. Otherwise, text from selected codes is not displayed. So, you have to remove single code from category if you want use only this one.

It will be good if you will able to select also single codes from category, and insert them into matrix.

2. And one more thing. When the matrix displaying specific codings, it would be nice when there in the text, after colored part, will be information about "File:" of codings, not only "Case:".

**Comment by ccbogel** [comment]
OK done this: can choose top categories, or any selected codes.
Also added filename to output.

**Comment by AndrzejWawa** [comment]
Hi, I tested.

1. Files names: ok
2. Creating matrix - only possible with the highest category. When you select lower category (category in category) or specific code/codes, matrix is empty. I am attaching print screens: 

![Highest category](https://user-images.githubusercontent.com/77200214/106274119-0b292780-6234-11eb-90cb-1f45323d5a59.png)
![Lower category category](https://user-images.githubusercontent.com/77200214/106274142-13816280-6234-11eb-80df-f00a6ee6c649.png)
![Two codes](https://user-images.githubusercontent.com/77200214/106274156-18dead00-6234-11eb-8e4c-75d2e55ab967.png)

**Comment by AndrzejWawa** [comment]
However, if the code is outside all categories, it works. So, whatever, code or category, to work, cannot be in category.
![One code but outside all categories](https://user-images.githubusercontent.com/77200214/106274909-4f68f780-6235-11eb-98bd-69bcdb4edf4e.png)

**Comment by ccbogel** [comment]
Ok. So i did not explain well how it works.  I can further change it.
The selected codes works - need to select 'codes' in the combobox.
The 'categories' only works with the top level categories and unassigned codes.
TODO:
1 I can easily remove the unassigned codes from the matrix when Categories is selected.
2 I can try and use selected categories

**Comment by AndrzejWawa** [comment]
Ahhh, sorry, it works :) I did not notice this combobox.

When I am choosing "code", selected codes in the category work.

When I am choosing "code", and select sub-category, all codes from this subcategory are inserted to the matrix.

So, only sub-category, when selecting "category" in combobox, does not work.

**Comment by ccbogel** [comment]
Updated the software.
Matrix: Cases by Codes
Matrix: Cases by Top Categories -  top level categories (contains all codes from all categories underneath)
Matrix: Cases by Categories collects codes directly under the categories

This is hard to do well, I do not think I can further improve on it,

**Comment by AndrzejWawa** [comment]
Hi, good work! It works well now :)
