### ISSUE TITLE
Simple shortcuts to support laborious analytical tasks

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#361]
I think that a very significant support for the users could be provided by:

1) simple shortcut to "mark" text by previously selected code,

2) creating simple shorcut which open a list (next to coursor) with 5 previously used code, which you can immediately (without using mouse) by arrows, and by clicling "enter" made a mark,

3) shorcuts to annotate and set a bookmar, not such important for me personally, but maybe for others,

4) shortcut to open window with memo for text coding and the same to close this window,

5) to changing highlighted code from overlapping codes, by clicking specific buttons,

6) ctrl+f to be automatically moved to the search window and clicking arrows left and right to automatically jumping over searched fragments,

7) if possible, introduce shortcuts manager to adjust shortcuts to the individual needs (including also other features, like report window, coding window.

I think that these improvements could be absolutely fundamental for further improvement of work efficiency with coding.

**Comment by ccbogel** [comment]
3. shortcuts to bookmark and annotate - the context (right click) menu does this. Annotations needs a selection of text to annotate, bookmark does not.
4. context menu does this already
The problem with using a keyboard shortcut is that you may not see where the cursor is on the text edit area, and you may assign a memo or bookmark to the wrong location. 
I cannot add a cursor to show location because this option is only available for an editable textedit.

**Comment by ccbogel** [comment]
Point 1. You can already mark the selected text using the right-click context menu providing a code has been selected. As you would already have immediately used the mouse to select the text, the right click is the net fastest option to code it with the last used code.

**Comment by ccbogel** [comment]
Point 6. ctrl+f to be automatically moved to the search window and clicking arrows left and right to automatically jumping over searched fragments.

How about I implement CTRL + F (or maybe SHIFT + S - unsure which keys yet) to jump to the search box if no text is selected.
If text is selected, then fill the search box with the text and jump to the arrow next button ?

**Comment by AndrzejWawa** [comment]
Hi,

1. When it comes to the marking by recent could, I think it could be helpful to have shortcut anyway. For example, when you selected text, you can simply click letter "q" to mark, instead of opening right-click context menu. And in the first position of context menu, there could be information about the shortcut. I would to test this, if you implemented, but seems to me very helpful to have one letter shortcut (or two buttons if it is necesarry). 
2. When it comes to other recent codes (second and third e.g.), I mean that the second position in context menu is e.g. "recent codes", and when you click it, it opens new sub-context menu with list of e.g. 5 recently used codes. If introducing sub-menu is to difficult, maybe it is not good idea to introduce names of second and third code in the main context menu - it might mess the menu. 
6. When it comes to searching, your ideas seem to be nice :)

**Comment by ccbogel** [comment]
You must be in the TextEdit to use these keys (i.e. the textEdit must have focus).
text edit shortcut keys a,m; b,s

In Code_av and code_text:
a = annotate - requires a text selection
m = mark - requires a text selection - also requires a code to be selected

In code_text only:
b = bookmark  -sets bookmark to current text file at current text cursor position
s = search - uses selected text if present to fill search box and focus on the Next button. Press space while on next button to activate (or mouse click).

**Comment by AndrzejWawa** [comment]
Hi,

Great work! I will test them!

May I only suggest to change the "m" mark to "q" and bookmark to, e.g. "r"? The explanation lies in the practical usability of shortcuts. When you are working on the computer you have the right hand on the touchpad/mouse and the left near the buttons q, w, e, r, a, s, etc. So, using "q" is very convenient, because your hand naturally has acces to them, also, taking into account, the q is higher than e.g. ctrl and you do not need to raise your wrist which is lying on the laptop.

Otherwise, clicking "m" or "b" rather requires using the same hand as for touchpad/mouse or keeping both hands very close what significantly reduce usability of shortcuts I mean.

When it comes to semantic connotations of letter, in Atlas.ti e.g. there use function "quick coding" meaning the same as mark (by the latest code in QC). So, this "quick" also has connotations. Bookmark has "r". But the crucial, from my point of view, is that you need to using the same hand as for touchpad, moving your hand or keeping close, and all ot these is real alternative to using context menu, if someone prefers shortcuts.

**Comment by ccbogel** [comment]
OK I have implemented the q shortcut key.
I will keep bookmark as b  - it will only be used infrequently - i.e. when going to lunch or finishing for a day.
p.s. I am left handed

**Comment by AndrzejWawa** [comment]
Hi,

Thank you for taking into account my arguments! :)

PS Haha, so, maybe there could be implemented two set of shorcuts: for right-handed (like now), and left-handed - more on shorcuts on numeric keybord and close to it. In the future, potential shorcuts manager.

**Comment by AndrzejWawa** [comment]
And when it comes to this point 2 related recently used code, I think that solution could be, that below "mark" in context menu, there will be "Recent codes mark", and if you click it, it opens similar window, as feature "move code to" opens. But, in this window will be 5-7 recently used codes.

And to this "Recent codes mark" shortcut -"r" :) Could be helpful, if the tree is  big in the further stages of project.

But if you think that it is not good idea, is better to leave as is in my opinion, not adding specific codes to the main menu.

**Comment by AndrzejWawa** [comment]
All of new shortcuts work very well :)

Shortcuts to search, including this selecting text function - wonderful revolution!

**Comment by AndrzejWawa** [comment]
I was thinking more about this, and basing on my recent experience with QC, 10 recent codes in the window (like as when "clicking move code to"), as on the print screen below, would be excellent for faciliating work - if possible of course.

![Code box](https://user-images.githubusercontent.com/77200214/105507796-ed0b7680-5ccb-11eb-983d-35f6513146bc.png)

It is about that you can have very long tree, with tens of codes, but at the specific fragment of document you are often using repetitively the same, e.g. 10 codes. If you will have this option in the context menu, as well shorcut, e.g. "r" ("recent codes mark") you can only select text,  then quickly press r + arrow down (a couple of time) + enter, and text is selected. Otherwise, you have to scroll the whole coding tree and find appropriate code. I work about two days, but already feel, that window could be helpful at early stages of work.

Among all of my active issues now, I think this would be most valuable, then specific button for changing overlapping colors, and finally - information about shorcuts next to context menus options (as in the main menu). So, newcomers will be immediately informed how good network of shorcuts QC has :) At a first glance, these advancements could make, in some respects, QC even more convenient and friendly for the new users than specific commercial softwares :)

 - but, of course, all of these is only feedback for you. I hope, will be helpful.

**Comment by ccbogel** [comment]
Hi. Thanks for the feedback. I will work (have started) on the submenu of recent codes, and will add in this r key shortcut idea also.
I dont think i can add shortcut information in the context menu, but will investigate. Currently I have a weekend away, so a temporary halt to programming.

**Comment by AndrzejWawa** [comment]
Hi,

Sure. Let me know, if you can't add informaton about shortcuts to the context menu, so I can prepare list of the shortcuts to the "help" tab and send to you.

Have a nice weekend!

**Comment by ccbogel** [comment]
then specific button for changing overlapping colors
Can you put this up as a separate issue. -and perhaps give me some detail of how it will work (the process) when coding.

**Comment by ccbogel** [comment]
The right click context  now offers recent codes.
TODO an r key shortcut to do the same menu

**Comment by ccbogel** [comment]
Added the R key for recently used codes.
So we have:
A annotate
        Q Quick Mark with selected code
        B Create bookmark
        S search text
        R opens a context menu of recently used codes
