### ISSUE TITLE
Allow more modification of view (lower priority)

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#362]
I thinkg that such adjustments regarding view could be helpful:

1) providing possibility of changing font size of analyzed files but in the coding window (not in settings). Appropriate shortcut, e.g. ctrl++ ctrl+- could be introduced,

2) the option for changing font size of files should be separated from option related to software panel font. Already there is separated option for categories and codes tree - and it is very good. The issues is that user may want to minimalize names of features on panel, because they are known, but the she may want to dynamically changing font size of documents (by shortcut). 

3) option for changing size of the icons on the panels - more advanced users could prefer smaller icons cause they know them,

4) and finally, allow for hiding window with list of files to expand the codes tree. If I work on the one document, more important is easy access to the tree, not to files. Similar option of hiding could be made for the whole upper panel, especially, that after introducing shortcuts for searching files, adding memos, and changing overlapping codes, there will by only more advanced functionalities in the panel, more rarely used, and why panel could be hidden to expand size of text, size of tree and to hide everything what may distract attention of researcher. I think that it could be great minus and, at the same time, great advantage of the QualCoder, that many commercial softwares have very overwhelming panels, which distract researcher from most important issues - deep theoretical reflection and understanding of the data.

**Comment by ccbogel** [comment]
1. - font size can be changed in the code text pane.
2. - not quite sure what is meant.
3. - changing icon sizes - actually this will be quite difficult to resize them all and move them in all the different dialogs, I will not do this now (or ever?) as will be very time consuming to do this.
4. Implemented in code text and code image - the top pane is hidden/unhidden using key 'h'. Click in the text area (or in the image area) and press 'h'. I was not sure to implement this in the code audio/video dialog.

**Comment by AndrzejWawa** [comment]
1. Very nice! Maybe you would like to introduce also a corresponding option in settings - to select default size of text in file. Now, the default size of text in files = default size of text in main menu, so, the change size of text in files, you have to, in each new session, change size in the coding mode.. However, I am not sure if it is important.

2. Exactly what you already introduced. That size of font in the text can be different that size of font in the main menu (previously, for the size of menu and text was the same option).

3. I think that, after the implementation of hiding panel option, it is not important and worth time.

4. Wonderful! Maybe it is reasonable to provide icon of hiding in the upper-right of the panel - for information for new users.

**Comment by ccbogel** [comment]
unsure about the icon - I have added instructions to the manual. Im not sure how the user interaction process would work best.
but glad the other stuff is enacted well enough
