### ISSUE TITLE
Advancing graphs (lower priority)

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#363]
Good ideas is to enrich graphs feature in such ways:

1) allow to saving graphs, e.g. as files or cases,

2) allow to export them, e.g. as jpeg,

3) allow to change the whole size of the graph window (as image files),

4) allow to move the whole tree of graphs by clicling on certain place on the category,

5) allow to do more operations, like introducing new connections between elements, introducing free elements (simple text boxes, boxes with name of files, codings, or cases), and deleting existing links.

**Comment by ccbogel** [comment]
2. Can now export as a png file.

**Comment by ccbogel** [comment]
@AndrzejWawa  Point 4.  Now moving a category moves all the subcategories and codes.

**Comment by ccbogel** [comment]
Point5. Can add links and add new text items (free text). Can hide/remove links and text items.

**Comment by AndrzejWawa** [comment]
Moreover, as use QC for literature review (coding articles, creating memos, and introducing different attributes to organise corpus), following functions of graphs would be very useful:

1) importing text boxes with names of all files (apart from boxes with names of categories and codes),
2) optionally, adding to the boxes from point 1, names and values of attached attributes, namely: <name of file> <name of attribute 1> <value of attribute 1 for this file> <name of attribute 2> .... This will allow to see existing files, its attributes and organise them graphically,
3) see coding memos for selected file and selected code by right-clicling the file. In other words, after importing names of files to graph you can righ-click the file, select code, and see all coding memos for this file,
4) import all coding memos from point 3 as free text boxes.

When it comes to 3 and 4 I personally would prefer to have option to see and import only coding memos, without attached original coding text for these memos. This is because I have such a procedure for coding papers that, firstly I code texts by code 1, and then I make summary for all of codings for this paper in memo for the first coding. Through this way, I can create SQL table with only ready-made summary for the all codings for specific code and file, not returning to all original coding texts, what could be overwhelming.

**Comment by ccbogel** [comment]
Fixed dark text on dark. Fixed the above AttributeError.

**Comment by AndrzejWawa** [comment]
[BUG] When trying to export graph in png the following window appears:

![obraz](https://user-images.githubusercontent.com/77200214/166494220-7b2eb9e9-0424-4858-bc74-3fefe7de4a5f.png)

**Comment by ccbogel** [comment]
Fixed bug (on Windows but did not occur on Ubuntu).
Added option to reveal hidden items.

**Comment by ccbogel** [comment]
Can now show files and cases, and optionally in right-click menu their attributes.

**Comment by AndrzejWawa** [comment]
Thank you! Works really good! Allowing to connect these new elements by lines could be further improvement.

**Comment by AndrzejWawa** [comment]
For explanation of point 1, I mean to save the last state of the graph, so, after reopening QC you can start work from this last state, not beginning. Ideally, there could be option to have many saved graphs, which could be reopened and editied, like journals.

> Good ideas is to enrich graphs feature in such ways:
> 
>     1. allow to saving graphs, e.g. as files or cases,
> 
>     2. allow to export them, e.g. as jpeg,
> 
>     3. allow to change the whole size of the graph window (as image files),
> 
>     4. allow to move the whole tree of graphs by clicling on certain place on the category,
> 
>     5. allow to do more operations, like introducing new connections between elements, introducing free elements (simple text boxes, boxes with name of files, codings, or cases), and deleting existing links.

**Comment by ccbogel** [comment]
Yes, I understand. I think I will leave that for a later release.

**Comment by AndrzejWawa** [comment]
Sure :)

**Comment by ccbogel** [comment]
TODO: to wrap this issue up will be the storing and retrieving graphs

**Comment by ccbogel** [comment]
Closing as this is in Issue #658
