### ISSUE TITLE
Two adjustments to support coding pdf as jpf/png

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#365]
Hi,

As you remember, I asked about coding pdfs. There are the two ways. Firstly, you can convert pdf into txt and then upload into QC. It works for me, but I use externel converter, because QC converting very disrupts formating (at least when it comes to journal articles). But, it is not problem for me because there are a lot of ways (e.g converters, Libre Office etc.) how you can convert pdf into txt.

However, in article journals there are very often tables etc., which are difficult (at least for me) to convert into readible txt. So, I tried to convert pages of pdf to jpg or png (this second has better quality), and code tables or highly formatted text in the image coding mode. It works, however, I found to limitations:

1) when reading the report or matrix directly in the QualCoder, and the coded part of image with text is bigger, it is unreadable, because images in reports and matri are always displayed in the same size (whatever is their original size. So, the first issue: it is possible to allow change the size of displaying images in report and matrix, which allows you make them readible (especially, when containing text)? I think that good solution is to allow determining of default size of displaying images in reports and matrices by inserting specific numbers. Moreover, additional option for detemining size of specific image (e.g. by clicking and dragging a mouse) also could be helpful.

![Problem of images in the reports](https://user-images.githubusercontent.com/77200214/105252632-1ae2a500-5b7e-11eb-8941-0baa43214b8f.png)

I am attaching print screen presenting the main problem. As you can see, the first coding (small) is highly readable and could be compared, e.g. in the matrix, to codings from txt files. However, the second coding in report (and matrix) is significantly less redable, as the second ureadable at all. But, if you will be able to enlarge default size of images in the report, because you know, that there are a lot of text in these images, all images could be more readable. Moreover, individual sizing could be also helpful, but maybe not essential at the beginning.

2) The second issue introduce for images the same features as for texts in reports - if you are clicling on the text in specific place, you can see it on the original text. So, you will able to click on image extract and open the whole image with coded fragment.

And three additional, related issues:

3) It is possible to enable this feature to see the text extract/image extract (if introduced) in the context of original, coded file, but also in the matrix mode? - it is not available now.

**Comment by ccbogel** [comment]
OK so there is a lot of issues wrapped up here. You will have to separate, 4 and 5 into separate issue requests.

So for issue 1 & 2 above. I think I have enacted a reasonable solution: Click on the heading and you can see the coded image area in the context of the whole image. And you can scale the image to view the text more clearly.
Issue 3: This is not in the matrix for now - as it will be difficult to map the click to the opened 'in context' stuff. So it will take me quite some time.
I have not applied a solution for audio/video yet - but will work on this next for consistency.

**Comment by AndrzejWawa** [comment]
Hi, ok, it works well. 

When I code more pdf as images, I will provide more feedback.

I separated two last issues to new ones.

**Comment by ccbogel** [comment]
Also done for audio/video. will look at the other issue
