### ISSUE TITLE
Two simple bugs in A/V mode 

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#366]
Hi,

1. I found that ctrl+r shortcut does not work in the A/V mode because it is overlapped by ctrl+r shortcut for the report mode. 

2. There is no option for adding memos to codings on transcription, only annotations.

**Comment by AndrzejWawa** [comment]
3. I think that the similar situation is when it comes to alt+f (the same as manage files).

4. And to be sure, when you are clicking in main menu "coding" -> "code audio/video", can you there transcribe recording during listening?

**Comment by ccbogel** [comment]
I have updated controls: Shift + R, Alt + R, Shift + F  TODO: update manual.
And to be sure, when you are clicking in main menu "coding" -> "code audio/video", can you there transcribe recording during listening? **No its is not possible**. You must transcribe using Manage files - then view the AV file. Also you must transcribe before you code. As I only allow small sections of text to be edited once a file is coded.

**Comment by AndrzejWawa** [comment]
Hi, 

Ahhh, I did't understand how to run this transcription mode but now understand - simply opening the A/V file in File manager.

So, if you correct manual, it could be helpful to place this fragment "You can transcribe the file via viewing the audio or video in the Manage Files dialog. You can also get the file professionally transcribed and copy and paste the text into the transcribed text file." also  the section 4.3.4 (transcribing audio and video). 

Very nice feature!
