### ISSUE TITLE
Add category into category and appreciation

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#367]
Hi,

During work I found it would be helpful to have in the context menu, when righ-clicking on the category, not only add new code to this category, but also add category. After certain stage of work I realized that many codes in existing categories are overlapping and to provide order it is good to make subcategories for them.

I want also appreciate two existing features:

1) move "code/category to" in the context menu - very helpful, you don't have to scroll coding tree,
2) journals - firstly, I misuderstood them (as scientific journals : ) ), but now very appreciate. You can esasily switch by alt-j alt-t between code text and write journals.
Journals could be used for e.g. for:
a) making methodological notes, which are too specific for project menu and too general for memos for specific functions.
b) starting noting or writing specific papers, presentations for conferences, or study assignments (otherwise, you had to write everything in project menu, what could make it unclear). E.g. I have now to do one assignment related to the project, as well as one conference, so, during work on the project, simultaneously I can swithich to journals and write. Otherwise, I have to create different LibreOffice Writer files, now, can copy text from QC, paste to LO and process them.

Moreover, Atlas and Maxqda (there is also similar feature, separated from project memo) seem to import journals properly (my misunderstood cause that I colored these features is test report as yellow). 

Thank you! :)

**Comment by ccbogel** [comment]
ok have added this function
