### ISSUE TITLE
Req: Tabs should never be blank

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#368]
When I (re)open QC, most of the tabs are blank. I think the tabs should ideally remember what was displayed last time, or at least a message should advice the user to select something from the menus. At the moment it looks like there is something wrong.

**Comment by jdittrich** [comment]
> or at least a message should advice the user to select something from the menus. 

This would be great, otherwise it is hard to discover

**Comment by AndrzejWawa** [comment]
Hi,

I noted that new and old tags are overlapping:

![Overlapping new and old tags](https://user-images.githubusercontent.com/77200214/105842191-154dea80-5fd6-11eb-8b0c-9979bcbd182d.png)

**Comment by ccbogel** [comment]
aha, thanks  -fixed
