### ISSUE TITLE
Icons fail to load in Windows 10/conda environment

### ISSUE THREAD

**Issue by vmussa** [ccbogel/QualCoder#369]
**Bug description**
Hello @ccbogel and everyone. I have a working clone of QualCoder in the 2.1 version in my Windows/conda/Python 3.8.5 environment. Below in this post, I list all my OS and conda-env specifications. A few days ago I updated it to the 2.2 version but then some icons would not load. I know it's a new feature and hasn't been necessarily tested in all possible environments, but I thought it would be nice to share how it is performing in my specific configurations.

**Steps to reproduce the bug**
So, in a new folder, I clone the repo specifying the 2.2 tag. Then I load QualCoder with python.
```
git clone https://github.com/ccbogel/QualCoder.git --branch 2.2
python .\qualcoder\qualcoder.py
```
**Screenshots**
The result is this, for example:
![image](https://user-images.githubusercontent.com/4412998/105650921-22fb5700-5e94-11eb-819c-5c9ae9f9572a.png)

At the powershell instance that is running QualCoder I get a few messages like these:
![image](https://user-images.githubusercontent.com/4412998/105650776-9cdf1080-5e93-11eb-98dd-e2d98acb3798.png)

**Environment info**
* OS: Windows 10, below some specifications.
--> WindowsBuildLabEx: 19041.1.amd64fre.vb_release.191206-1406
--> WindowsCurrentVersion: 6.3
* conda environment with Python 3.8.5 and some packages listed in this [env.txt](https://github.com/ccbogel/QualCoder/files/5863697/env.txt) file 

Is there anything I can do to change this? Thank in advance you for the attention.

**Comment by ccbogel** [comment]
Hello, thanks for this information. I have not tried to use conda before.
However, I did change the way icons were loaded. This new way will be included in a 2.3 release soonish when I can make another release.
So can you download the code from here: https://github.com/ccbogel/QualCoder _not_ from the releases. Use the Green Code button to download a zip. (it is essentially a bleeding edge version).
Please let me know if this resolves your issue.

**Comment by vmussa** [comment]
Hi again, thanks for the answer. Actually, I've tried the bleeding edge version before and got the same results, which made me think the 2.2 release could be free of this error.
I've tried it now again both with conda and virtualenv. In the virtualenv case, I followed the `README.md` instructions and installed all dependencies in the new venv. In all cases for the bleeding edge version, the result is that the icons don't load, but, differently to the 2.2 release version, I don't get log messages in PowerShell.
For now, my 2.1 version is working fine, so I think I can wait for the 2.3 release to come and try this new way. Thank you very much for the attention again.

**Comment by ccbogel** [comment]
I think I know the problem.
https://stackoverflow.com/questions/47784295/anaconda-package-issue-an-internal-module-cannot-find-a-data-file-located-in-the-same-directory 
I will upload a test solution only for Manage Files initially, in a day or two.

**Comment by vmussa** [comment]
Cool, @ccbogel, thanks. I'll keep up with the updates, then. As soon as you publish it I will try it here.

**Comment by vmussa** [comment]
@ccbogel just to inform you: I've just tried to run `qualcoder.py` directly from its directory, based on the StackOverflow discussion you posted and the icons were loaded successfully:
```
cd .\QualCoder\qualcoder\
python .\qualcoder.py
```

**Comment by ccbogel** [comment]
@vmussa Hello. I have implemented base64. So in the Manage Files only, I have tested this new method for loading image data. Please test this with your conda implementation. If it works fine then I will roll it out across the other modules that load icons.

**Comment by vmussa** [comment]
Hello @ccbogel. I've tested it and now Manage Files is working well. All the icons were successfully loaded, no matter where I run the `qualcoder.py` script from. Thank you!

**Comment by ccbogel** [comment]
OK I will implement this method on the other dialogs also.
