### ISSUE TITLE
Simple shorcut for changing overlapping codes

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#370]
Hi,

1. When you click on the place where two or more codes are overlapping, you can drop down the list on the upper panel and click on specific code to highlight the whole range of it in the text.

However, it seems to me that it could be helpful, that you can click on such a place and despite dropping down the list, only press e.g. "c" (like "change") to highlight different codes in full range. If there are more codes, you can click "c" a number of time. For example, you are clicking on the place where 3 codes are overlapping, the shorcut (as well as drop down list in the panel) is available. First click of "c"  changes code 1 to 2, second click changes code 2 to 3, and third click changes code 3 again to code 1.

2. When it comes to the shorcuts information, maybe it is possible to add to the name of the feature in the context menu a shortcut symbol in the brackets, e.g. Mark ("M"), Mark with recent code ("R")?

PS Thank you for this feature of recent codes - looks and works really wonderfully. Congratulation!

**Comment by ccbogel** [comment]
shortcut key O  to cycle through overlapping codes.
I have added shortcuts in the context menu.
I Use Q to quick mar selected text.
I wanted to use M to Memo coded text, but it does not work correctly, unsure why for now.

**Comment by AndrzejWawa** [comment]
Good work.

It is good to mention in manual that to make a bookmark by "B" it is needed to click in specific place or mark text (if you haven't already done this).

 I think that these shorctcuts significantly improved easiness and flexibility of work, while keeping the structure of software quite simple and readible (to compare with certain commercial softwares).
