### ISSUE TITLE
Option for running search command after clicling enter

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#371]
Hi,

It seems to me that searching letters/words in the text starts immediately after putting first letters. So, when you start writing "horse", the QC is searching the text by "h", "o" etc., before you end.

I think that for older computers (I have a such) this could lead to crash or significant slow-dawn, however, for a new ones, it could be helpful. So, it is possible to add an option (e.g. in main settings or near the search window), that to start searching it is needed to click "enter" - so, you will have time to write the whole word, not searching all letters during writing process.

What will be the default option is up to you.

**Comment by ccbogel** [comment]
I have set it so that only a search of 3 or more characters activates the search (so it looks through the text for matches) to fill the 10/20 display.

**Comment by AndrzejWawa** [comment]
Hey,

Good solution. I think it is worth also to stress, that: However, you want TO search for phrases shorter than 3 character or individual characters anyway, e.g. letter "a", can use symbom "\b" (\ba\b) to find separate characters (but also next to dots, commas, semicolons etc.), "\B" (\Ba\B) to find all characters, also which are the parts of words, or space ( a ) to find characters surrounded only by blank spaces. Searching very numerous phrases or characters requires appropriate computer's computing power.

**Comment by ccbogel** [comment]
ok, well will close this issue for now

**Comment by AndrzejWawa** [comment]
I only mean that this information I wrote in quotaton marks could be added to manual. As I tried, everything works properly, automatic searching drom third character, but if you want, you can also search for shorter, but using symbols mentioned in the information.

**Comment by ccbogel** [comment]
yep sure, I m adding some of this to the manual. It must be very late at night in Poland ?

**Comment by AndrzejWawa** [comment]
Just before 1 am - I'm still working on regular sleep hours :)
