### ISSUE TITLE
Clarifying searching

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#372]
Moreover, it could be good to explain in manual, how searching actually works in QC, from my experience:

1) when putting space+word+space, it results in only words, not followed by dots or commas,

2) when space+word +comma, only words followed by commas,

3) when space+word+dot, words followed by spaces, commas, or dots - however, should result only in words followed by dots, and the same in the case of other special characters, but only, if introduced point 4.

I think that this way of searching is quite good, sensitive, and flexible, but there could be introduced two changes:

4) adding an option to select "search separate words", what will result in words surrounded by blank spaced, but also special characters, like dots, commas, colons, semcolons, hashtags etc., but not by letters or unidentified characters (becuse the latter could be also letters). Moreover, this option will be good for the newcomers,

5) after realizing point 4, when it comes to point 3, allow to also search words followed by dot (as in the case of point 2), because it could be helpful, if someone want to search only words at the end of the sentence.

**Comment by AndrzejWawa** [comment]
In the manual, it cluld me also mentioned that automative codings is case sensitive - I have a such experience coding whole sentences in one file.

**Comment by ccbogel** [comment]
Yes ok for case sensitive auto-coding.
Yes - I need to explain the search does use Regex so:
 A dot is a wild card
? is a this or that character
end[.]  would search for the word 'end.' where the dot is recognised.

**Comment by AndrzejWawa** [comment]
Hi,

Wow, it is very powerful tool!

I have also two little suggestions:

1) It is worth to stress in manual this important function (I also looked for it), e.g. in the form: The word boundary symbol "\b" allows you to search only separate words. For example, when you search for "ate" without using additional symbols, the engine will find "ate", but also "eaten" or "ate.". However, when search for "\bate\b" it will find "ate" or "ate.", but not "eaten".

Of course, verify me, if I understood the \b correctly :)

Moreover, maybe it is advisable to add, near to search window, option to select "search for separate words" which uses this function.

2) And second, very important issue. Initially, I did not realized how rich possibility of searching QC has, and rather interpreted my problems that the QC searching feature has problems. To avoid this negative misunderstanding, I recommend to place next to search box clear information that: "Information on a use of advance search functions, including searching separate words, inflection, plural forms, or words in specific context, you will find in the manual". This information could be placed as permanent tag (like information about creating new codes and categories) or like a specific symbol, and when move coursor on it, the information is displayed. However, if using symbol, it should be eye-catching, e.g. "?", to avoid the situation, that someone missed it.

**Comment by ccbogel** [comment]
I actually forgot about the regex. Another developer added this functionality a long time ago.
? symbol, OK
\b in manual, OK

**Comment by AndrzejWawa** [comment]
Hi,

When placing coursor on search box, there is already cloud with informations. So, the information: "Information on a use of advance RegEx search functions, including searching separate words, inflection, plural forms, or words in specific context, you will find in the manual" could be simply placed there.

**Comment by ccbogel** [comment]
Thanks good ideas.
