### ISSUE TITLE
Texts were not saved in the journals

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#373]
Hi,

I recently had a number of weird situations. In the night, when wrote something in the journal, close the journal and come back, the text disappeared. However, then clicled alt+j (opening journal mode again), text was there again. However, after opening today, it seems to disappear permanently.

Moreover, today I had similar situation with different text, and text seemed to disappear petrmenantly.

Do you know what is the reason of this? And is it save to write important part of text in the journals? - for me, it would be very convenient option of course, more than opening different text processor.

I did not check but is it possible that this problem could be also valid for memos?

These were only loose, unimportant comments, however, it can be problem if someone writes a big amount of text.

**Comment by ccbogel** [comment]
Hi,
Can you check this:
 Open the SQL dialog menu and run this code:

SELECT name,jentry FROM  journal 

Hopefully the original text is still stored in the sqlite database. This is a first step to check where a problem is occuring.

**Comment by AndrzejWawa** [comment]
Ok, so:

1. Opening new journal and paste text.
2. Switching to SQL - text invisible, only title of journal.
3. Opening again journal mode - text invisible, only title,
4. Opening again SQL - text visible.

So, when wrote text, close and open again journal, text invisible, doing again, visible etc. When there are two new journals,  first visible (text), second not, but reopening journal mode, situation change, firs invisible, second visible. Also, when last time visible in journal mode, not visible, and so for change.

What is important, when you:

1) close the software, after the text was visible in journal mode (you can also switch to coding mode, but not opening again journal mode) - it seems to be permanently save, in mode as well SQL,
2) but, when close, after text was not visible in mode - text seems to be permanently deleted, after reopening not visible in mode not in SQL.

**Comment by AndrzejWawa** [comment]
It seems that it is not the problem of memos. Only journals.

**Comment by ccbogel** [comment]
ok, it might be when I moved things to the tab widget. I will look at this next.

**Comment by ccbogel** [comment]
OK fixed. The text will be saved immediately after any text changes.

**Comment by AndrzejWawa** [comment]
Thanks! It works. I think it is an advantage of QualCoder over certain commercial softwares that the text is saved without the need of clicling "save".
