### ISSUE TITLE
Selected options are cleared after switching modes by shortcuts

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#374]
Hi,

When you switch between different modes, e.g. text codings and graphs, not using shortcuts, but only tabs, the selected options are saved during the same session (e.g. open files in coding modes, last place in the text, positions of graph elements, selected options when creating report etc.). However, when you use corresponding shortcuts to do this, e.g. alt+t, ctrl+r, alt+g, all selected options are cleared.

1. It is possible to allow shortcuts to work as tabs, without clearing selected options?
2. Additional issue, it is difficult to allow saving the selected options (e.g. open files, selected files in report, graph state) after closing and reopening QC? But simultanously, providing button "clear selected options".
3. And maybe related to this: in file management window or other management windows you can change width of columns. However, after filling specific cell the width isreaturning to original size. It could be inconvenient when you have a lot to rows to filling.

**Comment by ccbogel** [comment]
However, when you use corresponding shortcuts to do this, e.g. alt+t, ctrl+r, alt+g, all selected options are cleared.
Yes - this is because a new instance of that option (e.g. a new report, new code text) is created. I cannot resolve this easily. Same issue with point 2.
Issue 3: OK will look and see if I can change this.

**Comment by ccbogel** [comment]
issue 3: now fixed for manage files, attributes and cases tables.

**Comment by AndrzejWawa** [comment]
To let you know, in my case there is still problem. 

When I added a new attribute, the scale from bigger one changed to lower one - and it is ok, because now, more items are visible:

![After fillinf a one cell](https://user-images.githubusercontent.com/77200214/106272354-39593800-6231-11eb-904a-9e4f2b3a4fa6.png)

However, after filling one cell, the scale was changed to bigger one, so there is now good everview on items, as well as the new attribute column is not visible - to filling it now it is needed scrolling.

![After fillinf a one cell](https://user-images.githubusercontent.com/77200214/106272525-79b8b600-6231-11eb-8bce-92aec8ce4aea.png)

So, it think it would be ok, if the size, even during filling cells, will be still the same as in the first print screen.

**Comment by ccbogel** [comment]
Ah yes - I have extra code that limits the size of the filename column.
It enacts once at the start - but I can enact it every time the table is re-drawn.

**Comment by ccbogel** [comment]
ok uploaded a fix (I think). Time for bed at 11pm now.

**Comment by AndrzejWawa** [comment]
Good night! :)

Problem still occurs, after opening file manager there is size A, but after filling it changes to size B, which has too bug scale, there is neede scrolling and cant see e.g. file name. You can correct the size manually, to see names of files, but after this, again resaizing to size B.

So, there is sth as "default" filling size. Good solution could be e.g. impementation of minimum and maximum number of visible rows and columns. Not too small not to large, but especially the first one.

**Comment by AndrzejWawa** [comment]
Hi, now it works well with one exception. The problem returns when you add a new attribute in file management mode or delete file (but not, if you add). 

However, I think that main problem was resolved and these situations occur rather less often. Moreover, you reopen mode (alt+f), everything work fine again :)
