### ISSUE TITLE
Periodically update files contents without (necessarily) losing their codes

### ISSUE THREAD

**Issue by vmussa** [ccbogel/QualCoder#376]
**Problem**
As a digital sociologist, I work a lot with dynamic web text data. My _corpora_ are constantly changing as people interact in forums and digital communities like Reddit, Facebook, and so on. Therefore I usually build data pipelines that update my _corpora_ from time to time. To this time QualCoder doesn't seem to support such a workflow as it works with static text files that don't seem to be easily updatable through its GUI – at least without relying on SQL, which I propose below as an alternative, yet as an unknown one to me.

**Proposed solution**
It would be really nice if we could update the text files without losing their respective codes so we can study the _corpus_ while it's changing. Maybe it can be accomplished with a diff text tool like git's, so that we can manually update our files by selecting a folder with equally named files or directly choosing each file to be updated from a new one. A code would only be lost if its text source data is absent in the new file.

**Possible alternatives**
Maybe there is already a way to do this with SQL in QualCoder? I don't have the skills to do it and have got no clue about how to do such a thing. Would it be trivial to update the text in a file table without losing its correspondent codes? If it can be done, I would be happy to learn if anyone could give me some hint about it.

Thank you for the attention.

**Comment by ccbogel** [comment]
Hi, Yes correct re this: To this time QualCoder doesn't seem to support such a workflow as it works with static text files.
This could be either easy or a really difficult thing for me to fix. 

- If for example the original text file was unchanged say from character 0 to 1000, and the new text was appended at the end, then the codes can stay unchanged with their Start and End character positions. Subsequent codings would be unaffected.
- If the new text (of say 150 characters) was appended at the beginning (character position 0), then similarly it would be fairly easy to increase the Start and End positions by 150 characters.
- If the new text was interspersed, and some text deleted, I think it would be very difficult to update. I would not know how to replicate the diff function to make this work well. There is a dfflib module in python but I have not used it, nor would I be certain of how to make adjustments to codes based on using it.

**Comment by AndrzejWawa** [comment]
I had a loose thought that maybe automatic re-coding might be solution. E.g. old codes lost their initial start and end position, each by different number of character, but the new file could be automarical re-coded by the text of the old codes. So, the old codes (if unchanged), will be reintroduced.

**Comment by ccbogel** [comment]
Yes, i like the idea of 'if the content does not change' recode based on finding the same text. The only limitation would be if there are multiple identical texts.

**Comment by vmussa** [comment]
Maybe the context of each of the multiple identical texts could be used to distinguish the original coded section from other identical text data. The [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy) python library would be useful, in this approach.

**Comment by ccbogel** [comment]
Im unsure. are you likely to have multiple identical text segments in your analysis? Another approach might be to. assign then start from the next character pos. through the multiple identical texts and assign them as the text file is iterated through.
Separately, I have considered using blogs/facebook/reddit analysis for research projects in my area. How do you get the approval to use this data?

**Comment by vmussa** [comment]
@ccbogel, I guess this situation is highly unlikely to happen in my case.

Regarding the approval to use this kind of data, it depends on the context. In Reddit's case, for example, which is my field of study, you have to request access to the API and read [its rules](https://github.com/reddit-archive/reddit/wiki/API), which is a pretty straightforward, short and automatic process. Obeying its rules, which are mainly focused on the way you do your API requests, you have pretty much no limitations on how you use the data. At least not according to the API rules, which don't say anything about it.

I think that most of the other social media apps, including [Facebook](https://research.fb.com/data/) and [LinkedIn](https://www.linkedin.com/legal/crawling-terms), let you apply to do research with their data by crawling it or by offering pre-built datasets. A very good methodological article on the caveats and possibilities of this kind of research is [Venturini and Rogers (2019)](https://hal.archives-ouvertes.fr/hal-02003925/).

**Comment by ccbogel** [comment]
Great thanks for the information re research. 
I will look at a way to implement your request. I m wondering if you can help me by providing a zipped qualcoder project containing one text file with some codes, and a separate text file with updated text. So that I have something to work with. Can email me directly if you prefer.

**Comment by vmussa** [comment]
@ccbogel I'll be happy to help you. As soon as I can, probably in a few days, I will provide you with this project example. I will send it to your e-mail, then. Thank you again!

**Comment by ccbogel** [comment]
@vmussa can you provide an example for me. Otherwise I might close this issue down.

**Comment by vmussa** [comment]
@ccbogel sorry for the late answer. Can I send the zipped example to you later today or, at most, tomorrow night? Thanks for the attention again.

**Comment by vmussa** [comment]
@ccbogel I've just sent an e-mail to you with the requested example in a .zip file. Please let me know if I need to add or fix anything. Thank you again.

**Comment by ccbogel** [comment]
@vmussa It has been a long time, but  I have enacted this function now.
It is under Help > Special Functions.
You **must** back up your project first, in case the codings are incorrectly assigned, so that you have a project to revert to.

**Comment by vmussa** [comment]
thank you very much @ccbogel. Very complex feature, but will surely be useful! Gonna try it in my research and I can give you feedback when I do if you want. Thanks again for the amazing work!

**Comment by ccbogel** [comment]
@vmussa I just now updated the files again.
There was an error if the file was associated with a case. Improved this.
