### ISSUE TITLE
Introduce to "show coded files" functions like in report

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#379]
1. In text coding mode, when right clicling on code you can select "show coded files" which shows codings, the similar function "coded text and media" is in the graph mode. It would be nice if close the each coding displayed was this button to show coding in the context of file. In the codings mode it will select and scroll document to specific coding, in the graph mode it would also open text coding mode or show original file in seperate window. Such a function is in the report mode, but requires (if possible of course) adjustment of automatic scrilling to appropriate coding.

2. And, consequently, allow to show via these list of codings also images in the context of original file.

**Comment by ccbogel** [comment]
I think I have now completed this. Each coding is shown when clicking the option in the menu (code text, code AV, code image, graph). No need for a button, clicking on the heading will then open the code in context.
Text scrolls to the visible position.

**Comment by AndrzejWawa** [comment]
Works very good! :)
