### ISSUE TITLE
feature request: import RQDA projects.

### ISSUE THREAD

**Issue by atanasj** [ccbogel/QualCoder#38]
Hi

It would be great if you were able to import `RQDA` porjects into `QualCoder`. Both `PyQDA` and `QualCoder` GUIs seem to work much more smoothly than than the `RQDA` GUI. 

Thanks,
Atanas.

**Comment by ccbogel** [comment]
Thanks for the suggestion. I will have a look at doing this when I have the time.

**Comment by atanasj** [comment]
I'm on `macOS` and it was pretty easy to set up. Much easier than `RQDA`. However, it'd be nice to be able to launch via the icon like is available on `Linux`.

**Comment by siames3** [comment]
This feature would be really nice. Also related: #37 

Great project! Thank you, @ccbogel

**Comment by ccbogel** [comment]
Hi @atanasj @siames3 I have added the capacity to import RQDA projects. It imports everything except file categories. It appears to work fine with the RQDA file that I have. 
Let me know if it works OK for you.

**Comment by ccbogel** [comment]
import works
