### ISSUE TITLE
Bug: Uncaught exception when clicking Code Text

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#381]
I am getting this every time I click on Code Text on the menu:

![code_text](https://user-images.githubusercontent.com/16408198/107073868-ce36d500-67df-11eb-9192-fa1066fd515d.jpg)

**Comment by ccbogel** [comment]
Thanks fixed. Im not sure if I forgot to upload a file or if the file didnt upload correctly.
