### ISSUE TITLE
Bug: uncaught exception in Manage Attributes

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#382]
I downloaded the latest version just now (2.3?) from Master and when I right-click in the Manage Attributes tab, I am getting this uncaught exception:

![Clipboard01](https://user-images.githubusercontent.com/16408198/107118452-03433600-6879-11eb-9f44-78872d0e00b6.jpg)

**Comment by ccbogel** [comment]
Thanks for identifying.  Will fix this afternoon. Hopefully clicking ok, then sllowed you to add an attribute.
