### ISSUE TITLE
PDF Text imported out of order

### ISSUE THREAD

**Issue by bnjmnmorelli** [ccbogel/QualCoder#386]
Excited about this tool!

Not sure it is necessarily a bug with QualCoder, but my issue is that when I import pdfs into the tool and go to code them, often times some of the text is out of order. I have also seen instances where all the spaces between words are removed. I have tried using independent scripts to extract text from PDFs, still using pdfminer.six, and have had luck preventing spaces from being removed, but some text is still being extracted in the incorrect order. 

Any suggestions on workflows that can help me to solve or work around this issue successfully?

I just tested version 2.4 and am having the same issue as I did in the previous version.

**Comment by ccbogel** [comment]
Hi. Text extraction from pdfs is a problem. As pdfs are designed for printing/display rather than as a standard text document. So text sections are stored in frames on a page.
I suggest load the pdf and then before any coding or case assignment is done, replace the plain text (via manage files - view file) with another text extract using another pdf text extraction program.

**Comment by AndrzejWawa** [comment]
Hi, this works nicely for me: https://www.pdfmate.com/pdf-converter-free.html . However, there is Norton warning  on this page - I do not why.

It converts nicely, however there is problems with tables. So, when there is table, I convert the pdf page into png via Gimp and additionally code as image in QC.

**Comment by bnjmnmorelli** [comment]
Thank you both for responding so quickly. I will give pdfmate a try. I also discovered [pdf2go](https://www.pdf2go.com/) and had luck extracting text from a pdf that was previously giving me issues. I will report back once I have processed a number of documents and have a process that gives good results. Thanks Again.

**Comment by ccbogel** [comment]
Thank you both for the information

**Comment by glocalglocal** [comment]
A major problem with online converters is one of confidentiality and privacy. Have you tried https://pandoc.org ? It's considered the gold standard and it's open standard. I had reasonably good results.

**Comment by ccbogel** [comment]
Closing issue as there is no one ideal solution. But I have mentioned this is more detail in the manual.
