### ISSUE TITLE
Hide panel in report mode

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#387]
Hi,

I would like to propose to allow hiding top panel in report mode, which would allow maximising reports and matrices

OR/AND

Allow (as an option) to open matrix in separate window which can be maximised.

Regards.
Andrzej

**Comment by ccbogel** [comment]
Yes. I think I can do that tonight/tomorrow using a key shortcut, 
Overall, is QC working well for you?

**Comment by AndrzejWawa** [comment]
Hi,

Yes, it is working well :)

**Comment by ccbogel** [comment]
Resolved. Use the H key (same as in the code text window). to show / hide the top section. You can press H when the focus is on the text area, or in the selection (codes/cases/files) lists.
