### ISSUE TITLE
Issue running QualCoder on Windows

### ISSUE THREAD

**Issue by candideu** [ccbogel/QualCoder#389]
Hello,

I downloaded the QualCoder zip file, download Python 3, and installed the additional libraries. I don't have much experience with Python, but I tried running qualcoder.py in the command prompt and received this error:

`Traceback (most recent call last):
  File "qualcoder.py", line 45, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'`

![image](https://user-images.githubusercontent.com/55474996/108332621-ff2ee680-719d-11eb-84c3-830dc21f4b2f.png)

I tried re-installing pyQt5 dependency through the command prompt (using `python -m pip install pyqt5`), but I received a number of errors and warnings. Here were the last few lines:

`WARNING: Discarding https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz#sha256=2f230f2dbd767099de7a0cb915abdf0cbc3256a0b5bb910eb09b99117db7a65b (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.5). Command errored out with exit status 1: 'C:\Program Files\Inkscape\bin\python.exe' 'C:\Program Files\Inkscape\lib\python3.8\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\...\AppData\Local\Temp\pip-build-env-ooda9jcg\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'sip >=5.0.1, <6' 'PyQt-builder >=1.1.0, <2' Check the logs for full command output.
  Using cached PyQt5-5.14.0.tar.gz (3.2 MB)
ERROR: pyqt5 from https://files.pythonhosted.org/packages/7c/5b/e760ec4f868cb77cee45b4554bf15d3fe6972176e89c4e3faac941213694/PyQt5-5.14.0.tar.gz#sha256=0145a6b7de15756366decb736c349a0cb510d706c83fda5b8cd9e0557bc1da72 has a pyproject.toml file that does not comply with PEP 518: 'build-system.requires' contains an invalid requirement: 'sip >=5.0.1 <6'`

Is there a Windows installer that exists for QualCoder?

**Comment by ccbogel** [comment]
HI thanks for posting. I have no instant answers for you , but a few things to try:
In the command shell open python by typing:

python --version

It should give you a version number. Hopefully it is version 3.6 or newer. (from the above, looks like 3.8).
Or get a recent release here: 
https://www.python.org/downloads/windows/

Next upgrade pip by typing in the command shell:
python -m pip install --upgrade pip
python -m pip install pyqt5

If you definitely have python3.8 installed another install option goes like this:
python3.8 -m pip install pyqt5

As it is possible you may have more than one python version installed, and you are running QualCoder through one version, but you are installing the modules for another version, without realising.

Note: I have tried making an installer, which was not easy using pyinstaller. I will try to do so again later, but first I want to trim back the issues listed.

**Comment by candideu** [comment]
Hi @ccbogel, thanks for your quick response! It seems that I have Python 3.8.2. When I ran ` python -m pip install --upgrade pip` I got the following:

`Usage:
  C:\Program Files\Inkscape\bin\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  C:\Program Files\Inkscape\bin\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  C:\Program Files\Inkscape\bin\python.exe -m pip install [options] [-e] <vcs project url> ...
  C:\Program Files\Inkscape\bin\python.exe -m pip install [options] [-e] <local project path> ...
  C:\Program Files\Inkscape\bin\python.exe -m pip install [options] <archive url/path> ...

no such option: -u`

When I tried to install pyqt5, I received the same issue as the one in the original post.

**Comment by ccbogel** [comment]
Are you sure you typed -m as an option? Not -u by mistake?
Also, your python is inside Inkscape folder,  which seems unusual. I will Google a bit n see if i can find a solution.

**Comment by candideu** [comment]
I tried it again, but this time, I used `python3 -m pip install --upgrade pip` and `python -m pip install pyqt5`.

For the pip upgrade, I got:
`Successfully installed pip-21.0.1`

and for the pyqt5:

```
Requirement already satisfied: pyqt5 in c:\users\...\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\users\ucand\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyqt5) (12.8.1)
```

I suspect that there's already a Python installation because of another program on my computer (Inkscape), so it seems like using `python3` instead of `python` helped with the pyqt5 error. That said, I am now getting this error when I try to run `python3 qualcoder.py` from the Qualcoder's directory:

```
Traceback (most recent call last):
  File "C:\Users\...\Downloads\QualCoder-2.4\qualcoder.py", line 47, in <module>
    from attributes import DialogManageAttributes
ModuleNotFoundError: No module named 'attributes'
```

**Comment by ccbogel** [comment]
Ok, well it is nearly there. Ok inside the QualCoder-2.4 folder is another folder called qualcoder , in lower case. This folder contains all the program files for qualcoder to run.
Inside this inner folder is the qualcoder.py file that you need to run, by double clicking or command line.
The qualcoder.py file located in 2.4 but above the inner qualcoder folder, was a mistake in placement by me and i should have deleted it.

**Comment by candideu** [comment]
@ccbogel It worked! I made sure to install the extra modules you mentioned at the end because they were indeed missing. Thank you so much for your help! I'm looking forward to using this!

**Comment by ccbogel** [comment]
Thank you.  Im pleased yiu can start making use of it.
Ps how did you find out about QualCoder?

**Comment by candideu** [comment]
I was looking for an alternative to Nvivo and found this through AlternativeTo. This seemed to be one of the few that could handle multimedia data. I currently have access to Nvivo through my previous institution's license, but I don't want my projects and thesis work to be tied to paid proprietary software.

**Comment by ccbogel** [comment]
Great, thanks for the feedback. I have actually only coded textual data up to now for projects. So I'm hoping all the media aspects will be sufficient for your needs.
