### ISSUE TITLE
Import of survey responses from xlsx fails

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#390]
**Describe the bug**
Import of short, free test survey responses from xlsx  in a simple two column format (id, text) fails. When the responses (about 6400 in all with about 4000 short responses, mostly a few words, seldomly a sentence) are split up in chunks of about 400 per file, some of these chunked xlsx import, while others fail to import on MacOS as well as on Ubuntu Linux. This might point to the problem lying in some special characters used in some responses.

In addition, coding the importable chunks  on QC on Mac gradually slows down QC,as the code density increases QC becomes unusable. 

**To Reproduce**
I have emailed you synthetic data that closely resembles format and special characters used in the responses

**Expected behavior**
Import should be possible, esp as #265 has been fixed. QC performance should not be negatively impacted by a survey size that is equal in text length to a 60 minutes interview transcript

**Screenshots**
![screenshot_qualcoder_error_21](https://user-images.githubusercontent.com/5934115/109570202-f7e6d180-7ae9-11eb-91a1-0744bc9e2ce6.png)

**Comment by ccbogel** [comment]
@menelic Thanks for posting. I will have a look tonight to see how the field names (the first row of excel) are being interpreted, once you have emailed the file to me.

Regards "are split up in chunks of about 400 per file"  Are you importing one excel file or many files ? To reproduce the error , I should try and match as closely as possible your workflow.
Also is the first row if each file describing the field names? as this is a requirement. zB: "ID", "TEXT" as the field names

Regards second issue: "In addition, coding the importable chunks on QC on Mac gradually slows down QC, as the code density increases QC becomes unusable." I am not sure how to resolve this one yet. I am guessing the text file is incredibly large.

**Comment by menelic** [comment]
@ccbogel thanks lot for the swift reply! I hope you received my mail with the data, I sent it to the address listed here on GitHub (ccbogel@hotmail.com ) right after creating this issue. The email details the workflow, in short we created the chunked files because QualCoder became very slow when loading all responses in the one original answers  file- which would of course be the preferred way to handle coding these answers.

Apologies, I should have explained the remark on slowness further, as it might be helpful: The Mac version seems to get slower more quickly than the Linux version. A 40 page, 1,5 Line spaced interview transcript with complex codings works well on QualCoder 2.4 on Ubuntu 18.04, but becomes very slow on a Mac with more performant hardware. Yet, even the Linux version of QC that handled this coded interview well became very slow with the survey responses - despite the fact that the overall text is be less than that of the interview. The survey response data structure seems to make operations in QualCoder more resource intensive as coding complexity (using auto-coding and extensive manual coding) increases.

**Comment by ccbogel** [comment]
@menelic I have not received an email yet. 
Will the email contain 'faux' data but match the chunked files and processes that you are doing exactly? An easy solution might be to use the real data but find and replace words with nonsense words.
Regards slowness, at some stage I might have to Skype you to view and discuss.

**Comment by menelic** [comment]
I sent the email 22 hrs ago - please check or provide another email I can use. The data is ready and I believe If I can get it to you this issue can be solved. T

**Comment by ccbogel** [comment]
@menelic I have made a small update so that the top row field names are converted from integers to string when importing from excel. This should resovle the error that was displayed. But I dont think this alone will fill the problems you are having, which is why i do need to see the faux data.
In every 'chunked' file, please make sure the first row in the excel has the heading _id, text_ and is not actual data.
I have checked and cannot find the email. It is a pile of files zipped into a folder?  If the zip is too large emails will not send , I am not sure, but I think 10Mb or 20Mb is the limit.
An alternative email is: colin.curtain@utas.edu.au  (for temporary use only).

**Comment by ccbogel** [comment]
Hi. I have fixed the above error.
Re email:
The error regards openpyxl looking for images - upgrade pip and openpyxl (commands in the email) OR save the xlsx file as a csv file and import from the csv file.
Also: I have added a progress update at the bottom of the screen, to show how many survey rows (cases) are uploaded as it is processing.

**Comment by menelic** [comment]
thank you, will test the fix and report back. Unfortunately there are errors why trying to import from csv file on Ubuntu - see the screenshot below. I have sent details via mail. 

![qc error when importing from csv](https://user-images.githubusercontent.com/5934115/109880060-be8f9c80-7c76-11eb-9158-2130c8ca019e.png)

**Comment by ccbogel** [comment]
OK. there may be some csv specific issues here.
First open the csv file with a text editor to quickly look at it.
Is every field quoted "146", "bbb"  ?   if yes - select "QUOTE ALL" in the option box
Is each column separated with a comma  ?  if yes - ensure the separator is a comma 
this might fix the issue

**Comment by ccbogel** [comment]
I have added an improvement in progress in the Develop branch

**Comment by ccbogel** [comment]
WIll close this for now.
CSV import have been resolved
