### ISSUE TITLE
Attribute always created as numeric attribute

### ISSUE THREAD

**Issue by WouterSpekkink** [ccbogel/QualCoder#392]
**Describe the bug**
I tried to create a character attribute for a file. The attribute is always created as a numeric attribute. It does not matter whether I select "character" or "numeric" from the attribute creation dialog.

**To Reproduce**
Go to the file manager and create an attribute. Choose character in the dialog.

**Expected behavior**
The creation of a character attribute.

**Screenshots**
![sh1](https://user-images.githubusercontent.com/6826078/109881127-0b27a780-7c78-11eb-9f00-c483e0e738a9.png)
![sh2](https://user-images.githubusercontent.com/6826078/109881141-0ebb2e80-7c78-11eb-9b0b-0c66bfc01e1c.png)

**Desktop (please complete the following information):**
 - OS: ArcoLinux (Arch based)
 - Browser: qutebrowser. I don't get why this matters though? 
 - Version: 2.4

**Additional context**
Just downloaded the software from Github today and was trying things out.

**Comment by ccbogel** [comment]
I thought  I had fixed this error in the 2.4 release. However, you are correct.

OK a work around for now, before you start entering variable values:
Open the Sql Statements window and run this code to change to character:
update attribute_type set valuetype='character' where name ='Char'

**Comment by WouterSpekkink** [comment]
Quickest response to a bug report I ever had. :) 

Thanks.

The right click change from the attributes manager also works, btw.

Best,

Wouter
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


3 Mar 2021, 23:56 by notifications@github.com:

**Comment by ccbogel** [comment]
ah yes, funny, I forgot I added that option.

**Comment by ccbogel** [comment]
OK, fixed in the latest code (but not in the release - as this will be unchanged).
A stupid error, missing brackets ()  in the add_sttribute.py module

**Comment by WouterSpekkink** [comment]
Yes, it works fine now. Thanks!
