### ISSUE TITLE
Text coding slow with large text files

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#393]
**Describe the bug**
When a large text file is loaded, coding and moving around the file is very slow.
This has occurred on a text file containing 300,000 characters.

**To Reproduce**
Load a file containing 300,000 characters.

**Expected behavior**
Either make the process faster, or find another solution to reduce the slowness.

**Comment by ccbogel** [comment]
@menelic I have put a solution in place in the develop branch. Please test it at your end.

You need to use the right-click menu on the file to load 60,000 character portions of the text.
![pic1](https://user-images.githubusercontent.com/5834638/110203786-2981e300-7ec4-11eb-825f-d770ca987cfd.png)

Keep clicking on the the Next 60000 Characters menu option to load the next section of the large text file.

Hover the mouse over the filename to see that only a portion is loaded.
![pic2](https://user-images.githubusercontent.com/5834638/110203834-5df59f00-7ec4-11eb-9594-f142cbea8f5c.png)

**Comment by menelic** [comment]
thank you for implementing this! It works partially in that the option is present when loading this dummy file. The working aspect of the feature is also indicated in the counter on how many signs have been loaded:

![load segments of texts files - over 30 000 loaded](https://user-images.githubusercontent.com/5934115/111073565-90645500-84df-11eb-91bf-513cc9145ddc.png)


however, when I click load next 60 000 I get the following Uncaught Exception:

Traceback (most recent call last):
  File "/usr/share/qualcoder/code_text.py", line 2004, in combo_code_selected
    cursor.setPosition(int(item['pos0'] - self.file_['start']), QtGui.QTextCursor.MoveAnchor)

UnboundLocalError: local variable 'item' referenced before assignment

**Comment by ccbogel** [comment]
Thanks. In trying to update all the positioning code relating to this new feature, I missed this one. I have fixed it now.
