### ISSUE TITLE
Show Coded Files does not work reliably anymore

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#395]
**Describe the bug**
The option "show coded files" which provides a key overview of all text snippets that have been coded with a given code does not work reliably anymore in the current master branch - it sometimes shows just an empty window, with projects where it did work before. This happens with a qda file that contains just one densely coded plain text file. The project has not changed since it was last opened with a prior, working version of 2.4. 

In a coded survey file, the function shows number strings but not the coded text when used on the REFI import project flle uploaded as part of  #396 . This file can be used to reproduce the bug. 

**Desktop (please complete the following information):**
Ubuntu 20.04
2.4 installed form current master branch

**Additional context**
This is true for several projects, this functionality worked reliably with yesterdays master version.

**Comment by ccbogel** [comment]
OK. I downloaded a new Master just now, and tested it.
It does work,  it only shows the coded text/images etc for the current selected coder.
So to see another coder's codings, you need to select another coder's name in Settings.

**Comment by menelic** [comment]
thank you, it works with current master - I am closing this issue.
