### ISSUE TITLE
REFI Import from MAXQDA results in unusable listing of files in QC

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#396]
**Describe the bug**
When importing a REFI of open ended survey data coded in MAXQDA, QualCoder successfully imports files and codings, but shows each ID as a separate file in the file list window. This makes it nearly impossible to continue coding, as only one answer string is shown at a time. When clicking on "show all files" Qualcoder does not list  the  text snippets coded with the given code across all files in the project.

**To Reproduce**

survey file with dummy data that was coded in MAXQDA

[qtest_maxQDA.xlsx](https://github.com/ccbogel/QualCoder/files/6126609/qtest_maxQDA.xlsx)

MAXQDA-produced REFI

[qtest_maxQDA.zip](https://github.com/ccbogel/QualCoder/files/6126624/qtest_maxQDA.zip)  <- please rename quest_maxQDA.qdpx 

When importing qtest_maxQDA.xlsx directly, it works very well and crucially, there is only one entry in the file list, when it is clicked all open answers are shown, which enables coding of the open answers. 

P.S.: The progress indicator for importing larger survey files works very well, as does csv import which crucially works as a fallback for xlxs files where survey import aborts with errors. Thanks for implementing this! I d say this alone is worth 2.5 or at least 2.4.1

**Comment by ccbogel** [comment]
OK this is very interesting. I wonder - have you tried to import the qtext_maxQDA.qdpx into any other qualitative software (e.g. Atlas, Quirkos).
I think this is an unfixable problem.

The problem I am seeing is that the MAXQDA export looks **really** wrong. 
Make a copy of the zip file, and extract it. 
Inside the source folder are the text files (using the long hexadecimal notation for filenames that qdpx uses). Each file only contains a copy of the id, and no actual text.
The text is stored as a variable assigned to each file. See the extract from the project.qde file:

  <TextSource plainTextPath="internal://D451893D-9000-424A-BFDE-79DFAAD3A85E.txt" guid="D451893D-9000-424A-BFDE-79DFAAD3A85E" name="150" modifyingUser="9649C964-3598-4779-9A3F-14643CE9A929" modifiedDateTime="2021-03-11T13:36:03Z" creatingUser="9649C964-3598-4779-9A3F-14643CE9A929" creationDateTime="2021-03-11T13:36:03Z">
   <PlainTextSelection guid="5E788999-9D92-40FB-90FF-B0C3C782CBDC" name="1,4" modifyingUser="9649C964-3598-4779-9A3F-14643CE9A929" modifiedDateTime="2021-03-11T13:36:03Z" creatingUser="9649C964-3598-4779-9A3F-14643CE9A929" creationDateTime="2021-03-11T13:36:03Z" startPosition="1" endPosition="4">
    <Coding guid="9095DEAB-2FAA-4601-ACC8-920FEF2BA07A" creatingUser="9649C964-3598-4779-9A3F-14643CE9A929" creationDateTime="2021-03-11T13:36:03Z">
     <CodeRef targetGUID="4739883E-0CB7-4AA1-8B67-7AFFB73EBC77"/>
    </Coding>
   </PlainTextSelection>
   <PlainTextSelection guid="56515C60-EAA2-4564-9D8B-6C25AC1F5910" name="1,4" modifyingUser="9649C964-3598-4779-9A3F-14643CE9A929" modifiedDateTime="2021-03-11T13:56:12Z" creatingUser="9649C964-3598-4779-9A3F-14643CE9A929" creationDateTime="2021-03-11T13:56:12Z" startPosition="1" endPosition="4">
    <Coding guid="3C1F4799-193A-4FC7-995E-149E21061079" creatingUser="9649C964-3598-4779-9A3F-14643CE9A929" creationDateTime="2021-03-11T13:56:12Z">
     <CodeRef targetGUID="4FA1E229-F88D-408B-A8D9-9EDE76B336EF"/>
    </Coding>
   </PlainTextSelection>
   <VariableValue>
    <VariableRef targetGUID="73826F99-4542-4A31-AEA5-425092992AC3"/>
    <TextValue>Code 4 – its a bit longer and w</TextValue>
   </VariableValue>  
</TextSource>

**Comment by menelic** [comment]
I will have to organise an opportunity to import into another software - will do so if you say it helps your work. Would you want us to try to import, add codes and categories and re-export as REFI from, say, ATLAS?

But please note: When using the show all files option on such imports in QualCoder it *does work*! So here is hoping that its not unfixable. It would be important to be able to use it for a project partly done with MaxQDA and partly with QC, where we need to pull all MaxQDA coded files through QC because we need the get coding table export function for further analysis and visualisation in R.

**Comment by ccbogel** [comment]
What i meant was. I am sure importing that file from maxqda to another software will still have problems. As the qdpx contents exported from maxqda are wrong. Each text file contains no text only one id number in each file. The only codings are highlighting id numbers.

The writing about show all files, i don't understand what you mean.

**Comment by menelic** [comment]
Because we have a lot of interpretive (and thus extremely time-intensive to reproduce, as auto-coding won't work for most codes) coding in MAXQDA files that we had planned to import and process in QualCoder, I want to make sure there is no misunderstanding on this issue. When importing a REFI from MAXQDA in which survey answers have been coded, clicking on a code imported fro MAXQDA and selecting the QualCoder option "show all files" does show all coded text snippets from all files correctly. So that means that Qualcoder is able to correctly import MAXQDA REFI despite their questionable implementation in MAXQDA.

This means the character positions of the codes are correct relative to the single text files created per ID. Given that QualCoder has all relevant information and is dislaying it correctly in the show all files window, displaying all files and enabling further coding seems to be a question of displaying the files in the coding window. Thats why I said:

> Maybe your implementation of #393 offers a solution in that the single, id-based files could be loaded into the workspace in an extra step? The fact that Qualcoder can show all coded text for a given code across all files shows that it does access the right  info on code positions. It also shows single coded files with correct codings. So all the elements are there - it would just need to  show all the text, all the time....

**Comment by ccbogel** [comment]
Ok let me clarify the problem I have with the qdpx loading with pictures:

This picture is when loading the qtest_maxQDA.qdpx file:
This is OK ish.
![pic1](https://user-images.githubusercontent.com/5834638/111059323-d4a82300-84e8-11eb-872d-93cbfacc41f8.png)

This is the text of the file '153' and it contains only the id '153' The other text that I think should be here is in an attribute called qtest_maxQDA.
![pic2](https://user-images.githubusercontent.com/5834638/111059413-6b74df80-84e9-11eb-9005-e127426d0e25.png)

Manage files screen:
![pic3](https://user-images.githubusercontent.com/5834638/111059443-ab3bc700-84e9-11eb-9f9f-07de16267e68.png)

**Comment by menelic** [comment]
thanks for the clarification - I do understand the issue. 

> So to fix this in a reasonably acceptable way:
I would have to add a function to lump each row together into one file containing the id and the text.
Also calculate the coding positions for the entire text (shown in the manage files attributes) for each row and then store these.

yes, please! That would ensure QualCoder can be an endpoint for MAXQDA files. MAXQDAs non-compliant implementation of REFI itself is another reason to migrate to QualCoder.

**Comment by ccbogel** [comment]
I am not certain that one instance here is definitive of non-compliance. 
But I will see of I can resolve this a little, as a unique circumstance.

**Comment by ccbogel** [comment]
I have a solution that might do what you want. I will email Joshua (menelic?) about it.

**Comment by menelic** [comment]
Thanks a lot for looking into this. I can confirm that with QualCoder installed from the current master, the picture represents the issues we face with both the dummy file and the original file.There is one curious difference however - with the original file, switching to the correct coder in settings will enable the display of the coded text snippets when "show all coded files" is shown. With the dummy file you used above, doing this will result in just the ids and what seems to be the code location (eg 2-7) being displayed, but not the coded text snippets.

**Comment by ccbogel** [comment]
In that case, the dummy is not an accurate dummy of the original file.

**Comment by ccbogel** [comment]
I am going to close this issue here, as yours is a unique issue,  and we have been working via email to resolve
