### ISSUE TITLE
Progress Counter/Progress Bar when importing large REFI files

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#398]
**Is your feature request related to a problem? Please describe.**
With the implementation of chunked loading  (#393 ) QualCoder is now able to work well with larger files. This implementation included a counter that indicates progress during import. However, when importing REFIs there is no such indication of progress. With Survey REFIS with complex codings taking 5 minutes or more to import, it can be unclear for the user if QualCoder is still working or has crashed, as the interface is unresponsive or extremely slow during import.

**Describe the solution you'd like**
Add a counter like the one that was added for survey import. If possible, both the survey import and the REFI import would also benefit form a progress bar that indicates current state and rate of import visually.

**Comment by ccbogel** [comment]
updated now
