### ISSUE TITLE
Whatever changes (deleting,renaming, reorder) happening in 'manage files' should automatically be reflected in 'code text'

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#399]
Modifying files in 'manage files' does not automatically reflect the status when you are in the 'code text' window. You need to close it and reopen, or for example deleted files still appear in the 'code text' window, clicking on them will result in an uncaught exception:

Traceback (most recent call last):
  File "/usr/share/qualcoder/code_text.py", line 1600, in listwidgetitem_view_file
    self.load_file(self.filename)

  File "/usr/share/qualcoder/code_text.py", line 1612, in load_file
    file_result = self.app.get_file_texts([filedata['id']])[0]

IndexError: list index out of range

**Describe the solution you'd like**
Whatever changes (deleting,renaming, reorder) happening in 'manage files' would automatically be reflected.

Lubuntu 18.04.2 QualCoder 2.2

**Comment by ccbogel** [comment]
This change has been enacted in Qualcoder 2.4
