### ISSUE TITLE
(suggestion) Merge 'help file' and online 'how to use' into a single manual and ship it with QualCoder

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#4]
Right now users have to go on the website (which could be down or the user could be without internet) or dig into QualCoder folders to find a 'help' file.

I suggest to merge the two in order to have a PDF manual to be shipped with QualCode and to be added to "QualCode-Master" folder so that once installed the user can clearly see the manual. 

I know writing documentation is a pain but it really helps users, and avoid them (us) to ask questions to devs, especially as with time new features are added and you can just document them in a single file.

 If you think pictures in the files could make the size of zip balloon you can losslessly compress them with online services or even FLOSS software like caesium.

**Comment by ccbogel** [comment]
Yes this is a great idea and perhaps a bit of work too.
I really appreciate your help with moving this project forward.
with regards Colin

________________________________

**Comment by ccbogel** [comment]
I have now created and uploaded a user manual.

**Comment by WPFilmmaker** [comment]
I gave it a brief look and looks good I like the layout! 
I did not see any "how you can help/contribute" section, I think it could be useful to have, just make a list of possible ways contributors can help (translation,coding,feedbacks etc.)

When I have more time I will definitively give it a proper look and let you know more details (and thanks for the mention!).

Just  a tip, I don't know what software you used for it, but as documentation it will expand in the future, I recommend using something which will make working on several pages easy. You don't want to end up rewriting documentation because the original manual is too bloated to be editable.

**Comment by ccbogel** [comment]
Yes thats true re writing big documents, I have been using LibreOffice which I am pretty comfortable with.
