### ISSUE TITLE
Relative imports

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#40]
@mortbauer I pulled your changes across. The dependencies work fine, thanks very much.
The relative imports made the software unusable on Ubuntu and Windows, so I made them absolute. I have not tried on Mac. I tried to learn about relative imports and how to fix this, but I could not understand how.

In your README file there is a reference to a requirements.txt file which I could not locate.
I have updated instillation instructions to include the additional modules.
I will try and make a new deb package soon-ish using the files you have uploaded.

**Comment by mortbauer** [comment]
You are right about the requirements.txt, actually for applications like Qualcoder requirements.txt is often used, however I actually put all dependencies into the setup.py directly.

For the relative imports I'm not sure what you mean, they work equally on windows, linux, ... . How do you start qualcoder?

**Comment by ccbogel** [comment]
On Windows - in the correct directory command prompt **python qualcoder.py** OR by double-clicking the qualcoder.py file (I sometimes also make a shortcut to this file on the desktop).
On Linux either via IDE (pycharm or ninja IDE) or via terminal **python3 path/qualcoder.py** (this is during testing, otherwise I would use the program launcher).
It cannot resolve the relative imports - 'cannot find module ...'

**Comment by mortbauer** [comment]
Yes exactly, setup.py install a script called qualcoder, this does not require relative imports but it works with them. For development I usually install via `python -m pip install -e .` inside a virtual environment.
I fixed now the instructions in the README on my latest master branch.

And sorry for making such big changes, there is quite a lot of confusing steps when one doesn't, and even when one does, software development as a job.

**Comment by mortbauer** [comment]
Maybe you can try on my master before any merge, everything should work, including relative imports on all platforms.

**Comment by ccbogel** [comment]
yes that a good idea.
