### ISSUE TITLE
Displaying and moving through coded text in ALL files

### ISSUE THREAD

**Issue by gdzqzzx** [ccbogel/QualCoder#400]
The buttons underneath the codes tree are only able to display and move through the coded text within the current file. My feature requests are based on these buttons:

1. Is it possible to traverse coded text in **ALL** text files in the project? 
2. And it would be even better if there can be a tick box/dropdown to choose moving through coded text within one single text file or all text files. 

Thank you for writing this brilliant new tool for QDA.

**Comment by ccbogel** [comment]
HI I dont think I need to do anything more. If you click on the next file in the list then click the buttons its fine.
