### ISSUE TITLE
Bug: Error in Search all text files

### ISSUE THREAD

**Issue by gdzqzzx** [ccbogel/QualCoder#401]
I am running on Windows 10, using python 3.7.10.

Uncaught exceptions were thrown when I tested the **Search all text files** tick box. Searching only work correctly in current displayed files but failed in searching all text files.

- Scenario 1
When I searched *like* in *transcript.txt*, the searching result was correct as moving through 2 results. However, when "Search all text files" was ticked, the other 3 results out of current files weren't displayed though the number of searching results seems correct.
![image](https://user-images.githubusercontent.com/48874535/113742452-fe4e1600-9745-11eb-9fc5-0182628a03f1.png)

- Scenario 2
Following the former steps, when "Search all text files" unticked, another exception was thrown as following and no matched result out of current file displayed, although number of results was correct and searching term was highlighted correctly as well.
![image](https://user-images.githubusercontent.com/48874535/113743027-87fde380-9746-11eb-91c5-bab5be4551e1.png)

- Scenario 3
Similar to Scenario 1, same exception was thrown when I changed to search *and* in *ID1.docx*. But this time the highlighted terms were wrong except the first 3 *and* in current file, and results out of current file weren't shown as well.
![image](https://user-images.githubusercontent.com/48874535/113744880-74537c80-9748-11eb-9fc6-cc9323fb633e.png)

I guess some bugs may exist in locating the start of matched terms across the files. Maybe files that don't have matched results need to be handled?

**Comment by ccbogel** [comment]
Thanks for this. Yes I added a new feature - loading chunks of large text files, and this feature has caused the issue. I will rectify soon.

**Comment by ccbogel** [comment]
ok this should be fixed not (in latest code, not the release)
