### ISSUE TITLE
Bug: QC creates speaker names out of {string}

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#404]
I opened an mp3 for transcription and pasted text into the box. QC created speaker names for Ctrl+1, 2 etc out of all my {string} instances. 

My speaker format in Settings is indeed set to { }, and I often use it in transcription for my own inserted comments. I use { } for this and timestamps instead of the usual [ ] because the latter are reserved in markdown.  

I think QC should not try to extract names from the text. If it must do that, less common bracketing should be available as option, eg {{ }}. 

I can ignore those names but my strings can be of any length and number, which will probably create all sorts of problems for QC, not to mention that the user will think QC is buggy.

**Comment by ccbogel** [comment]
I will see what I can do.

**Comment by glocalglocal** [comment]
More annoyingly, even if I delete these wrong names, next time I open the dialogue, QC recreates them. If this is how QC 'remembers' names, I am guessing it may replace your preferred order with the order they appear in the text, which will disrupt how people work.

**Comment by ccbogel** [comment]
OK, I have turned that function off.
