### ISSUE TITLE
Req: Suggestions for Large Files Coding

### ISSUE THREAD

**Issue by gdzqzzx** [ccbogel/QualCoder#405]
1. <b>**Next 60,000 characters**</b> only provide a backing page feature for large file, it would be nice if a forwarding page feature can also be provided.

2. Although splitting the shown text can speed up coding, loading a large file is still slow. Maybe it would be faster if QualCoder can read the large files using a iterator and restricting the size of chunk.

3. Also it might be good to split the text block by the first line break closest to 60,000 characters but not just splitting by character, because this could split a paragraph/sentence/word in the text.

**Comment by ccbogel** [comment]
1. OK I have added forward and back functions. 
2. I have reduced the file chunk size to 50,000
3. True, but a bit tricky to implement right now.

**Comment by gdzqzzx** [comment]
Thanks for updating.

I am trying to use a bin packing algorithm to tackle the splitting problem. I will make a update for your reference after I finish it.

**Comment by ccbogel** [comment]
OK, I am not sure what you mean by that, LOL.
for point 3, I have decided I can work it out, but looking 50,000 characters ahead and then backtrack to the line ending.

**Comment by gdzqzzx** [comment]
It just a dummy idea that how I preproceed our data before loading into QualCoder. Since paging forward and backward but no specific page loading is still a little bit inconvinient for my team, I just try to splitt our records into as few 60,000 characters (now it's 50,000) files as possible, using an algorithm called [bin packing](https://www.youtube.com/watch?v=vUxhAmfXs2o). I just realize that might be more space-efficient but more time-consuming, which it's unnecessary here 😅. I think splitting a chunk and tracing back to the end of line is an easier method.

**Comment by ccbogel** [comment]
OK I think I have sorted this out now.
%0,000 char limit. 
When moving forward, it looks back to line endings,
when moving back, it looks forward to line endings.
So gives a better separation at the start and end of each text chunk.
