### ISSUE TITLE
minor issue Linux wayland

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#406]
**Describe the bug**
running qualcoder in the linux shell (via gnome and wayland) results in the error message

qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

this is on the current master.

Work around proposal: detect whether  qt runs via wayland. If yes, don't request activate. Or use available wayland options?

**Comment by ilippert** [comment]
Have now conducted some video coding. Which works quite well (thanks!!!). But the shell contains a range of errors messages


<details>
  <summary>Log File</summary>
  
  ```
[00007fb8e40794b0] xcb_window window error: bad X11 window 0x00000007
[00007fb8dc00b5d0] gl gl: Initialized libplacebo v2.72.0 (API v72)
libva info: VA-API version 1.9.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[00007fb8dc00b5d0] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.9.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_9
libva info: va_openDriver() returns 0
[00007fb8dc00b5d0] glconv_vaapi_drm gl error: vaDeriveImage: operation failed
[00007fb8e4045fa0] main video output error: video output creation failed
[00007fb904c14150] main decoder error: failed to create video output
[00007fb8e40cab80] xcb_window window error: bad X11 window 0x00000007

  ```
</details>

**Comment by ccbogel** [comment]
Yes, vlc does lots of error messages, but does not affect its use, so I ignore those. I think it looks for particular installed components, reports an error if not found, and then uses a secondary /backup position.

Yes wayland does not work with this qt method
Is wayland Fedora specific?
https://bugzilla.redhat.com/show_bug.cgi?id=1820923
https://bugzilla.redhat.com/show_bug.cgi?id=1769060
https://code.mythtv.org/trac/ticket/13483

They suggest installing xwayland.

How do you get QualCoder to run if the qt activate issue occurs?

**Comment by ilippert** [comment]
Thanks. [Wayland](https://en.wikipedia.org/wiki/Wayland_(display_server_protocol))  is used by quite a few unixes incl several Linux distributions (incl Debian, Slackware...). So, not Fedora specific. Wayland is increasingly replacing the x windows system and its server. Gnome and KDE Plasma are both running on Wayland.

XWayland works by default - maybe that is also the reason why I have no problem running QualCoder.

**Comment by ccbogel** [comment]
I have googled, but do not know how to detect the use of wayland from the python software. 
I could add an instruction for Fedora that xwayland needs to be installed.
Can you provide that instruction?

**Comment by ccbogel** [comment]
closing issue, i have mentioned the need to install xwayland, I have no way to solve this otherwise.
