### ISSUE TITLE
Bug: ctrl+R in transcribing 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#409]
In transcribing audio files, ctrl+R doesn't do anything but it is listed on the hints line.

**Comment by glocalglocal** [comment]
Also, Alt+F (listed as hint at the bottom) doesn't do anything, but Shift+F does (not listed, but it appears as button tooltip).

**Comment by ccbogel** [comment]
I dont know how to fix the delay. issue with Ctrl+S - I dont see it, but this might occur on older computers.

Thanks crtl + R  is an error. It was meant to say alt+r shift+R shift+F  - i had change these key some time ago but did not update that text. Updated

**Comment by glocalglocal** [comment]
> I dont know how to fix the delay. issue with Ctrl+S - I dont see it, but this might occur on older computers.

This is not about computer speed, and an idling i7 should be able to cope really. Something else is going on. With ctrl+S I get these: (a) no delay, (b) any amount of delay up to about 1 sec, or (c) the key press is completely ignored. It's mostly (b), followed by (c) and then (a).

**Comment by ccbogel** [comment]
ok, I dont know how to fix this to be honest. anyway Im off to work now

**Comment by glocalglocal** [comment]
>  It was meant to say alt+r shift+R shift+F

There is an unfortunate typo now :)

**Comment by ccbogel** [comment]
ah funny, fixed

________________________________

**Comment by glocalglocal** [comment]
More on this in case it helps: I noticed I get an unusual number of missing letters as I type. I thought it was me mistyping but I observed more closely and somehow QC misses occasional keystrokes. I haven't seen this in any other application.

**Comment by glocalglocal** [comment]
> Alt+R and Alt+F print r (after it rewinds 5 secs as expected) and f respectively.

This bug is still there. Alt+F isn't supposed to do anything, but Alt+R is for rewind 5 secs.
