### ISSUE TITLE
Debian Package Binary (/usr/bin/main) needs to be renamed

### ISSUE THREAD

**Issue by vollzeitaffe** [ccbogel/QualCoder#41]
Hey,
as the title implies. Debian-Package contains /usr/bin/main as executable which should be rather /usr/bin/qualcoder.
Otherwise appreciate your work! Thanks buddy!

**Comment by ccbogel** [comment]
Thanks for the advice. I have tried renaming main to qualcoder. I can build a package, but it does not install. 

So I might revert to the install.sh script and  give up with Debian packages as they really are not easy to create.

The Debian structure I have created is:
qualcoder-1.4
- DEBIAN
-- control
-- rules (OK this is not required according to lintian, so can delete)
- usr
-- bin
--- qualcoder (shell script: #!/bin/bash newline python3 /usr/share/qualcoder/qualcoder.py)
-- share
--- applications
---- qualcoder.desktop
--- doc
---- qualcoder
----- changelog.gz
----- copyright
----- README.md
--- pixmaps
---- qualcoder.png
--- qualcoder
---- all the python and data files

To make the package:
```
sudo chown root:root -R qualcoder-1.4
sudo chmod 0755 qualcoder-1.4/usr/bin/qualcoder
dpkg -b qualcoder-1.4
```
Running lintian

```
lintian qualcoder-1.4.deb 
W: qualcoder: changelog-not-compressed-with-max-compression changelog.gz
W: qualcoder: unknown-control-file rules
W: qualcoder: package-contains-timestamped-gzip usr/share/doc/qualcoder/changelog.gz
W: qualcoder: duplicate-font-file usr/share/qualcoder/GUI/NotoSans-hinted/NotoSans-Bold.ttf also in fonts-noto-hinted
W: qualcoder: duplicate-font-file usr/share/qualcoder/GUI/NotoSans-hinted/NotoSans-BoldItalic.ttf also in fonts-noto-hinted
W: qualcoder: duplicate-font-file usr/share/qualcoder/GUI/NotoSans-hinted/NotoSans-Italic.ttf also in fonts-noto-hinted
W: qualcoder: duplicate-font-file ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: qualcoder: binary-without-manpage usr/bin/qualcoder
W: qualcoder: desktop-command-not-in-package usr/share/applications/qualcoder.desktop python3
```

The desktop file contains:
[Desktop Entry]
Name=QualCoder
Type=Application
Version=1.4
Comment=Qualitiatve data analysis
Exec=python3 /usr/share/qualcoder/qualcoder.py
Icon=/usr/share/pixmaps/qualcoder.png
Terminal=false
Categories=Science;
Name[en_AU]=QualCoder

**Comment by ccbogel** [comment]
See this repository, an updated deb with the renamed file is here:
https://github.com/ccbogel/QualCoder-Debians
