### ISSUE TITLE
Req: Controlling Pause/Start

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#410]
It would be useful to have key combinations optionally defined by the user in transcribing or across the application. Eg in transcribing audio, ctrl+P or S make sense for Pause/Start but many users may prefer a quick ctrl+space (or a single key like the unusual '`', or even a double-space) when racing against time. 

Specifically on controlling pause/start, it would be great to have QC read from a USB device, like a foot pedal. QC may not be professional transcription software, but this may not be too difficult and offering the possibility would make QC as good as paid-for applications like [Express Scribe](https://www.nch.com.au/scribe/index.html#101).

**Comment by ccbogel** [comment]
1 User defined keys is a lot of work for now. so will leave it for now. One of the problems will be that the menu shortcuts will override these also.
2 I would not know how to begin with a usb pedal, nor do I have one. so I dont think I would try this.

**Comment by ccbogel** [comment]
Closing ony because I dont know how to resolve this for now.
