### ISSUE TITLE
Cannot build QualCoder with py2app (macOS)

### ISSUE THREAD

**Issue by roberto-arista** [ccbogel/QualCoder#412]
**Describe the bug**
Cannot open the app build with py2app. Getting the following error:

> This version: QualCoder 2.5
> Could not detect latest release from Github
> <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
> Settings
> ========
> Coder: default
> Font: Noto Sans 14
> Tree font size: 12
> Working directory: /Users/simonacolucci
> Show IDs: False
> Language: en
> Timestamp format: [hh.mm.ss]
> Speaker name format: []
> Backup on open: True
> Backup AV files: True
> ========

**To Reproduce**
- copy the source code (release 2.5) in the Applications folder
- change terminal directory to Applications/QualCoder
- run `python3 setup.py py2app`
- open the app from the dist folder

**Screenshots**
![Immagine 14-04-21 alle 11 50](https://user-images.githubusercontent.com/2218712/114691212-b74cbb80-9d17-11eb-90ac-4ecb5c9a22d6.jpg)

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Version 11.2.3

**Comment by ccbogel** [comment]
The software  is running. Did you get it to run using the py2app method?
It was suggested to me by a mac user.
I am not sure if i can fix the ssl certificate issue,  but will try to google some answers.

**Comment by roberto-arista** [comment]
yes, I used the py2app method

**Comment by ccbogel** [comment]
I dont think I can fix this URL certificate issue, so instead, I have hidden the error output.

**Comment by roberto-arista** [comment]
Now I realize that it wasn't an alert modal, but just a console log
The app was running just fine

Sorry for the trouble, the message disappeared

<img width="1136" alt="Screenshot 2021-04-15 at 10 01 11" src="https://user-images.githubusercontent.com/2218712/114835146-8f219300-9dd1-11eb-82d0-830e7cebb3fe.png">

Thanks!
