### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by pokojprogrammer** [ccbogel/QualCoder#413]
I get the following bug in 2.5 version (the programme cuts the bottom of the menu labels - commands fall on each other):
![2021-04-17 (5)](https://user-images.githubusercontent.com/82689320/115099023-a8daeb80-9f33-11eb-8996-0156733a5ab4.png).

**Comment by ccbogel** [comment]
Thanks for posting. Ok. There are limits to how big the fonts can be before this happens.
I see in the bottom left of the main screen you have set the font size to 14.
Is it better with a font size of 12?

**Comment by pokojprogrammer** [comment]
Unfortunatelly not. I tried with all available font sizes and it always
cuts the bottom of words.

Colin Curtain ***@***.***> schrieb am Sa., 17. Apr. 2021,
08:41:

**Comment by ccbogel** [comment]
I am not sure what to do. Is the font size changing visually, when you change the font size?

**Comment by pokojprogrammer** [comment]
Yes, the font size is changing correctly.


Colin Curtain ***@***.***> schrieb am Sa., 17. Apr. 2021,
15:39:

**Comment by ccbogel** [comment]
OK,. its strange as for me the text is displaying correctly in this window for me, and many other users. I will make the window labels a little bigger to try and display the text.
 
![Screenshot from 2021-04-18 10-41-08](https://user-images.githubusercontent.com/5834638/115130402-e2dee700-a032-11eb-95e1-31d49c8f0f42.png)

**Comment by pokojprogrammer** [comment]
OK, thanks a lot.  Yes, I already asked my friend who is using the 2.4 version of the qualcoder and he also told me that he never had such a problem. I decided to try version 2.4 then but unfortunately with the same result. Od: Colin CurtainWysłano: niedziela, 18 kwietnia 2021 02:44Do: ccbogel/QualCoderDW: pokojprogrammer; AuthorTemat: Re: [ccbogel/QualCoder] Bug (#413) OK,. its strange as for me the text is displaying correctly in this window for me, and many other users. I will make the window labels a little bigger to try and display the text.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ccbogel** [comment]
Most of your post is unclear ?

**Comment by pokojprogrammer** [comment]
I meant that the same bug occurs no matter which version I use (tried 2.4
and 2.5).

Colin Curtain ***@***.***> schrieb am So., 18. Apr. 2021,
03:35:

**Comment by ccbogel** [comment]
I will close this issue, as I have no way of resolving it. 
It seems like a really unusual situation.
Perhaps you could look at another qualitative software.
