### ISSUE TITLE
Bug: pasting preserves formatting in text

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#414]
When transcribing, if I copy formatted text (eg bold) from another application and paste it into QC's plain text box, the format is preserved even though the text will be saved as plain. Same in the memo box below and possibly other text boxes around QC. 

Also, ctrl+shift+V that strips any formatting before pasting in Windows doesn't work.

**Comment by ccbogel** [comment]
I don't have a fix for this.I can acknowledge it in the manual.

**Comment by glocalglocal** [comment]
A workaround is pasting formatted text into a plain text editor, and then copying it from there as plain text. Not very elegant but it does the job.
