### ISSUE TITLE
Bug: Can't type R, F if Shift+R or F controls playback

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#415]
Not sure why we didn't think of this before, but Shift+key controlling the player in transcription means you can't press Shift+R to type 'R' etc. Perhaps these could be ctrl+R, F.

**Comment by ccbogel** [comment]
Yes OK I now resolved.
Ctrl+R rewind 5 secs, Alt+F and Alt+R for 30 seconds
