### ISSUE TITLE
Req: Playback timer format 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#416]
When transcribing imv it would be better to display the timer next to the playback control buttons as hh:mm:ss / hh:mm:ss for consistency with the timer ctrl+T generates and most media players Currently, it's not immediately obvious how, say, 133.05 compares to 02:10:15.

**Comment by ccbogel** [comment]
done

**Comment by glocalglocal** [comment]
I am getting "ImportError: cannot import name 'msecs_to_hours_mins_secs' from 'helpers'". Could it be because I think the name is actually "msecs_to_hours_mins_and_secs"?

**Comment by ccbogel** [comment]
I just now uploaded those files again.
in helpers it is called

msecs_to_hours_mins_secs()

In view_av the import name matches.

if it happens again, after you download this, let me know.

________________________________

**Comment by glocalglocal** [comment]
It open now but when I open an mp3 in Manage I get: 

![qc](https://user-images.githubusercontent.com/16408198/115713742-e097c800-a365-11eb-8a60-362dc325ad3b.jpg)

**Comment by ccbogel** [comment]
That is actually fixed now. try downloading again.

**Comment by glocalglocal** [comment]
Working OK now.
