### ISSUE TITLE
Search in journals and export all journals to one file

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#418]
Hi,

Taking into account, that I extensively use the journals mode, I have two suggestons:

1) Is it possible to provide an option of exporting all journals to the one file, where above the each journal text will be corresponding title?

2) Is it possible to provide a search option in journal mode? Including the searching simulatneously in all journals? Taking into account, that after time there is a lot of meterials, it will be helpful to identify, in which journal you made specific notes.

Kind regards
Andrzej

**Comment by ccbogel** [comment]
I have done both of these now. I have tested, but just to be safe, make a backup copy of what you have.
