### ISSUE TITLE
Bug: minor tiding up 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#419]
Not serious, but slider tooltip in the transcription window refers to video only. It should also mention audio. If I remember correctly it was not possible to get the timer to update when you moved the slider, right? 

The location of 'Select an option...' on the Coding, Report, Manage tabs is different (different row and indentation).

**Comment by ccbogel** [comment]
Fixed the first issue. the second - I dont undersand what you mean.

**Comment by glocalglocal** [comment]
> I dont undersand what you mean.

Check the x and y relative position of 'Select...' below:

![qc1](https://user-images.githubusercontent.com/16408198/115163354-2d467f00-a098-11eb-9e79-091c19f29bd2.jpg)
![qc2](https://user-images.githubusercontent.com/16408198/115163355-2ddf1580-a098-11eb-8b0f-a8f5242505fe.jpg)
![qc3](https://user-images.githubusercontent.com/16408198/115163353-2cade880-a098-11eb-88b8-685740a9c872.jpg)

Both x and y in the Coding tab (or Reports and Manage tabs) are off.

**Comment by ccbogel** [comment]
updated in Develop branch.
