### ISSUE TITLE
"Overwrite" question

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#422]
When I exported the journal to the folder where was the previous version of this journal, the QC asked me "overwrite"? However, if you click "no", it will not export journal at all. I think that it could be unintuitive for many users, while in the other cases, softwares anyway save/export files but adding specific index (2), (3) etc.

So, maybe the information should state that "you cannot export journal without overwriting". And, such information should be also added to the other exporting options in QC.

**Comment by ccbogel** [comment]
Fixed, now when files are exported, and if there is an overwrite, then it adds an index,
