### ISSUE TITLE
Req: Find in texts

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#423]
As in #418, it would help to be able to have Find (and possibly replace) in transcribing. With very long texts, it can make a big difference. Find would be useful elsewhere (eg in Coding). 
 
Of course the beauty of plain text is that we can copy the whole text into a text editor, do what we have to do there, and paste the amended text back into QC (which is how I do spellchecking or strip special formatting) but it would be nice to have that built-in.

**Comment by ccbogel** [comment]
OK I have added find in the viewing the a/v with transcription via manage files.
I think it will clutter the AV coding window. so will leave that out for now.I might do a right click context menu, or key shortcut for that later.
I wont touch spellcheck for the forseeable future.

**Comment by glocalglocal** [comment]
> I wont touch spellcheck for the forseeable future.

For the record, I didn't suggest that spellchecking be added (although it will be nice to have at some point).

**Comment by ccbogel** [comment]
haha, its enough as is for now. its late here, so enough for today.
