### ISSUE TITLE
Req: Editing in coding and viewing

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#424]
I understand that we can edit text while coding and viewing but that is limited. Would it be possible to improve that to allow more extensive editing? This would save hours of work. 

Currently, I am working on very long interviews - 5000+ words each. I transcribe them in QC but before I start coding I have to proofread them. But I will read them very closely while coding anyway, so that extra step is a very substantial waste of time. I can see how adding/removing characters can mess up the offset in coding. If substantial editing is not possible for every part of the text in coding, perhaps it could be done only downwards in the first pass -- ie the part that is not coded yet. That would allow merging proofreading and coding as you go along, provided that you don't proofread coded sections.

**Comment by ccbogel** [comment]
In the develop branch, I have made it so that via Manage Files, a plain text file can be extensively edited even if it has been coded/annotated/assigned to a case. 
I have tested it but I would prefer further testing before adding to the Master branch, and also before adding the same functionality to the MangeFiles > A/V transcribing section. 

I am not sure of editing while coding for now. As I feel this functionality is still quite risky.

**Comment by glocalglocal** [comment]
This seems to work fine. Of course the real efficiency benefit is in editing while coding -- ie not having to leave coding, switch to Manage Files, edit the file and switch back to Code (not forgetting to refresh the display). But this is already an improvement because you are not trapped with a coded text you can't edit at all.

**Comment by ccbogel** [comment]
I have applied it to the transcription area to for coding A/V also.
I have added warnings not to select stretches of text that contain uncoded and coded text. If the text selection is overwritten or deleted the underlying codes and annotation positions will be wrecked. At the moment I do not know how to resolve this.

**Comment by ccbogel** [comment]
Now can edit text when coding text. You need to click on the text pane and then Ctrl+E to enter a text edit mode.
To exit press Ctrl+E again.
This loads the entire file, rather than file chunks.(if you were coding a really large file).

**Comment by ccbogel** [comment]
I will add information to the wiki manual about this feature.
Yes nothing else is available (again information on this added to the manual).

**Comment by glocalglocal** [comment]
I think I know the answer, but it would be great if everything else was displayed in greyscale or something. Then it's self-explanatory.

**Comment by ccbogel** [comment]
I think the best I can do is hide the side pane.

**Comment by glocalglocal** [comment]
It would be useful if the text in Edit view looked the same as in Coding 
-- ie fonts, line spacing, margins etc so that text won't be reflowed. 
Ideally, switching between coding and editing modes wouldn't cause 
scrolling to the top either. It is annoying when you want to add a word 
and you have to find your place in a long text that looks completely 
different too. Without Find it's even more time-consuming and disruptive.

**Comment by ccbogel** [comment]
fonts, line spacing, margins are not changed.
Resizing (hiding the left pane) would change the text flow. I have another solution to this to keep the shape. 
Yes, I have worked out how to go to the current text position.
