### ISSUE TITLE
A dark mode (lower priority)

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#426]
During the PhD classes I found out that Maxqda has dark mode (black background and white letters) and my lecturer appreciates it, whicle it is more convenient for his eyes furing long work. Maybe it is good idea to provide such a function in QC?

**Comment by ccbogel** [comment]
A work in progress. Download the latest code. Run QC then close it.
In the .qualcoder folder there is a file called config.ini 
open with a text editor. Then the last line shoud be:
stylesheet = 
change to stylesheet = gray
or stylesheet = black

This is a temporary test really.

**Comment by AndrzejWawa** [comment]
Hi,

I cannot find this file in the folder. I tried to use color in the code of the file "qualcoder.py", but it doesn't work.

**Comment by AndrzejWawa** [comment]
And actually one more think. A huge part of colors for code are quite dark, so, the dark letters are barely visible on them (in codebook, on the information on activated code, as well as coded text or context information about code and memos, when you move mouse on coded text. It is possible to provide white letters when they are on darkest colors? - I think that this is quite practical issue, for many (including me) maybe more important than the night mode.

**Comment by glocalglocal** [comment]
That would significantly increase the range of useful colours we can use, as we will then be able to pick very dark colours too.

**Comment by ccbogel** [comment]
I'm not keen for adding more colours. There's over 100 to choose from, a lot more than some qualitative programs. Yes some are too dark, I will see if I can fix the text display.
But first, to get this dark mode working.

**Comment by glocalglocal** [comment]
> There's over 100 to choose from

To clarify, when I said 'useful' colours I meant that if they are close, they are not useful. I ran into problems with a lot fewer colours than 100. The dark colours would allow spacing them out and the range will be more useful. Just making the point. Not all that concerned personally.

**Comment by AndrzejWawa** [comment]
I think that glocalglocal does not say about adding new colors, but only improve visibility of dark. When the visibility is worse, users tend to use only part of the colors which are already available.

**Comment by ccbogel** [comment]
yep I get it. I will do a little more work then stop for the night. The dark mode is coming along, but initially there will be a few issues with the white text on light codes. Until I sort it out.

**Comment by ccbogel** [comment]
@AndrzejWawa If you download the Develop branch, you can change to dark mode in Settings. (Then restart qualcoder)
There is still lots of work to do to make the text dark against light code colours.

**Comment by AndrzejWawa** [comment]
It looks very nice :)

**Comment by ccbogel** [comment]
should be all good now

**Comment by glocalglocal** [comment]
I must say this looks great! Much better than I thought and I may switch to that. Two issues: 

when a menu is selected (Project etc), the text becomes unreadable because of the colour combination (much worse than on screenshot below):

![image](https://user-images.githubusercontent.com/16408198/116242624-9fccf400-a755-11eb-883f-b0cab9f38690.png)

Similarly, the grey text in the button tooltips is almost unreadable: 

![image](https://user-images.githubusercontent.com/16408198/116243234-46b19000-a756-11eb-8be6-0764a8f550cd.png)

and in the overlapping codes menu (the mouse pointer is hovering over the second option below, so colours are better): 

![image](https://user-images.githubusercontent.com/16408198/116243648-ac9e1780-a756-11eb-9945-e426aec4e669.png)

Also, the selected code (top left) appears as white on black without highlighting:

![image](https://user-images.githubusercontent.com/16408198/116243726-c50e3200-a756-11eb-8910-3b16709fb498.png)

**Comment by glocalglocal** [comment]
And when I select one of the overlapping codes from the menu and the menu collapses, the colours there are gone -- the selected code appears as white on black.

**Comment by glocalglocal** [comment]
And here is another one from Show Coded files: ![image](https://user-images.githubusercontent.com/16408198/116246228-4ff02c00-a759-11eb-925b-0b23ef90c1b3.png)

The grey-ish font doesn't work against light colours. 

BTW, that '?' shows up in these two dialogues:

![image](https://user-images.githubusercontent.com/16408198/116246346-70b88180-a759-11eb-890c-719d178f680c.png)

**Comment by glocalglocal** [comment]
And here is another one: tooltip in Manage Files:

![image](https://user-images.githubusercontent.com/16408198/116248681-9777b780-a75b-11eb-8d5c-ccb13b960448.png)

Again it looks much worse on the actual screen.

**Comment by AndrzejWawa** [comment]
1. And when you want change the color of code, in the color selection window the selected color and already applied color is not displayed (the white font also is not displayed).

2. Moreover, I would suggest to change the colors of font to white for the colors in the codebook on the pictire.
![Colors to change](https://user-images.githubusercontent.com/77200214/116250859-6c4a9380-a76e-11eb-9221-92b872a2cafe.png)

**Comment by AndrzejWawa** [comment]
Moreover, the links and names in graph mode are still black.

**Comment by ccbogel** [comment]
Moreover, I would suggest to change the colors of font to white for the colors in the codebook on the pictire.
Can you open the color selector. take a screenshot and put a dot on the ones to change.
I have already changed some.

**Comment by glocalglocal** [comment]
Wouldn't this be an opportunity to space colours out more if darker colours can be used with white text? I supposed colours can't be too dark because they will have to work with the dark theme.

**Comment by ccbogel** [comment]
> Wouldn't this be an opportunity to space colours out more if darker colours can be used with white text? I supposed colours can't be too dark because they will have to work with the dark theme.

True, but to be honest, I don't feel like re-visiting this again. It was a lot of time and effort trying to get these colours together initially and then with a revisit some time ago.

**Comment by ccbogel** [comment]
OK dark mode is ok, I think most/all issues addressed now.
@AndrzejWawa create a new issue with the font color on the code background with suggestions for the colours to have light font. - as mentioned use a screenshot of the color selector and then indicate which.

**Comment by glocalglocal** [comment]
Colours 2, 3, 5 are selected below but the white asterisk often won't be visible: 

![image](https://user-images.githubusercontent.com/16408198/116411459-43d1a080-a825-11eb-9783-c94c26d0b0de.png)
