### ISSUE TITLE
No way to code image

### ISSUE THREAD

**Issue by griesfel** [ccbogel/QualCoder#43]
Hi there,
I'm interested in coding images (there are not many apps out there). After some issues in Windows, I got the app running in Ubuntu. I'm able to code and edit text, but no images... (I managed to add them and they are visible in the preview), but I always get the following error message when I try to edit or code images, although I added attributes as indicated in the instructions. Help is appreciated.
Cheers,
Alexander

Traceback (most recent call last):
  File "qualcoder.py", line 726, in image_coding
    ui = DialogCodeImage(self.settings, self.ui.textEdit)

  File "/home/user/Downloads/QualCoder-master/qualcoder/view_image.py", line 100, in __init__
    self.get_image_files()

  File "/home/user/Downloads/QualCoder-master/qualcoder/view_image.py", line 163, in get_image_files
    cur = self.app.conn.cursor()

AttributeError: 'dict' object has no attribute 'conn'

**Comment by ccbogel** [comment]
Hello Alexander,
Sorry, I made some changes over the last few days and did not upload all the files, my silly mistake. Download a new version from github - I have tested image coding it and it works for me.
Let me know how the image coding workflow suits you as it is possible to change the way it works for the better. Also look at pulling out reports once you have done some image coding.

On Windows:
No sure what issues you had on windows - once you have python3.x and vlc installed and the additional python modules are installed via command line:
python -m pip install pyqt5 lxml Pillow six ebooklib ply chardet click pikepdf pdfminer.six  
It should run then by double-clicking the qualcoder.py file (in windows 10 at least)
Later, when I purchase my own windows machine, I will try making an executable for windows.

regards Colin

**Comment by griesfel** [comment]
Hi there, 
I appreciate the quick reply. I installed the update. Now I can enter the coding image dialogue, but I'm unable to load image in the first place (manage files), see error message:

raceback (most recent call last):
  File "/home/user/Downloads/QualCoder-master/QualCoder-master/qualcoder/manage_files.py", line 431, in import_files
    self.load_media_reference("/images/" + filename)

  File "/home/user/Downloads/QualCoder-master/QualCoder-master/qualcoder/manage_files.py", line 460, in load_media_reference
    cur = self.app,conn.cursor()

NameError: name 'conn' is not defined


Sometimes I also get the "unknown file format" message, although I'm working with normal JPG/JPEG files.

Thanks again for the follow-up!

Cheers
Alexander

**Comment by ccbogel** [comment]
Thanks again, I fixed a typo: , instead of .
That's interesting regards the unknown format message. This would occur if you got an error on importing - such as occurred due to the above typo. Hopefully now the typo is fixed it will not occur.
