### ISSUE TITLE
Req: Compact appearance

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#430]
In coding, the minimum window width is 1149. Any narrower than that, buttons start becoming invisible. I think 1024 should be the absolute max required, and all assets should be visible in 840. Space can be saved by reconsidering layout and the size of buttons. Most buttons in different dialogues across QC are far too big by general toolbar standards, and there is a lot of white space that could be used for a more compact appearance. Eg I am not sure why the space below Coder: in Coding is not used. 

On height, the memo area in transcribing could be made collapsible -- I am not sure about others, but personally, I hardly ever use this and it just sits there taking up space.

**Comment by ccbogel** [comment]
In coding, the minimum window width is 1149. OK I have reduced this to 1024. Starting work on resizing buttons from 36x36 to 32x32. 
Resizing labels containing images requires more work though.

**Comment by glocalglocal** [comment]
Thanks. 32x32 will help, and further resizing will be better. Eg, that '?' in the coding and transcription dialogue, and that 'T' are massive for what they do!

**Comment by ccbogel** [comment]
OK I think fixed/improved generally.
In code text: the overlap bit: do you think is is necessary?
![pic_overlap](https://user-images.githubusercontent.com/5834638/116085881-9ce4eb80-a6e2-11eb-8177-5d632c1da12d.png)

**Comment by glocalglocal** [comment]
> In code text: the overlap bit: do you think is is necessary?

I wish it wasn't but I think being able in more complex cases to bring to the foreground a highlight that may be invisible is indispensable. Eg I am looking at a longish passage that is highlighted in three ways that don't match in length. It gives you a headache to try to figure out from the tooltip where each highlight starts and ends. 

But the function could be added to the right-click menu, which would declutter the toolbars. So, hovering would show the tooltip, and the right click menu would show 'x overlapping codes' with a submenu populated with the current drop-down menu options. 

Incidentally, once I select a highlight, I can't undo it -- ie if I select the unhighlighted (first) option from the menu, I can't go back to how the highlights looked (ie in the order first applied) before I selected one of the colours.

**Comment by ccbogel** [comment]
You know that you can click on the overlapping text, and press o to cycle through the overlapping codes

**Comment by glocalglocal** [comment]
A cleaner approach we discussed ages ago was to indicate the selected code and the applied code in the codes tree. Selecting one of the applied codes would bring it to the foreground. Because the tree is so colourful, arrows or some other character or feature (bold?) would probably be necessary. That would help declutter the toolbars -- Code and Overlapping codes would be removed. 

I can't remember why this was not pursued.

**Comment by glocalglocal** [comment]
> You know that you can click on the overlapping text, and press o to cycle through the overlapping codes

No I didn't it! Nice. Now I do, but it's not very obvious for new users. 
It's not working with certain segments though. I am looking at the passage I mentioned above (3 highlights of different lengths). It shows the second highlight as long as I press 'o' and reverts to the previous state when I release it. It never goes on to the third highlight. Elsewhere, even with 4 highlights, it works fine.

**Comment by ccbogel** [comment]
it might be due to overly sensitive detection of the key press.

**Comment by ccbogel** [comment]
compactness and smaller buttons implemented.

**Comment by glocalglocal** [comment]
> it might be due to overly sensitive detection of the key press.

It doesn't look like this at all. Eg I am looking at a sentence with 3 overlapping codes. B_1_name1, B_1_X5_name2, B_1_X6_name3. Every time I press O once it switches to B_1_X5_name2 for a fraction of second and immediately switches to B_1_X6_name3.  B_1_name1 is always skipped. I can select any of the three codes from the menu. It's only with O that I get this. Another sentence with 4 codes doesn't present this problem at all, ever.

**Comment by glocalglocal** [comment]
> I have added a not when hovering over overlapping codes, to press o to cycle through them.

nice. It shouldn't show when the user got QC to only show a selected code (ie using the next/previous arrows at the bottom). There are no more codes   to cycle through.
