### ISSUE TITLE
Bug: transcription now appears as mp3 file memo

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#434]
I see the memo pane in Transcribing disappeared (good imv), but my .mp3 files in Manage now acquired a Memo which contains the whole of the transcription texts, which is the same as the text in .transcribed. It looks like a bug, but I am not sure if it serves another purpose. 

A side-effect is that the long transcript appears in a huge tooltip for the mp3 file in Reports.

**Comment by ccbogel** [comment]
Thats an error, to fix asap.
