### ISSUE TITLE
Req: merge codes

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#437]
Thinking about codebook building as sometimes highly iterative, I think in addition to new, delete, rename and move code, there should also be 'merge codes'. Obviously, existing codings across files should be amended accordingly. 

I suppose this means that if snippet1+snippet2 (eg two adjacent or overlapping strings) are coded with code1 and code2 respectively, then when you merge the two codes into code3 it should apply to a single, longer snippet3 that contains both snippet1 and snippet2. 

There may be other essential ways to manipulate the codebook in analysis, but I can't think of any at the moment.  

EDIT: These should also apply to categories and subcategories. It should also be possible to move a (sub)category to another sub(category).

**Comment by ccbogel** [comment]
Currently you can merge a code into another code by dragging and dropping it. But this currently won't merge and extend the coded section length if the two codes overlapped.

**Comment by glocalglocal** [comment]
> I feel this could be a bit problematic. Does other software do this?

I am not sure how other software does this. I can think of situations where keeping codings with the same merged code separate is preferred, and other situations where codings would rather be merged. Others may want to comment.

**Comment by ccbogel** [comment]
I think the best option might be to report on it. and then let the user do the hard work or unmarking and remarking coded sections - when it is required

**Comment by glocalglocal** [comment]
So, will overlapping fragments coded with the same merged code be displayed as overlapping (ie in italics with overline)? Odd, but otherwise users won't know they need to unmark/remark a fragment.

**Comment by ccbogel** [comment]
I wonder how other software handles this?

**Comment by glocalglocal** [comment]
Apparently. Nvivo merges both codes and codings: 

https://forums.nvivobyqsr.com/topic/1909-merge-codes/

**Comment by ccbogel** [comment]
From that link and the nvivo response, no it does not merge codes in the way you want. it merges into the node (code) name, but does not link and expand any overlapping coded sections.

**Comment by glocalglocal** [comment]
I re-read the page and you are right. I looked around and can't find a definitive answer. To check myself I will have to re-activate NVivo and I'd rather not do it. Users of other software may be able to comment. It seems to me that either codings will have to be merged too, or if they are kept separate they will have to be indicated as overlapping fragments (in italics, with O cycling etc). 
Looking at this: 
https://study.sagepub.com/jackson3e/student-resources/videos/top-tips-videos/merging-and-aggregating-nodes

and this: 

https://help-nv11.qsrinternational.com/desktop/procedures/reorder_and_refine_nodes.htm 

reminded me that Count in Coding could (imv should) show aggregate scores.

**Comment by ccbogel** [comment]
> if they are kept separate they will have to be indicated as overlapping fragments (in italics, with O cycling etc).
This occurs currently. So this is the approach I will use.
And open another issue - the ability to Merge the contents/tree structure of one category into another.

**Comment by glocalglocal** [comment]
Out of interest, if two codings overlap 100%, will we still get the same fragment coded twice with the same code? And then will the pop-up show the same code/coding twice and will O switch between two identical codings? I think most users would consider that a bug.

**Comment by AndrzejWawa** [comment]
As I see, you cannot do this. The same fragment (in 100%), can be coded only by one code. Previously, there was even warning that this segment was already coded by this code or sth, not there is no information.

**Comment by glocalglocal** [comment]
@AndrzejWawa you are right. Now I am confused. With partial overlap I am getting this: 

![image](https://user-images.githubusercontent.com/16408198/118182371-720bce80-b428-11eb-9952-5a8f9e436c54.png)

Does this means that if there are overlapping fragments coded with code1 and code2 anywhere in one of the files, then the codes can't be merged? And then do you have to look for possibly a single instance where this happens in one of many files?

**Comment by ccbogel** [comment]
> if two codings overlap 100%, will we still get the same fragment coded twice with the same code?
This cannot happen (is does with RQDA). I have made database constrained to the same segment coded by the same coder with the same code is rejected.
