### ISSUE TITLE
Bug: VIEW in exported reports & font size

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#439]
Exported reports should not include [VIEW]. 

The font size in exported reports (at least in html that I tested) doesn't follow the size specified in Settings.

**Comment by ccbogel** [comment]
I wont change font size in html reports.
Yes will try and remove [VIEW]

p.s. I am looking at another way to [view] in the table results also.

**Comment by glocalglocal** [comment]
> I wont change font size in html reports.
I suppose we can change the font size in the application we use to display the exported report, so it's not a problem.  

> p.s. I am looking at another way to [view] in the table results also.
That would be great
