### ISSUE TITLE
Updating transcripts once coding and annotations have commenced

### ISSUE THREAD

**Issue by zackbatist** [ccbogel/QualCoder#44]
One thing that would be nice is the ability to update a transcript after coding has already commenced. Sometimes I realize that I transcribed a word incorrectly, made minor spelling mistakes, or want to alternate between transcribing and coding a day's worth of footage contained within the same file. I get the following error when adding new text to the transcript in the Manage Files window:
`Cannot edit file text, there are codes, cases or annotations linked to this file`.

**Comment by ccbogel** [comment]
Hi Zack, yes I did this deliberately as updating all the text positions within all the relevant coding tables will be a substantial challenge. As I need to know not only how many additional (or subtracted characters) there are, but also their exact positions within the document. If in majority of cases it is minor changes then it will be more manageable.
I will put it on a todo list and consider options.
ps - did you mange to get the aspect ratio working as you wanted - I saw you added some lines in your fork?
ps2 - in general is the software doing as you wanted?

**Comment by zackbatist** [comment]
I gave this a bit of thought and some ideas come to mind for how we might implement this. After toggling on an editing mode, a system is initiated that tracks diffs instead of the whole sets of characters in the document. So once toggled on codings are hidden and users are free to edit text as they see fit. As a user edits, the position of diffs are noted, the kinds of diffs are identified (either addition or subtraction), the number of characters in each diff are calculated, and the content to be added or subtracted for each one is recorded. Then when the user hits save or toggles out of edit mode, the diffs are implemented in their respective positions, and the codings are shifted left or right based on the number of characters in the diff and their positions relative to the positions of the diffs. So for each coding, the number of diffs to its left are determined, a net number of characters to shift is calculated by summing all of those diffs to the left of the coding, and each coding's start and end position are shifted left or right according to the net amount of characters. If the diff begins within the range of a coding's characters, then the length of the coding is also extended to complement this change.

Regarding aspect ratios, I took a look at the code, figured out the logic you're using for file management and media playback, and looked at the vlc python wrapper. I tried out a few things but I have little experience with python and got a bit overwhelmed by other obligations. QualCoder seems to adjust fine to different aspect ratios by default, I think that my videos are just strangely assembled, so the problem is on my end. My videos are composites of three horizontally aligned 1280x720 videos (so 3840x720) with some 'natively' formatted title segments slotted in at various points, and although I re-encoded them I'm missing something in the way that I've configured my video processing workflow. So instead of fretting and wasting time re-encoding videos for the rest of my natural life I've decided to use excel to note start and end positions and notes for those segments, determine where those are situated in each of the original videos that make up the composite, and memo the original videos. It's a workaround that has exposed some limitations of my approach, and I'm generally satisfied with it (i.e. syncing is not exact so it's better to code each original video on its own rather than the composite). I'm transitioning to memoing within QualCoder without using excel as an intermediary (I copy the memos to QualCoder from excel based on the start and end times), but it's easier with some videos than with others. Coding, which is less free-form than my current memoing stage, will be done entirely in QualCoder, after I've narrowed down to a more accessible dataset via memoing. So in general, it's working out nicely, as a great component of a broader approach and set of tools. Sorry for the lack of updates about all this.

**Comment by ccbogel** [comment]
Hi again. thanks for the feedback. 
Yes I agree that an edit mode can be enacted. I have begun some work on this - my approach is perhaps not perfect - but I think will work. 
The text will be made read only if any codings or annotations are in place. To edit - highlight the word(s) that need to be edited and right click on a context menu to do the editing in an edit dialog. This will allow an easy approach to detect changes in characters and positions. As it is important that only one spot is edited at a time - to ensure character positions are easily tracked.

**Comment by zackbatist** [comment]
That sounds like a very sensible solution.

**Comment by ccbogel** [comment]
OK I have made some changes so that editing after coding is performed can be done. I have tested it somewhat, but I cannot be 100% certain it will be perfect. Restrict its use mainly to fixing small spelling errors.
To use: Open the manage files dialog and select the file. Then select up to 20 characters in the text and right click to open an edit dialog. Make the changes and then click OK.
Apart from this change, I also made some other changes in the way the settings variable is used across the dialogs - again I have tested somewhat, but if any errors please let me know.

**Comment by qwertygc** [comment]
I agree, it's a good idea to fix it.

**Comment by ccbogel** [comment]
Closing this issue as no feedback for a month. Current implementation appears to work.
