### ISSUE TITLE
Bug: Can't select snippets in Report

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#441]
In the middle pane in Report, when I try to select snippets by clicking and dragging, the context text dialogue pops up the moment I cross the clickable [VIEW] area of a snippet.

**Comment by ccbogel** [comment]
OK. Now use right click and 'view in context menu option'

**Comment by glocalglocal** [comment]
> However, you must left-click on the spot that you want to view first.

That could be confusing but we may have to live with it. 

Copy and Select All disappeared from the menu in this pane. Also, the same menu appears in areas where View in context is not applicable (eg the info at the top). 

Also, the context dialogue title bar now shows the Case info rather than the File info. And the '?' is still there. Incidentally, it would be better if the highlighted snippet didn't appear at the very bottom of that window. 

In the context dialogue and in the right Report pane (and possibly elsewhere) Copy is available even if nothing is selected. The standard behaviour is that it appears only when there is something to copy. Now I can select nothing, click on copy, paste in another application, and of course nothing is pasted.

**Comment by ccbogel** [comment]
Copy and Select All disappeared from the menu in this pane. - Yes I have to add those back in, as the new menu overrides the original one.

Case info - yes - if you have selected cases as a part of the search - then the case name and the file name will be shown , unless the case name is very long in which case only that will be shown in the title bar.

? - hope resolved now.

 Now I can select nothing, click on copy, paste in another application, and of course nothing is pasted. Yes that is the standard behaviour in the Qt framework. I wont change this as it is extra work for little gain

**Comment by ccbogel** [comment]
Ctrl + A does select all. should it be a menu option?

**Comment by glocalglocal** [comment]
In case this was missed, 'View in Context' is still available in areas where it it is not relevant (introductory text and coding text).  

I must say having to left-click first before selecting 'View in context' goes completely against many yeas of muscle memory. And I am sure many people won't figure out why it's not working for them. 

Copy/Select all in the right pane menu is displayed in bigger font than the menu in the middle pane and every other menu in QC.

**Comment by AndrzejWawa** [comment]
Hmmm,

Yes, this left-clicking is unintuitive. The "[VIEW]" place was very good. Maybe it is chance to resolve the problem maintaining this option?

**Comment by ccbogel** [comment]
ok fixed now.
right click on the relevant heading to open that coded section in context.

**Comment by glocalglocal** [comment]
Not working here. For 10 out of 11 snippets nothing happens. Only the 2nd snippets works and I am shown the context for the 5th. 

And confusingly, View in Context shows every time I open the menu, even in areas where View in Context is not applicable.

**Comment by AndrzejWawa** [comment]
Have you right-clicked on the coloured part every time?

**Comment by glocalglocal** [comment]
> Have you right-clicked on the coloured part every time?

Yes, and now I started the report all over again a couple of times and it is working fine! (*)
 
However, there may be something wrong going on anyway. The first time I re-started the report, all the snippets listed were displayed against the same light (green I think) rather than black background. The relevant code was correctly coloured. This is very odd, never seen it before, and I can't imagine in what circumstances this would even be possible. 

(*) Except that View in Context is available everywhere inculding the intro header.
