### ISSUE TITLE
Req: Indicating the more important codings

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#442]
With a lot of data, codes, cases etc, reports are likely to produce too many snippets. As we code along, I am sure we all know certain snippets are more important and more likely to be used in writing a paper, but the rest of the codings must also be there for completeness. 

It would be useful to be able also to get Reports with just the important codings. We can now do that manually by exporting all codings as normal and then re-coding the report, which is not practical or efficient. 

QC could help by allowing the user to create a special code for important snippets. That would be represented in coding with a distinctive colour, bold font or some other feature. More importantly, Report would offer a choice between (a) all codings and (b) important codings only. Currently, Reports applies OR to selected codes. (b) would be equivalent to: 

(code1 OR code2 OR code3...) AND important_code

I think this would be more than just a simple improvement. It would help tremendously with workflows.

**Comment by AndrzejWawa** [comment]
Hi,

You mean that you have code named e.g. "tree" and code different fragments, but some fragments have the status "important" other "not important"?

I am planning do sth similar, namely code legal acts on business taking into account different aspects, e.g. goal of business, organizational structure, benefits, salaries ect., however, each code will have certain status on the scale 1-5 ("clearly degrowth", "rather degrowth", "neutral", "rather growth", "clearly growth").

However, I noted that in QC there is not something as attribute of the codings, so I planned to create 5 collection of codes grouped in the 5 categories. 

However, maybe the creation of attributes to codings is a good idea, however, perhaps needs a reflaction how to do this correctly. My initiall ideas is that after make a coding, if you after this click a number on keyboard from 1 to 0, it will attach this number as the attribute to codings. So, to all coding you want to mark as important, you would click 1 on keyboard. And then, in the report mode, there will be new option to use only codings with certain attributes.

**Comment by ccbogel** [comment]
Hmm OK. Good  idea. and already I am swamped with things to fix and update.

**Comment by glocalglocal** [comment]
@AndrzejWawa I can see how this more complex scenario could benefit from attributes. What I had in mind is a lot simpler but could be part of what you described as long as 'important' codings are also visible in Coding Text.

As it is often the case, because QC is so open and text only, I can already sort of do what I suggested but my way is not very elegant and won't work for everyone. I use markdown for my interview transcripts. So, in Reports I can get QC to show codings for code A and use '**' (for bold in markdown) or '==' (for highlight in markdown) as Text Limiter. That will return only codings with bold or highlighted text in it. 

But if QC could include an 'important' flag to codings, it would be a lot more elegant in Reports.

**Comment by AndrzejWawa** [comment]
> Hmm OK. Good idea. and already I am swamped with things to fix and update.

Hahaha, I also think that these attributes are not the priority, so, I did not mention them before :)

**Comment by ccbogel** [comment]
I could implement and easier approach (no attributes as such) but to mark a coding as important or not. In the same way when you add a memo to a code - via the right mouse click.
This will require an adjustment to the database tables , but should be ok as it is only adding a column.

**Comment by glocalglocal** [comment]
Yes, an importance flag would be great and would really save a lot of time in preparing a research paper. The flagged text would have to be indicated in the Coding Text dialogue and removable if the user decides to remove the flag.

**Comment by ccbogel** [comment]
Currently you can assign an Important flag to a coded section using the mouse right-click menu. A hover tooltip shows whether the section is Important or not. You can also select Important flagged coded sections in the Codes report.
I have more work underway on this, I plan to add a button with all the other buttons under the codes tree, that when click will show only the codes flagged as important.
It is at least somewhat functional for now.

**Comment by glocalglocal** [comment]
This is great! Many thanks for adding this. When I select a section where codings overlap I get a dialogue asking me to pick the code for the 'memo'. The wording could be adapted. Also, it would be useful to be able to select multiple codes for the flag (and possibly the memos).

I know you are running out of ways to indicate the many characteristics of fragments in Coding, so the on/off switch you suggest may be the way forward. An alternative would be bold. 

In Coding reports, should a report already displayed with the flag off be automatically updated when you switch the flag on without having to click on Search? Similarly when changing any other parameters that would affect the report.

**Comment by ccbogel** [comment]
Yes bold is possible. I use that for annotations to text also. 
Apply to multiple codes at once - I don think i can do this.
Regards coding reports - I like the way it works now, that you have to actually click the button to get the results. Also, results can take some time to generate.

**Comment by ccbogel** [comment]
I think is is ok now. You right click on a coded section to add/remove the Important flag.
You can restrict results in Report Codes based on this flag.
You can toggle a star button to show all codings or important codings.

**Comment by glocalglocal** [comment]
This works well. Great! Why not use the same star in Reports instead of the tick-box? And imv 'important flag' is ambiguous. It could be 'importance flag' or avoided as in: (Un)Mark as important / Show important codings.

**Comment by ccbogel** [comment]
the tick box is easy to implement. 
I will update the wording on the important flag

**Comment by AndrzejWawa** [comment]
This important star is very nice! Maybe important codings can be bold while annotations underlined? I think that it could be better for both. Bolded codings will be better visible, even without clicling important star, so, it will be easy review the material, while the underlined annotations will be better visible than bolded, I think - especially in dark mode.

**Comment by glocalglocal** [comment]
I agree. I think it is only natural that important segments stand out in the way readers underline, highhlight etc text as they go along. In Coding the star button would still be relevant as it would reveal how the bold fragments are coded where there are multiple codes applied.

**Comment by ccbogel** [comment]
The underlining is a problem. as the underline colour matches the text colour. this will depend on which code is selected and will be visible or invisible , against the background (if dark or light).
I cam make the important coded bit bold it you all prefer.
