### ISSUE TITLE
Req: Removing bookmarks

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#444]
I am trying to remove a bookmark from a text in coding. This may be already possible but I can't find it.

**Comment by AndrzejWawa** [comment]
Is it needed? I know that the old bookmark is delted when new one is introduced, however, I am not sure if the delete option make sense here.

**Comment by glocalglocal** [comment]
Can there be only one bookmark? If setting a new bookmark replaces the previous one, I agree there is no need to delete it.

**Comment by ccbogel** [comment]
There is only one book mark. and it is replaced with a new one.
