### ISSUE TITLE
Change of the font colors

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#445]
Hi,

I suggest to change the colors of font to white for the crossed colors, also with the circles, in light as well as dark mode . However, I am not sure for all changes, especially in circles. So, there will be needed test.
![Colors to change 2](https://user-images.githubusercontent.com/77200214/116461963-33dbb000-a869-11eb-8e58-15f31761f8f5.png)

**Comment by ccbogel** [comment]
OK I have updated. Also I have added a tooltip on the new-colour label
It gives the Hex colour value. This will be useful for stating which code colours - for light or dark text

**Comment by glocalglocal** [comment]
I can see the changes in color_selector.py but the Colour Selector looks unchanged.

**Comment by ccbogel** [comment]
Yes, the color selector should look unchanged. Except when you mouse hover over the new colour label at the top. I added a tooltip that shows the hex colour code

**Comment by glocalglocal** [comment]
Wasn't the asterisk supposed to be black or white depending on the background colour? With the black theme all asterisks are white, so some are not visible at all. 
Also, the hex code doesn't show here. 

BTW, wouldn't it be more useful if something bigger, eg A or ABC was used instead if a small asterisk? It would give a better sense of what the combination would look like.

**Comment by AndrzejWawa** [comment]
Hi,

Seems to be ok, only:

I think that 3 blue colors below should be black in dark mode,
In ligh mode, the blue color in circle should be black.

**Comment by ccbogel** [comment]
I think that 3 blue colors below should be black in dark mode,
In ligh mode, the blue color in circle should be black.

I wont change these settings based on the light or dark mode. That will be too complex.
but I can set it as dard on that code colour or light on the code color only.
I have added the hex code in the Second Label down from the top of the window, temporarily so I can see which hex code needs to change - when you msg me on this.

**Comment by AndrzejWawa** [comment]
Ok, so only blue one within circle could have dark font in both modes.

**Comment by AndrzejWawa** [comment]
And this pink color, selected, to black font I think.

![Colors to change](https://user-images.githubusercontent.com/77200214/116784946-44716d80-aa97-11eb-94e5-2a42c89942aa.png)

**Comment by glocalglocal** [comment]
Shouldn't every single box specify the background _and_ foreground colour? Ie shouldn't every one of the boxes show something like an A, a string or whatever in black or white depending on what works with the specific background? A string in lower case would show what the combination looks like more realistically. The theme is irrelevant then. The selected boxes would still show an asterisk or whatever as indicator. 

I still don't see the hex value.

**Comment by ccbogel** [comment]
@glocalglocal there's no need for every box to show the font color,as on selection it is shown up top.
The hex code which I will keep temporarily for now, is on hover over the second from top label

**Comment by ccbogel** [comment]
OK the pink and blue have been changed. closing now.

**Comment by glocalglocal** [comment]
The selected colour in the grid is shown as blue with a dotted frame. Imv the dotted frame alone might not stand out immediately but it would prevent UI inconsistency. Ideally, there would be some other way to indicate the selected box, but I am not sure what is possible.
