### ISSUE TITLE
"Folders" (categories) for files

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#446]
Hi,

It is possible to create categories, named as "folders" to avoid confusion, for files? They could work exactly as the categories for codes, and be acailable in the manage file window and, especially, in the list of files in the code text/image/video modes.

When someone have a lot of files (as me), it will be easier to have categories them and not scroll through the all.

Kind regards
Andrzej

**Comment by ccbogel** [comment]
What I could do is: Perhaps add a button underneath (with the other buttons) which opens a selection dialog.
In here you can select a file attribute to show only files with a particular attribute.

**Comment by ilippert** [comment]
Lovely point, I was thinking of this issue with two questions:
- could the columns in the files dialog be sortable (alphabetically or numerically)?
- could the columns be filterable?

**Comment by ilippert** [comment]
In the coding view, I am shown the files. That is great. Here, too, it would be amazing, if I could filter the files/show a folder/group/selection of the files. 
This kind of interest matters as soon as I have more than say 15 files of which the file names are not systematised (in my ethnographic research, files keep the names of their "natural" setting, and so names are very idiosyncratic).

**Comment by AndrzejWawa** [comment]
> What I could do is: Perhaps add a button underneath (with the other buttons) which opens a selection dialog.
> In here you can select a file attribute to show only files with a particular attribute.

Yes, it is even better than folders. Is it possible to implement this also in the coding mode?

**Comment by ccbogel** [comment]
> Yes, it is even better than folders. Is it possible to implement this also in the coding mode?

Yes. I am working on this. The Graphical elements are in place now. I need to work on the code to select the files based on attributes.

**Comment by ccbogel** [comment]
@ilippert 
    could the columns in the files dialog be sortable - instead of (or in addition to) using the contextual mouse click?
    could the columns be filterable?
Do you mean in the Manage Files files dialog ?
As yes this happens now, right click on the file names, or to sort and filer by attributes, right click on the file attributes

**Comment by AndrzejWawa** [comment]
Works very well. If you do not specify the operator in filtering files in the codings mode, the window with warning will appear two times, not one.

**Comment by AndrzejWawa** [comment]
And maybe this filtering window with logical operators from coding mode could be also implemented in the file management mode? However, it is only loose idea, if it is not difficult to implement. For me, the most important was filtering in coding mode. Now. it is wonderful : )

**Comment by ccbogel** [comment]
OK, I will close this current issue.
In file management - that would be another issue to open.
