### ISSUE TITLE
Two correction to cases

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#447]
When you open the manage cases window, on the right hand you have window displaying files of cases.

1) firstly, for the dark mode the font for all should be white (sometimes is blue, e.g. for names of images) and for light - black,
2) secondly, when you have the name of the image, by clicling it, image should be opened. It works properly when you open the window with files list, but not, when ti comes to this window on the righ, which is immediately available when you enter manage cases mode.

I am not using this part of software but noted, so let you know : )

**Comment by ccbogel** [comment]
1. I have updated. I still use blue (as a link), but it is clear on black or white
2. A tooltip tells the user to right-click to view the image or a/v file
Not sure what you mean here: "It works properly when you open the window with files list, but not, when ti comes to this window on the right"

Will close issue for now, as I feel it addresses the concerns

**Comment by glocalglocal** [comment]
The header: 'File: filename Text: 0:10915':

(a) really doesn't stand out at all and takes some effort to spot the beginning of the next document. In addition to making this stand out, there could even be next/previous buttons. 
(b) that '0:10915' doesn't help much. At the very least it could be something like '10915 characters'. Before the first one there could be a 'Total for selected case: x characters'. 

Also, the 'AV media: ...' header is practically invisible on my screen in the black theme. Some other colour would work better against both white and black. 

The font size of Select All/ Copy is tiny. 

This is the kind of dialogue where Search is almost essential.

**Comment by ccbogel** [comment]
I have made some changes. differnt blue
The small font i nthe menu is a default , wont work on this now
