### ISSUE TITLE
contextual help (case of transcribing a video)

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#448]
**Is your feature request related to a problem? Please describe.**
I am transcribing a video. It is the second or third time I do it, but I am not working every day with the software. Now I miss a link to the help page on the video playback window - how to transcribe the video? 

**Describe the solution you'd like**
In this window (maybe later in others, too), offer a help icon (one for the window) or alternatively a tooltip function for the various buttons and fields, or a contextual help click with a link that gets me to an html anchor of an online help.

**Describe alternatives you've considered**
Remind myself, before I start using the software, open the help pdf

**Comment by ilippert** [comment]
Now, if a contextual help is enabled, with an online help doc html based, that could be done within github and users who cannot programme, might be able to help editing the help pages.

**Comment by ccbogel** [comment]
Great idea. I have added a help button in several windows now. 
It links to the github qualcoder wiki page
