### ISSUE TITLE
Transcribing video: missing update of time code

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#450]
**Is your feature request related to a problem? Please describe.**
Whilst navigating in a video file within the video view window, I can use the slider at the top to navigate to another point in time. I am sad I cannot easily see at what time code the slider is then set. The timecode field (next to the clock) is not updated.

**Describe the solution you'd like**
When I have move the slider, update the time code next to the clock.

**Describe alternatives you've considered**
Or on the slider itself a popup might indicate the time position indicated by the slider position.

**Comment by ccbogel** [comment]
OK I have fixed this.
The only time is does not work correctly, is in the Manage Files View a/v. Moving the slider **before** the a/v has been played, it does not give me the correct milliseconds value.
