### ISSUE TITLE
Manage files: missing info on cases

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#451]
**Is your feature request related to a problem? Please describe.**
When I view the files, I would love to see at one glance, to which case each file belongs. Would also be good to be able to order the files by case.

**Describe the solution you'd like**
Allow for an optional column that shows which case a file belongs, too. It might even allow editing, providing for each file in its case field a dropdown menu of the available (or new?) cases.

**Comment by ccbogel** [comment]
When you hover over the filename, any linked case(s) will be displayed in the tooltip
