### ISSUE TITLE
Bug: QualCoder_Manual duplication 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#454]
The master download contains two different QualCoder_Manual.pdf files. The one in qualcoder\GUI\ is shorter. 

A fifth of the installation on disk is taken by QualCoder_Manual.odt. Is it necessary?

**Comment by ccbogel** [comment]
I an considering removing the odt and pdf files. 
Instead will make use only of the github wiki

**Comment by WPFilmmaker** [comment]
You mean removing the pdf  manual from QualCoder? Please consider those who do not have access to internet or not always. QualCoder works offline so IMHO internet shouldn't be required to access how to use it.

**Comment by ccbogel** [comment]
@WPFilmmaker yes ok - for now. I will have to look at a way of making an offline manual from the online wiki.
Having the wiki and the other files means duplication of work.
@glocalglocal Yes the odt file need to be here while I still have to generate pdf files
