### ISSUE TITLE
Bug: one code, two colours 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#455]
In Change code colour, there are currently two colours assigned to the same code. I am not sure how this is even possible, or how to remove one of the two and which. It's not immediately obvious which one QC actually uses because they are so close.

**Comment by ccbogel** [comment]
tooltips added

**Comment by glocalglocal** [comment]
Not sure what you mean, but I think I know what is happening. My Code1 is associated with two colours in Colour Selector, box 2 and 3. I didn't know how it was even possible but now I see these two boxes in the QC palette are for the same colour: #F2F5A9 which apparently causes some sort of cross-linking.
