### ISSUE TITLE
Req: Categories in Code Summary Report 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#456]
In Code Summary Report, selecting the code category would better show the stats for the category. If this is not desired, at least the stats of the code selected previously should be removed to avoid confusion. Currently, you can select a code, see the stats for it, then select a category, and the stats for the previous code will still be displayed.

**Comment by ccbogel** [comment]
done

**Comment by glocalglocal** [comment]
I take it you mean the latter is done and selecting a category won't show the stats for the category. If that was the intention, I can confirm deleting the code stats is working.
