### ISSUE TITLE
dependency not detected

### ISSUE THREAD

**Issue by barichello** [ccbogel/QualCoder#457]
I am not sure this is a bug, but I think it is worth pointing out:
I installed Qualcoder on my KDE Neon 5.21 (based on Ubuntu) via .deb file and there was one dependency that was not detected during instalation: python3-pdfminer

Once I installed it, the software worked brilliantly!

PS: thanks for it! I am still getting used to it, but I am loving it so far :-)

**Comment by ccbogel** [comment]
Thank you, updated now :)
