### ISSUE TITLE
Qualcoder does not start after a fixed installation with unmet depedencies

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#46]
I installd the latest deb file, however several depedencies were unmet, I fixed it in terminal and the following additional packages were installed:
  libaribb24-0 libbasicusageenvironment1 libdvbpsi10 libebml4v5 libgles2
  libgroupsock8 liblivemedia62 libmatroska6v5 libmicrodns0 libnfs11
  libopenmpt-modplug1 libplacebo4 libprotobuf-lite10 libproxy-tools
  libqt5designer5 libqt5help5 libqt5sql5 libqt5sql5-sqlite libqt5test5
  libresid-builder0c2a libsidplay2 libssh2-1 libupnp6 libusageenvironment3
  libvlc-bin libvlc5 libvlccore9 libxcb-xv0 python3-bs4 python3-html5lib
  python3-lxml python3-pyqt5 python3-sip python3-webencodings qpdf vlc vlc-bin
  vlc-data vlc-l10n vlc-plugin-base vlc-plugin-notify vlc-plugin-qt
  vlc-plugin-samba vlc-plugin-skins2 vlc-plugin-video-output
  vlc-plugin-video-splitter vlc-plugin-visualization

However when i try to run qualcoder from the menu nothing happens. Any idea?
I am on lubuntu 18.04

Edit: from terminal  I get:
Traceback (most recent call last):
  File "qualcoder.py", line 39, in <module>
    import configparser
ImportError: No module named configparser

**Comment by ccbogel** [comment]
It looks like another unmet dependency. Lubuntu is a lightweight Ubuntu and does not have as many things installed, which is possibly why there seems to be more problems than Ubuntu or Linux Mint. It will not run past line 39 until the error is fixed.

Try in the terminal:
`pip install configparser`

There is one more import (on line 40) that you might need, if you get another error:
'pip install click'

**Comment by WPFilmmaker** [comment]
Thanks @ccbogel ! I installed what you said, but I get:

Traceback (most recent call last):
  File "qualcoder.py", line 42, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: No module named PyQt5


Howevever when I try to install PyQt5 I get:

python3-pyqt5 is already the newest version (5.10.1+dfsg-1ubuntu2).
python3-pyqt5 set to manually installed.

**Comment by ccbogel** [comment]
hmm thats interesting. It might be that you have multiple versions of python installed, and pyqt5 is in one of those versions but not in the version that is running QualCoder. Try this command as it might install pyqt5 into another recognised place:
sudo pip3 install PyQt5

**Comment by WPFilmmaker** [comment]
@ccbogel It seems that PyQt5 is already there, I get:
Requirement already satisfied: PyQt5 in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: PyQt5_sip<13,>=4.19.19 in /usr/local/lib/python3.6/dist-packages (from PyQt5)

**Comment by ccbogel** [comment]
At the moment I am at a loss. Can you run QualCoder from the terminal, by moving to the directory containing qualcoder.py and start it using:

` python3 qualcoder.py`

Can you open a terminal and go into python by typing: 

`python3`

Then try and import PyQt5 by typing:

`from PyQt5 import *`

You should get no errors from the import.

**Comment by WPFilmmaker** [comment]
@ccbogel 

I tried what you said:

WP@WPPavilion-Notebook:~$ cd /usr/share/qualcoder
WP@WPPavilion-Notebook:/usr/share/qualcoder$  python3 qualcoder.py
Traceback (most recent call last):
  File "qualcoder.py", line 41, in <module>
    import click
ModuleNotFoundError: No module named 'click'

And:
WP@WPPavilion-Notebook:/usr/share/qualcoder$ python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>  from PyQt5 import *
  File "<stdin>", line 1
    from PyQt5 import *
    ^
IndentationError: unexpected indent
>>>

**Comment by ccbogel** [comment]
Hi,
Click was added by another developer - I am not sure it is really needed, so if it causes further issues I might remove it.

For the first issue in the terminal, click needs to be installed:
`sudo apt install python3-click` 

For the second issue - there should be no spaces or tabs in front of that import statement - or an indentation error occurs. Try it again and if no errors thats OK. If there is an importation error you would also need to do (even though this was done before?):
`sudo apt install python3-pyqt5`

**Comment by WPFilmmaker** [comment]
@ccbogel I installed python3-click (python3-pyqt5 was already installed), however now I get:
Traceback (most recent call last):
  File "qualcoder.py", line 65, in <module>
    from .settings import DialogSettings
ModuleNotFoundError: No module named '__main__.settings'; '__main__' is not a package

**Comment by ccbogel** [comment]
Thanks, this  makes sense to me. 

This line `from .settings import DialogSettings` is not in the current code in the qualcoder repository [https://github.com/ccbogel/QualCoder](https://github.com/ccbogel/QualCoder) so you must have an older downloaded version of the code which contained something called relative imports that another developer had added. I have now removed these (about approx 1 month ago). 

If this occurred through using the deb file I will make another one, but I thought I had already sorted this issue of relative imports out, before creating the deb file.

The current correct line on line 44 in qualcoder.py is `from settings import DialogSettings`

**Comment by WPFilmmaker** [comment]
@ccbogel as far as I remember I downloaded the .deb file.
So to fix the issue do you suggest just to redownload the .deb file and try again?

**Comment by ccbogel** [comment]
@WPFilmmaker  I made another deb package qualcoder.15.deb  - I think I did not correctly put the rules in the deb file to download all the required imports. I also updated the qualcoder.py file so hopefully the above error does not occur.

**Comment by WPFilmmaker** [comment]
@ccbogel I installed the new deb with _dpkg -i my.deb_ (Lubuntu seems to have a bug in gdebi where when you click on it the installer closes itself so you have to use terminal), and had to install python3-ebooklib python3-ply as they were required.

However now I get:
/usr/share/qualcoder$  python3 qualcoder.py
Traceback (most recent call last):
  File "qualcoder.py", line 53, in <module>
    from manage_files import DialogManageFiles
  File "/usr/share/qualcoder/manage_files.py", line 40, in <module>
    from pdfminer.pdfpage import PDFPage
ModuleNotFoundError: No module named 'pdfminer'

**Comment by ccbogel** [comment]
OK try this command:
`sudo pip install pdfminer.six`
I am also doing a minor update to the debian 1. too.

**Comment by WPFilmmaker** [comment]
@ccbogel I installed pdfminersix (when I try to reinstall i get:)
Requirement already satisfied: pdfminer.six in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from pdfminer.six)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python2.7/dist-packages (from pdfminer.six)
Requirement already satisfied: pycryptodome in /usr/local/lib/python2.7/dist-packages (from pdfminer.six)

However launching qualcoder I still get:
~/Downloads$ cd /usr/share/qualcoder
marco@marco-HP-Pavilion-Notebook:/usr/share/qualcoder$ python3 qualcoder.py
Traceback (most recent call last):
  File "qualcoder.py", line 53, in <module>
    from manage_files import DialogManageFiles
  File "/usr/share/qualcoder/manage_files.py", line 40, in <module>
    from pdfminer.pdfpage import PDFPage
ModuleNotFoundError: No module named 'pdfminer'


I tried to see your updated deb but I still see 1.5 as latest, which is the one I already used, have you released a newer one?
ps: in the main page where you suggest linux users to try the deb files the link is broken.

**Comment by ccbogel** [comment]
@WPFilmmaker Thanks I have updated the link to the Debian. 
I have uploaded a newer Debian 1.6 today.
Try this command again but with a variation to make sure it puts pdfminer.six into a python 3 version and not into a python 2 version:
`sudo python3 -m pip install pdfminer.six`

**Comment by WPFilmmaker** [comment]
@ccbogel Updating to 1.6 didn't fix the issue, BUT  sudo python3 -m pip install pdfminer.six DID!
So thank you for the help!
I don't know if this will be helpful but maybe it will help other lubuntu users or will help you to better understand how qualcoder behaves in such environment.

**Comment by ccbogel** [comment]
@WPFilmmaker thank you for persisting with these issues. I have learnt more about installing python modules with the problems you have raised. One of the problems in python is that there are 2 main versions - version 2 which is slowly being phased out, and version 3 which is the  current series of python releases. Using pip install commands - does not automatically install into the latest version/series of python, so this is where the problem was occurring.
