### ISSUE TITLE
Req: indicating selection in codes, files, cases boxes

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#462]
Selected files, cases and codes in the Report (and similarly elsewhere) don't really show well. In the dark theme deep blue on black hardly stands out at all. Could the selection highlight be eg a lighter blue? When you click elsewhere and the focus leaves the files or codes box, shouldn't the selected items remain indicated somehow? 

The worse problem is with the codes tress in different places. With so many shades of colours there already, a useful indicator would have to be something like an arrow, bold or something else. With 20+ codes here the selection is currently invisible really.

**Comment by ccbogel** [comment]
I add a red border to the left of the selected item. Although in the tree widget, the left border is shown several times as each row has several items..

**Comment by glocalglocal** [comment]
When the red border is added to a code, the rest of that item turns into white on black (in the dark theme). I was wondering if the original colour combination could remain intact. Otherwise, that white on black is not ideal, but it is visible. 

An alternative would be prepending something like ▶►▸, or some other character. The advantage is that recognising the selected colour becomes intuitive and the band at the top can be removed.

**Comment by ccbogel** [comment]
prepending is not a viable option to implement. What is happening on Windows, before this change? (I dont have Windows compute to test on right now). On Ubuntu the selection is obvious, before the change:
![pic5](https://user-images.githubusercontent.com/5834638/117816337-c2105700-b2a9-11eb-87d6-81e24e38fd8e.png)

**Comment by ccbogel** [comment]
ok , I found another setting to tweak.

**Comment by glocalglocal** [comment]
This is working much better. Not perfect, but much better. 

The selection highlight overwrites the actual code highlight in pics 2 and 3. The new highlight appears to be a synthesis of the actual code highlight and light blue. In pic 1, it overwrites the tree arrow. 

![image](https://user-images.githubusercontent.com/16408198/117892076-91c7b900-b2a7-11eb-9752-5efa603733f9.png)

![image](https://user-images.githubusercontent.com/16408198/117892167-be7bd080-b2a7-11eb-8a7c-e913bb9c7eb4.png)

![image](https://user-images.githubusercontent.com/16408198/117892186-c89dcf00-b2a7-11eb-8f57-37d5cc7b2069.png)

Can the overlay be transparent or white? I am assuming that the synthesis will leave the original colour unchanged. The same can be done when hovering perhaps.

**Comment by ccbogel** [comment]
Yep OK, better is good. I cant do any more, as I have no more ideas that I can implement. will close this now.
The overlay comes from the Windows OS, just as in Ubuntu the blue came from the Ubuntu OS.
