### ISSUE TITLE
Bug: 2 identical colours in Colour Selector

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#464]
I think #455 got lost somewhere. My Code1 is associated with two colours in Colour Selector, box 2 and 3. I didn't know how it was even possible but now I see these two boxes in the QC palette are for the same colour: #F2F5A9 which apparently causes some sort of cross-linking in my case. 

![image](https://user-images.githubusercontent.com/16408198/117893520-16b3d200-b2aa-11eb-8cab-1ce5152893c3.png)

![image](https://user-images.githubusercontent.com/16408198/117893526-1a475900-b2aa-11eb-9246-1bf90f73c6f0.png)

**Comment by ccbogel** [comment]
Yes OK will fix that colour option when I return home. Do you want to find a #hex colour to replace it with?

**Comment by glocalglocal** [comment]
I would say shift 5 to 4, 4 to 3, and replace the current 5 with dde600 (a dark yellow).

**Comment by ccbogel** [comment]
updated
