### ISSUE TITLE
REFI-QDA Project import. Import variables from Quirkos

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#465]
Currently variables are imported as cases. Variable values imported incorrectly.

Accurate importation of variables assigned to files

**Comment by ccbogel** [comment]
solved 
maybe further testing of case variable import needed

**Comment by AndrzejWawa** [comment]
Ok.

1) When it comes to Quirkos, the importation is ok.
2) When it comes to Maxqda, it was ok previously, but now the values are not visible.

So, it seems that to Quirkos should be applied newest solution, while to Maxqda previous one.

**Comment by ccbogel** [comment]
Ok. It is interesting. The values - you mean the variables/ attributes ?
I think the issue is the refi-qda was never clear on this. This is shy i have problemd. It is also why maxqda and quirkos have done this differently.

**Comment by ccbogel** [comment]
ok I now have both solution in there

**Comment by AndrzejWawa** [comment]
Ok, now works for both : )
