### ISSUE TITLE
Retriving overlapping and unioning segments

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#467]
Hi,

In the report code relations we have information on:

1) segments which are under two overlapping codings,
2) segments which are under two unioning codings.

Is it possible to to show, e.g. in additional column, text extract which is in the range of overlapping ccodings (first additional column), and in the range of unioning codings (second additional column)?

Moreover, is it possible to show segments which are in the range of overlapping or unioning codings, but more than 2? E.g. to show in column only extracts which are marked simultanously by code 1, code, 2 and code 3.

I know that there is such option is Maxqda, and I thinkg it could  be helpful in many ways of analysis, espcially, that table can be already exported.

Moreover, it enables what we discussed as attributes to codes, because you can mark the same segments but selected codes and then, extract segments market with specific codes but not the others.

For me personally, might be very supportive in the project, however, I will have to verify this.

**Comment by AndrzejWawa** [comment]
Moreover, it might be helpful to provide to codings reports (as well as to matrices), information about number of codings which have been displayed, e.g. next to information about number of used codes, attributes, files, and cases.

**Comment by AndrzejWawa** [comment]
And, if possible, to allow in this overlapping segments possibility to click and see them in context.

**Comment by ccbogel** [comment]
@AndrzejWawa This is mostly done, in the code relations report, right click and show in context, when the row is selected. Will do the found codings totals in the other report.

**Comment by AndrzejWawa** [comment]
It looks great! Possibility to extract all of these overlapping and unioning segments in the form of csv table (e.g. in the SQL) would be wonderful. This would be helpful in creating columns with different kinds of overlapping segments (e.g. code A+B and A+C) and making comparisions.

**Comment by ccbogel** [comment]
thats getting too difficult

**Comment by AndrzejWawa** [comment]
Sure, what you have done is already very helpful! Thank you very much for wonderful work : )
