### ISSUE TITLE
Exportation of coding memos and annotations

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#470]
Hi,

Is it possible to show all memos and annotations, with information about file and code (in annotations only about file) in one place, as well as export them from this place, e.g. via word?

I think it is quite important, while we can make annotations and memos in on ongoing basis, and then, summarize them.

**Comment by AndrzejWawa** [comment]
Even, if it is not time consuming, there could be option to show and export all memos (to project, files, cases, attributes, codes, codings, annotations, and journals (separately from option in journal mode). Then, you can create e.g. table or matrix, to show all or only selected memos/annotations, with option to show only for selected files and codes.

However, I see that SQL statements offer much of these, but I cannot find codings to codes. So this function could be provided as new, ready-made query for SQL statements. 

But, maybe the new kind of report with memos (with easy with to select files, codes, kind of memo to displary, and export founctions) will be better. Memos are crucial part of the process, and, e.g. Maxqda, have separate menu for memos management, analysis, etc.

**Comment by AndrzejWawa** [comment]
I think can work on this topic in SQL and let you know.

**Comment by ccbogel** [comment]
OK I have added options for getting memos and annotations. There is an extra comboBox for selecting these. For Annotations - you must select the text files in the files list.
![pic1](https://user-images.githubusercontent.com/5834638/123892448-f5b05900-d99d-11eb-98e6-2e8de2ab1f75.png)

**Comment by AndrzejWawa** [comment]
Hi, good work! PS Why there is no "qualcoder.py" file in the latest zipped code?

**Comment by ccbogel** [comment]
Another person said that the name matched the folder, and tgat could cause some problenns. It is renamed to __main__.py
