### ISSUE TITLE
Installation information

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#476]
Could you add to the manual as well as installation guide here the information that during installation of Python you should mark this option make a path or sth (I do not remember the exact wordings). I remember, that this was one of my main problems, that during installation did not mark it, and then, command "py" or "python" did not work as the system did not know the path do the software. 

Moreover, it seems to me that not all versions of Python from 3.6 work, however, I do not know why. So, the the installation materials (manual and here) could be advice, that change of Python version could help. For me, worked (as I remember) 3.8.7.

**Comment by AndrzejWawa** [comment]
Hi,

I prepared such a guide for my colleagues from PhD course, including information about PATH, python version, and cmd.

You can paste it in the read me or sth:

"The installation process is as follows:

1) Firstly, download the packaged software from this side: https://github.com/ccbogel/QualCoder. This is the newest, but not yet officially released, version of code. You should click the green button "Code", and then "Download ZIP". Then, unpack the file in a selected place (e.g. desktop). 

2) Then, open the unpacked folder "QualCoder-master", then open the folder "qualcoder", and make a shortcut of the file "qualcoder.py" on the desktop - for easier access. This file is the file for running software.

3) However, regarding that the software is written in Python and yet, does not have the exe. file for Windows, you should download and install the Python programming language (similar to R in certain sense). It should be version at least 3.6, however, I recommend 3.8.7 (https://www.python.org/downloads/release/python-387/). Download the file (at the bottom of the web site) "Windows installer (64-bit)" (or 32- if you have such a system) and install the language.

REMEMBER: in the first window of installation mark the option "Add Python 3.8 to PATH" - it makes the last step quite easier.

4) And the final step, you have to install appropriate modules to Python (something as packages in R). Write the letters "cmd" in the Windows Start searching engine, and click on black software "cmd.exe" - it is the command console for Windows. And in the console paste, using the right-click context menu (ctr+v could not work) the phrase "python -m pip install pyqt5 lxml Pillow ebooklib ply chardet pdfminer.six openpyxl", and click enter. Wait, until all modules will be installed (the command phrase should be again visible: "C:\Users\[Your Windows account name]> or similar).

Now, you should be able to run the QualCoder by shortcut on the desktop."

**Comment by ccbogel** [comment]
thank you I have updated it here.
