### ISSUE TITLE
Inter- and intra-coder agreement

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#479]
Hi,

In coding comparisons you o through all files and codes at once.

It is possible to run comparison also on selected files and selected codes (e.g. at the already visible tree?).

Morover, it is possible to provide qualitative comparison of coding? E.g. create a matrix, at least two columns, and the first column will display coded document by first coder and the second by a second coder.

Actually, I am interested in this while the Qualitative Content Analysis stress the importance of realiability and consequence, and one of the method in intra-coder agreement, so, we can compare our own codings and how consistent we are.

The alternative option is provide to the coding report also coders, not only cases, as the possible categories of rows in matrices.

For example, in Qcamap there is such a view (on the one side codings by first coder, on the other, on the another):

![Intra-coder agreement, Qcamap](https://user-images.githubusercontent.com/77200214/118285243-8c4db700-b4d1-11eb-9cf3-a74f02e53309.png)

**Comment by ccbogel** [comment]
Now, I have added a report option - choose 1 text file, choose 1 code choose 2 coder names.
This show the overlap in green and places without overlap in yellow (coder 1) and blue (coder 2).
This only work for text files for now.

**Comment by ccbogel** [comment]
I have added an image comparison for 2 coders function. 
TODO: a/v segment comparison.

**Comment by ccbogel** [comment]
@AndrzejWawa I have finished this I think. its under Reports > coding comparison by file

**Comment by AndrzejWawa** [comment]
Yes, it looks very good! Thank you :)
