### ISSUE TITLE
QualCoder won't start on Ubuntu 19.04 (disco)

### ISSUE THREAD

**Issue by soundray** [ccbogel/QualCoder#48]
I installed the .deb with `dpkg -i` and let apt fix the dependencies (`apt --fix-broken install`). Running `qualcoder` fails with
```
Traceback (most recent call last):
  File "/usr/share/qualcoder/qualcoder.py", line 65, in <module>
    from .settings import DialogSettings
ModuleNotFoundError: No module named '__main__.settings'; '__main__' is not a package
```
I also checked out the Github repository without installing and ran `python3 qualcoder.py` in the `qualcoder` directory. It fails similarly:
```
Traceback (most recent call last):
  File "./qualcoder.py", line 65, in <module>
    from .settings import DialogSettings
ModuleNotFoundError: No module named '__main__.settings'; '__main__' is not a package
```
Grateful for any hints.

**Comment by ccbogel** [comment]
Hello. Thank you for posting this issue.
I have removed relative imports from the code now - these were in a try block, which what shown in the second traceback, so the real error will now show up.
Please download the latest zip from the repository, extract it (in your Downloads for example), then try and run the qualcoder.py file. This runs on my machine without problems, but if you get another error, I would like to know the details. It may be that there is still an unmet dependency.
`cd Downloads/QualCoder-master/qualcoder/`
`python3 qualcoder.py `

**Comment by soundray** [comment]
This revealed two more unfulfilled dependencies (pdfminer and ebooklib). Now that these are fixed, QualCoder is running. Thank you!

**Comment by ccbogel** [comment]
That's great to know.  Pity the debian didn't install these. Please let me know how you find QualCoder for your use.
