### ISSUE TITLE
Req: edit annotated text without selecting any of the text

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#481]
In coding, where there is annotated text (bold), I can select at least one character from the bold text, and then Annotate. It would make sense to be able to do that by simply right-clicking on the bold fragment (without selecting at least a character). This would be consistent with how unmark a coding works.

**Comment by ccbogel** [comment]
implemented

**Comment by glocalglocal** [comment]
Some codings that are flagged as important (the tooltip correctly states 'IMPORTANT' and the fragment is displayed as important when I click on the star) do not get the 'Remove Important mark' option in the right-click menu. This happens both when I click on the coding without selecting text and when I select the fragment. Instead I see 'Add important mark'. The coding I am looking at is coded with two codes.

**Comment by ccbogel** [comment]
create a separate issue for this

**Comment by AndrzejWawa** [comment]
Could you insert the same shortcut, "a" for displaying and edditing annotations?
