### ISSUE TITLE
Take an advantage on SQL and promotion of QC

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#483]
Hi,

I think that this SQL is maybe less eye-catching but really powerfull, valuable, and flexible analytical tool. I think that it could be one of the main advantage of QC over commercial softwares (I do not remember, if they have SQL statements).

So, I would like to suggest such things:

1) Is it possible to create table from data of reports: file summary, code summary, and code frequencies? Then, everyone will be able to make many comparisons on the data, without need of additional reports,

2) Is it possible to allow to create and save users' queries? There are exemplary, but maybe some people are willing to add and save sth, what is suitable for her project. However, it is not very crucial, while you can always save your queries in memos.

Moreover, regarding the promotion and popularization of SQL possibilities:

3) I think that it is needed to make more information on SQL statements in software and manual, e.g.
- explanations of this symbols, like fid, anid etc,
- explanations and simple quides how to display tables you prefer,

4) More queries could be helpful and maybe, the buttons to queries could be placed in different other modes. E.g. you are in certain reports, file management etc, but when you click the button, the software generate in additional window appropriate table. E.g. this comparisons between files could be added, maybe also between all files grouped in cases.

5) If possible, when clicking on the table row with specific coding, memo etc., there should be possibility to see the coding, memo etc. in original context.

6) In some place it would be generally described what are the advantages of open source software for qualitative analysis, including flesibility, access to source code, possibility of modyfying more features if you can and want etc. The YT movies are most attractive I think.

7) Is it possible to change, e.g. the memos of codes from the level of SQL table? In other words, firstly, you creates table with memos to each codes, and then, can modify the content of each sell and save. It could be helpful, e.g. for standardize content of memo and correcting them all at te same time.

8) Is it possible to automatically wrap text and adjust size of cells in SQL tables? - to make many columns visible at once? Also, to change zoom of table?

When it comes to points 3-5, I could work on this and make contribution. However, rather after June 15, as I have grant deadline.

**Comment by AndrzejWawa** [comment]
Ok, here is my first humble contribution : D. Two propositions of additional queries in SQL:

1) 

-- ALL OR SELECTED ANNOTATIONS

select  annotation.anid as "Annotation ID number " , annotation.memo as "Annotation text",  annotation.fid as "File ID number" , source.name as "File name",  annotation.pos0 as "Start position (character)", annotation.pos1 as "End position (character)",   annotation.owner as "Coder name", annotation.date as "Date"  from annotation left join source on source.id = annotation.fid

-- IF YOU WOULD LIKE TO TO DISPAY ANNOTATIONS ONLY FOR SELECTED FILES, ADD THE FOLLOWING PART IN THE END OF THE CODE:

-- "       AND  source.name = "[PLACE THE NAME OF FILE, E.G. CTRL+C IN MANAGE FILES]"      " - TO SELECT SPECIFIC FILE


2) 

-- ALL OR SELECTED CODINGS MEMOS

select code_text.memo as "Coding memo" , code_text.cid as "Code ID", code_name.name as "Code name",  code_text.fid as "File ID",   source.name as "File name",  code_text.owner as "Coder name",  code_text.date as "Date",  code_text.important as "Important mark (1 - yes, 0 - no) "   from source  left join  code_text on  code_text.fid = source.id left join code_name on code_name.cid = code_text.cid where code_text.memo != ""

-- IF YOU WOULD LIKE TO TO DISPAY CODING ONLY FOR SELECTED CODES OR FILES, ADD THE FOLLOWING PART IN THE END OF THE CODE:

-- 1)  "      AND  code_name.name = "[PLACE THE NAME OF CODE"      "  - TO SELECT SPECIFIC CODE

-- 2)  "      AND  source.name = "[PLACE THE NAME OF FILE, E.G. CTRL+C IN MANAGE FILES"      " - TO SELECT SPECIFIC FILE

-- 3) "      AND code_name.name = "[PLACE THE NAME OF CODE]" AND source.name = "[PLACE THE NAME OF FILE]"      " - TO SELECT SPECIFIC CODE AND FILE

3) And my proposition is that if your are in the coding mode, you can click one button that is "Show annotations for this file" or "Show codings memo for this file", and then, the software show you the SQL table with annotations or codings, but for the selected file. Like in the instructions for above statements.

**Comment by ccbogel** [comment]
Ok thanks . I have added the code in the SQL window for the first 2 suggestions.

**Comment by ccbogel** [comment]
I have added a wiki page that details the tables and fields in the sqlite database.

**Comment by ccbogel** [comment]
transferred the above to separate issues.
