### ISSUE TITLE
Bug: 'Remove Important mark' not showing

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#487]
Some codings that are flagged as important (the tooltip correctly states 'IMPORTANT' and the fragment is displayed as important when I click on the star) do not get the 'Remove Important mark' option in the right-click menu. This happens both when I click on the coding without selecting text and when I select the fragment. Instead I see 'Add important mark'. The coding I am looking at is coded with two codes.

**Comment by ccbogel** [comment]
Is this still happening with the latest download. I have tested it now and it worked fine. 2 codings on the one spot. one was important and one was not.  I had options to add and to remove the Important mark.

**Comment by glocalglocal** [comment]
I believe this is working OK now.
