### ISSUE TITLE
Last issue when it comes to Quirkos

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#488]
If do you want to work on this, there is last issue related to importation/exportation to Quirkos, namely the memos.

In Quirkos there is only one kind of memo and it works as annotations in QC (it is not related to specific codings). So, memos from Quitkos should be imported as annotations, and annotations from QC should be exported as memos.

The questions is what to do with other kinds of memos in QC. My idea is that they all could be exported into the one of the memo in Quirkos.

In Maxqda however, the memos (comments) to codings are imported but as annotations, but should be as memos to codings. However, the data is not lost.

**Comment by ccbogel** [comment]
@AndrzejWawa Ok so there are many issue listed in this one issue :)
The annotation import from Quirkos to QC now works.
Next is the export of annotations from QC (based on my knowledge of how Quirkos does this).

**Comment by AndrzejWawa** [comment]
Hahah, sorry :) I mean the last category of issues related to memos etc. :)

**Comment by AndrzejWawa** [comment]
And, yes, works. Congratulation :) I only saw the annotation box where there was not an annotation, however, I think that in spare time I can install Quirkos and make the general test.

**Comment by ccbogel** [comment]
Annotations can now be exported from QC.

**Comment by AndrzejWawa** [comment]
Nice. So, when it comes to other memos of QC, which do not have their counterparts in Quirskos, they will not be exported?

**Comment by ccbogel** [comment]
I think most memos are exported
If Quirkos does not use other memo types , then it would not import them, I guess.

**Comment by AndrzejWawa** [comment]
Ok,

If you want, I have also that idea, regarding non-existing memos in Quirkos:

1) while creating REFI for Quirkos, QC could create one additional annotation and put there all memos (except to codes, annotations, and codings), 
2) memos to codings could be transformed into annotations and exported.

- Quirkos should be able to import these memos in the form of annotations.

**Comment by ccbogel** [comment]
while creating REFI for Quirkos
I am not making a special arrangement for only one of the other QDA softwares. This type of situation will end up causing a lot of problems. Problems will occur when the project is meant to be imported into another software that is not quirkos.
