### ISSUE TITLE
Can't run QualCoder on either Linux, Mac or Windows

### ISSUE THREAD

**Issue by huyenmaddie** [ccbogel/QualCoder#49]
I've installed all the dependencies and VLC on all three OS. Every time I try to run qualcoder.py I run into the same error message: `"AttributeError: 'MainWindow' object has no attribute 'settings' "` and then the program closes.

**Comment by WPFilmmaker** [comment]
@huyenmaddie Maybe you can provide more info such as which Windows version and which Linux distro?
Did you install it from the .deb or?

**Comment by ccbogel** [comment]
To double-check. I downloaded the github code just now. I can run the program without errors on Linux Mint using:
`python3 qualcoder.py`  from withing the qualcoder directory

**Comment by huyenmaddie** [comment]
I use Windows 10 and Ubuntu 16.04.
On both OS I installed it using the terminal like instructed in the manual. And I also run the program using the terminal from the directory. My friend who installed it from the terminal on Ubuntu 16.04 also ran into the same problems I did.

**Comment by ccbogel** [comment]
OK Ubuntu 16.04 is fairly old. I do not think they are providing updates now for these. [http://old-releases.ubuntu.com/releases/](http://old-releases.ubuntu.com/releases/)
Have you tried using the software on recent versions of Ubuntu such as 18.x or 19.x distributions.
I have not yet had a chance to access a Windows 10 computer to test the software myself.

**Comment by huyenmaddie** [comment]
I see, my friend also suggested I try it out. I will update ubuntu to 18.xx tomorrow and let you know!

**Comment by ccbogel** [comment]
I have also right now updated the main starting file - qualcoder.py   just in case this was a problem too.

**Comment by ccbogel** [comment]
I am going to close this issue now., as I havent heard back. Other people are now able to run QualCoder by installing the latest Linux Deb and via the source code too. However I still need feedback on Windows and Mac.
