### ISSUE TITLE
Double windows when using shorcuts

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#490]
Hi,

When you use shortcuts the specific windows are opened two times, e.g.

- if you try use "q" withour selected cores, the warnings windows appears, you close it by ok, but then, it appears second time and you have to second time close it,
- if you use "m", the memo windows is opened, you close it by ok, by then it is opened second time, you should click ok second time,
- the same with annotations.

But, the problem occurs only, when you use shortcuts, using context menu is ok.

**Comment by ccbogel** [comment]
yes, I see the problem, and have looked at it, but for now cannot work out how to solve it.

**Comment by ccbogel** [comment]
OK, this seems to be fixed in the Code Text section. I will transfer the solution to the Code A/V section.

**Comment by ccbogel** [comment]
I think fixed now
