### ISSUE TITLE
Adding coded files from other softwares to you project

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#494]
Hi,

1. I have a question. Is it possible to import coded files from other softwares (in REFI), but not as a new project but through adding coded file into your existing project?

2. Or, is it possible to merge QC project, e.g. you have coded files in other QC project and you want to import them into your main project for joint analysis (e.g. code frequencies, or making tables)? Then, first problem will be also solved.

**Comment by ccbogel** [comment]
I would have to create a function to do this. Not a quick an easy fix at all. 
If the coder names in each project are the same, how are these handled?
If the codes have the same name but are in different categories, how are these handled?

**Comment by AndrzejWawa** [comment]
I think that:

1) When coder names are the same they should be merged by default (but there could be notification, if you want to merge or keep them separated. If separated, new coder can have additional number index, like 0, 1, 2...),

2) When the codes have the same name but in different categories, also adding number index is solution. However, in the manual there should be explained how procedure works,

3) Hmmm, maybe, files with the same names should not be imported? Imported are only new codings with positions, but the positions will be linked to the files in main project (to which you want import others). Only files with other names than in main project will be imported.

**Comment by ccbogel** [comment]
I have decided that this is too difficult an issue to fix.
