### ISSUE TITLE
Req: base dir and relative paths

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#496]
I set up a Debian KDE Plasma system and installed QC. Then I opened a project stored in a folder in my local Mega folder (this works like Dropbox). The idea is that this folder is synchronised seamlessly across my machines. It opened the stored texts OK but of course the log shows all paths to linked mp3 and text files as broken ('Bad links to files') because the directories structure is completely different between my Windows and Debian machines. 

The solution would be what Zotero does: an option to set the base directory and then relative paths. So, we can then use any syncing method, and then eg in Windows my base dir would be `c:\Mega`, on Linux it would be `/home/user/MEGA/`

The good news is QC works fine on Debian KDE Plasma (almost -- another report follows)

**Comment by ccbogel** [comment]
I have added a Special function under Help > Special functions to change the base folder path.

**Comment by glocalglocal** [comment]
Not sure why there is a comma above 'Existing'. That box after 'New 
prefix' doesn't seem to do much. Is the idea that you select a new 
prefix and then files are moved to the new location when the 'Run' gears 
button is clicked?

**Comment by ccbogel** [comment]
I will get back to you on this, I missed uploading an updated file.

**Comment by ccbogel** [comment]
I have updated the files.
The idea is that you change the link text in the database so that QC can point to the correct file locations.
It does not move files.

**Comment by glocalglocal** [comment]
My linked files are in something like 
"C:\work\MEGA\folder1\fiolder2\folder3" and my project is in 
"C:\work\MEGA\folder1\folder4"

I would like to be able to set the base directory to 
"C:\work\mega\folder1" so that my linked files will be in relative 
"folder2\folder3", and my project will be in "folder4"

I don't see how this can be done now. QC defaults to "C:\work" instead 
of "C:\work\MEGA\folder1" and when I change the prefix, say, to 
"C:\work\MEGA" then it looks for files in "C:\work\MEGA\MEGA".

Also, shouldn't the Action log show something like:
Base path: C:\work\
Project path: MEGA\blah.qda
Project backup created: MEGA\blah_BKUP_20211109_00.qda

**Comment by ccbogel** [comment]
OK, I will not continue with this, as its not easy. So I have removed that option from the special functions.
Instead, I have made the Manage Bad Links function a bit better.
So now you can click on the file name or current path to open the file selector dialog, as before.
But also now, it searches the use's file system for a matching file name and provides up to 2 alternative file path suggestions.
Click on a suggestion to implement that file path.

**Comment by glocalglocal** [comment]
This means users working with multiple synchronised machines and OSs 
will have to correct many, possibly hundreds of paths on different 
systems semi-manually. Not ideal, but we can live with it.

**Comment by ccbogel** [comment]
Thats true
