### ISSUE TITLE
Bug: text in code colours is always white on Debian

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#497]
I synchronise a project between Windows and Debian KDE Plasma. The code colours looked fine in Windows but the lighter ones are unusable on Debian because text is always white. In the image below there are several white asterisks in the two left-most and the middle columns. 

![image](https://user-images.githubusercontent.com/16408198/123554756-16e03200-d771-11eb-972d-0f266224d54b.png)

And this is how it looks in Windows: 

![image](https://user-images.githubusercontent.com/16408198/123645478-e7373580-d815-11eb-80df-1e4d5826af9b.png)

**Comment by ccbogel** [comment]
OK, that is really odd. I have looked at the code that chooses the light or dark for text. 
Right now, I cannot see a problem in the code, nor solution.

**Comment by glocalglocal** [comment]
Not sure if this is related or if it should be a separate item, but something is not right about the dark mode on Debian with a system-wide dark theme. 

The dark mode setting on Windows: 

![win3](https://user-images.githubusercontent.com/16408198/123959489-c1d53380-d99d-11eb-84d9-a231df7eb7fa.jpg)

and on Debian:
![deb3](https://user-images.githubusercontent.com/16408198/123959518-cb5e9b80-d99d-11eb-9d3f-60110c26f180.jpg)

The buttons on Windows: 
![win1](https://user-images.githubusercontent.com/16408198/123959556-d9142100-d99d-11eb-9572-d546099cb67a.jpg)

and 

![win4](https://user-images.githubusercontent.com/16408198/123959567-dc0f1180-d99d-11eb-94da-220e909f1e83.jpg)

and on Debian: 

![deb1](https://user-images.githubusercontent.com/16408198/123959667-f47f2c00-d99d-11eb-8306-f5ff7f5dae90.jpg)

and

![deb4](https://user-images.githubusercontent.com/16408198/123959672-f517c280-d99d-11eb-9449-d608fe362132.jpg)

The selected code indicator on Windows: 

![win2](https://user-images.githubusercontent.com/16408198/123959766-0e207380-d99e-11eb-90ca-87efea60aeae.jpg)

and on Debian:

![deb2](https://user-images.githubusercontent.com/16408198/123959793-15e01800-d99e-11eb-9f9f-faf42e53697c.jpg)

It seems to me QC thinks it's in light mode and there is no way to tell it to switch, but the system-wide theme messes up the scheme.

**Comment by ccbogel** [comment]
I dont think you are running the same current qualcoder code on Debian. The positioning of the buttons is different.
For Debian, try downloading the latest code and installing that. cd to the QualCoder-master folder and run:
sudo python3 setup.py install 
Then again from the terminal, run QualCoder by typing:
 qualcoder

**Comment by glocalglocal** [comment]
Yes, you were right. I installed the latest version and the dark mode 
and the correct colours are back. Except that in Coding the first three 
buttons at the bottom (previous, next, all codings) appear grey on grey. 
If I click on one of previous/next buttons, its colour changes to match 
the background of the code colour, and the tooltip turns white text on 
the colour of the code. The fourth button (star) looks OK.

Also, the Show Coded Files dialogue doesn't use the new colour 
combinations -- the files names appear as white text on light background 
and unreadable. And there is the ? on the title bar -- I thought this 
only showed on Windows.

**Comment by ccbogel** [comment]
updated the colours except for this: And there is the ? on the title bar -- I thought this
only showed on Windows.
can you show me a screen shot

**Comment by glocalglocal** [comment]
![image](https://user-images.githubusercontent.com/16408198/124048878-cf72d380-da06-11eb-9257-c9f3aa659cb5.png)

KDE Plasma uses shows that ? in dialogues

**Comment by ccbogel** [comment]
should be fixed now

**Comment by glocalglocal** [comment]
all fixed. thanks.

**Comment by ccbogel** [comment]
thanks
