### ISSUE TITLE
SMall improvement to 'auto code'

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#50]
I finally started fiddling with QC again, and I would like to request a small improvements to the 'auto code' feature.

I noticed that if I want to code similar words (let's say 'politic','politics','politicians') I have to manually run autocode 3 times, I was thinking, wouldn't be better if user could run autocode once for multiples words by diving them with ","? For example 'politics,politic,politicians'. This would speed up autocode noticeably.

Best Regards.

Ps: please keep in mind that I am no expert in qualitative analysis...so my request might make no sense, I am just speaking from a user pov.

**Comment by ccbogel** [comment]
I am mulling over this request. Have to think about it.

**Comment by ccbogel** [comment]
OK I have updated the file here. Use the pipe symbol to separate texts  '|'
