### ISSUE TITLE
Preparing for a 2.6 release

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#502]
I am now preparing for a new 2.6 release.
Many things have changes - lots of functionality and bug fixes.
So will not resolve issues any further for now. I need to work on translations (German, French, Spanish, Portuguese specifically - as people from these language countries are viewing the wordpress site).

I will close issues #470 and #500 soon as they I think are resolved for now.

I may close issue #483 soon and extract two new feature requests from #483:
i) Save user sql queries
ii) In coding text, a button to "Show annotations for this file" and "Show codings memos for this file". 

# Functionality and bug fixes:

## Fixed bugs:
Coding text: when searching for text and the 'all files' option is selected, an error occurs. (due to an upgrade in another functionality). Fixed.

Case deletion: This can affect the case attributes for multiple cases. Fixed.

## Functionality:
Added dark mode. Activate in Settings.

Added search text function in Journals and in Manage Files > view audio/video file.
Improved overly sensitive code extension and reduction keys in Code text(Shift or Alt + Left or Right arrow).

Added new auto-code function in Code text. This function uses start and end marks for autocoding. It includes all of the start mark and stops just before the end mark. The line ending character is '\n'.

Added Important function to coding. This flags coded text, AV, images as important codes. To use for exemplars.

Added files filter when coding text, AV, images. This shows a filtered list of files, based on attribute values selected.

Added 'I' shortcut in code text code av text to mark important

The codes tree - can now merge one category into another category.

Improved importation of file variables from REFI-QDA Projects.
Improved exportation of REFI-QDA Project file.

Added ctid unique autointeger column to the code_text database table. 
This also updates older QualCoder projects, when opened.

Can now edit coded text files while the text file contains coded/annotated/case-assigned text. Avoid selecting text chunks and deleting or pasting text across selected text chunks which contain combinations of unmarked text sections and  marked coded/annotated/case-assigned sections. As this will not update those assigned text segments correctly.

Reports: 
Added function to report on annotation in a text file.
Added function to add reporting memos: Options: None, Coded text memos, All memos.

**Comment by AndrzejWawa** [comment]
Hmm, when I'am running the "main" file, this error appears.

![QualCoder name](https://user-images.githubusercontent.com/77200214/124264500-d697ff80-db34-11eb-97ad-9e50d795d3fe.png)

**Comment by ccbogel** [comment]
to be clear. how are you opening the software?

**Comment by glocalglocal** [comment]
SImilar situation here:
 
```
C:\Other programs\QualCoder-master\qualcoder>py -m qualcoder
Traceback (most recent call last):
  File "C:\Users\MKlon\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\MKlon\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", line 47, in <module>
    from attributes import DialogManageAttributes
  File "C:\Other programs\QualCoder-master\qualcoder\attributes.py", line 37, in <module>
    from .add_attribute import DialogAddAttribute
ImportError: attempted relative import with no known parent package
```

**Comment by AndrzejWawa** [comment]
Double-clicling on the file "__main__.py". Previously, it works with "qualcoder.py"

**Comment by ccbogel** [comment]
For the moment, usind cmd.exe, if you move to the QualCoder-2.6 folder, then type:
py -m qualcoder

Let me know if the above works.

**Comment by glocalglocal** [comment]
yes, that works

**Comment by ccbogel** [comment]
@glocalglocal good. I have updated the Readme instructions to clarify this. And now will work on the wiki instructions.

**Comment by glocalglocal** [comment]
As before, this also works if you don't want the terminal box:
C:\Windows\pyw.exe -m qualcoder

**Comment by ccbogel** [comment]
I have updated to a 2.7 release. I found an annoying bug in the 2.6 code av section.
If the double-click still does not work to open. perhaps create a new issue for that. I will test it when I can.
Otherwise, closing this preparing issue.

**Comment by AndrzejWawa** [comment]
Yes, it works. Hmm, maybe it is better to come back to the previous name of file, when double-click worked? - I wonder, if this cmd is not too much complication for average users.

**Comment by ccbogel** [comment]
Hmmm. Good point. This version works a lot better with setup.py on linux. I have to try and make an exe with pyinstaller

**Comment by ccbogel** [comment]
@AndrzejWawa To add, the name of the file is not the cause of the double-click problem. It is relative imports. So each .py file imports from other .py files using qualcoder.  ...    this is known as relative imports and helps with things such as setup.  But it makes double-click a problem.

**Comment by ccbogel** [comment]
@AndrzejWawa @glocalglocal Double-cllick the \_\_main|-|-.py file starts QualCoder on my work Windows 10

**Comment by glocalglocal** [comment]
Not here. Double-clicking "__main__.py" causes a shell box to open and 
close immediately. Running "__main__.py" from the shell returns:

C:\Other programs\QualCoder-master\qualcoder>__main__.py
Traceback (most recent call last):
   File "C:\Other programs\QualCoder-master\qualcoder\__main__.py", line 
48, in <module>
     from qualcoder.attributes import DialogManageAttributes
   File "C:\Other programs\QualCoder-master\qualcoder\qualcoder.py", 
line 47, in <module>
     from attributes import DialogManageAttributes
   File "C:\Other programs\QualCoder-master\qualcoder\attributes.py", 
line 37, in <module>
     from .add_attribute import DialogAddAttribute
ImportError: attempted relative import with no known parent package

**Comment by ccbogel** [comment]
@glocalglocal OK thats interesting. It works fine for me on Windoww from the inner qualcoder directory using: py \_\_main\_\_.py  
Anyway I am currently looking at using pyinstaller to create an exe for Windows. Making some progress
