### ISSUE TITLE
Menu and tab order

### ISSUE THREAD

**Issue by qualithium** [ccbogel/QualCoder#507]
First of all I'd like to thank you for offering a working and vivid multi-platform open source QDA solution. Great work.

Some things surprise me UI-wise.

Not sure if this is a bug report or a feature request:

![image](https://user-images.githubusercontent.com/87800738/126660422-282a16ef-ffdb-4697-96da-1caf99f786f0.png)

The order of the tabs do not reflect the order of the menu (vice versa). This cross-thinking interrupts a fluid workflow (at least for me).

And: Changing a view inside a tab using a menu item in the first place is a surprising UI experience to me as well. I have seen the other UI related issues. So maybe this can be considered if an overhaul is planned.

I'd like to support your project by offering a native speaker's clean-up of the German translation. Are you interested?

**Comment by ccbogel** [comment]
@qualithium thank you.
I can change the tab order easily. 
Changing a view inside a tab. This developed into a simple and practical way to display dialogs that were associated with that tab name. It occurred naturally as I moved from the earlier, many Dialog Windows (which became confusing to everyone) to the Tabbed UI.
I am glad you are interested in the software, how did you find out about it, and do you know if it is used much at all in your area?

**Comment by ccbogel** [comment]
OK tab order is changed.
