### ISSUE TITLE
Help->contents opens Signal Desktop....

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#51]
Ok this is weird but if I go on Help->contents Signal desktop app opens..............

Is it me or you changed how manual opens? I think somewhere in the commits I read that manual should be displayed on browser? Signal is built with electron so the system kinda sees it as a chromium instance, could it be the reason that makes it open it?

Are you able to replicate this on your linux system? If not I am afraid you might have to install lubuntu in a virtual box and try there?

I tried to run QC from terminal but it shows nothing.. It just opens Signal desktop and nothing else...

I am on Lubuntu 18.04 QC 1.6 and Signal Desktop v1.29.3

**Comment by ccbogel** [comment]
Hi, yes i changed the help so that it opens in your default browser, mine is Firefox. The browser displays the help html better, which i changed it.

**Comment by WPFilmmaker** [comment]
Mine is FF too but I don't get why it opens signal...

"Signal is built with electron so the system kinda sees it as a chromium instance, could it be the reason that makes it open it?" it was just my speculation on the cause :D

**Comment by ccbogel** [comment]
OK interesting. I guess ultimately does signal display the help file reasonably well?

**Comment by WPFilmmaker** [comment]
No the thing is that it doesn't do anything!
I thought maybe it will just open and point to a link but nothing...it just opens it and I am unable to access the documentation :/

**Comment by ccbogel** [comment]
OK on your Lubuntu, Signal is being made the default app for opening html files.
There is a trail of this issue here: https://github.com/signalapp/Signal-Desktop/issues/3602
This also contains some terminal commands to get around this too.

**Comment by WPFilmmaker** [comment]
That was the issue indeed!

**Comment by ccbogel** [comment]
OK great, you are lucky - I cant sleep its hot and its 11pm here :)

**Comment by WPFilmmaker** [comment]
Thanks again :D I was indeed surprised to see you up at this time :D

**Comment by ccbogel** [comment]
closing this issue :)
