### ISSUE TITLE
Search after click enter

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#511]
Hi.

Is it possible to introduce possibility of runnking search procedure after clicling enter? Such a possibility could be optional, e.g. option in the settings "Automatic searching", which you can activate or not.

I have still problems with this immediate searching and introducing the option would be very helpful.

Kind regards,
Andrzej

**Comment by ccbogel** [comment]
do you mean when clicking the search button [button with cogs] ?

**Comment by glocalglocal** [comment]
Yes.

**Comment by AndrzejWawa** [comment]
Yes, allow to disable automatic searching and allow to  start searching process only after clicling the search button.

**Comment by glocalglocal** [comment]
> Yes.

Oops, I misread the email notification and thought you were asking me in another thread :)

**Comment by ccbogel** [comment]
@AndrzejWawa "Yes, allow to disable automatic searching and allow to start searching process only after clicling the search button."

![Screenshot from 2021-09-07 07-49-09](https://user-images.githubusercontent.com/5834638/132262229-b7165894-46c8-4599-9a29-40e9b55bbc96.png)

I am a bit unsure still. You can tab to the cogs button and when it is highlighted press space or enter to make it run.

**Comment by AndrzejWawa** [comment]
No, sorry for misunderstanding. I mean add a NEW search button near to the searching window in coding mode (or, possibly, journals). Now, it works that searching starting with putting 3 characters, however, sometime it slow down computer (if the computer is older). So, it is good idea to provide search button and option (e.g. in settings) to disable automatic searching. Then, searching starts only after clicling new search button.

![search button](https://user-images.githubusercontent.com/77200214/132330886-a1fc8c8e-a875-4a4d-8b9b-bb49def443be.png)

**Comment by ccbogel** [comment]
OK I understand now. Instead of an extra button I might add a right-click menu to choose between automatic searching on 3 characters or more,  or Enter to search.

**Comment by AndrzejWawa** [comment]
Yes, possibility to search by clicling enter is also totally good!

**Comment by ccbogel** [comment]
@AndrzejWawa OK right-click on the search text widget to change the auto-search options: 
3 or more characters
5 or more characters and,
press Enter

**Comment by AndrzejWawa** [comment]
Thank you very much! It is very helpful. I still work with QC, it is very good software!
