### ISSUE TITLE
Deleting new attribut in the cases management

### ISSUE THREAD

**Issue by Kapu06** [ccbogel/QualCoder#512]
Hi there, I just mistakenly created a new attribut but I don't see how to delete it. Is it a bug, or is it hidden somewhere ?

I hope this is the right place.

Thank you for your work anyway !

**Comment by ccbogel** [comment]
Hi. In the menu bar. Click the Files and Cases tab then select Manage Attributes.  Then select the attribute and delete using the x button.

**Comment by Kapu06** [comment]
Very well, thanks to you!
