### ISSUE TITLE
Excellent software!

### ISSUE THREAD

**Issue by donnekgit** [ccbogel/QualCoder#515]
Gosh, what a great piece of software!  All the key features of Nvivo without the price and the additional "feature list" stuff you'll never use.  Thanks so much for making it. I've been using v2.7 on Ubuntu 20.04 to code text, and the qdpx files import fine into Nvivo.  Cool!

I also love that you can run your own SQL queries on the coding database.

**A couple of cosmetic wrinkles:**

1. In the install docs, `python3-qt5` should read `python3-pyqt5`.
2. On both the installs I did, tooltips have black text on a dark grey background - possible to read, but you have to squint. It may be a Python platform thing.
3. `Reports → Code summary` doesn't show figures for counts in the column beside the codes.

**Some suggestions for features to add:**

`Reports → Coding reports` for all codes has the quotes for a particular code grouped together, but the codes themselves are not in alphabetical order, which I find useful to save you leafing through pages searching for the location of a particular code. I'm not sure what order the main report is in, but it would be nice to have the option of a report with the codes in alphabetical order.  I was able to get a basic code+text output by going to `Reports → SQL statements → Query` and running:
```
select  code_name.name as "codename", code_text.seltext from  code_name join  code_text on code_name.cid = code_text.cid order by code_name.name
```

Related to this, it would be nice for the odt report to have the option of having the codes (in alphabetical order) as headings, below which are all the quotes relating to that code.  In my case, I would also like to lose the [VIEW] lines, since I code each file separately.

`Reports → Code frequencies` lists codes, coders and total, but only in alphabetical order of code.  Could an option be added to list them in terms of decending total frequency?  Something like:
```
select code_name.name as "codename",  count(code_text.ctid) as "number" from code_name join code_text on code_name.cid = code_text.cid group by code_name.name order by number desc
```

**Is this a bug or a feature?**

I also noticed that codes apply across ALL your projects - if you have used a code in one project, you can't add it to another project, but also you cannot reuse it (because there is no way to access it).

**Comment by ccbogel** [comment]
@donnekgit the cosmetic wrinkles are fixed now.
I'm glad you like the software (a gradual work in progress beginning in 2013? with its predecessor PyQDA), how did you find out about it.

The is this a bug or feature. I don't understand the issue there? 
I'm not sure what you mean about codes apply across ALL projects?
In a different projects you can create codes with the same code name.

**Comment by donnekgit** [comment]
I saw a reference to it when I was investigating RQDA, and then Vicky Rampin discussed it in the CAQDAS 16 webinar:
https://www.youtube.com/watch?v=9teZO-KVwqk
(The other two she discussed, qcoder and Taguette, are interesting, but at a very early stage of development.)

I git pulled, ran `sudo python3 setup.py install` again, and, sure enough, all the cosmetic issues are fixed - thanks!

That also seems to have fixed the codes per project issue as well.  Previously I couldn't create Project A, add code "whatever" to it, close it, create Project B, and add code "whatever" to it without getting a message that the code already exists (and therefore can't be used), whereas now I can.  Great!

**Comment by ccbogel** [comment]
OK that last issue (codes per project) is quirky. I did not do anything different to fix  that. so I feel it could yet be unresolved and occur under as yet unknown conditions.
I will close this issue down as I transferred the reports code ordering into a separate issue.
I am currently, gradually, working on issue #479 and developing the Reports>coding comparison by file function
