### ISSUE TITLE
Code ordering in reports

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#516]
Reports → Coding reports for all codes has the quotes for a particular code grouped together, but the codes themselves are not in alphabetical order, which I find useful to save you leafing through pages searching for the location of a particular code. I'm not sure what order the main report is in, but it would be nice to have the option of a report with the codes in alphabetical order. 

It would be nice for the odt report to have the option of having the codes (in alphabetical order) as headings, below which are all the quotes relating to that code. In my case, I would also like to lose the [VIEW] lines, since I code each file separately.

Reports → Code frequencies lists codes, coders and total, but only in alphabetical order of code. Could an option be added to list them in terms of decending total frequency? Something like:

select code_name.name as "codename",  count(code_text.ctid) as "number" from code_name join code_text on code_name.cid = code_text.cid group by code_name.name order by number desc

copied from multipleissue by @donnekgit

**Comment by ccbogel** [comment]
So far, I have updated so that the report orders the results alphabetically by code name. This will be alphabetically within each media group text, image, AV).

**Comment by donnekgit** [comment]
Oh, great!  I've just tested this and it's exactly what I was looking for.  Thanks!

**Comment by ccbogel** [comment]
I have done the totals descending in code frequencies report.

odt report. I would like to lose the [VIEW] lines, since I code each file separately. - to think about this.
