### ISSUE TITLE
Error in Coding | File atrtributes 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#517]
In Coding, when I OK this: 
![image](https://user-images.githubusercontent.com/16408198/131255440-05009fda-549d-4aa2-a684-62bf97b5b660.png)

I am getting this: 
![image](https://user-images.githubusercontent.com/16408198/131255418-5b32f8d1-ba69-4a7b-9246-4d76449aefe4.png)

btw, 'reports'? That's presumably from the Reports tab

EDIT: Also, the selected file indicator on the files list tree disappears when this happens. It comes back when I select another file.

**Comment by ccbogel** [comment]
fixed

**Comment by glocalglocal** [comment]
Fixed but 'Select parameters to select...' doesn't make much sense.

**Comment by ccbogel** [comment]
true. updated
