### ISSUE TITLE
Bug: Exporting transcribed text as linked file 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#518]
I tried to export a transcribed text as linked file. I select a folder and then I get '[Errno 2] No such file or directory: path_to_project/documents/text_title_.mp3.transcribed' 

The text is in data.qda and I am trying to export it. I don't see why qc is looking for the file.

**Comment by ccbogel** [comment]
Yes, I get it. One problem is the way I set up transcribed files for QualCoder. As I did it in a way that made easy sense to me initially. It may need a major re-vamp which would mean revision of a lot of code, during Summer.

I can hide the error, easily, but not really fix the problem.

**Comment by glocalglocal** [comment]
Does that mean transcribed texts cannot be exported? Hmm, that's not good. I am guessing that if you can't simply copy/paste the plain text computationally, the problem is you would have to reapply any codes. Copy/paste and linking can still be done manually of course, but the coding won't be transferred. I suppose in the meanwhile the user should be warned to copy/paste into a file and link it as new file before the start coding. That's what I did because I don't like embedding data.

**Comment by ccbogel** [comment]
Does that mean transcribed texts cannot be exported? You can export the file which then gets a .txt ending

**Comment by ccbogel** [comment]
I have been thinking about this, and have an idea to fix it. It will take a bit of time though.

**Comment by ccbogel** [comment]
Added a bit more explanation. in the Manage files tooltips. The transcription is never stored as a text file, as is it created internally within the sqlite database. You can export the database text as a txt file, using the Mange File  - Export file button.

**Comment by ccbogel** [comment]
From what folder did you run that command?
It should be run from the QualCoder-master folder

The errors read as though python is trying to set up some other python package

**Comment by glocalglocal** [comment]
I did run it from that folder. I even tried:

C:\Other programs\QualCoder-master>py C:\OTHERP~1\QUALCO~2\setup.py install

I got the same errors.

**Comment by ccbogel** [comment]
You should not be running (from the master folder): 
py -m test_qualcoder.py

You should run:
py -m qualcoder

**Comment by glocalglocal** [comment]
I had tried that and several other combinations too. VideoLan is in 
C:\Program Files and I believe it's always been there.

C:\Other programs\QualCoder-master>py -m qualcoder
Traceback (most recent call last):
   File "C:\Other programs\QualCoder-master\qualcoder\code_by_case.py", 
line 46, in <module>
     os.add_dll_directory(r'C:\Program Files (x86)\VideoLAN\VLC')
   File 
"C:\Users\username\AppData\Local\Programs\Python\Python39\lib\os.py", 
line 1111, in add_dll_directory
     cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 3] The system cannot find the path 
specified: 'C:\\Program Files (x86)\\VideoLAN\\VLC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File 
"C:\Users\username\AppData\Local\Programs\Python\Python39\lib\runpy.py", 
line 197, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File 
"C:\Users\username\AppData\Local\Programs\Python\Python39\lib\runpy.py", 
line 87, in _run_code
     exec(code, run_globals)
   File "C:\Other programs\QualCoder-master\qualcoder\__main__.py", line 
54, in <module>
     from qualcoder.code_by_case import DialogCodeByCase
   File "C:\Other programs\QualCoder-master\qualcoder\code_by_case.py", 
line 48, in <module>
     logger.debug(str(e))
NameError: name 'logger' is not defined

**Comment by ccbogel** [comment]
OK, sure . I re-did all on Windows 10 at work.
This worked fine:
py setup.py install 

This failed:
py -m qualcoder 

I have now fixed and uploaded the fixed code_by_case.py file
