### ISSUE TITLE
Bug: QC thinks an attribute already exists 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#519]
I deleted an attribute from Manage Attributes, and tried to create a new one with the same same as before. I get this: 

![image](https://user-images.githubusercontent.com/16408198/131256691-8a9c991b-5a49-4210-800c-363b1a4ce082.png)

EDIT: It stops complaining if I restart QC.

**Comment by ccbogel** [comment]
@glocalglocal I could not re-create this error, but I reviewed the delete and add attribute methods.  I made a change to the delete attribute methods, which might resolve the problem.
