### ISSUE TITLE
Trying to delete a category throws an error

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#52]
I was coding a text file, I added a category, tried to delete it, but when I click 'ok', QC throws an error:

Traceback (most recent call last):
  File "/usr/share/qualcoder/code_text.py", line 397, in tree_menu
    self.delete_category_or_code(selected)

  File "/usr/share/qualcoder/code_text.py", line 653, in delete_category_or_code
    self.delete_category(selected)

  File "/usr/share/qualcoder/code_text.py", line 721, in delete_category
    self.get_codes_and_categories()

AttributeError: 'DialogCodeText' object has no attribute 'get_codes_and_categories

I am on Lubuntu 18.04 QC 1.6

**Comment by ccbogel** [comment]
Ok thanks for this, i will look at this tomorrow.

**Comment by ccbogel** [comment]
I have uploaded a file to fix this. I will need to make a new Debian too.  It is actually a minor error luckily becuase the category is actually deleted.

**Comment by ccbogel** [comment]
Resolved now
