### ISSUE TITLE
Req: Manage attributes dialogue design 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#520]
In Manage Attributes, the tickbox next to cases seems off: 

![image](https://user-images.githubusercontent.com/16408198/131256875-81160ccb-bd05-41b6-881e-3dd0b6f7fd7f.png)

![image](https://user-images.githubusercontent.com/16408198/131256882-abb9afe5-bdef-4f29-acf4-97f9ee086e49.png)

**Comment by ccbogel** [comment]
thanks. fixed.
