### ISSUE TITLE
Bug: file tooltip info in Coding is not updated

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#521]
I add or remove codings but the number of codings in the tree tooltip for that text is not updated. That's even if I switch to another text and back. It could be that Characters: is not updated either.

**Comment by ccbogel** [comment]
@glocalglocal I am not getting this issue. It works fine for me, and updates the code count when I add or remove a coded section immediately.

**Comment by glocalglocal** [comment]
It happens here every single time. 
![image](https://user-images.githubusercontent.com/16408198/131354504-bf0d209e-44a2-4cf9-8489-a9336dc7a655.png)

I added one coding, and get this: 
![image](https://user-images.githubusercontent.com/16408198/131354639-548422b0-b703-4969-bbb1-cbbed227407c.png)

I switched to another text and back, and got the same. I removed the extra coding, nothing changed.

**Comment by ccbogel** [comment]
ah, i misunderstood, i missed reading the 'tooltip' part

**Comment by ccbogel** [comment]
ok fixed
