### ISSUE TITLE
Req: white under/overline for dark theme

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#524]
In Coding with dark theme, under/overline should be white. Currently, it is often black line against black background. 

EDIT: Similarly, the regex cheatsheet link is dark blue against black.

**Comment by ccbogel** [comment]
In Coding with dark theme, under/overline should be white. Currently, it is often black line against black background.
I cannot fix this. The overline color matches the underlying text color and cannot be changed.

The regex hyperlink has been removed, so text appears as an ok color.
