### ISSUE TITLE
Bug: Next/previous arrows missing

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#525]
In Coding, I see this: 
![image](https://user-images.githubusercontent.com/16408198/131370586-2011fec4-0df1-4bfe-b858-0d8f748d52ce.png)

and this: 
![image](https://user-images.githubusercontent.com/16408198/131370627-6a0a6d95-81dc-4518-9662-af8cdd522b4e.png)

No arrows.

**Comment by ccbogel** [comment]
I have put up a fix that I have to text on Windows tomorrow. The issue does not occur on Ubuntu.

**Comment by glocalglocal** [comment]
The arrow now show until the moment I select a code. I am running the 
latest master but I am not sure if the arrows disappeared in the same 
way before. When I noticed yesterday they were already missing.

**Comment by ccbogel** [comment]
I think this is fixed now. seems ok to me.

**Comment by glocalglocal** [comment]
it's fixed.
