### ISSUE TITLE
Req: overlines are shown when show Important codings is on

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#526]
When I click on the star button to show Important codings, I also see the overlines for segments where codings overlap even though these have nothing to do with the Important codings. I am not sure how this is useful. In fact, it's confusing because I was trying to figure out the logic I thought I was missing. 

Showing overlaps could be useful as a separate function or the Star should be clearly associated with Important + Overlaps. Then if the star is pressed the overlaps should show the codes used in the tooltip (currently this only happens with the Important codings).

**Comment by ccbogel** [comment]
I have made is so that the overline is not displayed when important codings only are displayed.

**Comment by glocalglocal** [comment]
Thanks. Now I realise that in the Important-only view segments that are 
coded several times are not italicised but the tooltips showing the 
multiple codes applied are there.

I think I may have missed something but if overlapping codings are shown 
with both an overline and italics, why not just do italics? And why 
overlines instead of underlines? I am sure we discussed this before, but 
I still find overlines incredibly confusing in dense text with lots of 
codings.
