### ISSUE TITLE
Bug: Show next coding mixes up colours 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#528]
I click on an arrow button below the codes tree to reveal segments coded with code A (black text on yellow). One such long segment contains a segment coded with code B (normally white on blue). The double-coded segment appears as white on yellow surrounded by the rest of the segment (black on yellow). It should all appear as black on yellow. 

This doesn't happen with other overlapping segments where the text is meant to be black. It looks like the correct background is displayed (code A) but the foreground is inherited from code B, C or D. This is revealed when the foreground for B, C, or D is not black.

**Comment by ccbogel** [comment]
this should be fixed now. will close soon.

**Comment by ccbogel** [comment]
i think the other changes have fixed this now
