### ISSUE TITLE
Req: Next/Back arrows in coding

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#529]
In coding, while using the Next/Previous coding arrows: 
* when I press Next and reach the last coding, and press Next again I am taken to the top of the text, rather than than the first coding. I need to press Next again to get to the first one. This doesn't happen in reverse (ie if I am at the top and press Back, I am correctly taken to the last coding). 
* It would be useful to see something like '2nd of 5 codings' (eg 2nd/5 or 2/5) near the arrows. 
* The on/off toggle could have an additional 'show only codings for this code' -- this would be extremely useful when there are many overlapping codings. 

EDIT: BTW is the current tooltip ('Show all codings') appropriate? I can already see all codings).

* And switching off the function by pressing 'Show all codings') shouldn't trigger a scroll to the top.

**Comment by ccbogel** [comment]
I yhink have fixed all of this. It now only shows the code, not all codes. This was how it was meant to be originally.
Hover over the arrows to see a 1/5 codings.

**Comment by glocalglocal** [comment]
Yes, but what does the underline in codings signify? The whole coding is underlined even if there is partial or no overlap. Also, I think O should be available as long as the tooltip and the instruction to Press O are visible. Currently, I have to click on the coded text first. That's confusing, particularly as I can see the instruction 'Press O'. 

The tooltip 1/5 text is ambiguous. It can be read as 'click this to go to the next coding which will be 1/5'. Something like 'blah blah. Now showing 1/5' perhaps? 

'Show all codings' is essentially 'exit this mode'. Could it be possible to make it a real toggle. ie if you click on it again you could return to where you were -- seeing one coding. I can see how this can complicate things if the user goes away, does other things, and then presses the button again.

**Comment by ccbogel** [comment]
Updated. I have removed all the tooltips apart from the selected code. So no need for O. This is easier for me to work it.
I will keep the show all to exit this mode. it works fine as is.

**Comment by glocalglocal** [comment]
> I have removed all the tooltips apart from the selected code. So no need for O.

In that case, the tooltip is completely unnecessary. All the info is already there. I can imagine some people will want to see overlaps but then Show all codings can allow a quick peek (if Show all is changed to a toggle, which it won't, so the peek won't be so quick).

**Comment by ccbogel** [comment]
one advantage of keeping the tooltip is any memo for that coded segment will show.

**Comment by glocalglocal** [comment]
> I yhink have fixed all of this.

When the arrows indicate a colour, they stay like that when I select another file even if that file has no codings at all. The only way to switch them off is to click on Show all codings.

**Comment by ccbogel** [comment]
fixed this
