### ISSUE TITLE
Specify which version of Lubuntu and MacOS QC was tested on

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#53]
In the about section, you mention Lubuntu and MacOS, however no version is specified and as we saw there can be different errors between versions, so I would suggest to specify the version, I did some testing on Lubuntu 16.04.3 and Lubuntu 18.04.

**Comment by ccbogel** [comment]
Ok thanks, i will update the wording tomorrow.

**Comment by ccbogel** [comment]
I have updated the qualcoder files, but not in the Debian. Iwont do another Debian for a little while. I don't know what version of Mas OS the other users have been using, so  I cant fill in the version number.

**Comment by ccbogel** [comment]
closing this issue for now
