### ISSUE TITLE
Req: Colour of selected code in the codes tree

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#532]
Does selecting a code in Coding have to change its colour in the tree to indicate it's selected? If not, it would be more intuitive and less confusing if that shading was removed now that there is an added indicator pointing to the code selected. That would make displaying the selected code with its correct colour at the top unnecessary. More intuitive, less confusing, and saving space too.

**Comment by ccbogel** [comment]
I did look at this, but I cannot resolve it.

**Comment by ccbogel** [comment]
I can get rid of most of the coloured area above (pink in the image) and have a small square of colour without the wording instead.
![pic1](https://user-images.githubusercontent.com/5834638/132508668-6aa6766e-28fa-44fb-9db6-4d90913fe8f5.png)

**Comment by glocalglocal** [comment]
It is unfortunate the shading can't be removed, but this sounds like a 
good compromise.

**Comment by ccbogel** [comment]
ok I have made that change
