### ISSUE TITLE
Bug: Wrong colours in ovelapping codes combo 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#533]
In coding, the drop-down menu showing overlapping codes above the text frame doesn't seem to follow the new palette colours. I am getting several white text on light yellow etc combinations that are impossible to read. The same coding appears OK in the coded text and the sample below the search field.

**Comment by ccbogel** [comment]
Is the drop down overlapping menu needed anymore? it would be easier to remove this and have more space.

**Comment by glocalglocal** [comment]
I agree now that the tooltip shows the codes and O switches between 
codes the combo ma not be necessary, as long as the tooltip will also 
inform the user which code is currently on top. Eg the tooltip could 
show that in bold or whatever. And that would have to be updated as you 
press O. Without that, if the colours for 2+ codes are very similar you 
won't know which one is on top. The combo doesn't have this problem 
because you can click on one of the codes to put it on top.

If this goes ahead, then the selected coding colour in the square box 
you just created for #532 could move to the buttons bar above the codes 
tree. That's more intuitive and will save space in the area below the 
search field.

**Comment by ccbogel** [comment]
Showing which code is current as the first code in the tooltip will be relatively hard to implement. I dont believe its necessary, as the tooltip shows the code names and is coloured.

**Comment by glocalglocal** [comment]
Suppose coding1 and coding2 overlap and they are coded with code1 and code2.
If the colours of code1 and code2 are very similar there is no easy way to tell which is which. With ~30 codes here, I speak from experience. My trick is I find a spot in the segment where there is no overlap and the new tooltip gives me the name for that single code. It's not ideal though. I suppose I can read the start...end string in the tooltip, but it takes too much effort and disrupts the workflow esp if a coding is several paragraphs long. But if it's too complicated, this is a bit academic.

**Comment by ccbogel** [comment]
yeah  I get it. but is it not at all easy to implement this. Will next remove the overlap bit at the top of the screen.

**Comment by glocalglocal** [comment]
> If this goes ahead, then the selected coding colour in the square box
you just created for #532 could move to the buttons bar above the codes
tree. That's more intuitive and will save space in the area below the
search field.

In fact, why not indicate the selected code colour by lighting up the next/previous coding buttons permanently for the selected code, even if there are 0 codings for that code? Or otherwise the code colour box could be placed somewhere there.

**Comment by ccbogel** [comment]
Or otherwise the code colour box could be placed somewhere there. - This I have enacted.
