### ISSUE TITLE
Bug: duplicate coding of a segment

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#534]
A coding is coded twice with the same code like this: Code1, Code2, Code3 (IMPORTANT), Code2 (IMPORTANT) 

I removed the duplicate and it's OK. I am not sure how it happened and can't yet find another instance.

**Comment by ccbogel** [comment]
I can't repeat this with the 2.7 version. It might have happened when using an earlier version of QualCoder 2.5 or earlier. This was something I resolved at some stage. So if the project was created on an older version it is possible the duplicate was carried across.

**Comment by glocalglocal** [comment]
I did the coding a couple of days ago using the latest Master available 
at the time, so that's later than the 2.7 release. There is certainly 
something going on there and it happened so many times I am sure I will 
find more instances as I go along. I am coding a batch of interviews, 
which explains why I am reporting so many issues lately. More to follow.

**Comment by ccbogel** [comment]
was the project created using the 2.7 or later version? or was the project created using an earlier version?

**Comment by glocalglocal** [comment]
The project was created and most of the texts were added before 2.7. The 
problematic coding was done 2-3 days ago.

**Comment by ccbogel** [comment]
That makes sense. Older versions created the database without a constraint on a duplicated coding of the same code for the same coder on the same segment of text in the sale text file. Projects created with the newer versions have a constraint on this so it cannot happen. I noticed this issue occurred with RQDA also.
I cant back fix this. When you come across duplicates you will have to delete the them.

**Comment by glocalglocal** [comment]
I will probably check QC's reports and find duplicates more 
systematically. So far no more duplicates. Good thing future projects 
won't have this bug.

**Comment by ccbogel** [comment]
will close issue. now you are aware of the ins n outs of it.
I have a bit of time to work through some things here, gradually. 
I was thinking how much of QC has changed over the last couple of years.

**Comment by glocalglocal** [comment]
>  I was thinking how much of QC has changed over the last couple of years.

This is truly phenomenal. It has changed dramatically thanks to you. People increasingly use it as an alternative to the big guys. It's an advert for FOSS. Personally, I recommend it to colleagues and students.

**Comment by ccbogel** [comment]
Thank you. Your assistance is a plus. help to direct ideas and bug fixes. Even if I dont always agree.
p.s. I am currently in the process of changing the way text files are linked to the A/V files. I think this will eventually help with the other issues you have here. 
However, I have to do a few more changes over a few days and testing too, as I don't want it to break older projects. I will be adding columns to some db tables and replacing the .transcribed with .txt when older projects are opened. 
This will also mean that older versions of QC (2.7 and below) will not work with the newer database format (for audio/video), but the newer QC (2.8) will change the older database format to the newer format to work with it.

**Comment by glocalglocal** [comment]
I said this before. I think what would really make qc take off would be help from a UI expert, esp icons and certain workflows. I've seen how much difference it makes for other applications (eg Joplin, which I highly recommend as a FOSS Evernote alternative, does a lot less than QC but looks and feels very polished). 

> This will also mean that older versions of QC (2.7 and below) will not work with the newer database format (for audio/video), but the newer QC (2.8) will change the older database format to the newer format to work with it.

Upgrading the db is standard practice, and I don't see a problem (unless I missed something). It all sounds very promising.
