### ISSUE TITLE
Bug: zombie searh query

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#535]
In coding, I searched across all texts for word1. Much later I searched for word2 and discovered that 
* QC returned both word1 and word2 as hits
* every instance of word1 was coded with a random, but always the same, code. I am not sure if I caused the coding earlier by pressing a key shortcut but I doubt it. 

EDIT: I searched for word3 and now an instance of word3 in one of the files is coded again with the same code as above. I just remove those codings but it seems every time I search for wordX, I am left with instances of wordX coded with the same code in different texts.

**Comment by ccbogel** [comment]
This does not happened to me under Ubuntu, will check under Windows, but  I have not seen it before on Windows.

**Comment by ccbogel** [comment]
I will close this issue,as I cannot find a problem here.

**Comment by ccbogel** [comment]
This issue of both words hit does not happen. Random coding does not happen - except , if a word is highlighted and you select a code  - which is normal functioning.
