### ISSUE TITLE
Req: Reports dialogue: forgotten attributes 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#536]
While creating reports, selected attributes are forgotten when you close the dialogue. Even if you immediately reopen the attributes dialogue the selections are gone. The summary of selections (codes x/y etc) still shows a number of attributes are selected.

**Comment by ccbogel** [comment]
updated

**Comment by glocalglocal** [comment]
When I re-open the dialogue and click Cancel it clears all set 
attributes. Following convention, I would expect Cancel to cancel any 
changes made since I opened the dialogue, and a separate Reset, Clear or 
something to clear all settings.

**Comment by ccbogel** [comment]
OK I have fixed the clear attributes on Cancel.

**Comment by glocalglocal** [comment]
This is working now. Cancel doesn't clear settings. I see the issue is 
open and flagged as priority, so I am guessing there will be a 'Clear' 
settings button added.

It would also be useful to have an on/off button. Eg you want for a 
moment to switch off the many attributes you laboriously set and see the 
full report, and switch them on again. This would be far more useful in 
Attributes in Code Text (eg switching between show all and filtered 
files). I am not sure why Attributes in Code Text and Reports should 
look and behave differently.

**Comment by ccbogel** [comment]
Added clear button
