### ISSUE TITLE
Req: Reports: selection summary info

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#537]
It is very confusing that the summary shows what was selected to produce the report (or 0/0 if there is no report). I think most users would wonder why these numbers don't change as they select/deselect files, cases etc. They do change only after you click Search. 

Perhaps this should show the current selections. The ones used for the report appear in the header of the report anyway. 

btw, it would be very useful if the report header shows info like 'Codes (15/15):'. We often need to know for sure and instantly that all 54 files were selected and we didn't miss 1-2. You can't easily tell from a list of 54 filenames. 

Generally, for peace of mind I think wherever an application lists things you can select there should be info like that (eg total number, number of selected items). Computers are good at that, humans are not. We shouldn't have to count numbers of items etc, particularly when there are many of them.

**Comment by ccbogel** [comment]
Yes I should remove that display would be best, but also yes add the counts in the report header.

**Comment by ccbogel** [comment]
updated

**Comment by glocalglocal** [comment]
The only difference I see is that x/y counts are missing completely. I 
thought x/y counts would change to show what is now selected. Also, the 
report doesn't include the x/y for items used to produce the report.
