### ISSUE TITLE
Req: attributes dialogue operations

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#538]
In the attributes dialogue, '==' doesn't men anything to non-coders. Are 'in', 'not in', 'like' applicable to numeric values?  Does 'be...en' stand for 'between'? And how would that work? I am guessing these may be issues elsewhere in qc too. 

![image](https://user-images.githubusercontent.com/16408198/131847953-05dc6576-b2da-4f63-9355-9c3f14560596.png)

**Comment by ccbogel** [comment]
updated =, widened the column to show between, but still depends on font chosen. added some extra wording around use of these

**Comment by glocalglocal** [comment]
I am not sure if I have the wrong version, but I just downaloded the latest master and I see: 
![image](https://user-images.githubusercontent.com/16408198/132214642-60dab55f-c395-41da-805b-3c41479db598.png)

The distribution of columns is not great, == is still there. != could be replaced with ≠ if allowed. 
I am not sure if the same options appear with character attributes. If they do, I am not sure how in, not in, between work. Presumably these will follow ascii sorting conventions.  

That's attributes in Coding Reports.

**Comment by ccbogel** [comment]
yep sure, i forgot to upload the report_attributes.py file yesterday.
in  :  looks for matching values in character or numeric, not in is the reverse
!= have to keep this. it is common in stats software, eg spss nd users will learn by experiementation, i can add to documentation.
