### ISSUE TITLE
main.py missing

### ISSUE THREAD

**Issue by Robaire3** [ccbogel/QualCoder#539]
**Describe the bug**
Instructions say to double click on "main.py" in the qualcoder folder. There is no such item
**To Reproduce**

**Expected behavior**
starts QualCoder
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version [e.g. 22] 22

**Additional context**

**Comment by ccbogel** [comment]
@Robaire3 Hello. In the current 2.7 and above version it is here:

![pic1](https://user-images.githubusercontent.com/5834638/132148060-2c47f7ed-a691-4770-97a4-50e2d0217166.png)

But, if you downloaded the 2.7 release  it is easier to use the exe which was developed on Windows 10, and double-click that.  https://github.com/ccbogel/QualCoder/releases/tag/2.7

I would not recommend using older versions, newer versions have bug fixes.
In the older 2.2 version double-click on qualcoder.py  - this file is located QualCoder-2.2/qualcoder/qualcoder.py
Alternatively run py qualcoder.py from the inner qualcoder folder QualCoder-2.2/qualcoder

**Comment by ccbogel** [comment]
I presume you have resolve the issue now with the above suggestions

**Comment by Robaire3** [comment]
Hi Colin,

Thanks very much for your help and update.

Bob

**Comment by ccbogel** [comment]
Thats ok. Let me know how you find using QualCoder.
Regards Colin

________________________________
