### ISSUE TITLE
Req: Search hit always appears at the very bottom 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#547]
It is a little annoying that every time we jump to a location (eg because of search or View in context) the hit appears at the very bottom of the screen and we always have to scroll down. This is very unconventional, and it is annoying because it happens every single time. Can't qc scroll down automatically so that the hit appears, say, in the middle of the screen?

**Comment by ccbogel** [comment]
I cannot make it scroll to the middle of the screen, but I have added some code so that the search term is not always right at the bottom of the screen.

**Comment by glocalglocal** [comment]
It's not the most professional way to do this, but can't you just fake 
scrolling down by, say, 10 lines.

**Comment by ccbogel** [comment]
I fake it by setting the cursor position to 300 characters after the search term. I cannot do this by lines

**Comment by glocalglocal** [comment]
I search for a word across all texts. There are 4 hits. 2 of them are 
shown at the very top, 2 at the very bottom. There is room for scrolling 
up/down.

Incidentally, I can only enter a search string after I select a file. If 
I want to search across all files, it shouldn't be necessary to select one.

**Comment by ccbogel** [comment]
I have reverted the changes made. They can introduce more problems if there are newlines in the subsequent characters, pushing the selected text up and out of view. You can scroll text to position with the mouse scroll wheel.
I cannot find a satisfactory solution, so will close this.

**Comment by glocalglocal** [comment]
When I said you could fake scrolling, I meant something like emulate the 
user clicking on the scroll bar or pressing keys. If that is possible, 
it shouldn't cause other problems.

Using the mouse scroll wheel is OK, but if you are clicking repeatedly 
on the arrow button for the next search hit until you find the one you 
need, i think you will have to move the mouse pointer between the text 
box (for scrolling) and the next button. Not a big problem. Just saying.

**Comment by ccbogel** [comment]
I cant emulate moving the scroll bar via programming. I tried this and nothing was working.
