### ISSUE TITLE
ModuleNotFoundError: No module named 'qualcoder'

### ISSUE THREAD

**Issue by atanasj** [ccbogel/QualCoder#548]
I am getting the below error. I have installed all dependencies as instructed on in the `README.md`, however cannot get this working… Any ideas what I might be going one or if I have done something wrong? 

Let me know if you need any more info. 

```sh
~/git
❯ python Qualcoder/qualcoder/__main__.py

Traceback (most recent call last):
  File "/Users/atanas/git/Qualcoder/qualcoder/__main__.py", line 50, in <module>
    from qualcoder.attributes import DialogManageAttributes
ModuleNotFoundError: No module named 'qualcoder'
```

**Comment by ccbogel** [comment]
Hi. I'm guessing you are running the latest (2.8 version) code on Windows.
I presume the 'python' command is using a 3.6 or newer python version, 'py' will use the latest installed version.
Also run this from cmd from the QualCoder-Master folder location:
python setup.py install

Once you have run this, then try each of these to run:
From any directory:
`qualcoder`
From the QualCoder-Master directory:
`python -m qualcoder`
`python qualcoder/__main__.py`

**Comment by gorkemozdemir** [comment]
Hello Colin Curtain, thank you so much for maintaining QualCoder. I encountered with a similar message as well.

Currently running on MacOS 11.3.1 with Python 3.9.7 & pip 21.2.4. I First tried to install QualCoder 2.7 which did not work for me. Then managed to install QualCoder 2.8 with the above mentioned procedure, it works somehow. But have problems on playing media files (wrong video size, freeze, timeline not working, etc.) which effects the usability in a drastic manner.

**Comment by ccbogel** [comment]
@gorkemozdemir Thanks for posting. I do not have any easy solutions for your problems on Mac. I only rarely have access to an old Mac (High Sierra) to test if QC works. 
Some ideas:
Does the media work OK using VLC, without using QualCoder? As QC is using VLC to play media. If VLC is having a problem, you  might have to change the video format.
Is the VLC a 3.x version?
I have not tried large media files, this also may be an issue. I have only tried short media files, up to about 10 minutes long so far.

Ultimately, I may not be able to suggest much more, apart from using an alternative open-source or commercial product.
