### ISSUE TITLE
Req: Spectogram or sonogram on audio files

### ISSUE THREAD

**Issue by gorkemozdemir** [ccbogel/QualCoder#551]
In addition to the waveform view, a spectogram or a sonogram view would be super!
Thanks!

**Comment by ccbogel** [comment]
Interesting suggestion, its a low priority for me at the moment.

**Comment by buscon** [comment]
it is not directly relevant to the main question of this thread, but I am not able to find any waveform view, how can I see that?
I am running version 2.9

**Comment by ccbogel** [comment]
@buscon none of these views have been made.

**Comment by buscon** [comment]
ok, thanks for the clarification. The waveform view and the possibility to code it with the mouse, would improve a lot the usability.

**Comment by ccbogel** [comment]
OK. I have used ffmpeg (you need to install this software) to create a waveform. This is shown in Manage Files -> then open the A/V file. I have only tested this on Ubuntu, I'm not able to test this on other operating systems so far as  I cannot install ffmpeg on my Work Windows computer.  
I also have some ffmpeg code to create a spectrogram also, which I am testing,.

**Comment by ccbogel** [comment]
I will close this issue. Providing you have ffmpeg installed opening A/V in manage files will show a wavwform or spectrogram.
