### ISSUE TITLE
Req: % code of a text

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#552]
In the coding report, it is possible to see how many times a code is used. An interesting feature would be to see what % of text a code represents.

This could be implemented in the following way:
number of words or characters highlighted with a code/total number of words or characters × 100

**Comment by ccbogel** [comment]
@qwertygc 
Do you mean a % along with each  of the individual codings? (which would usually be very small and not likely to be useful)
![pic1](https://user-images.githubusercontent.com/5834638/141195504-6a100f37-1b51-4f65-8428-9cf92e43717e.png)

Or do you mean in the search parameters section where each code is displayed. A total of the text coded / a total of the text in selected text files * 100?
![pic2](https://user-images.githubusercontent.com/5834638/141195697-8f3f2682-cbc5-4842-8ec0-d193089102d9.png)

**Comment by qwertygc** [comment]
Hello, the second solution is better :-)

**Comment by ccbogel** [comment]
I thought I would look at this now. I am realising it will take quite some work.
I need to know what the real benefit of this feature is. 
It will not really help with qualitative analysis.

**Comment by qwertygc** [comment]
It is to find out the coverage rate of a code, to see how much it recurs and comes up in an interview.

**Comment by ccbogel** [comment]
done

**Comment by qwertygc** [comment]
Oh thanks you ! 😁
