### ISSUE TITLE
Req: output condings in context

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#561]
A colleague was telling me that an assistant coded in a minimalistic way, ie short phrases that didn't make much sense in NVivo's reports. Qualcoder allows you to see a selected snippet in context. How about allowing the user to switch on/off a verbose mode in reports? That would show, print, export all codings at the same time in context (ie with x periods before/after the coding, and the codings themselves highlighted). That would be useful as a toggle esp when others do the coding.

**Comment by ccbogel** [comment]
Periods can be tricky. What if I extended the text to include 250 characters before and after the coded section.

**Comment by ccbogel** [comment]
OK I have added a checkbox that will give 250 characters pre- and post- the coded segment.
