### ISSUE TITLE
Req: UI transcription

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#565]
In MaxQDA, there is a nice feature to help with the transcription of audio files. I use parlatype, but unfortunately it is only available on Linux, which is a shame. One suggestion is to integrate a transcription software within QualCoder. The idea is to write text using audio.

Features:
Playing a file with a play/pause
When paused/played, it resumes two seconds before
The possibility to insert timestamps
The possibility to insert interlocutors at the end of the line.
The possibility to vary the speed.

In my opinion, a large part of the player is already available with audio coding.

That's it :-)

**Comment by ccbogel** [comment]
closing, as no feedback received and functionalities are present.

**Comment by qwertygc** [comment]
Hello,
Sorry for the lack of response. Yes indeed, I don't know how I missed it.

Two things:

- A graphical improvement would be to mark what this or that keyboard shortcut corresponds to
- I can't seem to get the name of the person to appear on the screen, even if I press ctrl+1 (with my numeric keypad).

**Comment by ccbogel** [comment]
Yes OK regards more on screen instructions.
You do need to click inside the text area before these controls will work.

**Comment by qwertygc** [comment]
Thanks !

**Comment by ccbogel** [comment]
For your interest, i had a zoom meeting with a PhD student in Berlin yesterday morning. So, more improvements to come.

**Comment by qwertygc** [comment]
Damn, I didn't see the information in time, I'm sorry :/
