### ISSUE TITLE
QualCoder 2.8 won't start, missing qualcoder.py

### ISSUE THREAD

**Issue by josesia-amazon** [ccbogel/QualCoder#566]
**Describe the bug**
When I use the command line to start QualCoder2.8 on MacOS, it gives me the following error:

```
username$ python3 __main__.py
Traceback (most recent call last):
  File "/Applications/QualCoder-master/qualcoder/__main__.py", line 50, in <module>
    from qualcoder.attributes import DialogManageAttributes
ModuleNotFoundError: No module named 'qualcoder'

```
I have followed all Installation steps for MacOS listed at https://github.com/ccbogel/QualCoder/wiki/01-Introduction#macos  

**To Reproduce**
Type in "python3 __main__.py" at the command prompt when in the appropriate directory:

```
username$ pwd
/Applications/QualCoder-master/qualcoder
```

**Expected behavior**
A description of what you expected to happen.
QualCoder brings up its GUI interface

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] Big Sur 11.6

**Additional context**
Tried this with QualCoder-2.8 and with QualCoder master branch. Both have the same error on MacOS

**Comment by ccbogel** [comment]
Closing issue as no feedback provided.
