### ISSUE TITLE
Req: AND for persistance for Attributes dialogue 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#568]
In Coding, Attributes used in filtering files should optionally support AND between attributes as well as the current OR (possibly a NOT too). 

Also, there should be a way for the user to reopen the attributes dialogue and have the attributes selected earlier remembered. Currently, if I click on the attributes button, the dialogue opens and resets the currently selected attributes. If they persisted I could see for info what was previously selected and wouldn't have to set several attributes all over again.

**Comment by ccbogel** [comment]
Updated so that Attributes are remembered now.

**Comment by AndrzejWawa** [comment]
It seems to me that there is still, on default, "OR" betweem attributes. I means filtering files in coding mode.

**Comment by AndrzejWawa** [comment]
So, I think that here is the problem as in the case of issue "Multiple Code Relations", to allow using logical conjunction - https://en.wikipedia.org/wiki/Logical_conjunction. Very helpful for analytical purposes.

**Comment by ccbogel** [comment]
Select attributes (for coding reports and coding-text,img, AV to select files)
Can use an OR or an AND option for file selection based on file (and case) attributes.
