### ISSUE TITLE
"Uncaught Exception" when trying to change settings

### ISSUE THREAD

**Issue by KneckerMcKnack** [ccbogel/QualCoder#572]
**Description**
When trying to save any altered setting (except changing the default authors name) from the settings dialogue, it will create an error:
`Uncaught Exception`
`Traceback (most recent call last):`
`File "/usr/lib/python3.9/site-packages/Qualcoder-2.8-py3.9.egg/qualcoder/settings.py", line 161, in accept cur = self.app.conn.cursor()`
`AttributeError: 'NoneType' object has no attribute 'cursor'`

**Desktop**
 - OS: Manjaro Linux (Arch), KDE 5.22.5 (QT 5.15.2), X11

The settings can be changed in the config file manually. The program also can write data in the config files, for it remembers window settings.

**Comment by ccbogel** [comment]
Thanks, fixed in latest code. This occurs if no project is opened.
If using the 2.8 release, create a project and have it opened first, to avoid the error.

**Comment by KneckerMcKnack** [comment]
Found it by searching for an opensource alternative, love it! It's perfect!
PS: I am Julius btw.

**Comment by ccbogel** [comment]
@KneckerMcKnack thank you very much. ☺
P.s. please send me the vector file.  Its great.

**Comment by KneckerMcKnack** [comment]
I already have! I hope you get my mails?

**Comment by ccbogel** [comment]
The png files, Yes I did, thank you

________________________________
