### ISSUE TITLE
Script to visualize the codebook export

### ISSUE THREAD

**Issue by buscon** [ccbogel/QualCoder#576]
**Is your feature request related to a problem? Please describe.**
I would like to create more interesting visualizations of the codebook. 
Right now there are two possible exports:
1. one it is a text file
2. one it is an xml file (.qdc file)

**Describe the solution you'd like**
A python script to analyse the xml export 

**Describe alternatives you've considered**
I think it is possible to use the .qdc file and use it for visualizing the data.

**Additional context**
I am wondering whether anyone tried to work on visualization of the codebook using python and can share the results.

**Comment by ccbogel** [comment]
@buscon Hello, your request/issue is not clear. "A python script to analyse the xml export"
What exactly do you want?

**Comment by buscon** [comment]
> @buscon Hello, your request/issue is not clear. "A python script to analyse the xml export" What exactly do you want?

what I meant is to have a python script that visualize the data in different forms, possibly with nicer graphics, for example: mindmaps, tree view or using Seaborn.

**Comment by ccbogel** [comment]
Ok. I coild look at Networkx which could be used to create node graphs. Seaborn is for presenting quantitative data, so doesnt seem suitable.

**Comment by ccbogel** [comment]
OK you can create a code graph in Reports > Graphs and export this as a png image.
