### ISSUE TITLE
Error "code already exists" when creating a recently deleted code of the exact same name

### ISSUE THREAD

**Issue by KneckerMcKnack** [ccbogel/QualCoder#578]
How to reproduce:
Create a code of any name (test-01), then delete the code. Create the code with the exact same name (test-01) again.
This will result in the error that this code already exists, though it shouldn't anymore - it must still be in the database I assume.

Circumvent:
When the program is closed once and reopened again, the code can be created again without error.

**Desktop (please complete the following information):**
 - System: Arch Linux / Manjaro
 - Qualcoder Version 2.9

**Comment by ccbogel** [comment]
fixed
