### ISSUE TITLE
Files as rows in matrix

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#579]
Hi,

Is it possible to allow select files as rows in the matrix, not only cases?

Moreover, option for selecting codes as rows (not only as columns) could be other improvement.

**Comment by ccbogel** [comment]
I have added files as rows, so more options in the drop down selection.
To have files not cases, do not select cases.
To have cases not files, select cases.

**Comment by ccbogel** [comment]
can now transpose matrix : "Moreover, option for selecting codes as rows (not only as columns) could be other improvement."

Please test to confirm. Regards CC

**Comment by AndrzejWawa** [comment]
I have such an error.


![image](https://user-images.githubusercontent.com/77200214/148269456-bc5ad7a2-97b4-466e-b980-d43d4e155853.png)

**Comment by ccbogel** [comment]
@AndrzejWawa Sorry. I forgot to upload one file to GitHub. Should be fine now.

**Comment by AndrzejWawa** [comment]
It is wonderful now! Thank you.
