### ISSUE TITLE
Number of findings

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#580]
In the coding report, below "Search parameters", number of obtained findings could be displayed.

**Comment by ccbogel** [comment]
I have done this for text, now for Images and AV

**Comment by ccbogel** [comment]
OK this is now updated. Check the Statistics checkbox to show summary count and percent of file for each code/file selection.

**Comment by AndrzejWawa** [comment]
Hi, the statistics option is very good!

a) However, in this case I mean number of ALL segments obtained in the particulat search (in other words, total number of codings displayed in the report or the sum of all "counts" in the in the statistics). Such a number should be placed rather directly below the "Files" list.

b) Moreover, is it possible to have percentages rounded to two decimal places?

**Comment by ccbogel** [comment]
@AndrzejWawa OK Done this now.

**Comment by AndrzejWawa** [comment]
Hi, thank you, looks very good! Could you only add, at the top, the position "all found segments" as the sum of all identified segments in all codes and files selected in the search?

**Comment by AndrzejWawa** [comment]
Thanks!
