### ISSUE TITLE
Ctrl+z in coding mode

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#584]
Hi,

It is possible to enable ctrl + z shortcut to reverse some of the actions? For example, I had coding with memo and accidentially unmarked it. So, the coding and memo had to be created again.

PS Qualcoder is nice for systematic literature review : )

**Comment by ccbogel** [comment]
I would like to see how it works for a systematic literature review.
Yes I will see if I can do a crtl+z for reversing coding deletions.

**Comment by ccbogel** [comment]
OK I have done Ctrl + Z to undo the last code deletion - this is only in the Code Text section for now.
