### ISSUE TITLE
Bug in the export of SQL table

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#587]
Hi,

When exporting SQL table I noticed two bugs. Firstly, cell A5 is in the different row than further cells. The same problem is in the case of cell A12:

![Export of SQL table](https://user-images.githubusercontent.com/77200214/145596488-91a67201-3c40-4456-9f42-25a46597706b.png)

I think that this may be related to difference in displaying the same rows but in the SQL table in QC (rows 2 and 5 in this case):

![Export of SQL table 2](https://user-images.githubusercontent.com/77200214/145597033-f4944d1f-27f0-4889-9f3f-6b636f8056b4.png)

Moreover, is it possible to export SQL tables without empty rows between rows with data? - however, this is not an important issue and easy to solve with sorting option in the LibreOffice Calc.

**Comment by ccbogel** [comment]
OK. Can you email me the csv file that is created, that contains the error?

**Comment by ccbogel** [comment]
OK. I understand the cause of the problem. At the end of that section of memo text, there is a new line character. This causes Calc to then create a new line/row.
![pic1](https://user-images.githubusercontent.com/5834638/145885635-e399e411-6bff-432e-a02a-8f20734769af.png)
.

**Comment by ccbogel** [comment]
OK. I have updated the export function.
Try it as is first. Then try it with the 'quote option selected'.
Let me know if this resolves the problem.

**Comment by AndrzejWawa** [comment]
Hi.

Ok, but when initating QC through cmd, I have such a problem (normally, I use exe file):

![Error QC](https://user-images.githubusercontent.com/77200214/146053151-9955bbfc-7cce-47c2-b81e-6b964acd9341.png)

**Comment by ccbogel** [comment]
Yes. You need to add a new python module, for Windows:
 py -m pip install SpeechRecognition

**Comment by AndrzejWawa** [comment]
Hi, yes, now it is ok, even without "Quote" option : )
