### ISSUE TITLE
Fedora Linux dependencies & install script - ready for Fedora 35 and python 3.10?

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#591]
**Describe the bug**
I am trying to run `python3 -m qualcoder ` and get the error message

```
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/il/Techy/QualCoder/qualcoder/__main__.py", line 47, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: /lib64/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/local/lib/python3.10/site-packages/PyQt5-5.15.6-py3.10-linux-x86_64.egg/PyQt5/QtCore.abi3.so)

```
This is on Fedora35.

**Comment by ilippert** [comment]
Hmm,
upon further investigation I note that my Fedora 35 does not know either

python3-pyqt5
python3-pil

**Comment by ilippert** [comment]
I searched a bit around, trying to find how the packages are now called - but am not sure what precisely to look for.

https://pkgs.org/search/?q=python3-pyqt5
https://pkgs.org/search/?q=python3-pil

does not immediately help me

**Comment by ccbogel** [comment]
@ilippert 
for pyqt5, I found this page: 
https://fedora.pkgs.org/35/fedora-updates-x86_64/python3-qt5-5.15.6-1.fc35.i686.rpm.html
The package name on the page is:  
python3-qt5

For pil or pillow, On this page:
https://fedora.pkgs.org/35/fedora-x86_64/python3-pillow-8.3.2-1.fc35.x86_64.rpm.html
The package name on this page is:
python3-pillow

**Comment by ilippert** [comment]
Hi, ok, I make some notes here on my research on why it currently runs.

a) Qualcoder install installed files at

`/usr/local/lib/python3.10/site-packages/`

On Fedora, python files are expected at `/usr/lib/python`...

**Comment by ilippert** [comment]
A question, could the dependency of Qualcoder to pdfminer.six also be satisfied by python3-pdfminer?

**Comment by ccbogel** [comment]
Pdfminer.six is currently being maintained and updated. 
I do not believe the earlier pdfminer is being maintained .

**Comment by ilippert** [comment]
thanks
