### ISSUE TITLE
Set up python virtual environment

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#593]
The current fedora installer script uses `pip` to install packages directly. However, this should be avoided within the normal operating system as not to interfere with the system's package manager. Instead, a virtual environment could be set up. see https://docs.python.org/3/tutorial/venv.html

**Comment by ccbogel** [comment]
Sure, I will look at adding instructions for this

**Comment by ccbogel** [comment]
Ok I have updated the instructions to run in a virtual environment on Ubuntu.
You may need to tweak them for Fedora.
