### ISSUE TITLE
Wrong time & timestamp when transcribing audio and video files

### ISSUE THREAD

**Issue by Kyon34** [ccbogel/QualCoder#598]
Hi, I want to use QualCoder for transcribing audio (mp3) and video files (mp4). 

However, the wrong time is displayed while transcribing, resulting in wrong timestamps when using Ctrl + T. 
When I'm actually at say #00:07:35:000# (Time format setting is #hh:mm:ss:SSS#), QualCoder wrongly displays time at 00.07.35. 

I'm using Ubuntu 20.04.3 LTS and QualCoder Version 2.8.

Help on this would be appreciated! Thank you.

![Screenshot from 2022-01-08 12-16-53](https://user-images.githubusercontent.com/46073710/148642563-e5c020f0-cdff-4a9b-9a60-cb8aa6f632b5.png)

**Comment by ccbogel** [comment]
@Kyon34 Hello.
Can you download the latest code (not the 2.8 release), using the green Code button.
![pic1](https://user-images.githubusercontent.com/5834638/148661590-bbe3cf77-4bc1-4ddf-b174-1051b334743c.png)

This latest code works fine when you change the time format in Settings to #hh:mm:ss.SSS#

**Comment by Kyon34** [comment]
Hello and thank you for the fast reply.
Following your instructions I'm on QualCoder version 2.9 now with time format set to #hh:mm:ss.SSS#. However, the issue still remains even though it looks slightly different now:

![Screenshot from 2022-01-09 14-38-07](https://user-images.githubusercontent.com/46073710/148684574-71859832-130f-4777-833b-e2c8bcc4d46f.png)

The #hh:mm:ss.SSS#  format is now displayed for the timestamps in the transcription, but minutes are still shifted to seconds etc.

**Comment by ccbogel** [comment]
thanks for the feedback. I will have another closer investigation.

**Comment by ccbogel** [comment]
OK it should be fine now. please double check.

**Comment by Kyon34** [comment]
Perfect, works fine now on all time formats.
Thank you!
