### ISSUE TITLE
Import from Nvivo .qdpx file shows no text file.

### ISSUE THREAD

**Issue by donnekgit** [ccbogel/QualCoder#599]
Close the current project.
Project → Import → REFI-QDA Project Import
Click OK on the info panel.
Give a name for the new project, Save.
Select the .qdpx file, and click OK on the info panel.

There is only one file in this export, which I can see OK (as a .txt file) if I unzip the .qdpx file, and I can also see the XML .qde file.

However, after the above import steps, there is no file in the Files and Cases → Manage files window.

Coding → Code text says the project contains no text files.

If I go back to Manage files, and import the .qdpx file itself (!), and then go to Code text, I can see the list of codes used by the coder, and even export them to a codebook.  But of course there's no text there to which they refer, and all are coloured grey.

I seem to remember that last year I imported a .qdpx file OK, so I wonder if anything has changed (either in QC or in Nvivo) since then?

**Comment by ccbogel** [comment]
@donnekgit Hello. I am presuming this is using the latest code (the 2.9 QualCoder-Master) ?
I cannot resolve this yet, as I need a lot more information.
If the project is not sensitive information, you could email me the zipped qdpx folder so that  I can try and recreate the error and identify the problem.

**Comment by donnekgit** [comment]
Yes, it's 2.9, updated yesterday.

After a bit of investigation with my colleague, I seem to have solved this.  Basically, a second test .txt file opened fine from the .qdpx import, and comparing the unzipped .qdpx files for both revealed a .pdf and .txt in the Sources folder for the first, and a .docx and .txt in the Sources folder for the second.  Sure enough, she had imported a .pdf into Nvivo for the first (non-working) example, and a .txt file for the second (working) example.  QC then tries to display the pdf, can't, and we get a blank window.

However, the good news is that we can retrieve the coding from the pdf version by editing its .qpe file.  Open that, and go to the `<Sources>` tag.  Change this:
`
<PDFSource guid="172ad2b6-0e5f-485c-b4d9-d1d74356393d" name="L1_transcript" path="internal://172ad2b6-0e5f-485c-b4d9-d1d74356393d.pdf" currentPath="" creatingUser="e353edb1-bbeb-4366-87d9-d14fb4d90d82" creationDateTime="2022-01-07T12:14:32Z" modifyingUser="e353edb1-bbeb-4366-87d9-d14fb4d90d82" modifiedDateTime="2022-01-07T12:14:32Z">
      <Description />
      <Representation guid="172ad2b6-0e5f-485c-b4d9-d1d74356393d" plainTextPath="internal://172ad2b6-0e5f-485c-b4d9-d1d74356393d.txt">
`
to this:
`
<TextSource guid="172ad2b6-0e5f-485c-b4d9-d1d74356393d" name="L1_transcript" plainTextPath="internal://172ad2b6-0e5f-485c-b4d9-d1d74356393d.txt" creatingUser="e353edb1-bbeb-4366-87d9-d14fb4d90d82" creationDateTime="2022-01-07T12:14:32Z" modifyingUser="e353edb1-bbeb-4366-87d9-d14fb4d90d82" modifiedDateTime="2022-01-07T12:14:32Z">
      <Description />
`
So you change `<PDFSource` to `<TextSource`, and change the `path=` to the `plainTextPath=` found in `<Representation`, and then delete that.

At the bottom of the file, delete `</Representation>` and change `</PDFSource>` to `</TextSource>` just before the `</Sources>` tag.

Then delete the .pdf file from the Sources folder (for tidiness), and rezip the Sources folder and the .qpe file to give a new .qdpx file.

Go through the REFI-QDA Project Import steps above, and now the .txt file shows up in the Manage window.  Going to the Coding window shows the codes, and clicking the filename shows the coded text.

All the codes are marked in grey, so for each one right-click and select a code-colour, which will then show on the coded text.

It may be that the above could be automated in some way if the string "PDFSource" is found in the .qpe file, but it's not a major pain to do it manually.  So QC wins this round!

Sorry for the false alarm!

**Comment by ccbogel** [comment]
@donnekgit Thank you for your investigation into this. Im glad you found a solution.
It is not a false alarm, it is an issue that I will have to add code in to fix.
As the pdf text representation should have been imported, this bit below.
`<Representation guid="172ad2b6-0e5f-485c-b4d9-d1d74356393d" plainTextPath="internal://172ad2b6-0e5f-485c-b4d9-d1d74356393d.txt">`

This is a big ask, but, if you/or your colleague, could create a faux project in Nvivo that does not import into QualCoder (re-create the original problem), with a small pdf and maybe a couple of codes with a small amount of text coded.
Then create the qdpx folder and email it to me. I would like to work with this to automate a solution.
A part of this improvement would also be to see why the colours are coming across as gray, and see what I can do to fix this also.

By the way: in the original problem qdpx, was there both the pdf and a file with the text representation?  - As this is important to get a suitable solution.

**Comment by donnekgit** [comment]
@ccbogel Oh, cool - thanks.  We'll do a test pdf and check that it doesn't load, and then send it on ?tomorrow.

>  in the original problem qdpx, was there both the pdf and a file with the text representation?
Yes, there was.

> I hope you are finding QualCoder good to use
Yes, indeed, and thanks for responding to the suggestions!  The main aim of the current work is in fact to move data from a proprietary format to an open one.

**Comment by donnekgit** [comment]
Sent a test file that recreates the original problem.  Thanks!

**Comment by ccbogel** [comment]
@donnekgit 
The email was not received. hotmail blocks various file types and sizes, even before I receive them.
Is is possible to add the zipped project folder here, or try sending to the email address again, but replacing the file ending from .qda to .zip

**Comment by donnekgit** [comment]
Oh, fine.  Added it here, replacing the .qdpx with .zip.
[FeminismTest.zip](https://github.com/ccbogel/QualCoder/files/7861044/FeminismTest.zip)

**Comment by ccbogel** [comment]
@donnekgit Thank you, received.
The first thing I see in the project xml, Nvivo does not provide any colours for the codes. That's why QC defaults to a gray colour.
I will be working through refining the refi.py file and trying to fix the text representation import.

**Comment by donnekgit** [comment]
@ccbogel I asked my colleague about the colours, and she said she hadn't specified any (which would account for everything being grey!).  Sorry about that.  I'm attaching another version where she has added colours, and these seem to come through if I reimport the .qdpx as a text file (as I did in the very first post in this thread).  Apparently, though, in Nvivo these colours don't actually appear on the text, but only on the nodenames, and on the sidebars (coding stripes?) they print alongside the text, even though it is a longstanding user request to have them printed on the text, as in QC.
[FeminismTest2.zip](https://github.com/ccbogel/QualCoder/files/7869476/FeminismTest2.zip)

**Comment by ccbogel** [comment]
@donnekgit I have made some changes to the refi-qda import. It seems to work OK now. I also tested some of my other qdpx folders that I was given earlier (from Nvivo, maxqda, Quirkos, Atlas.ti), and no errors so far.

**Comment by donnekgit** [comment]
@ccbogel Oh, excellent!  Yes, that works fine now, and also imports the colours in the one she marked with colours. Thank you!

**Comment by ccbogel** [comment]
Great, thank you :)
