### ISSUE TITLE
View in context in "show coded files" in coding mode and zoom shorcuts

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#601]
1) You cannot show in context image codings, when you click "show coded files" in text coding mode.

2) Moreover, when you see in context image coding in coding report, you cannot use shortcuts to zoom-in and zoom-out.

**Comment by ccbogel** [comment]
Hi @AndrzejWawa 
1. the coded image is shown in the show coded files menu option, but not in the context of the overall image. This is the same issue for text - text is not shown in context when using the right-click 'show coded files'
![pic1](https://user-images.githubusercontent.com/5834638/150025842-550d9da2-f2e2-434e-9eb8-685d92f10d6f.png)

**Comment by AndrzejWawa** [comment]
1. In the coding mode you already can see codings from "show coded files" in the context. Example:

![image](https://user-images.githubusercontent.com/77200214/150118604-fe4f259c-e4bb-4e70-a48b-41fe7b7e1a75.png)

However, it is still not possible for images in coding mode's "show coded files".

2. Shortcutts still do not work in the image in context in coding report:

![image](https://user-images.githubusercontent.com/77200214/150118994-ad69ddf3-f17f-4131-8a59-8f02d360b06e.png)

However, both issues are not very important.

**Comment by ccbogel** [comment]
@AndrzejWawa - did you download the latest code?
Yes the shortcuts do work + and - for zooming in and out in the image. I have checked again right now.
The coded area in the image is shown with the dashed border. So this is in context of of image - as is shown in your picture.
Unless I am misunderstanding something? - these things are correct.

**Comment by AndrzejWawa** [comment]
Hi, yes, everything is good. It was my mistake - I downloaded the new file but ran the old one :)

**Comment by ccbogel** [comment]
ok
