### ISSUE TITLE
Open window for memos

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#602]
Hi,

Recently I often write memos in coding mode basing on the coding report. Is it possible to have open window for writing memos and, at the same time, using coding report? Now, if you want change coding mode to reports mode, you have to close window for writing memo:

![image](https://user-images.githubusercontent.com/77200214/150119920-bcf0074f-5c56-456e-8861-8ab56f5634e1.png)

**Comment by ccbogel** [comment]
@AndrzejWawa I cannot do what you are asking here.
