### ISSUE TITLE
can't delete file in manage file view

### ISSUE THREAD

**Issue by adcodercdn** [ccbogel/QualCoder#603]
I've tried deleting a file by right-clicking and by the clicking the 'x' at the top. Neither work. I get the message below (see next comment)

**Comment by adcodercdn** [comment]
Tips for how to delete a file in the manage file view? I get the message below when trying:

![qualcoder-cantdelete](https://user-images.githubusercontent.com/98040117/150164118-5536b51a-63e7-440f-a1a6-134686a4a22e.png)

**Comment by ccbogel** [comment]
@adcodercdn Thank you for reporting the error. I have fixed the error. Please download the latest code from the Green Code button and install using he command line - see the ReadMe instructions for Windows to install the python modules and build the program.

**Comment by ccbogel** [comment]
the latest code release 2.9 should fix this

**Comment by adcodercdn** [comment]
screenshot

**Comment by ccbogel** [comment]
Damn, yes you are right. I missed something.
OK. well first make a backup of your project. Then identify the id number of the file you need to delete. You can go to settings to tick show ids.
let us say as an example the file id is 999
Then go to Reports > Sql Statements
In the the top box enter each of these statements and run each one, one at a time:
delete from source where id = 999    
Then press the Cogs button
delete from code_text where fid = 999
Then press the Cogs button
delete from annotation where fid = 999
Then press the Cogs button
delete from case_text where fid = 999
Then press the Cogs button
delete from attribute where attr_type ='file' and id=999
Then press the Cogs button
