### ISSUE TITLE
Code already exists - workaround

### ISSUE THREAD

**Issue by donnekgit** [ccbogel/QualCoder#605]
Just noting this in case it helps others.

Occasionally QC will report that you can't add a codename because it is a duplicate (eg you might have "Organisational strengths - already notified", and you want to add "Organisational types").  This happens only sporadically (maybe a misfiring regex?), but the workaround is simply to add another codename with a dummy name, and then rename that to the one you need.

**Comment by ccbogel** [comment]
Thanks, i will add a note about this to the manual.

**Comment by ccbogel** [comment]
added information on this to the Wiki manual.
