### ISSUE TITLE
Codebook import: note on usage

### ISSUE THREAD

**Issue by donnekgit** [ccbogel/QualCoder#606]
Another note on usage, rather than a bug.

To transfer a codebook between projects, don't use Project → Export → Export codebook in the old project.  There seems to be no way to import that into the new project.

Instead, use Project → Export → REFI_QDA Codebook export in the old project..  This will produce a .qdc file that is importable to the new project via Project → Import → REFI_QDA Codebook import

BUT: Note that you have to import the codebook as the first step after you create the new project, BEFORE you add files.  If you add files, and then import the codebook, the codes will not show.  In that case, just delete the new project and start again, this time importing the codebook first.

**Comment by ccbogel** [comment]
To transfer a codebook between projects, don't use Project → Export → Export codebook in the old project. There seems to be no way to import that into the new project. Correct, this export is to make a text file of the codes and their rules, and not used for importing.

**Comment by ccbogel** [comment]
This will produce a .qdc file that is importable to the new project via Project → Import → REFI_QDA Codebook import
BUT: Note that you have to import the codebook as the first step after you create the new project, BEFORE you add files. If you add files, and then import the codebook, the codes will not show. In that case, just delete the new project and start again, this time importing the codebook first.

To clarify:
You can have files already in an existing project, and then import the codebook. However, the newly imported codebook will not be associated with any existing codings in the project. 
If you like,  I can add a note in the manual that its recommended to import the codebook before importing files into a project.

**Comment by donnekgit** [comment]
> However, the newly imported codebook will not be associated with any existing codings in the project.

When I did that, the codename box was empty.  So the codenames are actually there, but not accessible? But how would I use them in a new file to be coded then?

**Comment by ccbogel** [comment]
This is a bit tricky to understand/answer here. I will be at work in an hour, could Zoom then?

**Comment by donnekgit** [comment]
Haha! Sorry, I'd just knocked off! I'm assuming you're on the other side of the globe - 9.00am Sydney would be 10.00pm here, so I'm happy to Zoom (my) tonight if you like, when you get in to work (your) tomorrow.

**Comment by ccbogel** [comment]
@donnekgit HI. Please email me on colin.curtain@utas.edu.au and we can organise this. 
10:00 pm Thursday, in London, UK is 9:00 am Friday, in Hobart, Australia.
