### ISSUE TITLE
Selecting codenames: note on usage

### ISSUE THREAD

**Issue by donnekgit** [ccbogel/QualCoder#607]
When there is a long list of codenames, it can be difficult to read the entire list to light on the one you are looking for.  To shrink the list, right-click in it and select `Show codes like`.  Type a word from the codename you want to find into the search box and click OK.  The list will shrink to those codenames containing that word.  You can do the same again to further shrink that list if necessary.

To go back to the full list, repeat the process, but leave the search box empty, and click OK.

Note that the search box (currently) cannot use regular expressions, so you cannot search for "Observations" and "observations" simultaneously by using `(O|o)bservations` or even `.bservations`.  One way around this would be to not use capitals in codenames.

**Comment by ccbogel** [comment]
@donnekgit so , are you suggesting more instructions in the manual?

**Comment by donnekgit** [comment]
Yes - the last two points threw me for a bit.

**Comment by ccbogel** [comment]
At the end of the page under Categories and Codes heading there is information on this.
https://github.com/ccbogel/QualCoder/wiki/07-Coding-Text
