### ISSUE TITLE
Move visualization in a specific menu

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#61]
As a user IMHO it makes sense to have visualization in a different category, maybe next to reports. Right now graph is in the coding menu, which is not intuitive, furthermore when QualCoder will be able to visualize in different ways, it would look intuitive having a "visualization" menu and there all the options for various graphs/charts.

**Comment by ccbogel** [comment]
I have moved the graph to the Reports menu for now. Later when there are many options I will consider adding a graphing menu section. I have not done a new Debian file for this small change yet.
