### ISSUE TITLE
QualCoder 2.9 executable on Ubuntu 18.04: GLIBC_2.29 error

### ISSUE THREAD

**Issue by stragu** [ccbogel/QualCoder#613]
**Describe the bug**
I tried to run the latest version's Ubuntu executable on Ubuntu 18.04.6 and got the following:

```bash
./QualCoder-2.9-Ubuntu 
[22766] Error loading Python lib '/tmp/_MEIRVZfQ0/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIRVZfQ0/libpython3.8.so.1.0)
```

Looks like Ubuntu 18.04 is stuck with GLIBC version 2.27:

```bash
apt-cache policy libc6
libc6:
  Installed: 2.27-3ubuntu1.4
  Candidate: 2.27-3ubuntu1.4
  Version table:
 *** 2.27-3ubuntu1.4 500
        500 http://au.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.27-3ubuntu1.2 500
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     2.27-3ubuntu1 500
        500 http://au.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

Is this just a case of "QualCoder is not available for Ubuntu 18.04, unless you are able to upgrade to GLIBC 2.29 somehow."?
Happy to help out and do some more tested if needed :slightly_smiling_face: 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6
 - Version 2.9

**Comment by ccbogel** [comment]
OK thanks for that - I updated the release information. I do not know how to resolve this. So the longer install in your other issue I have added some more detail that might help.

**Comment by ccbogel** [comment]
Closing this issue. Note: I have added how to install QualCoder into a virtual python environment,
