### ISSUE TITLE
Possible to store a 'text file' with text highlights pasted from external applications? 

### ISSUE THREAD

**Issue by carloscadux** [ccbogel/QualCoder#614]
Hi,
I'm using QualCoder (2.9). 
As shown in the screen-recording (https://tinyurl.com/ybrjfra9), I pasted into a QualCoder 'text file' some content with highlight from (a) web browser, and (b) Zotero note.

Although initially QualCoder recognizes and parses the highlighted content, it is removed automatically by QualCoder later, after closing the 'edit text dialog.
 
Is it possible to store a 'text file' with text highlights pasted from external applications?
 
Thank you,
Carlos

**Comment by ccbogel** [comment]
Hello Carlos,
External highlights cannot be kept. The database stores only the plain text. The copy paste that you use (from zotero or wiki) temporarily includes the original highlighting,
