### ISSUE TITLE
Possible to rename a 'Text file' created within QualCoder?

### ISSUE THREAD

**Issue by carloscadux** [ccbogel/QualCoder#615]
I'd appreciate your help.
As shown in the screen-recording (https://tinyurl.com/yammnznx), I created 'Text file' within QualCoder, but couldn't rename it later.

I could see a 'rename' item on the context menu of a code, but not on manage files menu.
Also I could 'rename' a case by double-clicking its name, but double-click on 'text file' open its content instead.

Is it possible to rename a 'Text file' created within QualCoder? 
 
Thank you,
Carlos

**Comment by ccbogel** [comment]
Hello Carlos. I deliberately did not add a special function to rename a file. I think this could case problems later on when linking or using original files.
You can rename the file using SQL.
Go to Report > SQL Statements, in the top box write this SQL statement:

update source set set name = "A new name" where name="File name"

Then press the Cogs button to run the SQL statement.

**Comment by ccbogel** [comment]
completed
