### ISSUE TITLE
Running at Win10

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#617]
Hi,

I have a new laptop with Win10 and the following error:

![Error Windows 10](https://user-images.githubusercontent.com/77200214/154249545-ebb87599-02f7-42af-8e4f-96dbcdd7fb3d.png)

**Comment by ccbogel** [comment]
Ok. It is looking for the vlc library.
First. Make sure you have a current 64 bit version of VLC installed.

**Comment by AndrzejWawa** [comment]
Thanks, it works with VLC, (64 bit).
