### ISSUE TITLE
Delete Button Does Not Work

### ISSUE THREAD

**Issue by agsolbe2** [ccbogel/QualCoder#619]
**Describe the bug**

I am currently using the recent release of qualcoder. When I add image files to the project and try to delete the ones I don't want with the delete button the delete button does not work. I have downloaded the application in my Documents directory if that helps.

**To Reproduce**

Add in a file and try to delete the jpg file using delete button

**Expected behavior**
A description of what you expected to happen.

I expected a selected file to be deleted

**Screenshots**

![error](https://user-images.githubusercontent.com/40770170/155822715-4894c17d-6ab8-4390-8ad7-dd59b272c9da.JPG)

**Desktop (please complete the following information):**
 Windows 10 Home
21H2
**Additional context**

**Comment by agsolbe2** [comment]
This worked thank you, but is there a way to refresh the list of files in the program without having to close out the program to refresh the list of files?

**Comment by ccbogel** [comment]
Yes. Go to the menu bar, then select mabage files. Instead of directly clickingnon the files tab.

**Comment by agsolbe2** [comment]
This refresh also worked thank you.
