### ISSUE TITLE
Explain why certain features are greyed out

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#62]
Right now I can visualize only with a "view graph 2", graph 1 option is greyed out, it is not clear whether this is because the option has not yet been implemented or it is due to the data I am using. It would be nice, when you hoover a greyed option, to see a popup telling the user why such option is not available.

**Comment by ccbogel** [comment]
Good feedback thanks, I have removed the greyed out options now. I won't make a new Debian file just yet for this change.
