### ISSUE TITLE
Deletion error

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#628]
Hi,

When I want to delete file, I have this error:

![Error](https://user-images.githubusercontent.com/77200214/159374670-ddbbc9fa-e53b-466a-9e96-3acd906981d0.png)

**Comment by ccbogel** [comment]
Yes that is an issue identified in 2.9 release:
https://github.com/ccbogel/QualCoder/releases/tag/2.9
There are instructions near the end of the 2.9 release page.
The latest code has fixed this.

Try this:
Save a backup of the project.
Go to Reports > Sql Statements
Get the id of the source file, lets say it is 999
Then run each of these delete statements:

delete from source where id = 999
delete from code_text where fid = 999
delete from annotation where fid = 999
delete from case_text where fid = 999
delete from attribute where attr_type ='file' and id=999

**Comment by ccbogel** [comment]
Further update, I detected the error **again** which I thought I had fixed.
I have now updated this - now fixed!
