### ISSUE TITLE
Font colors in the image coding

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#629]
Hi, I noted that colors of names of codes are not appropriated to colors of codes and dark mode in the image coding (and maybe in the video coding too). Such appropriation, e.g. white or black color of font depending on color of code or dark/light mode, has been introduced by you in the text coding and works very good.

However, it is not huge problem for me as I work mainly in the text coding.

**Comment by ccbogel** [comment]
fixed
