### ISSUE TITLE
Debian-Package does not install dependencies

### ISSUE THREAD

**Issue by steinhmor** [ccbogel/QualCoder#63]
Hi,
I would love to test this program and used the 1.7 .deb-file to install.
Running the software from the terminal I got several errors, because some phython-extentions where missing. I tried to install them step-by-step (pdfminer, configparser, PyQt5, ebooklib) and got stuck with this one: "HTMLParseError". I was not able to find this plugin. But regardless of this I was surprised, that the dependencies were not installed automatically. Do you know why and what packages I also need?
BTW: I always tried to start the app with python instead of python3 to see the missing packages, because I was not able to find the python3-packages - or are these the same?

**Comment by ccbogel** [comment]
Hi, thanks for the feedback. What OS were you using? HTMLParseError is not a package, it is an error. If there are other lines around this it would be good to see them. 
From terminal run the following lines too, to make sure all were installed into python3 and not python2:
sudo apt install python3-pip python3-pyqt5 python3-lxml python3-pil python3-ebooklib python3-ply python3-six python3-chardet
sudo python3 -m pip install pikepdf pdfminer.six

Python3 and python2 are different, and when you install packages the packages might go into one or the other python unless clearly stated - as in the above terminal lines. Its a problem with python.

**Comment by steinhmor** [comment]
Hi, and thanks for your quick reply!
the error after running python /usr/share/qualcoder/qualcoder.py is:
```
Traceback (most recent call last):
  File "/usr/share/qualcoder/qualcoder.py", line 54, in <module>
    from manage_files import DialogManageFiles
  File "/usr/share/qualcoder/manage_files.py", line 66, in <module>
    from html_parser import *
  File "/usr/share/qualcoder/html_parser.py", line 9, in <module>
    from html.parser import HTMLParser  #, HTMLParseError  # Python 3.5 does not have HTMLParseError
ImportError: No module named html.parser
```
i tried to run the suggested comments and after the second one i got this error:

`              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    In file included from src/qpdf/utils.h:11:0,
                     from src/qpdf/utils.cpp:12:
    src/qpdf/pikepdf.h:15:10: fatal error: qpdf/PointerHolder.hh: Datei oder Verzeichnis nicht gefunden
     #include <qpdf/PointerHolder.hh>
              ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/qpdf/object.o build/temp.linux-x86_64-3.6/src/qpdf/pipeline.o build/temp.linux-x86_64-3.6/src/qpdf/page.o build/temp.linux-x86_64-3.6/src/qpdf/pikepdf.o build/temp.linux-x86_64-3.6/src/qpdf/qpdf.o build/temp.linux-x86_64-3.6/src/qpdf/annotation.o build/temp.linux-x86_64-3.6/src/qpdf/qpdf_pagelist.o build/temp.linux-x86_64-3.6/src/qpdf/object_repr.o build/temp.linux-x86_64-3.6/src/qpdf/object_convert.o build/temp.linux-x86_64-3.6/src/qpdf/utils.o -lqpdf -o build/lib.linux-x86_64-3.6/pikepdf/_qpdf.cpython-36m-x86_64-linux-gnu.so
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/object.o: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/pipeline.o: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/page.o: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/pikepdf.o: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/qpdf.o: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/annotation.o: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/qpdf_pagelist.o: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/object_repr.o: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/object_convert.o: Datei oder Verzeichnis nicht gefunden
    x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/utils.o: Datei oder Verzeichnis nicht gefunden
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ii61xgvh/pikepdf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sularawz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ii61xgvh/pikepdf/`

**Comment by ccbogel** [comment]
Hi again. 
My apologies HTMLParseError is a part of the html.parser module and not an error.
Line 9 in html_parser.py: from html.parser import HTMLParser works for me. 
I am using python 3.5.2  perhaps earlier versions use an older naming convention.
You could try replacing line 9 with: from HTMLParser import HTMLParser 
- this may work for older versions of python.

I do not know why the qpdf module did not compile for you. However, the program should work fairly well without it.

**Comment by steinhmor** [comment]
i was now able to install the missing packages using pip and the software now runs :-)
