### ISSUE TITLE
supporting csv or spreadsheet file formats

### ISSUE THREAD

**Issue by meefen** [ccbogel/QualCoder#633]
QualCoder can import csv files, which is great.

But the coding interface renders a csv file as plain text, losing the table structure. 

Is it possible to render a csv file as a table so that the coder can code individual cells?

**Comment by ccbogel** [comment]
Hi I think I understand your requirement. So to be able to code within each cell of a csv. I have not considered this at all. 
Currently, when importing a csv survey. A column can be designated 'qualitative' on import and the text from each cell is combined into one text 'file' aka database entry for coding.
I am not sure I can enact this at all easily.

**Comment by ccbogel** [comment]
closing this issue now
