### ISSUE TITLE
Export graph image does not work

### ISSUE THREAD

**Issue by Bleighhhh** [ccbogel/QualCoder#641]
Descritpion
I try to export the code graph and I get this error: 
Traceback (most recent call last):
  File "/home/pietro-k/Programmi/QualCoder-master/qualcoder/lib/python3.10/site-packages/qualcoder/view_graph.py", line 153, in export_image
    image = QtGui.QImage(max_x, max_y, QtGui.QImage.Format.Format_ARGB32_Premultiplied)

TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(QSize, QImage.Format): argument 1 has unexpected type 'float'
  QImage(int, int, QImage.Format): argument 1 has unexpected type 'float'
  QImage(bytes, int, int, QImage.Format, cleanupFunction: Callable[..., None] = 0, cleanupInfo: object = 0): argument 1 has unexpected type 'float'
  QImage(bytes, int, int, int, QImage.Format, cleanupFunction: Callable[..., None] = 0, cleanupInfo: object = 0): argument 1 has unexpected type 'float'
  QImage(PyQt6.sip.voidptr, int, int, QImage.Format, cleanupFunction: Callable[..., None] = 0, cleanupInfo: object = 0): argument 1 has unexpected type 'float'
  QImage(PyQt6.sip.voidptr, int, int, int, QImage.Format, cleanupFunction: Callable[..., None] = 0, cleanupInfo: object = 0): argument 1 has unexpected type 'float'
  QImage(List[str]): argument 1 has unexpected type 'float'
  QImage(str, format: str = None): argument 1 has unexpected type 'float'
  QImage(QImage): argument 1 has unexpected type 'float'
  QImage(Any): too many arguments

To reproduce it simply code some text and categories (2 levels of categories) and then try to export the image you get. 

**Expected behavior**
I should save the image  but I do not get it.
**Screenshots**
I copied above the issue.

**Desktop (please complete the following information):**
 - Kubuntu 22.04 kernel 5.15-0-27-generic and python 3.10.4

**Comment by AndrzejWawa** [comment]
Moreover, the scope of png is limited and not always all graph is catched on png. But, maybe there is justified reason for this.

**Comment by Bleighhhh** [comment]
> 

Do you have any idea about how can I solve this? I kind of need this exported asap

**Comment by AndrzejWawa** [comment]
In the newest code Colin solved this. Moreover, you can make simply print screen and cut the graph in paint.

**Comment by Bleighhhh** [comment]
> In the newest code Colin solved this. Moreover, you can make simply print screen and cut the graph in paint.

How do I get the newest code? I downloaded the program zip from here yday. It would be far better otherwise I will do as you suggested.
Thank you for your time and program

**Comment by ccbogel** [comment]
@Bleighhhh download the zip again, using the green Code button. Then install again, following the command line install instructions. 
Whic operating system are you using, by the way?

**Comment by Bleighhhh** [comment]
> @Bleighhhh download the zip again, using the green Code button. As the code has been updated. Then install again, following the command line install instructions again.

I am on Kubuntu 22.04 I did what you say yesterday. I see there is a new upload for 4 hours ago, I hope that's it. Thank you so much! Have a nice day

**Comment by ccbogel** [comment]
Ok. Im off to sleep. I can check again here in about 10 hours from now. To check if it worked for you.

**Comment by ccbogel** [comment]
Im guessing it was resolved.
