### ISSUE TITLE
Rotate image (low priority)

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#642]
I found that sometimes it would be helpfull to be able to rotate image in coding mode as well as reports mode/show coded files etc. However, not very important for me personally at this moment.

**Comment by ccbogel** [comment]
Can now rotate the image in show file image and on coding mode.

**Comment by ccbogel** [comment]
OK I will close this issue. 
In Report Codes - right click near the image result to rotate the image 180 degrees. I could not make a successful version to rotate 90 or 270 degrees. (as width and height of the format for that section was not able to be updated).
