### ISSUE TITLE
Alphabetical order

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#645]
It seems to me that alphabetical order in manage files does not work for number greater than 10, it is possible to solve this?

**Comment by ccbogel** [comment]
I will try. Where was this occuring?

**Comment by AndrzejWawa** [comment]
Manage files, e.g.

![obraz](https://user-images.githubusercontent.com/77200214/167381609-6c638525-a95e-4b1b-bc97-84d83ef98c8f.png)
