### ISSUE TITLE
Search box in coding report

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#648]
Hi, during work I have found that search box in coding reports could be often helpful, e.g. to control coding process and quickly find needed information.

**Comment by ccbogel** [comment]
Is this when you have really long search results?

**Comment by AndrzejWawa** [comment]
Hmm, I think that it would be helpful even in short search results but when you have extensive codings or when you intensively analyse many search results.

**Comment by ccbogel** [comment]
done

**Comment by AndrzejWawa** [comment]
Thanks! It is very practical.
