### ISSUE TITLE
Highlighting the whole row in managing files

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#649]
Hi,

Now, I'm working a lot with files mangage and attributes. I noted that it would be helpful to be able to highligt the whole row (after clicking the added number of row). This is because when you have in column 1 name of file, and in column, e.g. no. 10, one of the attributes, it is sometimes difficult to realise to which file it belongs.. Highlighting the whole row should resolve this problem (as in the LO Calc or Excel). Similar option, to highlight the whole columns could be added through clicking their headings). Moreover, introducing visible numbers of rows (and, potentially, columns) should be also convenient.

And. consequently, these solution could be introduced to other tables, e.g. cases.

**Comment by ccbogel** [comment]
I cannot easily highlight the row.
Instead I have added a label above which shows the file name when you click on a table cell.

**Comment by AndrzejWawa** [comment]
Ok, it is already very helpful!

**Comment by AndrzejWawa** [comment]
I noted that highligting the whole row/column and numbers of rows already exist in SQL, to it is not addressed for it.

**Comment by ccbogel** [comment]
hmm. I cannot see this happening in my sql. I nm working on Linux Ubuntu right now.

**Comment by AndrzejWawa** [comment]
I use Windows 10

![obraz](https://user-images.githubusercontent.com/77200214/168060701-0551ac70-1219-4ab9-97e6-6b6daa3fa63f.png)

**Comment by ccbogel** [comment]
I cannot do this easily, as the table cells can be individually clicked/edited. This is different to the other SQL table, where this is not allowed.
However, I did add that test box showing which file was currently clicked on.
