### ISSUE TITLE
Assigning an audio clip to a transcribed segment

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#65]
Hi,
I don't know if this functionality is implanted and if is useful, but i would like implant a link beetween the audio coded and text coded, for mark the text with timecode (the extract of transcription is between 05:02 and 05:49 for example).

![image](https://user-images.githubusercontent.com/4261986/74874742-79494700-5361-11ea-9a87-acb9981dcdae.png)

**Comment by ccbogel** [comment]
There is no functionality for this, unless time stamps are inserted.
 I could make some changes to allow the user (you) to add start and end times to the coded text segment.
OR
perhaps select the coded text and link it to the coded audio segment.
These are ideas.

**Comment by qwertygc** [comment]
Yes, the second choice is exactly what i have thought.

By the way, i have never understand how use time stamp for that usage.

**Comment by ccbogel** [comment]
OK, I have added function to add text to segment.

1 Create segment:
![v1](https://user-images.githubusercontent.com/5834638/76758932-cdb7d900-67de-11ea-8caa-f51786d69cf7.png)

2 Select text and choose menu option (right click):
![v2](https://user-images.githubusercontent.com/5834638/76759004-ea541100-67de-11ea-83a3-030b79293a61.png)

3 Right click for menu option on the segment:
![v3](https://user-images.githubusercontent.com/5834638/76759052-0b1c6680-67df-11ea-8712-1c0a19f05e36.png)

4 The text now has the same code assigned. The text can be right-clicked and the audio/video can play:
![v4](https://user-images.githubusercontent.com/5834638/76759163-3bfc9b80-67df-11ea-9a94-1f599b5e9462.png)

5 The text with mouse hover shows the time positions
![v5](https://user-images.githubusercontent.com/5834638/76759195-520a5c00-67df-11ea-94f3-3cfefc957851.png)

Please experiment, and tell me this is what you want.

**Comment by qwertygc** [comment]
OK with your pictures it's clear and your resume my wish. I not sure for step 2. Maybe it's more ergonomic audio to text rather than text to audio.

**Comment by ccbogel** [comment]
Ok. I understand.  I will try and make linking from audio segment to text.

**Comment by ccbogel** [comment]
OK, now it is possible to select av segment and assign it to selected text

**Comment by qwertygc** [comment]
Think !
