### ISSUE TITLE
Introduction of values list

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#650]
Hi,

It would be helpful to introduce displaying of values list, when introducing values for attributes in files and cases manage. This was introduced in sorting files, by attribute, in coding mode.

**Comment by ccbogel** [comment]
Not sure what you are asking here?

**Comment by AndrzejWawa** [comment]
I mean displaying this information on what values of certain attribute already exist. It was introduced in filtration of files in coding mode, but not in manage files and manage cases.

![obraz](https://user-images.githubusercontent.com/77200214/168048635-30e6cdf3-1ae9-468e-abe0-d0763c5afbad.png)

**Comment by ccbogel** [comment]
Ah. OK, I understand now.
I _might_ fix this in this release.
I am not planning to do many more features or changes now, as I want to do all the extra work needed to get the 3.0 release prepared. (Language updates, and Instruction Manual Updates)

**Comment by AndrzejWawa** [comment]
Sure, good luck!

**Comment by ccbogel** [comment]
updated

**Comment by AndrzejWawa** [comment]
I think that the value list should not be limited to 10. It is usefull as far as it shows all of the used values because the pursposes are, for example:
a) detect typos, e.g. good, goodd, god,
b) detect duplicates, e.g. good, well, nice,
c) select most suitable value.

So, I suggest that the tooltip should contain all of the already used values, however, it will be displayed only by clicking right-click option "show values list".

And the same solution in "show files with the file attributes" in the coding mode.
