### ISSUE TITLE
Allow for coding material that comes simultaneously from different sources

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#651]
**Is your feature request related to a problem? Please describe.**
I often take multiple video recording of the same situation from various perspectives, rendering different features of the situation visible. I have to manually synchronise these in a video rendering program to then allow simultaneous playback of all the sources and then transcribe.

**Describe the solution you'd like**
It would be great, if the user could open various audio/video sources simultaneously (say several media windows), but allow the user to define how these temporally relate (as in, to define the points in time of each linear recording that are to be in sync).

**Comment by ccbogel** [comment]
I think this could be possible, but could be very complicated also. I am not keen to implement this anytime soon.

**Comment by ilippert** [comment]
Thank you so much for your note. Maybe, let's keep it on a kind of list of wishes.

**Comment by ccbogel** [comment]
@ilippert , Andrzej gave me an idea. An easy way to accomplish this is to copy the project folder, save it under another name. Then open both projects at the same time in two different terminals, so that you can view multiple videos of the same scene.

**Comment by ccbogel** [comment]
not a thing i can fix.
