### ISSUE TITLE
Ubuntu standalone file does not run on 22.04

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#652]
**Describe the bug**
The Ubuntu standalone QualCoder file which ran so well on 20.04 unfortunately does not run on 22.04

**To Reproduce**
 download Qualcoder-2.9-Ubuntu on 22.04 and make the file executable as program. Run it - it does not start

**Expected behavior**
it should open and run as on 20.04

**Screenshots**
traceback:

pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
/tmp/_MEIqz3kff/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_tls_channel_binding_error_quark
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so

(QualCoder-2.9-Ubuntu:61122): GLib-GIO-ERROR **: 22:25:45.655: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'

Trace/breakpoint trap (core dumped)

**Desktop (please complete the following information):**
Ubuntu 22.04

**Additional context**
eagerly awaiting 3.0, would be great if the standalone ubuntu file of the new versoin would be functional!

is this an Appimae? Would creating an Appimage be an alternative? I think many Linux users beyond ubuntu would be grateful for one...

**Comment by ccbogel** [comment]
Thanks for the feedback. I do not know how to create an appimage. I do not have Ubuntu 22.04 , so I will release the executable under Ubuntu 20.04.
You can create your own executable:

Install pyinstaller then from the QualCoder-Master folder run:
pyinstaller -w -n "QualCoder-3.0" --onefile qualcoder/__main__.py

You might need to run under sudo:
sudo pyinstaller -w -n "QualCoder-3.0" --onefile qualcoder/__main__.py

The executable will be in a folder called dist

**Comment by ccbogel** [comment]
I will close this issue, as I updated the release notes and have given the install instructions above.

**Comment by menelic** [comment]
thank you for the instructions for creating an executable locally - unfortunately they do not work, presumably because python and pip require specific designations such as pip3 etc. In 22.04 I could not figure out how to get this to work.

I am assuming these designations are the issue because while I did get qualcoder to work via the suggested virtual environment install method - but only after lengthy trial-amd-error fidgeting with various designations for specific pyton3, pip3 and pyinstaller. 

Given the fact that 2204 is an LTS release just like 20.4, it will increasingly be the main driver of ubuntu users, especially in institutional settings. That is why I strongly recommend you set up a virtual 22.04 install in your 20.4 , which can easily be done with Gnome Boxes which is available from the software center. The actual install of the virtual machine can be done with a few clicks. This would enable you to build an installer from within and for 22.04 or at the very least provide install instructions.

**Comment by ccbogel** [comment]
I will consider this Gnome Boxes if it is easy to use. 
Can you remember the instructions that you used to install on Ubuntu 22.04? it would be useful to see that.

**Comment by ccbogel** [comment]
CLosing issue as I am aware of it and will try and use gnome boxes for 22.04
