### ISSUE TITLE
Bug: uncaught exception in Manage files

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#654]
In Manage files I added some characters to a blank txt. I closed, re-opened it and got this error: 

![image](https://user-images.githubusercontent.com/16408198/169418043-a02a5fa7-71ea-4af2-9d17-27644f73946a.png)

QC v3, Win10

**Comment by ccbogel** [comment]
Ah yes a port to Qt6 issue I missed.
This only occurs when you right click on the text to open the right-click context menu (well only occurs to me under those circumstances).

**Comment by glocalglocal** [comment]
My mistake. I right-clicked too.
