### ISSUE TITLE
Search and change in sumamries

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#656]
Hi,

It would be helpful to have search function also in code cummary and file summary.

Moreover, to add information on FILES which are NOT coded by specific code (in code summary), as well as on CODES which have not been used in file (in file summary). Recently, I looked for such information in code summary.

**Comment by ccbogel** [comment]
OK I now  have added the search function.

Files which are not coded. It might be better to run a sql query than have the code or file summary have a big list of not coded or no files for a code.
Examples below:

-- Files that are not coded with code 24
select source.name from source where source.id not in 
(select code_text.fid from code_text where code_text.cid=24 
union select code_av.id from code_av where  code_av.cid=24 
union select code_image.id from code_image where code_image.cid=24)

-- Codes that are not used in a text file (id 1). 
-- Uncomment the select code for another file type if needed
select code_name.name from code_name where code_name.cid not in 
(select code_text.cid from code_text where code_text.fid=1)
-- (select code_av.cid from code_av where  code_av.id=1)
-- (select code_image.cid from code_image where code_image.id=1)

**Comment by AndrzejWawa** [comment]
Hi,

Thanks, it works!

Can you add both these into the Default Queries?

**Comment by ccbogel** [comment]
ok done
