### ISSUE TITLE
Minor adjustment

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#657]
Memos for file should be able to be opened by right-click menu also, not only icon (what can be misleading, while there exists right-click menu for files in coding mode).

**Comment by ccbogel** [comment]
I need more information on this. Where in QC is this needed?

**Comment by AndrzejWawa** [comment]
I mean list of files in coding mode (above the coding boom). There is no option to open file memo by right-clicking the file.

**Comment by ccbogel** [comment]
I can add a the memo to the Tooltip

**Comment by AndrzejWawa** [comment]
The same for image and A/V coding. Add memo to the right-click menu for files.

**Comment by ccbogel** [comment]
completed
