### ISSUE TITLE
Further improvements of graphs

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#658]
1. It would be extremely helpful to be able to select many staring point and many ending elements to be connected by lines, as well as determinig, at the same time, color and other characteristics for all of these lines.

For example, I created a graph for the purpose of my systematic literature review, which presents conncentions between files and attributes attached to them. This means that QC is already prepared to create complex and analytically insightgfull graphs, but it was relatively time consuming. Improvement from point 1 would significantly reduce this time.

![Schemat 5](https://user-images.githubusercontent.com/77200214/169531005-4e97e5a3-bc4e-4f34-96a7-d4e57bb2d7a8.png)

2. Moreover, option to add number of connections in different elements would be nice. I introduced them manually, as text boxes.

3. There is also possibility for automatic creation of pre-defined graphs, e.g. files connected to their attributes, where lines to each attribute is different, and each attribute displays number of connection (exactly as on the image), as well as codings connected to their codes, for selected codes and files (after introducing option to add codings). 

4. Introducing more colors for lines (and boxes).

5. Allow to change font of all elements, or for selected (e.g. to highlight their importance).

6. Allow to change features of boxes, e.g. shape, color, bold font, as well as add option that different kind of boxes (files, codes, codings, attributes) have different shapes (but color is white-black by default, as it is now).

7. Allow to edit text in boxes.

8. It seems to me that there is minimum of 2 characters to create new text box, could be changed to 1? When I was introducing boxes with numbers, e.g. "1", I initially did not know why I can introduce new box, so needed to add empty character.

**However, most points are not priority in my opinion,. Most important is saving graphs to further modification in the future, as well as point no 1.**

PS Your idea for changing colors of lines was excellent, it is veery helpful for readibility of graph.

**Comment by ccbogel** [comment]
I do love this graph - very nice. Yes my next task is to save and restore graph images.

**Comment by AndrzejWawa** [comment]
9. At this moment you can remove this option as the list view is more readible and practical fo further modification. Moreover, you can replace this drop-down list of categories with icon "add a new tree". Clicling the icon opens window where you can select kind of tree: codes tree, files tree, cases tree (as well as attribute and coding tree in the future), and after clicling particular option you have another window, where you can select categories for codes, select files (possible also filtered by attributes or cases int he future), and cases.

This would be more universal, as current list is dedicated solely to codes, and especially more save. Now, by changing view of graph or categories of codes from list, the whole graphs is reset to initial state, what is very unintuitive and surprising, and may upse many inattentive users. In the option with icon, where you have existing graph and clicking icon "add new tree" there would be clear dialog window with question: ?do you want add a new tree in addition to existing or replace it"? - then, all will be clear.

The question is, if there should be any tree by default or not. It can be like now, but, after clicling icon, you select option of introducing in addition to existing or replacing it.

**Comment by ccbogel** [comment]
I am working on a development branch. Currently: 
1 starting point to many ending points. Some more line colours (not too many). Make a font larger. (from sine 9 to size 12).
I have started work on creating the extra tables needed to store the graph items. So they can be saved and loaded. LOTS more work to do on this. As it is complex.

**Comment by AndrzejWawa** [comment]
Wow, thank you for your work! It works great :)

Minor issues:

1) when you click "clear", there should be additional dialog window which asks you, if you are sure, that you want clear the whole graph, and info, that you should save it if you want return to it.

2) ctr+z of clearance, if possible, maybe for other actions.

3) window with loading saved graph is named as delete graph.

And two issues quite important for me:

4) can you allow for wrapping text in the free boxes? I mean that I plan to often place the text of codings or memos, but, if it is one paragraph, the text is not wrapped. It could be linked with determining the size of box, if possible. If not, wrapping text to default size of box.

5) can you add the function, that you can introduce text boxes with codings for selected code and file? In the form of icon for adding files and cases. It would be very, very helpful, because the number of codings can be great, so, time-consuming to insert manually, but seeing the codings in the form of movable text boxes, which can be linked etc. provides you totally new kind of analytical insight, which addrresses the limitations of presenting codings in classical tables.

**Comment by ccbogel** [comment]
Updated points 1,3,4.

**Comment by AndrzejWawa** [comment]
Hmm, is it possible to introduce automatic saving the recent graph, e.g. as "Your recent draft", and automatic reloding this graph after opening the graph mode again? So, you will be able to saving different graphs, but the recent graph will be always saved as "Your recent graph position".

If it is not possible you can add the window with information that you have to save the graph before changing report. This window may appear after each opening of the graph mode.

**Comment by ccbogel** [comment]
HI 
* I have added the functions to show coding and memo for a File + Code. - New Buttons. still a little bit more work to do on this. Again, this means deleting the graph tables as I made a further change to one of them.
* I can add a button to load the most recent graph. (As I am saving the date/time).

**Comment by ccbogel** [comment]
export image bug - will try to fix, may not be possible. - does it happen all the time ?
2, 3 - I will make it so that another text entry box opens - to enter text into.  so a right-click function
4 - done now
5 - I tried this before -could not make it work
6 - again too hard for me to do I think
7 - yes- if I add options to the right-click on the screen.
8 - too hard to implement - that way I have the text as gray colour

todo -  I will add a right-click to the graph button - to order the graph by date/time or by alphabet - up or down

And - can also now add coded image areas to the graph

**Comment by ccbogel** [comment]
OK I have updated. fixed the error (Windows only as Qt is implemented slightly differently).
I have sorted out Pt 8 - the black/white color issue. Now default is black text - but with a white background.

**Comment by AndrzejWawa** [comment]
Ok, looks great! Now. it seems be quite more stable and optimalised.

Bug:

Ad 3. if you create text box with only one line of displayed text (e.g. word "Australia"), when the wrapping of text is not yet needed, and after this, edit text through lengthen the text line (to the length when text should be wrapped), the wrapping does not work.

Technical improvements:

Ad 5. these shortcuts for zooming in/out as e.g. "q" and "w", if it is not a problem.

Ad 7. can you add also inserting coding memos to the righ-click menu?

Ad 8. can you also add the white background for grey?

Ad 10 images work now, however, can you add the righ-click function to "see image in context" - images cannot be zoomed-in, so, they are often very unclear. Optionally, could be also introduced for text codings (see coding in context) and file (open file).

11 when it comes to colors, to shorter the right-click menu, it could be created only one position in the "main" right-click menu, e.g. "change color", and after moving coursor on it, the sub-menu with list of colors will be displayed. Exactly, how you have done this in "code by recent code" in coding mode.

**Comment by ccbogel** [comment]
3. To reviee.
5. Click on the blank scene area. + and - to zoom in and out.
7. To do.
8. Ok. Will do.
10. To do.
11. Good idea.

**Comment by AndrzejWawa** [comment]
5. Yes, yes, I know. But I meant to add additional shortcuts, namely q and w, because these letters are on the left side of the keyboard. + and - are on the right side, too close to arrows, so, it is inconvenient to use arrows and +/- at the same time. Moreover, when it comes to the + and - which are not on the numeric keyboard, you have to use also shift to use +.

Taking into account, that moving graph by arrows and zooming in/out will be the most common operations, these q and would be very helpful.

12. And this automatic saving graph can be good option - actually not for me, because I know QC very well, but for new users, who can easilly change the report and accidentally clear the graph. This is not the problem in the case of journals, as they are saved automatically. It could work like this, that graph is saved to the item named "recent graph", and after closing and opening graph again, there will be window with question "Do you want restore the recent graph or create new?", if ryou choose restore, the item with recent graph will be opened. If you choose create new, there will be opened empty graph, and "recent graph" item will be overwritten.

If it is too complicated I would place clear, **always visible** information on the top of graph window on this, that changing reports will clear the graph if it is not saved. - to avoid unpleasant surprise for the new users.

**Comment by AndrzejWawa** [comment]
Everything works excellently!

13) Last thing but important: when you are inserting coding texts  and coding memos, and selecting colours, there is lack of black colour.

**Comment by ccbogel** [comment]
Good morning.  I have just woken up.
I smnhladcall working ok. I am also trying to get audio/video codings on the graph too. That means some more changes to database tables. But i am happy this is close to being completed.

**Comment by AndrzejWawa** [comment]
I found that this q/w is very convenient. Could you introduce this also for image coding and see image in context (in graphs, coding reports, and show coded files in coding mode)?
