### ISSUE TITLE
Exporting and zooming in/out graphs

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#659]
I noted problem that exported png with graph covers only limited area of graph, while other parts are cut. E.g.:

![Graph_0](https://user-images.githubusercontent.com/77200214/169535069-6c77f4da-f4fd-45b8-b56c-9970d1760ada.png)

Moreover, when graphs is big, you can zoom-in it, but you can move the view, cause there is not scroll bars:

![Problem with changing view with zoom](https://user-images.githubusercontent.com/77200214/169535367-78bcefb5-d8f0-419e-92a9-eda47858c977.png)

Finally, when you export graphs in dark mode, it is exported as the graph in light mode, but the lines are stiill white, so invisibile. I think there could be option, to select: export graph as in dark version or in light version. There should be lines:

![Graph](https://user-images.githubusercontent.com/77200214/169536030-2e14a845-90e0-455d-8a06-ddca212cb5cc.png)

I think that graphs are very gelpful in work, and can assist you during the whole process of coding, analysing, and thinking on data and project, why made such many comments on them.

**Comment by ccbogel** [comment]
"Finally, when you export graphs in dark mode, it is exported as the graph in light mode, but the lines are stiill white, so invisibile."  Lines are now gray - so light or dark export will be OK.

**Comment by AndrzejWawa** [comment]
Wonderful, now everything works properly.
