### ISSUE TITLE
Best practices of collaborating on a project

### ISSUE THREAD

**Issue by meefen** [ccbogel/QualCoder#661]
In a project, we need to have multiple researchers code a same set of files. They may have the same set of files stores on their own computer and code offline. They may also store everything in a cloud service such as Box Sync.

What is the best way to collaborate on such a task?

I see that QualCoder can merge different projects. But I am not sure whether it is meant for collaboration. 

Any guidance will be much appreciated.

**Comment by ccbogel** [comment]
Hello Bodong,

Yes QC was not originally meant for collaboration in the way you suggested.
When I started this project I was thinking one coder would do their coding , then afterwards, a second coder would code into the same project. (eg using the same project folder or transferring the project folder to a second coders computer).

I think it might work if the project folder is located in Box Sync? (you might have to do a faux text project first). Then ONE coder at a time does their work (and changes the coder name in settings - very important). Then when they have finished the next coder does their work. They could work in-between on different day perhaps, but essential to name change first. And essential not to access the database as the same time (as sqlite was not designed for this).

It may be possible for each coder to have their own copy of the project folder with absolutely identical text files (specifically the text and filenames stored in the sqlite database). Then each assigns their coder name in Settings before doing any coding.
Will each coder be using the identical coding tree structure? - if Yes - then it should be OK.
if No - then I guess my concern would be if the same code name (or category name) was used e.g. 'bodong' which was located in differing tree structures. In this case the destination code tree structure would override the imported code tree structure.
I hope this makes some kind of sense to you. 

with regards Colin

**Comment by ccbogel** [comment]
I will close this issue because I believe you have now read my response.
