### ISSUE TITLE
Qualcoder installs correctly, but then claims it is not installed (Ubuntu)

### ISSUE THREAD

**Issue by davidcbenson** [ccbogel/QualCoder#662]
**Describe the bug**
Qualcoder install from github installs correctly, but when running qualcoder from terminal, qualcoder claims 'Qualcoder==3.0' is not found.

**To Reproduce**
1. Follow installation from source/github instructions. 
2. Get the following message (after a lot of other confirmations that packages are installed):

```
Building wheels for collected packages: Qualcoder
  Building wheel for Qualcoder (setup.py) ... done
  Created wheel for Qualcoder: filename=Qualcoder-3.0-py3-none-any.whl size=2305627 sha256=7a078fff809410073be28bf03c81a0be4d31a2d3a5daf1dde226b48765dab44a
  Stored in directory: /tmp/pip-ephem-wheel-cache-qx357rhw/wheels/f2/26/e4/75f0cda7447c2506112c65a451b5bc5c816f1f2ec38e0f375a
Successfully built Qualcoder
Installing collected packages: Qualcoder
  Attempting uninstall: Qualcoder
    Found existing installation: Qualcoder 3.0
    Uninstalling Qualcoder-3.0:
      Successfully uninstalled Qualcoder-3.0
Successfully installed Qualcoder-3.0
```
3. Enter "qualcoder" in terminal.
4. Receive the following message (again after several warnings about future deprecations):
```
Traceback (most recent call last):
  File "/usr/local/bin/qualcoder", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/dcbenson/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/dcbenson/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/dcbenson/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/dcbenson/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/dcbenson/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/dcbenson/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Qualcoder==3.0' distribution was not found and is required by the application
```

**Expected behavior**
Qualcoder should load.

**Screenshots**
n/a, see "code" above

**Desktop (please complete the following information):**
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Additional context**

I am running Qualcoder within a virtual environment, as recommended.

I had several problems installing PyQt6. Ultimately, updating pip resolved the problem. As part of troubleshooting, I uninstalled everything, and then started again from scratch. When starting from scratch, the install went flawlessly, but now, although qualcoder does something, it claims Qualcoder is not installed.

**Comment by davidcbenson** [comment]
Thankfully, Option 1 worked. I will say that, like an idiot, I kept trying to run it from the command line, but once I figured out that the program does not install and runs through GUI, I was fine.

For reasons unrelated to this challenge, I had to completely reload Linux, and now no longer have the same version. I did follow those steps exactly, both with and without wheel, and got the same result. It may have been an error unique to my computer or configuration, which I no longer have. I hope, if anyone has the same problem, the same resolution will work for them.

**Comment by ccbogel** [comment]
@davidcbenson Thanks for the information David. It's helpful for making me provide clearer instructions in the install and run too.
I hope you fine QualCoder useful for you. I se you are also in education.

**Comment by davidcbenson** [comment]
@ccbogel Yes, I am a professor. I've used QualCoder in the past, and quite
liked it, but in my current project QualCoder will be more central. I'm
happy to send you a little description via email of what we're doing, if
you're curious. The project is examining online public information as it
relates to international competition (i.e. war, peace, trade, etc.).

**Comment by ccbogel** [comment]
Thanks for the feedback. No, perhaps i will find your project later, If you publish and cite QualCoder. Your project seems very topical today. As an Australian we have a lot of concern re trade and security in our region.
