### ISSUE TITLE
Shortucts in AV mode and some improvements

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#664]
I do not work with AV now, but looked for interest and found following issues:

1) When you move cursor on button "rewind 5 seconds", there is information that the shorcut is alt+r, but the working shorcut is ctr+r. Ctr+r is better than alt+r, so there is **only a need for information correction**.

2) when it comes to "rewind 30 second", the information claims that the shorcut is shift+r, but the working shorcut is alt+r. Shift+r is better, so **I would change the working shorcut to shift+r.**

3) the same when it comes to 30 seconds forward, **I would change working shorcut to shift+f**, as information claims.

Improvements:

4) I would introduce shorcut **"s"** for starting/ending/clearing segments (as these actions follow each other),

5) **"q" f**or coding segment by the recently used code,

6) **double click** on code to code segment,

7) allow to code segment by more than one code. Now, after coding the segment is automatically cleared, but there could be possible to assign many codes to segments, and clearing only after clicking "clear segment" or "s". Optionally, there could be option to decide, if you want automatic clearing after coding (default option), or not (when you unmark it).

**Comment by ccbogel** [comment]
Fixed to the original actions: At F forward 30, Alt R reverse 30 and Ctrl R reverse 5

**Comment by AndrzejWawa** [comment]
Now it is ok.

However, when it comes to "s", it is still needed **as you loss focus after each coding**, so, you have to come back with cursor to start again, and again. Shortcut s, in combination with existing shorcuts, will allow you to use mouse only for code book, as for other actions you can use keyboard. It will be quite more quicker and convenient.

**Comment by AndrzejWawa** [comment]
Yes, I tried. When you want to come back with focus to "start segment" after assignment to code### you have to click Tab six times. So, it is definitely more useful to have shortcut "s" fpr the start button. It is especially justified that you already have shortcuts for most buttons, e.g. increasing/decreasing play rate, which is rather not such often used as start/end/clear segment.

**Comment by ccbogel** [comment]
done

**Comment by AndrzejWawa** [comment]
Hi, now is much more quicker and convenient.

Can you only, only additionally as some people are left-handed, provide also **shift+s** for start and puse - to be simiar as previously? You changed this to ctr+p (good for left-handed), but for right-handed people it requires jumping from one side of the alphabetic keyboard to another.
