### ISSUE TITLE
Change code and change code/memo remotely

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#666]
**1.** May you introduce to the right-click menu for coded segment an option to change code? It would be look like that you right-click the coded segment in coding mode, click "change code", select code to change (not needed if segment is coded by one code only), and code to which you want to change it.

**Justification:** now you can code once-marked segment by many codes. It is very helpful, because you can be sure that all codes are assigned to the same character range. It is also important when you want to use codes as "attributes" for segments. For example, I plan to code standardised segments (e.g. legal section or legal article undivided to sections), and then create more complex statistics based on co-occurence report or try to use R. So, it is easier that all codes for the segment cover the same character range. However, when you want recode (e.g. to basing on additional findings from report or change coding conducted by other coder) segment traditionally, namely by unmarking and marking it again, but by other code, it is easy to make mistakes by one-two characters. This function will solve this problem.

**2.** May you introduce this function also to the right-click menu for:
a) codings in graph,
b) coding memos in graph,
c) coding report?

**Justification:** codings in coding mode are mainly based on the neighbour content. However, they can be also based on _relations_ between codings and _wider overview_. This is provided by coding reports and, especially,  by graphs. So, basing on these new insigths, overlooked in coding mode, there could be a need to recode many segments. Systematic and mass recoding, based on insigths from graphs and reports, would be easier from there.

Moreover, the Maxqda also introduced possibility for rearranging code book by the graphs, what is named as the "creative coding" - see page 256 (https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.maxqda.com/download/manuals/MAX2022-Online-Manual-Complete-EN.pdf&ved=2ahUKEwjy3Kut5an4AhVCrosKHeZlCoAQFnoECAUQAQ&usg=AOvVaw3P2j95VPnt3OJf1Ofi8CfF).

I do not remember this Maxqda function very well, but it is possible that the QC one may be even better as it would be applied in integrarive graph mode, not as separate function.

**3.** Moreover, to allow to change memo coding from the right-click menu for:
a) codings in graph;
b) codings in report

**Justification:** to complement change from point 2 and allow to make notes on insights related to codings, but based on graphs and reports.

**Comment by ccbogel** [comment]
I have done 1.   Right-click to change code.
I will not do 2  -  far too difficult to implement this change code in the other areas.
I will not do 3.- coding in report. Also coding in graph - risky - because if the codes are shown in other tabs, memo writing one a different tab will override unexpectedly.

**Comment by AndrzejWawa** [comment]
Ok, thank you very much for the new function.

So, when it comes to the point 2, is it still difficult to do this in the "show in context" window? I mean that you can show coding in context in coding reports as well in graphs. So, it would be based on the right-clicling on the code in context and changing code, as in the coding mode (the view in coding mode and coding context is similar). However, if it  is too difficult it is ok.

**Comment by ccbogel** [comment]
its too difficult for several reasons. but one of the main reasons is the risk of a clash of memo text in reports/graphs and coding tabs. So I wont do this request.
