### ISSUE TITLE
Coding comparison, excluding uncoded data

### ISSUE THREAD

**Issue by meefen** [ccbogel/QualCoder#667]
We have a coding task in which we look through a long document and tag any piece of text with one or several tags. A significant portion of the long document will remain untagged.

When running "coding comparison" report, the agreement % and Kappa measures are not very meaningful given they account for the uncoded/untagged data. 

What's the best way to analyze inter-rater agreement to only focus on whether two coders code the document in a similar way? 

Thank you in advance!

**Comment by ccbogel** [comment]
@meefen , Thanks for the question. I am not sure how best to answer it. I based the text code comparison on what other software did for these statistics and tried to replicate it. (in the reports.py file I have a method called calculate_agreement_for_code_name which details the workings out).  I agree that the kappa statistic does not seem of great value, but I tried to implement that also, as other software did this.

These are the main outputs that are shown in the table (for the report Coder comparisons - text files), It is in python but quite readable:
        total['agreement'] = round(100 * (total['dual_coded'] + total['uncoded']) / total['characters'], 2)     # The Agree % column
        total['dual_percent'] = round(100 * total['dual_coded'] / total['characters'], 2)    # A and B %   column
        total['uncoded_percent'] = round(100 * total['uncoded'] / total['characters'], 2)   #  Not A Not B  % column
        total['disagreement'] = round(100 - total['agreement'], 2)    # Disagree %   column

I could, if it is useful, add another column with a % based on _only_ coded text, like this:
        total['dual_percent_coded_only'] = round(100 * total['dual_coded'] / (total['dual_coded'] + total['single_coded']), 2)    # Agree % of coded text only

Now this question:
What's the best way to analyze inter-rater agreement to only focus on whether two coders code the document in a similar way? Several other commercial software use the Kappa statistic. I am not sure if there is a better way.

**Comment by AndrzejWawa** [comment]
Hi, for me this new column would be helpful.

@meefen you can also look at "comparison by file", and there the agreement/disagreement is also prezented graphically.

@ccbogel can you allow for selecting more than one code in comparison by file?

**Comment by ccbogel** [comment]
can you allow for selecting more than one code in comparison by file? - No the display would be too congested/confused.

**Comment by ccbogel** [comment]
I have enacted this change
