### ISSUE TITLE
multiple coders on different devices

### ISSUE THREAD

**Issue by marcysg** [ccbogel/QualCoder#668]
Hi - we have two coders on our project, each with their own device (we're located 2000 miles apart), and would like to compare and share coding.  Is there a way to do this?

Thanks!

**Comment by AndrzejWawa** [comment]
Hi,

I think (@ccbogel can correct me), that there are two different options for this:

**1) working on the same project**, but:
a) each coder has to remember to select her/his name in the settings before coding; 
b) what is important, in the case of working on the same project, you cannot work at the same time, so, you can place project in the cloud-synchronised folder, and then: first coder opens the project, select her/his name in settings, and code, then assures that the project in the cloud was updated. Then, the second code do the same, and so on. Alternatively, you can send the project via mail to from first coded to the second, and reverse. But it is essential to remember about chainging the name of coder in settings.

**2) working on the different projects,**, so, each coder has its own copy of project and both coders can work simultaneously. However, it is essential:
a) to remember that the coded files have to be identical.
b) there cannot be situation that each coder has the same-named codes but in the different places of the coding book structure,
c) traditionally, remember, that each coder has to have her/his own name in settings and assure that she/he is coding under this name.
Then, both projects can be merged and comparative analyses of codings by different coders (coding comparison and coding comparison by file) can be conducted in "reports" tab.

**Comment by ccbogel** [comment]
@marcysg yes @AndrzejWawa is correct on this. I always envisioned that one coder would code. then a second coder would separately code on the same data - for comparison purposes.
So my thoughts are one coder (e.g. you) does the work, then zips the project folder and email to your colleague for the second coding of the data.
You can do this in stages- so if you coded file-by-file and swapped the project to each other that would be ok too.
I have never tried having the project folder on a shared drive - eg google, dropbox, one drive. It might work - the main issue is that 2 coders do not code at the identical times, as the sqlite database is a one user at a time database.

**Comment by marcysg** [comment]
Thanks for your quick responses on this. We set up a shared folder and my collaborator saved her project there.  Unfortunately I’m unable to open it.  I get an error message:  “…/xxxxxx/… project.qda JamieK”

Does this look familiar?
Marcy



From: QC Developer ***@***.***>
Date: Wednesday, June 15, 2022 at 6:18 PM
To: ccbogel/QualCoder ***@***.***>
Cc: Singer Gabella, Marcy ***@***.***>, Mention ***@***.***>
Subject: Re: [ccbogel/QualCoder] multiple coders on different devices (Issue #668)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@marcysg<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcysg&data=05%7C01%7Cm.singer-gabella%40vanderbilt.edu%7Cc2f7ff5254b94f8eaff808da4f2564a6%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637909319288957622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wz%2FftH7amYfg2HNmq5UuooBWWPGfOOgaEyPQisdJ7T8%3D&reserved=0> yes @AndrzejWawa<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAndrzejWawa&data=05%7C01%7Cm.singer-gabella%40vanderbilt.edu%7Cc2f7ff5254b94f8eaff808da4f2564a6%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637909319288957622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7PBz91e%2BG8kNdoSSAsW%2BnapIsWH%2BJIwJgadVyAGWkCM%3D&reserved=0> is correct on this. I always envisioned that one coder would code. then a second coder would separately code on the same data - for comparison purposes.
So my thoughts are one coder (e.g. you) does the work, then zips the project folder and email to your colleague for the second coding of the data.
You can do this in stages- so if you coded file-by-file and swapped the project to each other that would be ok too.
I have never tried having the project folder on a shared drive - eg google, dropbox, one drive. It might work - the main issue is that 2 coders do not code at the identical times, as the sqlite database is a one user at a time database.

**Comment by ccbogel** [comment]
HI I'm not familiar with that error message. And I am not familiar with using these projects via a shared drive. Is it a permissions error?

**Comment by marcysg** [comment]
The permissions all look good, and there was initially a certificate error but that’s now fixed.  Will keep working on it.


From: QC Developer ***@***.***>
Date: Wednesday, June 15, 2022 at 8:35 PM
To: ccbogel/QualCoder ***@***.***>
Cc: Singer Gabella, Marcy ***@***.***>, Mention ***@***.***>
Subject: Re: [ccbogel/QualCoder] multiple coders on different devices (Issue #668)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

HI I'm not familiar with that error message. And I am not familiar with using these projects via a shared drive. Is it a permissions error?

**Comment by marcysg** [comment]
Hi - me again.  We are trying the zip and send strategy for file sharing, and I wonder if I'm getting stuck on something really basic.  Once I unzip the files and point Qualcoder to the folder, how do I get Qualcoder on my computer to recognize the project as one of my projects?

I have tried two strategies:
1) In the Project Menu, select "Open Project" -- it goes right to the folder with my colleagues files, but says I have no files in the project.
2) In the Project Menu, select RQDA Project Import (I also tried REFI-QDA)
What am I missing?

> @marcysg yes @AndrzejWawa is correct on this. I always envisioned that one coder would code. then a second coder would separately code on the same data - for comparison purposes. So my thoughts are one coder (e.g. you) does the work, then zips the project folder and email to your colleague for the second coding of the data. You can do this in stages- so if you coded file-by-file and swapped the project to each other that would be ok too. I have never tried having the project folder on a shared drive - eg google, dropbox, one drive. It might work - the main issue is that 2 coders do not code at the identical times, as the sqlite database is a one user at a time database.

**Comment by marcysg** [comment]
OKAY I've made it work.  I had to change the coder, and then change it back.  Now I can see my colleague's work.

**Comment by ccbogel** [comment]
@marcysg OK thanks for the feedback. Is there something more I need to add to instructions in the PDF manual or the github wiki to help with this?

This is the existing instructions I have mentioned here:
https://github.com/ccbogel/QualCoder/wiki/02-Settings

**Comment by AndrzejWawa** [comment]
@marcysg it is important that when you sharing QualCoder projects to someone using QualCoder too, you should not use REFI, but sending the project folder (QualCoder recognises the whole folder as project, not particular subfolders/files in it).

The reason is that REFI is designed for sharing codebooks and projects between different software packages, e.g. QualCoder and Maxqda. But it has limitations, cause the project can be send only once, so, after exporting to Maxqda, it cannot be exported further. Moreover, it was not fully tested on QualCoder, however, there are also some problems in sharing between software packages officially introduced REFI.

**Comment by marcysg** [comment]
I am a newbie to working with Python apps so take what I have to say with a grain of salt.  For me, it would have been helpful to have a short paragraph explaining what needs to be transferred (the whole folder), and what I could and couldn’t see when I added myself as a coder.

Marcy

From: QC Developer ***@***.***>
Date: Thursday, June 16, 2022 at 6:27 PM
To: ccbogel/QualCoder ***@***.***>
Cc: Singer Gabella, Marcy ***@***.***>, Mention ***@***.***>
Subject: Re: [ccbogel/QualCoder] multiple coders on different devices (Issue #668)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@marcysg<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcysg&data=05%7C01%7Cm.singer-gabella%40vanderbilt.edu%7Cc76ede76a63d4d30d66408da4fefb8f4%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637910188265964038%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eE8lGeBBkW9zKMSdcqt828KnxOaoMecqZxzmtr8jWg0%3D&reserved=0> OK thanks for the feedback. Is there something more I need to add to instructions in the PDF manual or the github wiki to help with this?

This is the existing instructions I have mentioned here:
https://github.com/ccbogel/QualCoder/wiki/02-Settings<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fccbogel%2FQualCoder%2Fwiki%2F02-Settings&data=05%7C01%7Cm.singer-gabella%40vanderbilt.edu%7Cc76ede76a63d4d30d66408da4fefb8f4%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637910188265964038%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0eIz6SlnD3%2F75DIaD5dXw4043tCm8RjE9XEmUadLmA4%3D&reserved=0>

**Comment by ccbogel** [comment]
OK well I have added some collaboration instruction at the bottom of the wiki Home page. Please let me know if this helps.

https://github.com/ccbogel/QualCoder/wiki

**Comment by marcysg** [comment]
Thanks – I think that is helpful.  Meanwhile, I appreciate all of your time and guidance!

From: QC Developer ***@***.***>
Date: Friday, June 17, 2022 at 7:17 PM
To: ccbogel/QualCoder ***@***.***>
Cc: Singer Gabella, Marcy ***@***.***>, Mention ***@***.***>
Subject: Re: [ccbogel/QualCoder] multiple coders on different devices (Issue #668)

OK well I have added some collaboration instruction at the bottom of the wiki Home page. Please let me know if this helps.

https://github.com/ccbogel/QualCoder/wiki<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fccbogel%2FQualCoder%2Fwiki&data=05%7C01%7Cm.singer-gabella%40vanderbilt.edu%7C2c992aa8fdb143f490cf08da50bfea51%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637911082455576801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qGxIMnA9HP%2FN8XimHwgSi68vW2mxmbX1Bd3D6qAFuMQ%3D&reserved=0>

**Comment by AndrzejWawa** [comment]
I checked this possibility with the could, on the example of the Dropbox folder, and it seems to work. However, each coder have to follow the procedure:

1) inform other coders about starting the coding (then, others do not work),
2) checki if the synchronisation is complete,
3) select her/his coder name in settings,
4) code,
5) closing project and check, if the synchronisation is complete,
6) inform other coders about ending the work.

And the second coder follows the same procedure.

Otherwise, there is risk that coders work simultaneously and the work done by one coder will be overwritten by work of the other, what leads to the loss of the one of the coders work.

However, in such a situation, the coders can try to not close the QC (project opened in QualCoder seems to be blocked against overwrite), stop synchronisation (.e.g by going offline), make backups and merge their project in classical way. Synchronisation seems to be based on replacing the whole project.

**Comment by ccbogel** [comment]
Yes thanks Andrej. Thats the process we use with Microsoft Access at work.
OK so Will close this issue now

**Comment by marcysg** [comment]
Thank you both.


sent from my iPhone


On Jun 18, 2022, at 7:29 PM, QC Developer ***@***.***> wrote:

﻿

Yes thanks Andrej. Thats the process we use with Microsoft Access at work.
OK so Will close this issue now
