### ISSUE TITLE
Facilitating selection of the end of line in graph

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#669]
Hi,

can you allow to select the end element of the line in graph as it is now for inserting new elements? I mean, that when you select end of the line, 1) firstly, you select category: text coding, image coding, AV coding, etc., 2) then, you select file, 3) code. and then, select 4) final element. Of course, selection is limited to the elements already existing in graph. Moreover, if there are elements without specific stage of selection (e.g. there is no codes and files for free text, or code and files for files), they will be ommitted.

**Justification:** when you have, lets say, 100 element, it is difficult and time-consuming to select, e.g. 15 text codings or memo to text codings for selected code and file. It is because you have long list of 100 elements.

**Comment by ccbogel** [comment]
I'm currently working on this. Hope to have it finalised soon.

**Comment by ccbogel** [comment]
@AndrzejWawa OK I have a working version of this. There is a selection grouper at the bottom of the window. Let me know if this is what you need or if it needs further refinement.

**Comment by ccbogel** [comment]
Actually I will close this now, I think it is OK

**Comment by AndrzejWawa** [comment]
Hi,

Can you only add two more further steps that are selecting files and code?

**Comment by ccbogel** [comment]
This is tricky. Try this - added a File name option

**Comment by AndrzejWawa** [comment]
Works, however you have only option to select  elements for specific files or free text. It is not possible to implement the same procedure as in the case of "insert coded text items", that you have 3 consecutive filters (coded text item > file name > code)? If there is possibility only for one filter I think that tha filtering by code will be most usefull.

**Comment by ccbogel** [comment]
OK I have done the 'filtering by code'

**Comment by ccbogel** [comment]
closing now
