### ISSUE TITLE
Image selection (when coding image) should reflect color of code

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#67]
Right now regardless of what is the code, the square signalling a part of the image coded, it is red. IMHO it would be better if the color of selection reflected the color of code as now when you open a coded image you can't quickly tell which part is coded according to what code as they are all red.

ps: I recently tried RQDA and I have to say QualCoder (IMHO) is way more functional and easy to use.

**Comment by ccbogel** [comment]
Thanks for that. Glad you prefer this to RQDA. Yes I have made those changes. I have not updated todays debian for this however.
