### ISSUE TITLE
Recent projects

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#671]
Hi,

I have this problem with recent projects list in project tab as they are not updated. As I remember you said that it is difficult to fix. Can you, however, provide right-click option to clear recent projects list to allow updating from the beginning?

**Comment by ccbogel** [comment]
An easy way is to delete the file.
Go to your Users/Andrej/Home folder and then open the .qualcoder folder.
Delete the recent_projects.txt file

**Comment by AndrzejWawa** [comment]
Thanks, it works!

You can mention this in the manual.

**Comment by ccbogel** [comment]
I tnink i already have
