### ISSUE TITLE
Bug and two additions

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#676]
Hi,

1. I noted that if you change code in coding mode or remove code, there is no change in the tooltip for the coded text boxes in graph.

 I mean that **show in context in graphs works correctly**: after changing code, the show in context shows new color of code, if you remove coding, the show context tells you, that the coding cannot be found.

However, where you move mouse on the coding in graph, the tooltip with information is in the initial (out of date) form. Can you **introduce updating this could** like it is in show code in context? I mean, that if the code was changed, the new name of code is displayed in cloud. If the code is removed, the information in cloud is that the coding was not found in database?

2. And the same updating of tooltip in the memo text boxes.

3. Moreover, can you add information on ctid in the a) coding report, b) codings in graphs, and 3) memos in graphs?

**Justification:** Taking into account that it is difficult to allow changing codes from coding report/graph I found, that I can use SQL statements, if it will be needed - I learned a bit of it basing on your default statements and using QC :) . However, I need to know ctid for this, as it is unique number for coding and the probability for making mistakes during use of SQL is lower.

4. Moreover, I noted that after inserting texts of coding into the graph they are stored in the "gr_free_text_item" table, not "gr_cdct_text_item", but I do not know if it is a problem?

**Comment by ccbogel** [comment]
Moreover, I noted that after inserting texts of coding into the graph they are stored in the "gr_free_text_item" table, not "gr_cdct_text_item", but I do not know if it is a problem?

This is the correct procedure.
The gr_cdct_text_item stores _only_ the categories and codes (like on the code tree that you see in the codingmode).
The gr_free_text_item stores all other text items.

**Comment by ccbogel** [comment]
1. I noted that if you change code in coding mode or remove code, there is no change in the information cloud in graph.
If you refresh  / reload the graph a removed code (from the code tree) should not show and an error message appears:
![pic1](https://user-images.githubusercontent.com/5834638/175941578-353e0d0e-1145-45ae-8b97-7ae3e4a899c8.png)

**Comment by ccbogel** [comment]
clouds?

**Comment by AndrzejWawa** [comment]
Hmm, this informational tool tip "File: Council Directive 2001...", sorry, I did know the proper name for this :)

**Comment by ccbogel** [comment]
OK, the tool tip.
Yes ok. these are difficult things to fix. I will see what I can do.

**Comment by AndrzejWawa** [comment]
"However there is another problem: If you have made changes the coded text in the graph items for better display. Then if I update these to match current coded text. any changes made would be replaced."

Hmm, I did not think about this. I forgot that the character range for coding can be changed without changing ctid. However, I would not change anything now, because sometimes users can edit text of inserted coding for specific reasons (e.g. to rephrase the codings or to short them). So, this automatic update is risky, but it is possible to allow for this, but only as facultatory, not default, option, which had to be selected intetionally.

**Comment by AndrzejWawa** [comment]
So, you can add the option in **right-click menu: "update coding text" and "update coding memo"** (for right-click menu for inserted memos). But there should be **confirmation window,** e.g. "are you sure for replacing text in the box"?. In the upper menu for the grapha there could be buttons **"upadate ALL coding texts" and "update ALL coding memo texts"**, **also with confirmation window.**

**Comment by AndrzejWawa** [comment]
Ok, I understand.

**Comment by ccbogel** [comment]
also for codings that have been deleted. I could remove them also automatically.

**Comment by AndrzejWawa** [comment]
Hmm, seems OK. It is not possible also for memos, as they do not have ctid, yes?

**Comment by ccbogel** [comment]
I have and idea. another modification to the columns and data stored in the gr_free_text_item to store an extra column for a ctid with a memo.

This is much like before - when  I was constantly testing and updating the details stored in the database.
I should be able to make this change without affecting existing stored graphs.

But if you have of memos in graphs now, the updated ideas I have cannot be back dated to fix the existing memos that you need to update.

These changes will take a some time to implement.

**Comment by ccbogel** [comment]
Improvements made to dynamic updates.
TODO: update coding memo text items.

**Comment by ccbogel** [comment]
OK, Closing issue for now. I think I have done my best to make the changes.
Create a new issue if needed.
