### ISSUE TITLE
Allow for running QC without VLC

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#677]
Hi,

1. Is it possible to allow running QC without installed VLC? I mean, that if you have not VLC installed, you can run QC and code texts and images, but cannot open AV mode? If you try, there will be window "Installation of VLC is needed for this mode".

If it is possible, then installation of QC **will be easier than commercial software packages**, becuse QC should be only downloaded and opened.

I think that many newcomers could try download and run QC quickly and forget about VLC (even I, after changing computer, forget about this, and did not know what is the problem - as you remember). Then, they will face the following **error window, which will be incomprehensible for them and they will be discouraged to try again**. Only more motivated newcomers will learn in detail from manuals or post issue.

Maybe this is minor issue but may behaviourally increase uptake of QC.

![obraz](https://user-images.githubusercontent.com/77200214/176173211-02de5dc1-b7fd-46ad-b3bf-20f013bc06d2.png)

2. Moreover, you can add **direct, visible TAB (clearly named as "DOWNLOAD"** with the newest release at wordpress site - it would be easier and quicker to find this.

**Comment by ccbogel** [comment]
For 1. it might be possible. I'm not that sure yet.

For 2. WordPress - perhaps rename the How to use page to -> Download and use
There is a download link here: https://qualcoder.wordpress.com/how-to-use/
And edit the page a bit more ?

**Comment by AndrzejWawa** [comment]
Yes, renaming the page is good idea.

And inside it, the first sentences should be straightforward "If you use Windows download and install VLC (if you do no have) from the link [link to VLC download się). Then, download the QualCoder exe file from [link to current release]. If you use Ubuntu, download the Ubuntu file".

And afrer this, in the next paragraph the current content. You can add that wiki contains instructions for installation from source, as well for "other Linux systems" (to note, that this is not only Ubuntu from the first paragraph).

**Comment by AndrzejWawa** [comment]
PS Have you removed ctid for codings intentionally?

**Comment by ccbogel** [comment]
Hi. This is a separate issue. No its not removed at all.

**Comment by AndrzejWawa** [comment]
Sorry for mistake!

**Comment by ccbogel** [comment]
OK I tried using the QMediaPlayer which is a part of the Qt framework. It does not work well at all. So for now I am reverting to needing to use VLC for audio/video.

**Comment by ccbogel** [comment]
OK, So I have added a lot of error catching code, so that if VLC is not installed, the same QualCoder program will still work for everything except audio/video. I have not been able to test it yet.

**Comment by AndrzejWawa** [comment]
![obraz](https://user-images.githubusercontent.com/77200214/199789439-e80e53d8-bada-4013-971b-2790c6c7ec4d.png)

**Comment by ccbogel** [comment]
Great! Thanks for this. I missed the vlc code in the refi import export module.

**Comment by ccbogel** [comment]
Updated ,please try again

**Comment by AndrzejWawa** [comment]
![obraz](https://user-images.githubusercontent.com/77200214/200400568-13d9c873-7866-469b-8e2d-b4cc3834b4af.png)

**Comment by ccbogel** [comment]
Aha, OK another missed vlc bit. Updated again.

**Comment by AndrzejWawa** [comment]
OK, it works!

Now, when clicling on audio-video it opens mode with info:

![obraz](https://user-images.githubusercontent.com/77200214/200435061-baa02b12-91cd-4e44-9b8b-05ae86484b48.png)


and after changing to another report mode it shows window:

![obraz](https://user-images.githubusercontent.com/77200214/200434998-7545a410-5e19-4db0-ad6b-a57b1d7a9206.png)

I think that better would be not opening mode at all but only show dialog window with info that VLC is not installed, you cannot code audio and video. The same way when you try to open image mode but there is no any images:

![obraz](https://user-images.githubusercontent.com/77200214/200435279-26c35761-e178-442d-941c-529189aff9c3.png)

**Comment by ccbogel** [comment]
@AndrzejWawa  Yay, It works. so that is good.
Yes sure. That is a sensible idea.  I will make that happen tonight or tomorrow.

**Comment by ccbogel** [comment]
I have  updated the warning

**Comment by AndrzejWawa** [comment]
Now is excellent!
