### ISSUE TITLE
Recode 

### ISSUE THREAD

**Issue by amrvs** [ccbogel/QualCoder#679]
It would be really nice to have a recode option. It would work like this: when right-clicking on coded text you could reassign a different code and both the text segment and code memo would move to the new assigned code. Right now the only way to do this is to delete the code and do it again, losing the code memo.

**Comment by ccbogel** [comment]
Yes I have already done this for the 3.1 version. (Not a release yet).
![pic1](https://user-images.githubusercontent.com/5834638/177891449-3d5542c2-d6b7-4248-9436-63fb262aefe8.png)

**Comment by amrvs** [comment]
great news! Congratulations for your work btw

**Comment by ccbogel** [comment]
@amrvs Thank you!
How did you find out about QualCoder?  And are you finding it good to use?

**Comment by amrvs** [comment]
I have been searching for an alternative to nvivo and maxqda for years. It's really smooth. So far the only thing that I miss is the recode button. I also can't make a report with just memos but that is because of some error that could be due my installation process.
