### ISSUE TITLE
Bug and minor issues related to graphs

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#680]
Hi, thank you for your great work! Now, the graphs are really powerfull tool and I hope that many users will appreciate this.

Issues I noted:

**1)** Cannot delete codings in coding mode:

![obraz](https://user-images.githubusercontent.com/77200214/177779957-c84c227d-c1d6-4a97-9acb-09bc980cb662.png)

**2)** When you updating memo text box, the tight-click option should me named "update memo text", if not possible, there could be "update codings/memo text",

**3)** After clicking update memo and coding boxes, there should be confirmation window - as it is rather serious change,

**4)** Loading saved graph leads to hiding warning about unsaved graphs - the warning should be still visible

**Comment by ccbogel** [comment]
1. fixed - an 'improvement' cased the error

**Comment by ccbogel** [comment]
4. kept the warning message.
