### ISSUE TITLE
Adding ctid to coding report and two tootips.

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#681]
Hi, 

Can you add information on ctid to

1) codings in coding report (this coloured heading started with the "[VIEW]",
2) tooltip for coding boxes in graphs,
3) tooltip for coding memos boxes in graphs?

I would be helpful for me for using SQL statements, e.g. to recoding segments. These information can be always visible or only afterselecting "Show IDs" in settings.

**Comment by ccbogel** [comment]
1. Done

**Comment by ccbogel** [comment]
all done.
