### ISSUE TITLE
After deleting the coding

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#682]
Hi,

In reference to the previous issue, now you can delete coding in coding mode, however, after loading the graph the following window appears:

![obraz](https://user-images.githubusercontent.com/77200214/177929903-dd78b621-d1f9-4256-b7ef-9d9687b8af1d.png)

**Comment by ccbogel** [comment]
Ahh thanks, I missed the word 'from'
fixed now
