### ISSUE TITLE
PermissionError:[Errno13] Permission denied

### ISSUE THREAD

**Issue by doffanaz** [ccbogel/QualCoder#688]
I**Describe the bug**
I am simply a commo software user interested in using QualCoder. I got a Windows 10 version of QualCoder 3.0. I installed the required applications (VLC, Python etc). I then started using the QualCoder. After creating new project, when I try to import files, i face this repeated errors message that does not allow me to import files. The error message is as depicted above in eh title. When you face such a problem at the start of testing a software it is disappointing. I am an expert user of the proprietary CAQDAS (currently engaged in using ATLAS.ti 9, MAQXDA 2020 and NVivo 1.6. But since these software are difficult to get legally we often resort to crack files, I find it difficult to train others with crack software. My hope is to shift to this free CAQDAS.... Your help in this regard is highly appreciated.
Regards

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/109099892/178499671-9fea5e9e-47c7-4b17-b46b-e7f4f74475ab.png)

**Additional context**

**Comment by ccbogel** [comment]
@doffanaz Thanks for reporting the issue. 
I am not an expert with Windows permissions, but I have some suggestions:

1 - make sure the file is closed before trying to import it,
2- run QualCoder as an administrator on Windows
3 - is an antivirus program causing a problem? - I had one user in the past have AVG stop QualCoder from copying files.
4 - To check: do ALL imports have this problem? for example if you made a plain text file and imported that- does it import? (I ask this because maybe your windows profile does not have the permission to have this file copied and it may be permissions allocated with another user profile or admin profile).
5 - If nothing else works - there is another free text coding software called Taguette www.taguette.org that you might like to try.

**Comment by AndrzejWawa** [comment]
6. Moreover, maybe other software is using the file at the same time, e.g. Maxqda? So, you can try make copy of the file to the desktop and then, try to import. Or it is problem with these specific files.

PS you don't need Python when using QC exe file, only VLC.

**Comment by ccbogel** [comment]
That is wonderful.
Can you tell me which of the advice was needed to fix the problem.

**Comment by ccbogel** [comment]
I am thinking copying the files to the desktop may be the solution - especially if the files were on external drives or cloud folders.

**Comment by doffanaz** [comment]
Thanks! But the files were in 'Documents' folder. C Drive.
*Kind Regards*



*Zerihun Doda, PhD* Environmental Anthropology, Development &
Conservation);
Director, Research & Publication Coordination Office;
Managing Editor of African Journal of Development Studies |
Ethiopian Civil Service University, CERI/CUED/Dep't of Environment &
Climate Change
*m:* + 251-944-062657
*p:* + 251-118278508
*e:* ***@***.***; ***@***.***
CMC Road, P. O. Box 5648
Addis Ababa, Ethiopia
www.ecsu.edu.et
[image: twitter icon] <https://twitter.com/DodaZerihun> [image: linkedin
icon] <https://linkedin.com/in/zerihun-doffana-9a6b1b174>

*Google Scholar: *‪Zerihun Doda Doffana - ‪Google Scholar
<https://scholar.google.com/citations?user=sPydrBQAAAAJ&hl=en>

ORCHID id    https://orcid.org/0000-0001-9545-8994

Web of Science Researcher Id http://www.researcherid.com/rid/V-7455-2018

*"[You] [have] formed us for [Yourself] and our hearts are restless till
they find rest in [You]."*

* St. Augustine*

**Comment by doffanaz** [comment]
Dear Sir/Madam,

I am coming back with similar problem. I was doing some sort of testing the
software (I am intending to use it if all my tests prove stable, to shift
form crack versions). I have watched the video and read the manual well. I
wanted to import survey data (about 60 cases with some 25 variable/ column
headings). The software gives eros message. Screen shot is attached
herewith. It frustrates....

Could you help?
[image: image.png]



*Kind Regards*



*Zerihun Doda, PhD* Environmental Anthropology, Development &
Conservation);
Director, Research & Publication Coordination Office;
Managing Editor of African Journal of Development Studies |
Ethiopian Civil Service University, CERI/CUED/Dep't of Environment &
Climate Change
*m:* + 251-944-062657
*p:* + 251-118278508
*e:* ***@***.***; ***@***.***
CMC Road, P. O. Box 5648
Addis Ababa, Ethiopia
www.ecsu.edu.et
[image: twitter icon] <https://twitter.com/DodaZerihun> [image: linkedin
icon] <https://linkedin.com/in/zerihun-doffana-9a6b1b174>

*Google Scholar: *‪Zerihun Doda Doffana - ‪Google Scholar
<https://scholar.google.com/citations?user=sPydrBQAAAAJ&hl=en>

ORCHID id    https://orcid.org/0000-0001-9545-8994

Web of Science Researcher Id http://www.researcherid.com/rid/V-7455-2018

*"[You] [have] formed us for [Yourself] and our hearts are restless till
they find rest in [You]."*

* St. Augustine*

**Comment by AndrzejWawa** [comment]
Hi, can you resend image? I have problem with opening it.

**Comment by ccbogel** [comment]
@doffanaz can you open a new github issue and give more details.

**Comment by doffanaz** [comment]
Hi ,
Thank you for your professional support. I have been testing QualCoder ( I am a professional CAQDAS user and trainer form Ethiopia, East Africa, focusing on MAXQDA 2020, Atlas.ti 9.) Due to problems in accessing official software for these , we are forced to resort to crack versions. I am hoping QualCoder might be a good option. I am trying to check how efficiently QualCOder 3.0 handles analysis of survey data (analysis of semi structured interviews with responses to open ended questions along with demographic variables. When I try the toll 'Import... Survey", it crushes, sending error message (see the screenshot below).  I have tired some options earlier suggested to me such as entering as administrator,  .. Could you kindly help?
Kind Regards
[Doc1.docx](https://github.com/ccbogel/QualCoder/files/9169239/Doc1.docx)

**Comment by doffanaz** [comment]
Dear Sir/Madam,

Thank you for your help. I have done as you instructed.
*Kind Regards*



*Zerihun Doda, PhD* Environmental Anthropology, Development &
Conservation);
Director, Research & Publication Coordination Office;
Managing Editor of African Journal of Development Studies |
Ethiopian Civil Service University, CERI/CUED/Dep't of Environment &
Climate Change
*m:* + 251-944-062657
*p:* + 251-118278508
*e:* ***@***.***; ***@***.***
CMC Road, P. O. Box 5648
Addis Ababa, Ethiopia
www.ecsu.edu.et
[image: twitter icon] <https://twitter.com/DodaZerihun> [image: linkedin
icon] <https://linkedin.com/in/zerihun-doffana-9a6b1b174>

*Google Scholar: *‪Zerihun Doda Doffana - ‪Google Scholar
<https://scholar.google.com/citations?user=sPydrBQAAAAJ&hl=en>

ORCHID id    https://orcid.org/0000-0001-9545-8994

Web of Science Researcher Id http://www.researcherid.com/rid/V-7455-2018

*"[You] [have] formed us for [Yourself] and our hearts are restless till
they find rest in [You]."*

* St. Augustine*

**Comment by AndrzejWawa** [comment]
Is this survey file also the one used by Maxqda? Have you tried copy this into desktop and import copied version?

**Comment by doffanaz** [comment]
Yes, it is. I have copied the file to desktop. I have also tested with the
sample file from QualCoder...

**Comment by ccbogel** [comment]
@doffanaz Please upload pictures not docx files as docx can contain viruses.
OK you still have this 'permission denied' problem.
I do not understand why you are getting Permission Denied errors. 
Maybe for you, you need to run qualcoder as administrator.

**Comment by doffanaz** [comment]
Ok, will do that.

**Comment by doffanaz** [comment]
Dear Sir

I have done as ibstructed, I opened as administrator, and did other things
as well but it's not working. I was so excited about the software, a tree
one which promised to do what a 1000 Dollar MAXQDA or Atlas. to does...
What else could you kindly advise me?

**Comment by AndrzejWawa** [comment]
Maybe you can try to open file you want to import, copy copy the all content, create a new file, paste content and save. The, try to import this new file.

**Comment by ccbogel** [comment]
I think there is something unusual in your computer setup. As the image is about a permissions error. Its not something i feel i can fix. I suggest you try another free program: Taguette

**Comment by doffanaz** [comment]
Ok, thanks. But Tagguette is not as full featured as QualCoder...
Any way, your help is much appreciated!

**Comment by AndrzejWawa** [comment]
You have to experiment, try other files, search for advices in google, maybe try at other computer. There are sometimes problems with Windows I do not understand and have to improvise.
