### ISSUE TITLE
Reports: coded memos breaking reports.

### ISSUE THREAD

**Issue by mikelgoni** [ccbogel/QualCoder#690]
Hi, 
As I told you yesterday in  FB requesting a report which includes coded memos breaks the report engine. 

**To Reproduce**
ask for a report that matches the criteria portraited in this pic:

<img width="989" alt="irudia" src="https://user-images.githubusercontent.com/109315261/179089094-370edc24-d20b-423d-b636-879b62f4a2d6.png">

Following your instructions, I attach the log content: 

ons/QualCoder-master/qualcoder/report_codes.py", line 1959, in matrix_fill_by_codes
    self.te[row][col].append(_("Coded memo: ") + r['coded_memo'])

TypeError: 'str' object is not callable
2022/07/13 22:14:33 ERROR qualcoder.memo.exception_handler Uncaught exception: Traceback (most recent call last):
  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1297, in search
    self.fill_text_edit_with_search_results()

  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1660, in fill_text_edit_with_search_results
    self.matrix_fill_by_codes(self.results, self.case_ids, "case")

  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1959, in matrix_fill_by_codes
    self.te[row][col].append(_("Coded memo: ") + r['coded_memo'])

TypeError: 'str' object is not callable
2022/07/13 22:15:01 ERROR qualcoder.memo.exception_handler Uncaught exception: Traceback (most recent call last):
  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1297, in search
    self.fill_text_edit_with_search_results()

  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1660, in fill_text_edit_with_search_results
    self.matrix_fill_by_codes(self.results, self.case_ids, "case")

  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1959, in matrix_fill_by_codes
    self.te[row][col].append(_("Coded memo: ") + r['coded_memo'])

TypeError: 'str' object is not callable
2022/07/13 22:16:35 ERROR qualcoder.memo.exception_handler Uncaught exception: Traceback (most recent call last):
  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1297, in search
    self.fill_text_edit_with_search_results()

  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1660, in fill_text_edit_with_search_results
    self.matrix_fill_by_codes(self.results, self.case_ids, "case")

  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1959, in matrix_fill_by_codes
    self.te[row][col].append(_("Coded memo: ") + r['coded_memo'])

TypeError: 'str' object is not callable
2022/07/13 22:16:58 ERROR qualcoder.memo.exception_handler Uncaught exception: Traceback (most recent call last):
  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1297, in search
    self.fill_text_edit_with_search_results()

  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1662, in fill_text_edit_with_search_results
    self.matrix_fill_by_codes(self.results, self.file_ids)

  File "/Applications/QualCoder-master/qualcoder/report_codes.py", line 1959, in matrix_fill_by_codes
    self.te[row][col].append(_("Coded memo: ") + r['coded_memo'])

TypeError: 'str' object is not callable
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
2022/07/14 00:05:51 DEBUG __main__.get_latest_github_release <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
2022/07/14 00:26:09 DEBUG __main__.get_latest_github_release <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
2022/07/14 23:06:35 DEBUG __main__.get_latest_github_release <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
2022/07/14 23:08:21 ERROR qualcoder.report_codes.matrix_fill_by_codes 'str' object is not callable
Matrix Coded Memo Error:
choice: All memos
Result dictionary:
{'codename': 'Elkarrizketatua', 'color': '#F4FA58', 'file_or_casename': '01_MAL_Elkarrizketa_Aizpea_Otaegi_transkripzioa.odt', 'pos0': 22, 'pos1': 35, 'text': 'Aizpea Otaegi', 'coder': 'Mikel Goñi Larrea', 'fid': 9, 'coded_memo': 'Errenteriako alkatea da eta bera egon da sarearen koordinazio gunean hasieratik, horregatik elkarrizketatu dugu', 'codename_memo': '', 'source_memo': '', 'ctid': 129, 'result_type': 'text', 'file_or_case': 'File', 'pretext': '\n\nErrenteriako alkate ', 'posttext': ' Mitxelenari elkarrizketa Qualcocoder-softwarea erabilita \n\n\n\n65\n\n\n\nLaburki, zer izan da Errenteriako Sare Publiko Komunitarioa? \n\n3:15 Bueno, ba, beharbada izenari helduz, zaintza sarea deitu diogu, ', 'textedit_start': 0, 'textedit_end': 101, 'row': 0, 'col': 1}

2022/07/14 23:08:21 ERROR qualcoder.report_codes.matrix_fill_by_codes 'str' object is not callable
Matrix Coded Memo Error:
choice: All memos
Result dictionary:
{'codename': 'Errenteria', 'color': '#0D47A1', 'file_or_casename': '01_MAL_Elkarrizketa_Aizpea_Otaegi_transkripzioa.txt', 'pos0': 84, 'pos1': 94, 'text': 'Errenteria', 'coder': 'Mikel Goñi Larrea', 'fid': 1, 'coded_memo': 'Hemen sarearen izenari egiten dio erreferentzia Errenteria hitzak', 'codename_memo': '', 'source_memo': '', 'ctid': 109, 'result_type': 'text', 'file_or_case': 'File', 'pretext': 'Errenteriako alkate Aizpea Otaegi Mitxelenari elkarrizketa\n65\n\nLaburki, zer izan da ', 'posttext': 'ko Sare Publiko Komunitarioa? \n3:15 Bueno, ba, beharbada izenari helduz, zaintza sarea deitu diogu, bere helburua zelako, bada, pandemia bizi dugunez, azkeneko hilabeteetan bizi izan dugun eta, bueno,', 'textedit_start': 0, 'textedit_end': 96, 'row': 1, 'col': 2}

2022/07/14 23:08:21 ERROR qualcoder.report_codes.matrix_fill_by_codes 'str' object is not callable
Matrix Coded Memo Error:
choice: All memos
Result dictionary:
{'codename': 'Kronologia', 'color': '#81F781', 'file_or_casename': '01_MAL_Elkarrizketa_Aizpea_Otaegi_transkripzioa.txt', 'pos0': 2062, 'pos1': 2072, 'text': 'kronologia', 'coder': 'Mikel Goñi Larrea', 'fid': 1, 'coded_memo': 'Honetan jarri behar dugu interesatzen zaigun informazioa; kasu honetan lotuta egongo da erabilitako kode edo etiketarekin. \n', 'codename_memo': '', 'source_memo': '', 'ctid': 110, 'result_type': 'text', 'file_or_case': 'File', 'pretext': 'sonak eta eragilek osatutakoa. Eta justu, bi hanka oso inportante dauzka. Parte instituzionala eta parte soziala. Eta horiek artikulatzean datza, nolabait bere  garrantziaren parte handi bat.\n\nNolako ', 'posttext': ' izan du sareak? \nBueno, egia esan, dekretua, alarma egoeraren dekretua, ez dakit den martxoan 12koa, izan daiteke? Hamabikoa uste dut igandea zela. Orduan, ostegun, ostiralean, jada dagoeneko neurri ', 'textedit_start': 0, 'textedit_end': 96, 'row': 1, 'col': 5}

2022/07/14 23:10:02 ERROR qualcoder.report_codes.matrix_fill_by_codes 'str' object is not callable
Matrix Coded Memo Error:
choice: All memos
Result dictionary:
{'codename': 'Elkarrizketatua', 'color': '#F4FA58', 'file_or_casename': '01_MAL_Elkarrizketa_Aizpea_Otaegi_transkripzioa.odt', 'pos0': 22, 'pos1': 35, 'text': 'Aizpea Otaegi', 'coder': 'Mikel Goñi Larrea', 'fid': 9, 'coded_memo': 'Errenteriako alkatea da eta bera egon da sarearen koordinazio gunean hasieratik, horregatik elkarrizketatu dugu', 'codename_memo': '', 'source_memo': '', 'ctid': 129, 'result_type': 'text', 'file_or_case': 'File', 'pretext': '\n\nErrenteriako alkate ', 'posttext': ' Mitxelenari elkarrizketa Qualcocoder-softwarea erabilita \n\n\n\n65\n\n\n\nLaburki, zer izan da Errenteriako Sare Publiko Komunitarioa? \n\n3:15 Bueno, ba, beharbada izenari helduz, zaintza sarea deitu diogu, ', 'textedit_start': 0, 'textedit_end': 101, 'row': 0, 'col': 1}

2022/07/14 23:10:02 ERROR qualcoder.report_codes.matrix_fill_by_codes 'str' object is not callable
Matrix Coded Memo Error:
choice: All memos
Result dictionary:
{'codename': 'Errenteria', 'color': '#0D47A1', 'file_or_casename': '01_MAL_Elkarrizketa_Aizpea_Otaegi_transkripzioa.txt', 'pos0': 84, 'pos1': 94, 'text': 'Errenteria', 'coder': 'Mikel Goñi Larrea', 'fid': 1, 'coded_memo': 'Hemen sarearen izenari egiten dio erreferentzia Errenteria hitzak', 'codename_memo': '', 'source_memo': '', 'ctid': 109, 'result_type': 'text', 'file_or_case': 'File', 'pretext': 'Errenteriako alkate Aizpea Otaegi Mitxelenari elkarrizketa\n65\n\nLaburki, zer izan da ', 'posttext': 'ko Sare Publiko Komunitarioa? \n3:15 Bueno, ba, beharbada izenari helduz, zaintza sarea deitu diogu, bere helburua zelako, bada, pandemia bizi dugunez, azkeneko hilabeteetan bizi izan dugun eta, bueno,', 'textedit_start': 0, 'textedit_end': 96, 'row': 1, 'col': 2}

2022/07/14 23:10:02 ERROR qualcoder.report_codes.matrix_fill_by_codes 'str' object is not callable
Matrix Coded Memo Error:
choice: All memos
Result dictionary:
{'codename': 'Kronologia', 'color': '#81F781', 'file_or_casename': '01_MAL_Elkarrizketa_Aizpea_Otaegi_transkripzioa.txt', 'pos0': 2062, 'pos1': 2072, 'text': 'kronologia', 'coder': 'Mikel Goñi Larrea', 'fid': 1, 'coded_memo': 'Honetan jarri behar dugu interesatzen zaigun informazioa; kasu honetan lotuta egongo da erabilitako kode edo etiketarekin. \n', 'codename_memo': '', 'source_memo': '', 'ctid': 110, 'result_type': 'text', 'file_or_case': 'File', 'pretext': 'sonak eta eragilek osatutakoa. Eta justu, bi hanka oso inportante dauzka. Parte instituzionala eta parte soziala. Eta horiek artikulatzean datza, nolabait bere  garrantziaren parte handi bat.\n\nNolako ', 'posttext': ' izan du sareak? \nBueno, egia esan, dekretua, alarma egoeraren dekretua, ez dakit den martxoan 12koa, izan daiteke? Hamabikoa uste dut igandea zela. Orduan, ostegun, ostiralean, jada dagoeneko neurri ', 'textedit_start': 0, 'textedit_end': 96, 'row': 1, 'col': 5}

2022/07/14 23:11:21 ERROR qualcoder.report_codes.matrix_fill_by_codes 'str' object is not callable
Matrix Coded Memo Error:
choice: All memos
Result dictionary:
{'codename': 'Elkarrizketatua', 'color': '#F4FA58', 'file_or_casename': '01_MAL_Elkarrizketa_Aizpea_Otaegi_transkripzioa.odt', 'pos0': 22, 'pos1': 35, 'text': 'Aizpea Otaegi', 'coder': 'Mikel Goñi Larrea', 'fid': 9, 'coded_memo': 'Errenteriako alkatea da eta bera egon da sarearen koordinazio gunean hasieratik, horregatik elkarrizketatu dugu', 'codename_memo': '', 'source_memo': '', 'ctid': 129, 'result_type': 'text', 'file_or_case': 'File', 'pretext': '\n\nErrenteriako alkate ', 'posttext': ' Mitxelenari elkarrizketa Qualcocoder-softwarea erabilita \n\n\n\n65\n\n\n\nLaburki, zer izan da Errenteriako Sare Publiko Komunitarioa? \n\n3:15 Bueno, ba, beharbada izenari helduz, zaintza sarea deitu diogu, ', 'textedit_start': 0, 'textedit_end': 101, 'row': 0, 'col': 1}

2022/07/14 23:11:22 ERROR qualcoder.report_codes.matrix_fill_by_codes 'str' object is not callable
Matrix Coded Memo Error:
choice: All memos
Result dictionary:
{'codename': 'Errenteria', 'color': '#0D47A1', 'file_or_casename': '01_MAL_Elkarrizketa_Aizpea_Otaegi_transkripzioa.txt', 'pos0': 84, 'pos1': 94, 'text': 'Errenteria', 'coder': 'Mikel Goñi Larrea', 'fid': 1, 'coded_memo': 'Hemen sarearen izenari egiten dio erreferentzia Errenteria hitzak', 'codename_memo': '', 'source_memo': '', 'ctid': 109, 'result_type': 'text', 'file_or_case': 'File', 'pretext': 'Errenteriako alkate Aizpea Otaegi Mitxelenari elkarrizketa\n65\n\nLaburki, zer izan da ', 'posttext': 'ko Sare Publiko Komunitarioa? \n3:15 Bueno, ba, beharbada izenari helduz, zaintza sarea deitu diogu, bere helburua zelako, bada, pandemia bizi dugunez, azkeneko hilabeteetan bizi izan dugun eta, bueno,', 'textedit_start': 0, 'textedit_end': 96, 'row': 1, 'col': 2}

2022/07/14 23:11:22 ERROR qualcoder.report_codes.matrix_fill_by_codes 'str' object is not callable
Matrix Coded Memo Error:
choice: All memos
Result dictionary:
{'codename': 'Kronologia', 'color': '#81F781', 'file_or_casename': '01_MAL_Elkarrizketa_Aizpea_Otaegi_transkripzioa.txt', 'pos0': 2062, 'pos1': 2072, 'text': 'kronologia', 'coder': 'Mikel Goñi Larrea', 'fid': 1, 'coded_memo': 'Honetan jarri behar dugu interesatzen zaigun informazioa; kasu honetan lotuta egongo da erabilitako kode edo etiketarekin. \n', 'codename_memo': '', 'source_memo': '', 'ctid': 110, 'result_type': 'text', 'file_or_case': 'File', 'pretext': 'sonak eta eragilek osatutakoa. Eta justu, bi hanka oso inportante dauzka. Parte instituzionala eta parte soziala. Eta horiek artikulatzean datza, nolabait bere  garrantziaren parte handi bat.\n\nNolako ', 'posttext': ' izan du sareak? \nBueno, egia esan, dekretua, alarma egoeraren dekretua, ez dakit den martxoan 12koa, izan daiteke? Hamabikoa uste dut igandea zela. Orduan, ostegun, ostiralean, jada dagoeneko neurri ', 'textedit_start': 0, 'textedit_end': 96, 'row': 1, 'col': 5}

**Desktop (please complete the following information):**
 - OS: macOS Monterey 
 - Version 12.4

**Comment by ccbogel** [comment]
Thank you. This log confirmed that the error was not in the data at all.
I now have I think identified the problem and uploaded a new file to fix this.

In python you can have a for loop like this:
for _ in range(0,10):   The _ is a variable for the for loop
In other areas I use _() as a translation function. e.g. _("The") may be translated as "Der"  where needed.
On MacOS the two uses are getting mixed up.
So I will have to go though all the remaining code to replace **for _** with another term, e.g. **for i**   

I will close this issue when you can confirm the fix has worked,

**Comment by ccbogel** [comment]
I will wait and here from @mikelgoni before closing this issue.

**Comment by mikelgoni** [comment]
Hi there, 
Sorry I was desappeared for some days, I was hit by covid...
I pulled down the code, follow install instructions. They worked as usual, that's like a charm. 
The changes in the program code worked fine, and I would say aswell that the bug has been solved. 
So, thanks again. 
Bye
