### ISSUE TITLE
Matrices issues

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#691]
1. There is no results in the categories/codes by filed untill I transpose the matrix (then it is ok):

![obraz](https://user-images.githubusercontent.com/77200214/179238696-1b2754fa-ae4e-412e-b266-3bcafd36804b.png)

2. Can you allow for wrapping names of rows as well as set maximal width of row name in the case of files?:

![obraz](https://user-images.githubusercontent.com/77200214/179238245-9038600e-5e5a-4202-8bd9-fe6a16084c1a.png)

3. When you select all memos/text memos and categories by file (also by case I think), coding memos are not visible

4. PS Have you removed code by case?

**Comment by ccbogel** [comment]
OK. Maximum width of the vertical headers is now 300 pixels. Added tooltips to these so the fill name is shown. I cannot do word wrap.
Code by case option is removed yes. It was much to hard to re-do all the coding needed for this when changes occur in code text, code image code av.

There is lots of separate issue listed in this issue #691. 
So I am closing this issue now that some is resolved. Please open more issues as needed.
