### ISSUE TITLE
Only memo report

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#692]
Hi,

I think there could be implemented sth that appeared in the discussions before and I also thought about this.

In the coding report there are options to show:
1) coded text + coding memos,
2) coded text + coding memos + code memos,
3) annotated text + annotations,

Could you add to this list also:
4) ONLY coding memos (so memos, but without displaying coded text),
5) ONLY code memos,
6) ONLY annotations.

Options 4 and 6 are already available in SQL default queries, and option 5 can be easily generated by SQL. However, adding them into coding report, into drop-down list will probably help many users, which are not familiar with SQL.

**Comment by ccbogel** [comment]
I have updated the choices to include "Only memos"
There is already an annotations option.

**Comment by AndrzejWawa** [comment]
Good, however, can you:

1) Divide this option to "only code text memo" and "only code memos". 
This is justified, because, when you are interested only in coded memos, you do not want also read code memo in each position (the report will be much longer then, especially when code memos is long), as well as, if you want only code memos and you have, e.g. 10 code, you need only 10 positions, not let's say 200 positions of codings.

2) Then, remove names "code text" and "coded memos", as it will be known what it is,

3) In the case of "only code memos" show only the number of memos equals number of codes. So, if you have 10 codes, so you have 10 code memos, and option "only code memos" will display only 10 memos. 
This option will be useful when someone wants systematically prepare consistent memos on definitions and coding rules for each of code.

4) And, in the case of already existing "code text memos" and "all memos" can you write words "code memo" and "coded memo" with CAPITALS, as it is in annotation report? It is quite more readible.

**Comment by ccbogel** [comment]
I have done some of this , more work to do still I think

**Comment by ccbogel** [comment]
I think  I have done most of this. It got confusing. Closing now. But test it out.

**Comment by AndrzejWawa** [comment]
I think that it is very helpful. Now, you can display only codings, but also codings with coded or all memos. Alternatively, you display only coded memo, but also all memos. It is very important as the main analytical work is based on analysing codings themselves or memos themselves, or comparing codings with coded and code memo. Now, you can generate very insightul reports!

1. To make them some clearer, you can name option: coded text memos and all memos as "also coded memos" and "also code memos", so, there will be logics:
None
ALSO coded memos
ALSO all memos
ONLY coded memos
ONLY all memos.

HOWEVER, THE BETTER option (but I don't know how easy to implement) is drop-down list:

"Select one or mamy:
codings (default)
coded memo
code memo 
annotations"

And then you can click one or more options and generate report you would like. E.g. if you want codings with coded memo, you click coding and codings memo. If only code memo, you click only code memo, etc.

2. Can you also implement this "only code memo"? So, of you have 30 codes with memos, it will be displayed 30 positions with information: code name, cid (both on code colour), code memo (in back and white).

Justification: so, you will have possibility to look at only code memos, as you know can look at only coded memo. Both options are very helpful in my opinion. Code memo for systematic review your codes definitions, anchor examples, and coding rules, and checking consistency along them.

**Comment by AndrzejWawa** [comment]
Hi, good! However, by adding "Only code memos" I meant: SELECT name, cid, memo FROM code_name.  So, without showing coded text, name of file etc.

**Comment by ccbogel** [comment]
You dont need a report for that.  Check the ODT codebook export options under the Project menu. I made some changes

**Comment by AndrzejWawa** [comment]
I have this problem:

![obraz](https://user-images.githubusercontent.com/77200214/180644876-e72702cc-7b10-48b6-993b-549fbae00c7a.png)

Nevertheless I think that report option would be better for some uses. Export is more suitable for sharing codebook with others, but the report would be better for analysing and editing memos on an ongoing basis, e.g. you look at report, detect lacks, fill these gaps, generate report again, correct inconsistencies between memos, generate again etc. Moreover, it would complete the logics of memo options: you have three for "also", and then, three for "only". So, I think that would be helpful to have this in export as well as in the coding report tab - if it is not very time consuming.

**Comment by ccbogel** [comment]
Oops. I forgot to upload the file.

**Comment by AndrzejWawa** [comment]
Very nice! Now, there is a lot of options to suit reports to individual users needs!

Minor issues:
1. when you generate codebook memos in report, you don't clear previous report, so, codebook memos are added. This could be interpreted as bug, because, firstly you generate annotation report and after generating codebook memos it is added at the end of annotation report. 
2. can you colour word "Code" and name of code in the case of codebook memos? 
3. can you delete the word "CODED MEMO", but only in the case of:
a) only memos,
b) only coded memos,
c) and word "CODE" in codebook memos (if the header can be coloured).

**Comment by ccbogel** [comment]
ok

**Comment by AndrzejWawa** [comment]
Sorry, the last thing.

I meant deleting word: "CODED MEMO" and "MEMO" from only memos, only coded memos, and codebook memos - it will be more readible and easy for analysis, as, when you selecf "only" memos you can be sure that there are texts of memos.
The word in codebook memos "Code" can be kept.

**Comment by AndrzejWawa** [comment]
Excellent!

Only one thing: in "only coded memos" only findings with memo should be shown, now, there are shown also findings without memos:

![obraz](https://user-images.githubusercontent.com/77200214/180898908-16ca128c-b3b4-4002-ac1d-93143a93435c.png)
