### ISSUE TITLE
Hide top panel also in right-click menu

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#696]
Can you add the option for hiding the top panel in "coding report" and "text code" to the righ-click menu, as well as indicate there shorcut? It is very helpful, however, many users may do not notice it while there is no any track for this in QC.

PS As I understand you prefer more issues but simpler than the aggregated ones?

**Comment by ccbogel** [comment]
added for report codings in right click text area, so far. needs to be results showing for this to work.

Simpler is better - because I can then mark as completed once it is done.
