### ISSUE TITLE
Resizing relation windows

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#697]
1. Can you allow to resize windows with relations table and stats table? E.g. to expand table with relations at the expense of stats window and vice versa.

2. Moreover, can you allow for this that when you click again stats button, for the same combination of codes, it will be hidden? So, you can show and hide this?

**Comment by ccbogel** [comment]
I have made it to resize. Both tables are now automatically filled.
Use the mouse on the horizontal bar to show and hide.

**Comment by AndrzejWawa** [comment]
Looks very good!
