### ISSUE TITLE
Adding coding memos to relation table

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#698]
The memo0 and memo1 could be added to the relations table displayed in QC, as some users may analyse mainly memos summarising codings, not the codings directly. Moreover, also to add them to the table exported into csv.

As we discussed the SQL for this is:

SELECT 
ctcode0.memo as "memo0", code_text.memo as "memo1"
FROM code_relations left join code_text on code_text.ctid = ctid1 
left join code_text as ctcode0 on ctcode0.ctid=ctid0

**Comment by ccbogel** [comment]
Thanks but not quite: see report_relations.py around lines 231 onwards
