### ISSUE TITLE
Adding more right-click options for relations table

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#699]
The righ-click menu options (now available in SQL statements) could be added (e.g. sorting, filtering) By default table should be sorted ascending by ctid1, as it will support interpretation (ctid's are generated in time order, as I understand).

**Comment by ccbogel** [comment]
right-click sort options available

**Comment by AndrzejWawa** [comment]
Good, you can also implement this to statistics table (e.g. to sort findings from maximal mean to the minimal). So, two tables will have similar, right-click options.

**Comment by ccbogel** [comment]
sorting in both tables done.
