### ISSUE TITLE
Missing features?(comparison with WeftQDA)

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#7]
Despite being abandoned, WeftQDA is one of the first results when you google open source qualitative analysis. I am not a coder and was never able to run it as it threw an error.

Have you given a look at it?

http://www.pressure.to/qda/# and manual http://www.pressure.to/qda/doc/weft_manual-en.pdf

Does it have interesting features you could/would port to QualCoder?

**Comment by ccbogel** [comment]
Thanks for the suggestion. From what I can understand in the WEFT manual, QualCoder has similar functionality. There might be some difference in developing search queries.The viewing coded passages in context might be something I could add, although coded text in context can be viewed in the coding dialog window. 
I have also been looking at ways to incorporate audio/video, but I think this will require a slightly different database structure and a few coding changes, so  I might later on create a new repository based in this one and work on that too.

**Comment by WPFilmmaker** [comment]
You are welcome, I thought it could provide some inspiration for the project given that despite being abandoned it is one of the first results that appear on google (so I suppose many try to use it). Audio/video would be a cool addition! 

By "create a new repository based in this one and work on that too" you mean fork QualCoder or just to put the coder on a new repo before merging?
I don't have much time right now but if you need testing I will be glad to help.

**Comment by ccbogel** [comment]
Yes its good inspiration. 
Instead of creating a new repository, I will upload the changes to this repository, mainly because at this stage likely very few people have downloaded or used it. So any impact with database changes and the qda folder structure will be minimal at this stage. I am presuming that you yourself have not actually begun using the software for a project.

**Comment by WPFilmmaker** [comment]
Yes you are right, I completed a project using a qualitative approach, but I discover QualCoder only in the final stage so it was too late to use it for that. Thus my testing at the moment is limited to following instructions from the manual and report feedbacks/bugs, but no "in field testing" so far.

I think I already mentioned that most of my experience (very limited) comes from quantitative not qualitative tools. Of course QualCoder's userbase is not and will never be of millions, because research it is a niche. 
However I do feel that there is room within that niche for Opensource projects for at the least 3 reasons: 

1)There are many FLOSS fans (for several reasons) who are willing to try out QualCoder 2) Not many can afford licenses for professional softwares 3) Qualitative FLOSS software are not many, so if your project is solid and functional it will eventually be discovered.

That's why I stress for simplifying things (manual,flatpak etc.) and promotion on the web (reddit,flathub etc.), if the already small user base, can't even find the project it will struggle to find people :/ only few will bother to search key terms in github and skim through the hundreds of repos to find the right software.

I saw in your last commit that you are preparing for video/audio analysis and I am glad to see you keep working on it.

**Comment by ccbogel** [comment]
Yes, it is a niche market. I will do a flatpack after I have improve the audio/video coding. It has been a bit of a challenge, but I have found the vlc media player helpful for displaying audio/video and it works with this software in Ubuntu / Linux Mint. I can currently import and view a/v files, but have yet to do the qual coding aspect.

**Comment by ccbogel** [comment]
Coding audio and video is now possible. However, I have not implemented **any** gui functions to view, report or edit this coding so far. The only way to report on or edit coded a/v/ segments is through the sql_dialog window.

**Comment by WPFilmmaker** [comment]
@ccbogel Great! Do you have plans to implement a guy in the future? Is there any specific format you can analyse or you use ffmpeg so that a lot of formats can be used? Is there any specific area where you think testing could be useful?

**Comment by ccbogel** [comment]
Yes I do plan to do a gui for the audio/video, but this takes time. I have allowed for a variety of common audio and video formats (see wordpress). Currently there's no need to use ffmpeg as the vlc player can play a variety of formats.

**Comment by ccbogel** [comment]
OK, well I will close this issue down now. I have done a lot of work getting the audio/video to work.  I have to check one or two things on Windows too. I think it is getting close to a flatpak now.
