### ISSUE TITLE
Improvements to the file manager

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#70]
I have a list of improvements which I think would improve the functionality of the file manager (the area where you load/delete files). These ideas are based on having multiple files loaded.

- Icon to represent the type of file audio/video, photo,text (if I have 10 or more loaded files, 9 of which are photos and 1 is text, I quickly can find the right one)

- Ability to rearrange the loaded files: per name/type/date of creation

- Ability to delete them through keyboard (right now you have to go each time on 'delete' and if you have many files it becomes tedious).

I know those are many features but hopefully with time the handling of files will improve :)

**Comment by ccbogel** [comment]
I have added file icons now. Now have to work on the other things.

**Comment by WPFilmmaker** [comment]
@ccbogel Thanks a lot!.

**Comment by ccbogel** [comment]
Also can order by name, date, or type

**Comment by ccbogel** [comment]
OK, to delete files, instead of using the del button, which  have some trouble implementing.  I have added options to the right-click context menu, including delete. Hope this is ok.
![pic1](https://user-images.githubusercontent.com/5834638/77239170-90fb4000-6c2b-11ea-90a4-f39e4966bf28.png)

**Comment by WPFilmmaker** [comment]
@ccbogel that's great! Thanks a lot!

**Comment by ccbogel** [comment]
closing
