### ISSUE TITLE
Chart for relations stats

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#701]
You can also add button in code relations to generate chart presenting stats. In the form of bar diagram. Here is example and LO Calc file:

![obraz](https://user-images.githubusercontent.com/77200214/179373067-d239764d-e7d4-4ca6-952d-34a74a77fbf3.png)

[NFP business model and legislation - pilot project_relations_0_stats chart.ods](https://github.com/ccbogel/QualCoder/files/9126654/NFP.business.model.and.legislation.-.pilot.project_relations_0_stats.chart.ods)

**Comment by ccbogel** [comment]
How does this help analysis?

**Comment by AndrzejWawa** [comment]
That at the same chart you have presented strength of relations between different codes. So, it can be easier to identify various patterns than looking at the table. Moreover, you have different indicators at the same graph, so more patterns can be indentify basing on different indicators or particular indicators can be quickly visually controlled by the others. In generał, for some people it easier way for analysis than only table.

**Comment by ccbogel** [comment]
Done, as boxplots.

**Comment by AndrzejWawa** [comment]
Thanks! This is wonderful!
