### ISSUE TITLE
Files for specific case

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#703]
Now, when you selected files and cases you cannot generate matrix "code by file". However, it should be generated but only for files which are assigned to the selected cases.

**Comment by ccbogel** [comment]
Yes thats correct. 
I will see if I can fix that, so that the Matrix Categories/Codes by File can be selected when you have only selected cases.

**Comment by ccbogel** [comment]
OK I have done this now. Best if you 0nly select one case at a time, as all the files for that case will be shown.

**Comment by AndrzejWawa** [comment]
Good, this is what I meant! It seams also work for many cases selected.

**Comment by ccbogel** [comment]
OK great.
