### ISSUE TITLE
Linking text boxes with the same content 

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#705]
I noted that you cannot create link between test boxes with the same content in graph mode. I mean that QC discerns that despite the same content they are different boxes and you can properly select the end of line however, after clicking ok, the line doesn't appear.

**Comment by ccbogel** [comment]
Yes this is a difficult thing to resolve. I suggest that you have different content in all free text boxes - this can be done by adding spaces.  e.g. 'the', 'the ', 'the  ', ' the'
I will add to the documentation that identical free text should not be created, or make is so that spaces are added somehow.

**Comment by AndrzejWawa** [comment]
Hi, I think that automatically adding spaces is the best solution. Is it possible to adding spaces AFTER text?

**Comment by ccbogel** [comment]
completed. you get a warning if the text is the same as existing

**Comment by AndrzejWawa** [comment]
Hmm, what about inserting boxes with codings and coding memos? - I don't see difference.

**Comment by ccbogel** [comment]
HI. No I wont automatically add spaces. I think it is better for the User to be aware and choose their own modifications of the text, when they are entering their own free text boxes.
Yes you are correct, multiple codings of the same text can be displayed for now - but again link links do not work well. -OK for this I will add a  text suffix. maybe [2], [3] or similar at the end of the displayed text.

**Comment by ccbogel** [comment]
OK. So for other items:
Only one of each can be added. so only one instance of coding of the same coded segment of a code in a file.
Adding extra text as  I suggested above caused a heap of other problems.

**Comment by AndrzejWawa** [comment]
Ok, so, can you add always visible information (after information about saving the graph) that inserted or showed text boxes have to have different content?

**Comment by AndrzejWawa** [comment]
Or better idea, when you insert codings or coded memos with concent duplicates or want to insert codings or coded memos with the same content as already inserted codings or coded memo, can you add information window: "X boxes cannot be inserted because there are concent duplicates". And X means number of omitted boxes.

**Comment by AndrzejWawa** [comment]
I would only change the phrase that X items already displayed to "there are X items with the same content". This is because often it is not about already displayed items but about that you selected items with the same content. 

Also, add this information for inserting coding memos.

**Comment by ccbogel** [comment]
I am working gradually on it. Currently now you cannot select files, cases or image or av codings that are already displayed.

**Comment by AndrzejWawa** [comment]
Hi, I noted that you can place many codings with the same text if they have different ctid, however cannot do this for memos. I think that the best solution is allow for inserting codings and memos with different ids but same content, but not allow to place many boxes with same ids. So:

1. Can you allow also for memos to insert many memos with the same text if they have unique ctid/imid/acid?
2. When inserting codings/memos with different id but same content show warning that "codings/memos with the same content cannot be linked. Change content to link".

Codings and memos with different ids always should be able to be placed bacause analytical reasons. Sometimes different segments can have same content but they are unique.
