### ISSUE TITLE
One default query and name of tab

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#708]
1. Can you enrich "CODES, FILEID, CODED TEXT" default query to:

-- CODES, FILEID, CODED TEXT
select code_name.name as "codename", code_name.cid, code_text.fid, source.name as "filename", code_text.pos0, code_text.pos1, code_text.seltext from code_name join code_text on code_name.cid = code_text.cid join source on source.id=code_text.fid
-- AND codename = "CODENAME" -- UNCOMMENT (CLEAR "--" AT THE BEGINNING)  AND FILL TO SELECT SPECIFIC CODE
-- AND filename = "FILENAME" -- UNCOMMENT AND FILL TO SELECT SPECIFIC FILE

2. Change the name of tab "SQL statements" into "Generate tables (SQL)", so, it would be more understandable for many users.

**Comment by ccbogel** [comment]
fixed. 
Changed menu entry to: Database queries
