### ISSUE TITLE
ctrl-tab/ctr-shift-tab problem

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#709]
I noted that shortcuts don't work after selecting "manage" and "coding" tabs. In the case of "mange" they start to selecting table rows when you click on them, and also stop, when you click in coding mode.

If it is too time consuming to fix this, you can simply delete this shortcuts for menu tabs and clear information.

**Comment by ccbogel** [comment]
I can remove the information about them.  I cannot remove the shortcuts themselves

**Comment by AndrzejWawa** [comment]
Ok, it is fine.
