### ISSUE TITLE
Weird behavior when trying to export file

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#71]
How to reproduce:
- Select a file
- Click 'export'
- File menu appears where you can select where to export
- Click X and close it without exporting (same thing happens if you press 'cancel')
- QualCoder shows popup 'file exported'.

Qualcoder Log shows: 
"nameofthefile.pdf.txt exported to"

It does not mention the file path (also is it normal that the extension is .pdf.txt when the file I tried to export is a pdf?)

Also I tried exporting a png file from QualCoder and all it happens is that the 'export' button remains selected but no file manager appears.

Edit: QualCoder 1.7 on Lubuntu 18.04.1

**Comment by ccbogel** [comment]
Yes. I had intended the export to only export texts that had been imported into the database. So when a pdf is imported, the text that was scraped from the pdf into the database was then exported.
I have to make it clearer what is being exported.
To obtain the original imported filed (pdfs, pictures) open the .qua folder and those documents are contained in the sub-folders.

**Comment by WPFilmmaker** [comment]
@ccbogel Thanks for your reply, it seems you refer to my last part right?
The issue I reported (you click X or cancel but the programs says it was exported) it is a bug or am I missing something? I just find very counterintuitive that when user cancel an operation the software popups a message saying it did the opposite I asked. Sorry for the confusion^^

**Comment by ccbogel** [comment]
Thats OK. I have just now finished testing the export. Now all files will be exported.
