### ISSUE TITLE
Ctrl+d for pause

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#710]
Hi, can you provide additional shortcut for pause in AV mode, namely **ctrl+d**? Other shortcuts are ok, however, ctrl+p is very inconvenient as the rest of the shorcuts are located on the left side of keyboard. So, taking into account that start/end/clear segment is ctrl+s (and this is wonderful), pause should be placed near to this, e.g. ctr;+d - because there are used by turns. Then. it will be very convenient, ctrl+d for start pause and ctrl+s for start, end, and clear segment - only one button have to be changed. Therefore, coding AV will be much quicker and convenient.

**Comment by ccbogel** [comment]
done

**Comment by AndrzejWawa** [comment]
Thanks! Can you only complete the tooltip thath the shorcuts are ctrl+d/ctrl+p?
