### ISSUE TITLE
Saving graph bug

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#711]
Hi,

I created the following graph:

![obraz](https://user-images.githubusercontent.com/77200214/181062529-09f7eae5-e868-4b7d-959d-58de925762e8.png)

But after saving and reloading it looks like this:

![obraz](https://user-images.githubusercontent.com/77200214/181062626-8c86b2f6-bac2-4fce-8764-62376277a868.png)

**Comment by ccbogel** [comment]
Hmm. I will need lots of information to 1: re-create the problem, and then 2: to fix the problem.

**Comment by AndrzejWawa** [comment]
Hmm,

I found that there are problems with saving lines in general. So, you can create two text boxes and try to link them by line.

**Comment by ccbogel** [comment]
Ok. I will test. I did make a change a week or 2 ago, to remove lines that had no staet or end points. I will check it out.

**Comment by ccbogel** [comment]
ok I think I have fixed this. But your exisitng graphs with the Free Text items may be a problem as the value of 'freetextid' was not being increased for each new FreeTextGraphics item.

**Comment by AndrzejWawa** [comment]
Hi, ok, thank you. It works. I have not done much work the so previous graphs are not a problem.

**Comment by ccbogel** [comment]
Thanks.
