### ISSUE TITLE
Ctid/imid,avid in tooltips

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#714]
Can you add ctid/imid,avid in tooltips for codings in coding mode? It will facilitate identification of cadings and modify them based on reports (as the modification of codings. from the report level is not possible). This could be only visible after clicking "show ids" in setting, if you prefer.

![obraz](https://user-images.githubusercontent.com/77200214/184152614-f8efa961-6a78-425b-8db3-f3f7b2690250.png)

**Comment by ccbogel** [comment]
OK so far have done this for code text and code images.

**Comment by AndrzejWawa** [comment]
Ids in image coding and graphs appears after reloading the coding image mode and graphs. In text coding they appears immediately after coding segment.

Not very important for me, however, can be fixed if easy.
