### ISSUE TITLE
Linking the same content info

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#718]
Thank you for making inserting the memos with same content but different id possible!

Can you only place information box, when inserting coding or coded memos with the same content, in the wording like: You cannot link boxes with the same content. Differ the wording by "edit text option" to link boxes.

So, it will not be not interpeted as bug but as one of the rules of QC.

**Comment by ccbogel** [comment]
yes OK, will do.

**Comment by ccbogel** [comment]
OK, now you cannot select the same text in the 'to' selection, as the same text does not show up.
