### ISSUE TITLE
Modernize and homogenize the icons

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#719]
Hi!

A suggestion would be to modernize and homogenize the icons within the same graphic (for example, using Fork Awesome). I wanted to do some tests, but unfortunately I couldn't find the source files.

Sincerely

**Comment by ccbogel** [comment]
Thank you if you would like to test those. If you email me, I can forward a zipped folder of images to you. Keep the file names the same after you have edited them. You then need to run a python file in the GUI folder called create_script_base64.py to convert the images in the GUI folder into a python file. The images must be in that folder location also.

**Comment by qwertygc** [comment]
You can upload on Wetransfert and share link here.
Are there other files needed to build the software that are not on the git repository?

**Comment by ccbogel** [comment]
Instead I uploaded a folder of icons to QualCoder. That is the only set of files needed to build. But the icons are not used directly, as mentioned above.The only other thing  I use is a notes file for translations to remind me of the commands to run.

**Comment by qwertygc** [comment]
OK, i try to create homogenize icon set.

**Comment by ccbogel** [comment]
thank you

**Comment by ccbogel** [comment]
closing as no progress
