### ISSUE TITLE
Installer is apt-based/compatibility with Fedora

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#72]
The installer requires apt. Did not work for rpm based Linuxes.
A warning would be helpful.

**Comment by ilippert** [comment]
except for the ebooks lib, all dependencies are available for fedora.
copying the debian ebooks lib into my fedora system /usr/lib/python3.7/site-packages allowed QualCoder to work.

**Comment by ccbogel** [comment]
Thanks for the information. I am not familiar with the Fedora rpm package OS. I will add a warning to the install.sh script
I have recently found ebooks lib did not work for obtaining a text that previously worked. So ebook importation may be a problem for now. Please let me know, and then I might have to source another ebook library.

**Comment by ilippert** [comment]
Thanks a lot for the immediate change. I looked into the production of rpm packages. If I find time, I might make a proposal for an rpm package.

**Comment by ilippert** [comment]
Hi, I am currently trying to reinstall the package on another Fedora system. The ebook package still provides headache. If you have a chance to source an ebook package that is easily available also as a fedora package, that would be amazing ;)

My current workaround is this

`python3 -m pip install Ebooklib`

and then move the files from root/.local to /usr

`mv ~/.local/lib/python3.8/site-packages/Ebook* /usr/lib/python3.8/site-packages/` & `mv ~/.local/lib/python3.8/site-packages/ebook* /usr/lib/python3.8/site-packages/`

**Comment by ccbogel** [comment]
maybe have a separate install.sh for Fedora that does these actions ?

**Comment by ccbogel** [comment]
@ilippert I have added a _install_fedora.sh_ script. For python 3.8 only.
Are you able to test this for me on Fedora?

**Comment by ccbogel** [comment]
I will close this issue soon, as I have not received a response.

**Comment by ilippert** [comment]
Thank you for your patience, sorry for not responding. Let's close it at this point. I will get back here if I encounter an issue in the next reinstall :)

**Comment by ilippert** [comment]
ok, tested now and offered suggestions at https://github.com/ccbogel/QualCoder/pulls
