### ISSUE TITLE
Couldn't install in Windows

### ISSUE THREAD

**Issue by IOA-Lotus** [ccbogel/QualCoder#727]
I am not able to run in Pycharm in windows

**Comment by ccbogel** [comment]
Hi, make sure you have VLC installed, then installed the dependencies using pip, then download the exe file for windows 10/11 from here:
https://github.com/ccbogel/QualCoder/releases/tag/3.1
Double click to run. Let me know if this works first.

Using PyCharm is more difficult to set up as you have to set up a python interpreter and environment (e.g. python3.10), and you have to install the dependencies for that interpreter via PyCharm. Then run the __main__.py file.  I cannot give detailed instructions on the use of PyCharm, as it is complicated and I also had to google a lot to get things to works well for me.

**Comment by ccbogel** [comment]
I will close this issue soon, as no response in 8 days.

**Comment by ccbogel** [comment]
Closing issue as I have had no response in 2 weeks.
