### ISSUE TITLE
Shortening code names in codelist and creating alternative full name codelist

### ISSUE THREAD

**Issue by diegopaucarv** [ccbogel/QualCoder#739]
Document text isn't manageable whenever the codenames are large enough. 

First, choosing a max characters threshold. But, as you may now, many analysts prefer to paraphrase and create long sentences as codes. So, for these cases I would use the strategy Tableau uses for long categories: displyaing a ... character whenever the limit is reached, and creating an alternative "original" codelist with the limitless codes. Maybe a button and other shortcuts might be needed to easen the access to this original code list. Whenever adding a new code from list directly from the document text, it might be extracted from the new "original" codelist.

**Comment by ccbogel** [comment]
OK. I had added along code name to my codes. I have added tooltips that show the full code name when you hover the mouse over the code name.
It seems ok, and quite manageable.
![long_code_name](https://user-images.githubusercontent.com/5834638/206895123-3529dfc3-733c-4d57-8069-ffff7952c679.png)

**Comment by diegopaucarv** [comment]
Yeah, but you can't really track how many texts are coded (which of the codes are being used or not), because the column that indicates this seems hidden. So, you can use two codes for the same thing, or create new ones if you don't have a picture of the currently active codes.

**Comment by ccbogel** [comment]
OK I have made it so that long code names are shortened to 50 characters. with '..' in the middle.
You can also make the code tree font a bit smaller in Settings (which I have done).
I will leave this as a test here for now and see what other feedback come from it, before I apply this change elsewhere.
![Screenshot from 2022-12-12 08-42-36](https://user-images.githubusercontent.com/5834638/206930480-4b1233fe-62ee-4cd1-a9df-03fffafcd8c4.png)

**Comment by diegopaucarv** [comment]
I feel is a particularly good solution. Consider, though, that MAXQDA also shorten the display of long code names. A caveat with this approach is that you need to easily access the full codelist somehow. I suggest creating a button for that.

**Comment by ccbogel** [comment]
You can hover over the shortened code name to show the full code name.

**Comment by ccbogel** [comment]
I notice reading MAXQDA documents that the maximum code length is 63 characters.

**Comment by diegopaucarv** [comment]
This is true. They still chop the codenames display when it's too large as shown in here.
![image](https://user-images.githubusercontent.com/14988865/207869660-854b2f9f-8b04-4501-a89c-07f961247797.png)

**Comment by ccbogel** [comment]
OK. I will close this for now, as I think my solution is Ok. You can re-open it if it is not quite correct yet.
