### ISSUE TITLE
Small one: after adding a new code, please let the highlightened text automatically be coded in it

### ISSUE THREAD

**Issue by diegopaucarv** [ccbogel/QualCoder#741]
When somebody creates a new code, they also need to make a click on it to add an already highlightened quote in order to code it. It would be great if just creating a code sufficed to code text if highlighted. I've found myself losing the pace of my analysis because of this.

**Comment by ccbogel** [comment]
Yes I added this in the latest 3.2 version. (not in 3.1).
You highlight the text then right click with mouse.
There is an option to 'Mark with new code'
It asks for a new code name and the selected text is marked.
