### ISSUE TITLE
Import of REFI-QDA Codebook fails

### ISSUE THREAD

**Issue by jbkieffer** [ccbogel/QualCoder#744]
**Description**
When I attempt to import a .qdc codebook file exported from a different QDA software, the import always fails with the message: 
`path/filename.qdc NOT imported` (where `path/filename` is my local information).

**To Reproduce**
Attempt to import a .qdc file. This is my first trial with QC; I am trying to import a codebook to avoid having to create many codes one by one. So far I have not been able to get the codebook import to work at all so this problem always reproduces for me.

**Expected Behavior**
It would be great if the codebook import worked. I can see the section in QualCoder/qualcoder/refi.py where the codebook import happens, but my Python is not good enough to troubleshoot this on my own.

**Desktop:**
 - OS: Windows 10 Enterprise
 - OS Build: 19044.2486
 - QualCoder 3.2 installed from source in a dedicated conda environment

**Additional context**
- The QDA software I exported the codebook from is Taguette
- I examined the codebook file for obvious xml and schema errors and tried a number of different edits in case Taguette's .qdc export doesn't follow the spec, but none of my changes fixed the import issue.
- Example codebook export from Taguette is attached
  - Contains 3 top-level codes and 0 child codes
  - File extension changed to .zip; the file is NOT compressed
[codebook-taguette-example.zip](https://github.com/ccbogel/QualCoder/files/10405991/codebook-taguette-example.zip)

**Comment by ccbogel** [comment]
Thank you. A recent typo caused this. It is updated now.
I can import the codebook with the codes: challenging, interesting skills
Please let me know if this is now resolved for you (download source and build again).
p.s. I see you used QC on macOS - please let me know if the install instructions for mac can be improved, as I do not own a mac.

**Comment by jbkieffer** [comment]
Thanks so much for the quick reply. I pulled the changes, rebuilt the application and the import job works now. Hooray!
I saw your edited comment about the installation instructions for macOS. I don't regularly use a Mac but I do have access to one. When I have some time and the Mac in my hands I'll test those install instructions and send a PR with any suggestions. I really admire what you're doing with this project.

**Comment by ccbogel** [comment]
@jbkieffer yes, for some odd reason I initially mistakenly read OS as macOS. LOL. 
Also, you can download exe's for Windows from the releases page. So for these, e.g. 3.1 release nothing apart from VLC needs to be installed. For 3.2 forward VLC will only be required to be installed for a/v coding.
