### ISSUE TITLE
Coding Video/ Audio is not possible on macOS.

### ISSUE THREAD

**Issue by kampfq** [ccbogel/QualCoder#748]
**Describe the bug**
when selecting "Code audio/video"  this message appears:
'module 'PyQt6.QtWidgets' has no attribute 'QMacCocoaViewContainer''

**To Reproduce**
load a videofile in a qualcoder project

**Expected behavior**
the interface for coding appears

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - Version 3.2

**Additional context**
--

**Comment by ccbogel** [comment]
OK. I suspected there could be a problem as pycharm was hinting at it.
In the file view_av.py can you comment out these lines:

        if platform.system() == "Darwin":  # for MacOS
            self.ddialog.dframe = QtWidgets.QMacCocoaViewContainer(0)

These lines occur two times in this file.

Then try and run again and see if it works.

**Comment by ccbogel** [comment]
I have updated some code i nthe view_av.py module. This _might_ fix the problem, but  I cannot test it.

**Comment by vansorat** [comment]
I downloaded the latest codes from Github and installed on MacOS (macOS BigSur v.11.74, MacBook Pro 2013, Intel). I could not code videos. I then installed FFpmeg and also placed the project folder on my desktop.  I can now code videos and can view coded segment from coding panel.  When running coding report, I cannot view the code in context. It gives the error noted above AttributeError: 'PyQt6.QtWidgets' has no attribute 'QMacCocoaViewContainer''

**Comment by ccbogel** [comment]
Thanks for the feedback. I do not have a mac to test on.
I updated what I think is causing the problem for viewing the code in context. Please download the latest code and install again.
I hope the install instructions were clear enough also.
ffmpeg is not essential for QualCoder to work. ffmpeg is only used for converting speech to text, and for creating a waveform image.
Please let me know if the updated file fixed the problem.

**Comment by ccbogel** [comment]
Works now

**Comment by vansorat** [comment]
Wonderful! Thank you.

    On Friday, June 30, 2023 at 06:47:07 AM EDT, QualCoder Developer ***@***.***> wrote:  
 
 


Works now
