### ISSUE TITLE
Add filter for files list

### ISSUE THREAD

**Issue by joehays** [ccbogel/QualCoder#749]
I have a lot of files. It would be VERY helpful to be able to filter files to be listed with a regex filter.

**Comment by ccbogel** [comment]
do you mean a filter on the file name?

**Comment by joehays** [comment]
Yes. Sorry for the ambiguity. A regex filter on the names of the files.

**Comment by ccbogel** [comment]
Yes ok. I will work through this and some other issues. I cannot say exactly when I will get them implemented, nor If I will be able to implement all of them.
I guess you must, in general, be finding the software OK to use.

**Comment by joehays** [comment]
Oh yes. Please don't misinterpret all my submitted "issues" as negative. I
very much appreciate the work that you are doing here. I see the great
potential of this tool. Yes, I have fairly strong opinions on workflow,
interface design, and usability but the general direction you're going in
is great.

Thank you for sharing it.

**Comment by joehays** [comment]
> p.s. there is currently a right-click option on the name of 'show values like' - is this not sufficient?

I tried using this but never succeeded. This is likely user error but... somewhere in the docs it said that the wild characters for this were '%' and '_'. When I enters filters such as '%<string>%' or '_<string>_', where <string> was present in at least one file name, I got an empty list. I also tried '.<string>.' and '*<string>*'. I always got an empty list. What am I doing wrong?

**Comment by ccbogel** [comment]
OK good to know that the work overall is good :) 
 I have been having some challenges with audio/video especially lately - across different platforms.

Ah yes. Those filters were for specific locations - only where the regex was mentioned. To filter a file name you could enter _ed_ or _doc_ to get a short list of those file named that contained ed  or doc. I did not implement the regex filtering in other places, as most people are not familiar with regex - (I admit I also and a bit vague on it too). Having regex with file name would be a problem as a lot of file names have an underscore and a dot. So then a lot of other people would get confused.

**Comment by joehays** [comment]
Ah, I see. That feature works great now that I know how to use it. Is there a way to get back to the full list without using the mouse? I hit ESC and the list went blank. Just curious. I LOVE interfaces that I can do most/all my work without ever touching the mouse. It just slows things down... :-)

**Comment by joehays** [comment]
> but maybe another right-click menu option

You're "show values like" is already a right-click option. This basically does what I was looking for. It's not general like the regex but this will get me a long way down the road without regex. 

I suggest that you add the ESC button feature to get back to the full list and close this issue. My $.02.

**Comment by ccbogel** [comment]
I cant implement ESC but  I have implemented Ctrl A
