### ISSUE TITLE
Add attribute columns in Case File Manager

### ISSUE THREAD

**Issue by joehays** [ccbogel/QualCoder#751]
When trying to add files to a case (in the Cafe File Manager) I need to be able to see the attribute columns to be able to properly assign the case. It's quite painful now without being able to see it. 

I'm working on a large set of imported files.

**Comment by ccbogel** [comment]
done

**Comment by joehays** [comment]
So, I cloned the latest repo and could not figure out how to add the attribute columns. Any hints on how you implemented this?

**Comment by joehays** [comment]
Scratch that, I saw your note from issue #752 

'Point 4. too much overhead for me to implement - this can be done in the Manage Files area. but I did add the columns to view. ps in the Manage files area, you can add a case to the selected file - right click menu in cases column"
