### ISSUE TITLE
Expected behavior of Case File Manager

### ISSUE THREAD

**Issue by joehays** [ccbogel/QualCoder#752]
1) Please stop resetting the column widths and row focus when I assist select 'add files to the case'. Currently when I assign the columns reset and the file list jumps to the top again. Very annoying and slows the process down.
2) there should be no need to click/double click to view the file of the active row. This should be implicit. As I move the active row with the arrow buttons the file view should automatically update following the arrows. 
3) and a button that optionally removes files that are already added to the case from the list .
4) PLEASE allow users to add attribute columns in the file list view.

**Comment by ccbogel** [comment]
Points 2 and 3 are done.

**Comment by ccbogel** [comment]
Point 4. too much overhead for me to implement - this can be done in the Manage Files area. but  I did add the columns to view.
ps in the Manage files area, you can add a case to the selected file - right click menu in cases column

**Comment by ccbogel** [comment]
Point 5. This is working fine for me.
The others you suggest eg file manager - these are embedded inside the main app window, so cannot be otherwise resized.
