### ISSUE TITLE
Allow users to assign case from the File Manager window

### ISSUE THREAD

**Issue by joehays** [ccbogel/QualCoder#753]
Allow users to assign case from the File Manager window. Ideally, let me multi-select and assign a case to all selected in the File Manager View.

Same multi-select assignment ability for Attributes.

**Comment by ccbogel** [comment]
I cannot implement multiple row select as this affects other functionality.

**Comment by ccbogel** [comment]
Can now assign cases to selected file. right click on case column for the menu option
