### ISSUE TITLE
Need Ctrl+F/search ability is file text

### ISSUE THREAD

**Issue by joehays** [ccbogel/QualCoder#754]
Users need the ability to search within the file being coded.

**Comment by ccbogel** [comment]
That is the search box at the top. then mouse click or tab to forward/back arrows and press  space.
![image](https://user-images.githubusercontent.com/5834638/215467988-8b873250-1b37-4872-aac3-f69d9661a2fd.png)

**Comment by ccbogel** [comment]
and added ctrl F to jump to search box
