### ISSUE TITLE
Reporting: Logical AND for attributes

### ISSUE THREAD

**Issue by erz96cxw** [ccbogel/QualCoder#755]
There currently seems no way to only report coded in cases with a combination of attributes. It also seems like one can select EITHER attributes OR files/cases to delimit the reporting search, not a combination of both.

Hence, I have two feature requests for allowing more delimited coding reports:
1) Add a check-box in the attributes whether one wants these joined with OR or AND. 
2) Allow a selection of cases with attributes. Currently cases get deselected when one opens the attributes dialogue. Conversely, attributes are ignored when one selects cases.

**Comment by ccbogel** [comment]
A bit of an update:
In the 3.2 version there is a radio button choice at the bottom of the screen for combining the attribute selections using Or or And.
I would not be able to enact a combination of Ors and Ands across multiple attributes as this would be too hard to implement, and would require consideration of how to group the combinations together.

**Comment by ccbogel** [comment]
I think fixed now
