### ISSUE TITLE
Improvements to the graph visualization

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#76]
Hello @ccbogel I would like to request a few improvements to the graph visualization.

- On my monitor 15' (16:9), "categories large font" is not very useful as the text remains quite small (basically it is shows how it should be by default as the default is very small). The standard size should be maybe 12/14? I don't know what's the actual size but on my average screen it looks very small.

- Have option to choose size and font of text

- Have option to choose shapes different than rectangles (oval/square/) for categories to highlight what they are (this is particularly necessary if you use black/white options, right now it is impossible to distinguish what's what).

- Have an option to specify the thickness of the lines

- Have option to change the style of lines which connect categories to cases (line, dotted, broken lines), this would give some variety and highlight what's what (libreoffice does it very nicely you can look at it).

- Ability to export the graph (PNG/jpeg) from the graph window, right now I can't find a way to do so, so have to screenshot with a third app.

- ' View Graph' button seems redundant because if i click 'view graph' then I already stated that I want the graph, so the user should view the graph, not a blanket space with such button to be clicked.

- I have not tested the graph view with many codes but I am curious to see how it behaves (whether parts are cut or window is enlargeable), once I have occasion I will let you know :)

- Right now QC connects everything with lines, and I like this approach, however I saw other software use arrows as well, which are quite nice to see and show the direction of relations, I think it would be nice having them as well, as option.

Thanks a lot for the work you put in this useful software, I hope I did not overwhelm you with my feedbacks 👍

**Comment by ccbogel** [comment]
Hi thanks for the advice. I can not do other shapes, but I could implement a bold font for categories perhaps.Other options like font size and line thickness and style - yes I think I can do this.

**Comment by ccbogel** [comment]
I have made it so the view button is not needed. The font size can be changed. Right-clicking on a particular line and you can change the line thickness, style and color - for emphasis.
I am not keen on the arrows idea.
Export as png - I have not looked at yet.

**Comment by WPFilmmaker** [comment]
@ccbogel Thank you!
May I know what does not convince you about arrows? I am a total newbie on data visualizations so I am curious if you have any reasons behind the rejection for arrows.

**Comment by ccbogel** [comment]
I do not see categories and codes as directional. They are simply grouped together

**Comment by ccbogel** [comment]
OK I will close this now, as I have implemented most of what was asked.
