### ISSUE TITLE
Add filters, Cases and Attribute columns in the Coding Windows

### ISSUE THREAD

**Issue by joehays** [ccbogel/QualCoder#767]
When in the Coding Window, I see all my files on the left but it would be very helpful if there was some features to help me find the file that I want to code. Things that would be helpful include:

- your right click and "show like" to filter the list based on the string typed in
- Add Case columns
- Add Attribute columns

Since I'm working with a lot of files... its currently difficult to find files to code. I don't always know the name of the file. Sometimes I'm looking for files to code based off of a Case or an Attribute...

**Comment by ccbogel** [comment]
OK can add more.
There is, underneath the files list, a set of button, one has a tag - this can be used to limit files shown by attributes

**Comment by ccbogel** [comment]
Function: show files like added
