### ISSUE TITLE
No "undo" is available when editing from the Coding Window

### ISSUE THREAD

**Issue by joehays** [ccbogel/QualCoder#768]
Unlike editing a file from the File Manager... no "undo" is available when editing files from the Coding Window.

(Also, Ctrl-E doesn't do anything in the Coding Window. Text indicates that it controls the editing mode in the Coding Window but it doesn't seem to do that.)

**Comment by ccbogel** [comment]
Ctrl E is back now.

**Comment by ccbogel** [comment]
I have thought about this one. It will be too hard for me to implement an undo in this area.

**Comment by ACR268** [comment]
My work-around for this is that I exit the editing window by selecting Coding-code text from the top menu instead of clicking the pencil. That way, my last edits are not saved. The downside is that if you have made several edits, everything is lost, not just the last action.

**Comment by ccbogel** [comment]
OK I will see what  i can do to add to the tooltip not on the pencil - thats a good idea that you have.

**Comment by ccbogel** [comment]
Undo button for last edited text to revert back to previous text.
