### ISSUE TITLE
Different ways to display codes and categories

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#77]
I am attaching here the scheme I am supposed supposed to use: https://i.imgur.com/0cR7crm.png

I couldn't find a way to do so in QC, and was wondering, is this a standard way to present such info or is it just our prof's way they used to teach us?

If it is a standard thing would it be possible/useful implementing it?

Best Regards

**Comment by ccbogel** [comment]
I have the Code frequencies report and I have the Export codebook. Are these similar enough?

**Comment by WPFilmmaker** [comment]
I haven't fully explored QC yet, I let you decide, if you think so, then okay and you can close this ticket. I feel these are small details, which would be helpful, but I don't want to bother you when you probably have other urgent tasks :)

By the way, if i am not too curious, what are your next steps for QC (i would like a new deb file with all the corrections 🥇 )

 :)

**Comment by ccbogel** [comment]
I will try and implement the other changes before  I make another deb file

**Comment by ccbogel** [comment]
I have made a new 1.9 deb file.
