### ISSUE TITLE
“Qualcoder.app” is damanged and can't run on MacOS

### ISSUE THREAD

**Issue by skickar** [ccbogel/QualCoder#771]
After downloading the MacOS release .ZIP file, I extracted the .app file and tried to open it. I got the following error:
“Qualcoder.app” is damaged and can’t be opened. You should move it to the Trash.

Any time I download the app and try to run it, this happened.

**Expected behavior**
The app is expected to open and run

**Screenshots**
![Screenshot 2023-02-08 at 7 46 00 PM](https://user-images.githubusercontent.com/40251293/217704925-065492ff-5834-4e5b-a9fb-caa110301fa0.png)

**Desktop (please complete the following information):**
16-inch, 2019 Macbook Pro, MacOS Venture Version 13.2 (22D49)

**Comment by ccbogel** [comment]
Thanks for the feedback. Ben (github user: kampfg) has made the app using pyinstaller. Previously apps had troubles on ARM macOS'es. Is your an Intel or ARM macOS?

**Comment by ccbogel** [comment]
There has been 150 downloads with only one known error for the app so far. It might be the version of macOS ?

**Comment by zuhairzah** [comment]
I got same error when try installing qualcoder in My Mac. 
My device is Macbook Air M1, Ventura 13.1.

![Screenshot 2023-02-27 at 12 32 55](https://user-images.githubusercontent.com/126471645/221553433-ce07109c-c7b3-4785-8c99-61b953cfff7d.png)

**Comment by skickar** [comment]
I guess make that two.

The computer it's failing on for me is a 2019 Intel Macbook Pro

**Comment by ccbogel** [comment]
OK. I will remove it from the releases page. 
Are you familiar enough with the terminal to install the software using the macOS manual install instructions.

**Comment by zuhairzah** [comment]
I am not familiar with the terminal to install the software. I have tried, but I guess I did something wrong since it does not run on my mac.

**Comment by ccbogel** [comment]
Ok. Maybe a computer macOS expert can help you.
I do not have  mac.  So I cannot guide you.
The install instructions for mac were provided by other users.
