### ISSUE TITLE
Add ability to code directly on PDF documents

### ISSUE THREAD

**Issue by ricardoamaro** [ccbogel/QualCoder#775]
**Is your feature request related to a problem? Please describe.**
Currently, QualCoder imports all PDF into raw text. This has a few drawbacks, like the text being unformatted and losing the context from figures/tables. 
In my mind, this could be improved so that users could have a better coding experience.

**Describe the solution you'd like**
I think we could show PDF documents in place, and use them while coding, highlighting text and selecting images into codes like in this example:
![image](https://user-images.githubusercontent.com/384962/219878448-28b248eb-1223-4969-a90a-c6f10eb672c7.png)

I am not sure if the database structure of qualcoder needs to be refactored, but for sure will help to keep a focused analysis on documents.

**Describe alternatives you've considered**
Another alternative would be to import from an external reference manager like Zotero 6 which can annotate the PDFs 
Or even use the engine https://mozilla.github.io/pdf.js/ while keeping track of the location references.

**Comment by ccbogel** [comment]
this is too hard for me to implement

**Comment by AndrzejWawa** [comment]
There is open source software Quiqqa which allows tagging pdfs: https://github.com/jimmejardine/qiqqa-open-source. Maybe its code or developers could help?

**Comment by AndrzejWawa** [comment]
Hi,

Maybe I have an idea how to be closer to coding on pdfs. In Zotero, thanks to ZotFile exntension you can extract all of the highlights with comments. So, you can determine in comment to what fid and cid specific highlight belong, as well as write a coding memo.

**But the crucial thing is:** are you able to add experimental special function to upload codings to QC SQL table "code_text" e.g. on this format:

“ent advancement of the developmental rule of law have involved the ‘freeing’ of the former colonies—from now on, ‘developing states’—with the consequences comparable to those, with which peasants were freed during Hobbes’ times [5] (p. 38). Today, the global developm” (Aseeva, 2018, p. 1) **2, 3, 1 ((this is another memo to codings))**

So:
1) the text in single quatation marks should be imported to the "seltext" column,
2) the first number will be imported as fid,
3) the next numbers as cids,
4) the text in double parentheses as memo.

Note: the text in bold is the text from comment, so, we can determine any format which will be convenient for Qualcoder importation.

I am attaching exemplary extracted Zotero file.

[Annotations to QC 2.md](https://github.com/ccbogel/QualCoder/files/10948761/Annotations.to.QC.2.md)

**Comment by ccbogel** [comment]
I will look at this again, when i have time.
I have found a python program called pdf-annotate on github. I might be able to use that.

**Comment by AndrzejWawa** [comment]
Maybe you can ask Chat GPT about this?

**Comment by ricardoamaro** [comment]
👍 Amazing work! 🎉
