### ISSUE TITLE
Coding tree unfolds all codes when a new code is created

### ISSUE THREAD

**Issue by ricardoamaro** [ccbogel/QualCoder#776]
**Describe the bug**
When the user has folded (closed) all or some categories in the coding structure, if a new code is created QualCoder unfolds all codes and categories. If there are many codes this impacts the work of the user since it is hard to keep folding everything.

**To Reproduce**
Fold some categories and create a new code or delete an existing one.

**Expected behavior**
Folded categories and codes should remain folded and should not be affected by unrelated user actions.

**Screenshots**
![image](https://user-images.githubusercontent.com/384962/219976282-e388a68e-ab54-44f2-bfeb-9e2a09a1ccee.png)

![image](https://user-images.githubusercontent.com/384962/219976300-74485473-a5f4-4b7c-bd86-3d98a500063c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by ccbogel** [comment]
Thanks. In progress -have done this for text coding so far

**Comment by ccbogel** [comment]
updated
