### ISSUE TITLE
Connecting categories in the graph

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#78]
For a task I am doing I need to visualize categories and their codes.

I am using QC and I had no issues so far (apart the initial struggle to understand how to add codes to categories, maybe it is useful to add in the manual that they can be drag-n-dropped?), however I noticed that the graph I am supposed to make has all categories connected, whereas QC keeps them separated.

Is there a way to do that? I couldn't find how. If it is not present, would it be possible implementing it?

**Comment by ccbogel** [comment]
HI, you can drag and drop a category onto another category. So you can have a tree with a main category and sub-categories under it. But you cannot cross-link categories, its not designed in that way.

**Comment by WPFilmmaker** [comment]
Thanks for the answer @ccbogel I tired that approach but hope someday someone will implement the cross link^^

**Comment by ccbogel** [comment]
ok :)
