### ISSUE TITLE
Export Video Segments as individual files

### ISSUE THREAD

**Issue by andybyte** [ccbogel/QualCoder#780]
**Is your feature request related to a problem? Please describe.**
I don't think so.

**Describe the solution you'd like**
I'm about to try out the software, but in going over the instructions I did not see this option and thought it would be helpful (and perhaps it already exists). In coding up video, I see that it creates video segments. It would be useful to click a button to export segments as their own video files to use in say a report or presentation. 

**Describe alternatives you've considered**
Using other video editing software to create such snippets manually.

**Additional context**

**Comment by ccbogel** [comment]
In Coding reports. You can export an html file which has a separate folder containing the original video.
The html display shows the segment section.
I think editing and exporting as separate files is possible, it you have ffmpeg - will see if I can do this.

![Screenshot from 2023-03-07 07-39-28](https://user-images.githubusercontent.com/5834638/223225512-3ae2f851-6209-401d-95ef-5c8cd3da45df.png)

**Comment by andybyte** [comment]
I see. That's still handy, especially for sharing with collaborators. 

The idea mainly came to me as I'm expecting to take clips from the analysis to include in a presentation. So it seemed like all the data is there to make the clips and would save time on the post-analysis side.

**Comment by ccbogel** [comment]
@andybyte OK a further update. If you have ffmpeg installed, then you can right click on the segment in Code A/V and export to file. Appears to work OK for me in Ubuntu and Windows.
