### ISSUE TITLE
Alternative pdf converter and exporting bug

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#783]
I noted that automatic pdf converting in QC usually does not work properly with pdfs of journal articles. E.g.:

Automatic convertion by QC:

![obraz](https://user-images.githubusercontent.com/77200214/224513603-6b4f3c66-f9fb-49a4-b283-cd3238b954ee.png)

Convertion by Zotero converter:

![obraz](https://user-images.githubusercontent.com/77200214/224514318-d6976e9f-f352-40fb-901d-7783b6fa5d53.png)

This is not crucial problem as it is possible to use external converters. However, maybe QC can use the same converter as Zotero?

The second issue is that exporting plain taxt automatically created by QC from pdf seems to not work. Same in the case of odt.

**Comment by ccbogel** [comment]
ok, i think i have fixed the exporting bug
