### ISSUE TITLE
Are Transkription Pedal Supported?

### ISSUE THREAD

**Issue by Lord-Leonard** [ccbogel/QualCoder#784]
Is it possible to hook up a Transkription pedal?

I want to Kontroll the playback speed of an Audio file with an transkription pedal. 

I tried to use the hotkeys, but its a mess...

**Comment by ccbogel** [comment]
Not possible at the moment.
I do not have a Transkription pedal to test.
I have no experience with implementing this, or how to get python to detect foot pedal signals.

**Comment by Lord-Leonard** [comment]
thank you very much.
