### ISSUE TITLE
Advanced search segments report

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#786]
Hi,

I have an idea. Can you, in free time, create a new report "Advanced search segments" which, after clicling, opens dialog window similar to this after clicking "Charts" and containing:

![obraz](https://user-images.githubusercontent.com/77200214/228665437-88ad0cd2-1811-4bb7-9d3d-86d4a726bf88.png)

After selecting file and code(s) in at least one of the other boxes it will display **exactly the same** table as the newest default query. But this drop-down lists are more convenient.

There will be options related to displayed table:
- export table in CSV,
- word search box,
- sorting table,
- filtering table by one of the value.

This kind of search is very helpful and rather available in all of the main CAQDAS:
https://www.maxqda.com/help-mx20/visual-tools/code-relations-browser-visualizing-overlapping-codes
https://atlasti.com/research-hub/co-occurrence-analysis-with-atlas-ti
https://study.sagepub.com/using-software-in-qualitative-research/chapter-13-%E2%80%93-interrogating-data-nvivo

**This is the same logic as in the Google Scholar:**

![obraz](https://user-images.githubusercontent.com/77200214/228669468-0f9dbb02-aef5-4c8e-b55b-95923c7e126b.png)

**Comment by AndrzejWawa** [comment]
Here you have this proposed report with corresponding SQL statement fragments from defult query "-- THREE OR MORE EXACTLY OVERLAPPING CODINGS IN A SELECTED FILE"

So, the issue is to create report based on them as on the image.

![Advanced search](https://github.com/ccbogel/QualCoder/assets/77200214/146d0a86-253e-48f6-96ac-e0dd4d1ae5da)

**Comment by ccbogel** [comment]
OK, I will look in to it.

**Comment by ccbogel** [comment]
I think now this does a lot of what you want. Under Reports > Code text exact matches.
Still need to add table functions such as sorting, etc

**Comment by AndrzejWawa** [comment]
Hi,

1. I checked and it does not work as SQL. For example, I created test project. The file (attached) includes a couple of countries and codes correspond to values of categories (language, size, continent). When selected codes: "Big", "English", "Independent" I received such a result:

![obraz](https://github.com/ccbogel/QualCoder/assets/77200214/b98e3b2c-95b9-4482-91c1-bdd43735b089)

But it should show only "Australia", as SQL does:

![obraz](https://github.com/ccbogel/QualCoder/assets/77200214/2f1b9ab5-3ed8-4d69-9f90-838d9b01a080)

2. Only part of coded text is diplayed, e.g. "Australi" without a, UK without k, etc.

**Comment by ccbogel** [comment]
Sure OK. The result of only Australia - yes  I can fix that fairly easily. 
Can you send me a zipped file of the qda project you used. It will help me

**Comment by ccbogel** [comment]
Fixed those issues. 
I might add a checkbox for ALL exact matching codes or ANY exact matching codes.

**Comment by AndrzejWawa** [comment]
Thanks, it works wonderfully! 

1. Ok, good idea with the checkbox.

Can you also:

2. Add coding memo as in the SQL?

3. Add checkbox to GROUP BY pos.1? - to optionally remove coding duplicates

4. Remove the gaps between results

5. See coding in context.

**Comment by ccbogel** [comment]
I think point 3 is already done ?

**Comment by AndrzejWawa** [comment]
> I think point 3 is already done ?

Aaaa, by "GROUP BY" I mean name of SQL function. I works in this way, that when you have 3 times "Australia", you will obtain only 1. But this should be optionally.

**Comment by ccbogel** [comment]
Ah. No, I don't like that idea. It i better to show all the codes for that coded location. It will confuse people, overwise.

**Comment by AndrzejWawa** [comment]
You might provide this only as righ-click option which will be cleared after clicking "clear filter". If not, ok. The report is excellent for me, very helpful!

**Comment by AndrzejWawa** [comment]
I thought about this and I think that you could add right-click option "Show only one coding for the same text positions" (it will show only one row for the same pos0 and pos1. It can facilitate work because, assuming that you have 4 codes attached to the same positions, when searching for 8 segments, you will obtain 32 rows, but for analysis text segments, you only need 8 rows.

Of course, many people could work in other way, so they simply will not use this functionality (by default, all rows are showed). But for me it will be helpful to have this right-click option, because I use codes more as a variables for segments - I plan to start this analysis soon. I can do this also in SQL or Calc, but right-click option would be time-consuming, as I will try to often control and compare different subgroups of segments.

**Comment by ccbogel** [comment]
OK. There is another CheckBox to show results of multiple codes for the same locations - as one row of results.

**Comment by AndrzejWawa** [comment]
Wow, great idea! Thank you!

1. Can you only also place coding memos in this one row? E.g. Code X: Memo X. Code Y: Memo Y, etc.?

2. And last thing: are able to allow searching many file at once? 

Thank you again, very helpfull functionality for me, and probably many other users!

**Comment by ccbogel** [comment]
All done.

**Comment by AndrzejWawa** [comment]
Can you only delete this "||" when there is no memos? I mean, when there are memos, they are separated by "I", and it is ok. However, when there are no any memos, there are still two lines "||", alone.

**Comment by AndrzejWawa** [comment]
Excellent! Thank you!
