### ISSUE TITLE
Code frequencies throws 'uncaught exception'

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#79]
I clicked on code frequencies to see what would happen and I got this:

Traceback (most recent call last):
  File "/usr/share/qualcoder/qualcoder.py", line 517, in report_code_frequencies
    ui = DialogReportCodeFrequencies(self.app, self.ui.textEdit)

TypeError: __init__() missing 1 required positional argument: 'dialog_list'

I don't know whether it is an issue on my side or a bug but decided to report it.

**Comment by ccbogel** [comment]
Thanks - yes an error. I have uploaded newer code to fix.
