### ISSUE TITLE
Python error when selecting attribute parameters

### ISSUE THREAD

**Issue by jbkieffer** [ccbogel/QualCoder#790]
**Describe the bug**
In Reports > Charts, when I attempt to select parameters to filter by attribute, I always receive an Uncaught Exception Python error:

```
Traceback (most recent call last):
  File "C:\mypath\qualcoder\view_charts.py", line 214, in
  select_attributes
    if a[1] == 'file':
IndexError: list index out of range
```

This error occurs whether I select a case attribute, a file attribute, or both, and whether I use AND or OR when selecting multiple attributes.

**To Reproduce**
- QualCoder 3.1
- Windows 10 Enterprise
- Dedicated conda environment
- Create a coding chart that includes filters by attribute

**Expected behavior**
I'm not sure what I expect to happen. Now that I have coded data, I'm playing with the reporting features to understand what QC's various reports will/not do. What I *think* is supposed to happen is that the software will chart the requested code category for the attribute(s) selected. This seems to be what happens if I filter by a specific file or case, with the exception of the Heatmap chart, which only seems to respond to the code category filter.

**Screenshots**
![QCAttributeFilters](https://user-images.githubusercontent.com/23423968/232894286-ef4e059a-5405-4668-8495-8befa0dbd9fa.png)
![QCPythonError](https://user-images.githubusercontent.com/23423968/232894356-acbe842f-2ce3-4b0d-b47d-58c773f45992.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version: 21H2
- OS build: 19044.2846

**Additional context**
Thanks so much for looking at this!

**Comment by ccbogel** [comment]
Hi thanks for testing QC out,
These charts are either bar charts (for character variables) or histograms.

I tested in the 3.3 in production code and it works ok with my test project.
First suggestion is to use the newer 3.2 release, it might have been a bug that I fixed:
https://github.com/ccbogel/QualCoder/releases/tag/3.2
Let me know if that was enough to correct the error

**Comment by ccbogel** [comment]
Thanks for identifying that bug. I will look into it.

**Comment by ccbogel** [comment]
No errors in the latest code (v3.3) now. 
I have made improvements for file selection.
I am still to test case selection.

**Comment by jbkieffer** [comment]
I pulled the most recent code and reinstalled. I'm not seeing the Python error anymore when filtering by attribute - hooray! Filtering by file attributes seems to be working better now, even for the Heatmap chart. 
Thanks so much for the quick response!

**Comment by ccbogel** [comment]
Good. Jus a bit more testing still to do from my end. I hope you ae finding QualCoder useful.

**Comment by ccbogel** [comment]
Now tested further and fixed another error with this. Should now be fine!
