### ISSUE TITLE
Add free, local, python based AI transcription of audio in many languages

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#797]
**Is your feature request related to a problem? Please describe.**
This would greatly enhance the utility of QualCoder since a lot of use cases involve audio recordings of interviews or focus groups. The transcription services with which QualCoder can interface currently are all external and on teh web, raising privacy and confidentiality concern especially, but not only fro sensitive interview data. 

**Describe the solution you'd like**
integrate existing open source implementations of OpenAIs open source Whisper model: https://github.com/hayabhay/whisper-ui or https://github.com/jojojaeger/whisper-streamlit or as an opn source desktop app: https://github.com/chidiwilliams/buzz

**Additional context**
This helps solve key privacy issues associated with the transcription of interviews by service agencies or AI services. QualCoder would greatly improve the ease of handling and analyzing confidential and sensitive material., as transcription happens fully local and does not require an internet connection. 

Additional benefits of existing implementations include: identify multiple speakers and color text of transcription according to the models word-level transcription confidence - this is helpful to be able to correct the transcript faster. (both features: https://github.com/jojojaeger/whisper-streamlit

There are various implementations that improve teh efficiency of Whisper, making it run significantly faster and this better on older hardware: https://github.com/Topping1/whispercppGUI

**Comment by kaixxx** [comment]
Take a look at noScribe: https://github.com/kaixxx/noScribe
(Disclosure: I'm the author)

**Comment by ccbogel** [comment]
Thank you. I will add this to the documentation - so that others can consider installing noScribe and using it for their transcriptions.

**Comment by kaixxx** [comment]
Nice, thank you. I have added a link to QualCoder too. We few open source QDA developers must stick together ;)
