### ISSUE TITLE
When adding a new code automatically add a new color?

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#8]
Noob question: does not make more sense to automatically assign a new color to each new code you add?

Right now when adding a new code you get the same color and need to manually change it.

If there is a good reason behind this choice you can ignore this ticket, otherwise I think it makes more sense to pick a random new color automatically.

**Comment by ccbogel** [comment]
Its a good point, there is no good reason, it is easier to implement as is. I can make it so that colours are randomly selected. I know that when I do code text, and add new codes, I tend to choose similar colours for codes that are aligned under the same category.

**Comment by ccbogel** [comment]
OK, I have made it so that colors are randomly created for each new code.
