### ISSUE TITLE
Menus opening on the wrong screen

### ISSUE THREAD

**Issue by sam-crawley** [ccbogel/QualCoder#801]
**Describe the bug**
When running QualCoder on my left hand screen, the menu opens on the right hand screen (see screenshot). Doesn't seem to matter if the window is maximized or not. The menus all open on the far left of the right hand screen.

Moving QualCoder to the right hand screen, the menus open in the correct position.

**To Reproduce**
1. Open QualCoder on left hand screen
2. Click on any of the menus
3. Menu opens on the wrong screen.

**Expected behavior**

**Screenshots**

![Menu problem](https://github.com/ccbogel/QualCoder/assets/42904636/4b16975b-494c-4791-b604-72d22f1a4fd1)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.19044

**Additional context**
I haven't noticed this issue when running on Linux.

I think I may have opened QualCoder on the right hand screen the first time I opened it on this machine. So is it possible it saved the wrong screen position settings somewhere?

**Comment by ccbogel** [comment]
I can't fix this issue. Apparently, this is a bug with Qt6.2.4 
https://forum.qt.io/topic/145075/qmenu-on-dual-screen-pc-with-qt6/2
An upgrade to a newer Qt6 version e.g. qt6.5 would fix it apparently.

If you are doing a command line install, then these comands from the main page should install the more current qt:
py -m pip install --upgrade pip

py -m pip install wheel pyqt6 chardet ebooklib openpyxl Pillow ply pdfminer.six pandas plotly pydub python-vlc rispy SpeechRecognition xmlschema


If this is occurring using the exe, then I cannot change the exe and you will have to use the other screen or make Windows use dual mirrored screens in Windows Settings.

**Comment by sam-crawley** [comment]
Thanks, I've worked around it for now by changing which is the primary display in Windows.

**Comment by ccbogel** [comment]
@sam-crawley p.s. I hope you are finding QualCoder useful.
