### ISSUE TITLE
REFI-QDA import error: not importing documents

### ISSUE THREAD

**Issue by melegati** [ccbogel/QualCoder#803]
**Describe the bug**

The import of a REFI-QDA project fails to include the documents.

**To Reproduce**

- Select a .qdpx project file with documents 
- Once the import finishes, go to manage documents. Nothing will be there.

**Expected behavior**

The documents included in the project should be there.

**Screenshots**

The console output is:

  File "/Users/user/Projects/QualCoder/qualcoder/refi.py", line 1319, in load_pdf_source
    destination = os.path.join(self.app.project_path, +"documents", name)
                                                      ^^^^^^^^^^^^

**Desktop (please complete the following information):**
 - OS: macOS 12.6.7
 - Python 3.11

**Comment by enricllagostera** [comment]
Hello! Would it be possible to release a new build with this bugfix on it? Unfortunately, this bug is breaking my project, and since a fix has already been made, it would be a matter of making a new release.

**Comment by ccbogel** [comment]
Hi, I see you are using macOS which means you would be OK installing QC using the terminal.
Can you go here: https://github.com/ccbogel/QualCoder and download the latest code as a zip from the Green Code button (at the top right of the page). Unzip the folder and install from using the extracted QualCoder-master folder.
This has the fix in it.
I am not quite ready yet to do another release just yet as there is another thing I am slowly working on with the journals.
Please let me know how you go with that.

**Comment by enricllagostera** [comment]
Hi! Thanks for the quick answer. I'm actually on a Windows 11 machine. Would the process for installing from master be the same?

**Comment by ccbogel** [comment]
@enricllagostera  
Yes pretty much, look further down on the page - under Windows. Do use a virtual environment as it says (otherwise any other python dependent programs could have conflicting python module issues and fail to work).

**Alternatively, and maybe better for you, create your own executable for Windows:**

Download again now - as I had to make a minor change to the refi module for the xml schema module that does not play well with pyinstaller.

Then, From the Command line:

install pyinstaller:

pip install pyinstaller

Then cd to the QualCoder-master folder and run the following:

pyinstaller -w -n "QualCoder-3.4alpha" --icon=QC_Logo.ico --onefile qualcoder/__main__.py

Wait a few minutes, then once it has completed you will find the exe file in a new subfolder called dist

Creating  the exe: At the moment I am getting an error relating to the numpy module. Using python3.11 on my home Windows. It might be different on my work computer under 3.10. will try later.

**Comment by ccbogel** [comment]
sorry the main.py it must be \_\_main\_\_.py

writing here turns the underscores into bold

**Comment by enricllagostera** [comment]
Hi! I had the same issue with the `pyinstaller` way. I also tried the README instructions and the EXE worked. I still could not complete the import.

This is the traceback:

```
Traceback (most recent call last):
  File "C:\tools\QualCoder-master\qualcoder\__main__.py", line 1474, in refi_project_import
    RefiImport(self.app, self.ui.textEdit, "qdpx")

  File "C:\tools\QualCoder-master\qualcoder\refi.py", line 163, in __init__
    self.import_project()

  File "C:\tools\QualCoder-master\qualcoder\refi.py", line 461, in import_project
    count = self.parse_sources(c)
            ^^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\QualCoder-master\qualcoder\refi.py", line 922, in parse_sources
    self.load_text_source(el)

  File "C:\tools\QualCoder-master\qualcoder\refi.py", line 1673, in load_text_source
    ) = self.name_creating_user_create_date_source_path_helper(element)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\QualCoder-master\qualcoder\refi.py", line 985, in name_creating_user_create_date_source_path_helper
    + element.get("plainTextPath").split("internal:/")[1]
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^

IndexError: list index out of range
```

And this is what the `Sources` section of my `project.qde` looks like:

```
  <Sources>
    <TextSource guid="437477f4-4326-4d8a-94fa-ee579e96ba72" name="commit_data_19e4dce" plainTextPath="internal://437477f4-4326-4d8a-94fa-ee579e96ba72.txt" richTextPath="internal://437477f4-4326-4d8a-94fa-ee579e96ba72.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.001-04:00"/>
    <TextSource guid="6bc37b27-cf41-4c08-be9b-20436fa7f563" name="commit_data_cdbfd92" plainTextPath="internal://6bc37b27-cf41-4c08-be9b-20436fa7f563.txt" richTextPath="internal://6bc37b27-cf41-4c08-be9b-20436fa7f563.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.004-04:00"/>
    <TextSource guid="06a0d9fa-aa8a-4137-a93a-ae3b30d806c8" name="commit_data_8fd947e" plainTextPath="internal://06a0d9fa-aa8a-4137-a93a-ae3b30d806c8.txt" richTextPath="internal://06a0d9fa-aa8a-4137-a93a-ae3b30d806c8.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.005-04:00"/>
    <TextSource guid="108586d9-32d0-4738-ab6e-a91baa19bdbc" name="commit_data_4170a1a" plainTextPath="internal://108586d9-32d0-4738-ab6e-a91baa19bdbc.txt" richTextPath="internal://108586d9-32d0-4738-ab6e-a91baa19bdbc.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.007-04:00"/>
    <TextSource guid="7f0df61e-cc5b-40a4-a6c7-f2b05f60590a" name="commit_data_1e350e7" plainTextPath="internal://7f0df61e-cc5b-40a4-a6c7-f2b05f60590a.txt" richTextPath="internal://7f0df61e-cc5b-40a4-a6c7-f2b05f60590a.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.008-04:00"/>
    <TextSource guid="59a9c718-6aab-405e-b00b-d7d9b1971ea4" name="commit_data_b924604" plainTextPath="internal://59a9c718-6aab-405e-b00b-d7d9b1971ea4.txt" richTextPath="internal://59a9c718-6aab-405e-b00b-d7d9b1971ea4.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.009-04:00"/>
    <TextSource guid="ad6bb85b-0213-4aef-9505-3d209c1912ff" name="commit_data_4a55963" plainTextPath="internal://ad6bb85b-0213-4aef-9505-3d209c1912ff.txt" richTextPath="internal://ad6bb85b-0213-4aef-9505-3d209c1912ff.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.010-04:00"/>
    <TextSource guid="e7e3fbe5-da6b-4f0a-b73f-3851d94da655" name="commit_data_6a14674" plainTextPath="internal://e7e3fbe5-da6b-4f0a-b73f-3851d94da655.txt" richTextPath="internal://e7e3fbe5-da6b-4f0a-b73f-3851d94da655.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.011-04:00"/>
    <TextSource guid="9c91c4dc-91d4-457e-9e7b-ef4d3135c35b" name="commit_data_19eb882" plainTextPath="internal://9c91c4dc-91d4-457e-9e7b-ef4d3135c35b.txt" richTextPath="internal://9c91c4dc-91d4-457e-9e7b-ef4d3135c35b.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.012-04:00"/>
    <TextSource guid="5a9f7b3c-746a-44a6-8031-be2bb957a099" name="commit_data_ac8098e" plainTextPath="internal://5a9f7b3c-746a-44a6-8031-be2bb957a099.txt" richTextPath="internal://5a9f7b3c-746a-44a6-8031-be2bb957a099.txt" creatingUser="0360cc18-7b95-4cb1-8db6-a2bc20798adc" creationDateTime="2023-08-15T13:57:43.012-04:00"/>
  </Sources>
```

**Comment by ccbogel** [comment]
To clarify - you created an exe and it worked. Thats good.
OK I have a test Nvivo qdpx project- that imported successfully for me. So there must be something a little different in your project. Are you able to email me your qdpx project so that I can see where the issue is. 
ccbogel@hotmail.com

You say you are generating the qdpx file yourself ? im not sure what you mean there - is it an export from nvivo or similar software?

The problem I suspect begins here:
File "C:\tools\QualCoder-master\qualcoder\refi.py", line 1673, in load_text_source
    ) = self.name_creating_user_create_date_source_path_helper(element)

One of the elements might not be a TextSource element
