### ISSUE TITLE
Code tooltips do not appear after selecting then deselecting a specific code

### ISSUE THREAD

**Issue by sam-crawley** [ccbogel/QualCoder#806]
**Describe the bug**
The tooltips displayed when mousing over a code in the coding window do not appear after selecting then deselecting a particular code.

**To Reproduce**
1. Code some text with at least two different codes
2. Select one of the codes and click one of the "Show next/previous coding of selected code" arrow buttons so that only that specific code is shown
3. Deselect the code (e.g. by clicking on the name of the code) so that all codes now reappear
4. Mouse over one of the codes that *wasn't* visible in step 2. The tooltip will not appear (but it will appear on the code that was selected in step 2).
5. Refreshing the text window (e.g. selecting another file and then reselecting the original) allows the tooltips to reappear.

**Expected behavior**
The tooltips should reappear immediately after the selected code is deselected.

**Desktop (please complete the following information):**
 - OS: Linux/Windows
 - Version: 3.3

**Comment by ccbogel** [comment]
fixed now
