### ISSUE TITLE
Tooltips for annotations appear in the wrong files

### ISSUE THREAD

**Issue by sam-crawley** [ccbogel/QualCoder#807]
**Describe the bug**
The tooltip that appears when mousing over an annotation will appear in *all* text files in a project.

**To Reproduce**
1. Have a project with at least 2 text files
2. Create an annotation in the first file
3. Go to a different file. When placing the mouse pointer at the same position as the annotation in the original file, the tooltip for the annotation is displayed.

**Expected behavior**
The annotation tooltip should only appear in the file that was annotated.

**Desktop (please complete the following information):**
 - OS: Linux/Windows
 - Version: 3.3

**Comment by ccbogel** [comment]
Thaks for picking that up.  I have uploaded a fix in the 3.4 pre-release version.
