### ISSUE TITLE
Position in text file resets after viewing "Show coded files" window

### ISSUE THREAD

**Issue by sam-crawley** [ccbogel/QualCoder#808]
**Describe the bug**
After closing the "Show Coded Files" window for a particular code, the position in the text file resets to the beginning.

**To Reproduce**
1. Have a project with a text file of a few hundred lines at least, and at least 1 code
2. Open a text file and scroll down
3. Right click on a code, and select "Show coded files"
4. Close the window that pops up
5. The position of the text file will be reset to the beginning of the file

**Expected behavior**
The position of the text file should not be affected by viewing/closing the "Show coded files" window

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Version: 3.3

**Comment by ccbogel** [comment]
Yes I did that deliberately, reload/display the text file. This was an easy way to deal with any coding changes that were made when codes were edited in 'show coded files'.
I will look at another way to do this.

**Comment by sam-crawley** [comment]
Thanks, fair enough. I've been using this as a quick way to check what else has been marked against this code, but it does disrupt the flow when the position resets.

**Comment by ccbogel** [comment]
Fixed now. So for all fixes, you will need to download the latest code (green code button). and install via install instructions, to run via command line/terminal.
