### ISSUE TITLE
Run on MacOS 10.15.7 ? 

### ISSUE THREAD

**Issue by cringefauna** [ccbogel/QualCoder#809]
though having Python 3 installed on my computer i get the prompt 
"Sorry, "python3" cannot be run on this version of macOS. Qt requires macOS 11.0.0 or later, you have macOS 10.15.7." when trying to install Qualcoder - is this by default and something to do with Qualcoder or is it my Python that doesnt run properly?

**Comment by ccbogel** [comment]
I don't know how to fix this issue.
I think it is to do with the python Qt modules.
I presume you are running a fairly new python e.g. 3.10 or 3.11 ?

**Comment by cringefauna** [comment]
i have been running both old and new python releases, i think it must have to do with the operating system on my mac, as it says, which is also weird, since you would think that it could boot  if python 3.xx can boot no? (im not a developer)
Anyway its a bit of a shame, it had looked forward to using your app, it seems absolutely excellent! unfortunate, that it macs keep going obsolete :/ thank you v much for you reply tho! lmk if i can do more to helt fix the problem. would be amazing to use Qualcoder in the future! xoxo
