### ISSUE TITLE
Unable to interact with Text coding while exploring a codes's "coded files" dialogue

### ISSUE THREAD

**Issue by diegopaucarv** [ccbogel/QualCoder#810]
**Is your feature request related to a problem? Please describe.**
I can't interact with the original documents while I open the coded text passages by clicking on one code. And this is very annoying. In the windows that opens I can't add memos, or new codes, or to expand the code. This is very frustrating and it limits my work.

**Describe the solution you'd like**
When I use the "coded passages" Window in MAXQDA, I'm able to interact with my original data after I click at each coded passage.  No new windows are needed. The main text coding window is still active. I've noticed, though, that MaxQDA takes a while to change between transcripts because it performs a whole dataset text search every time you click a coded file passage, and highlights the looked upon text. We don't really need that, since the only thing we need is to swap between transcripts each time we click on them. Or that's what I think. Wecould also perform a localized search within a same document,

I think that the problem might be due to the coded passages window being a dialogue. Maybe if it was another different frame or window, that could ease the interactions to the text coding main window. I know this comes due to the structure of the code and can seem a little hard to change, but structural changes in coding are the fastest, in my experience.

**Comment by ccbogel** [comment]
"I can't interact with the original documents while I open the coded text passages by clicking on one code"
Do you mean when you right click on a code and "Show coded files" ?

You can right click on a file and "View original text file"

But you cannot code on the original text file, only on the text extract stored in the QC sqlite database.

**Comment by diegopaucarv** [comment]
> "I can't interact with the original documents while I open the coded text passages by clicking on one code" Do you mean when you right click on a code and "Show coded files" ?
> 
> You can right click on a file and "View original text file" But you cannot code on the original text file, only on the text extract stored in the QC sqlite database.
> 
> When you right click on a code and select "Show coded files": You can then click on the coloured code (the Pink in the image) and open a little window for that code in context of the original file. In the original file you can then change the code positioning.
> 
> You can right-click on the coloured code _File: brighton storm_ and have options to: remove the code, or to apply other codes to the same segment.
> 
> ![Screenshot 2023-08-08 121851](https://user-images.githubusercontent.com/5834638/258966101-a3753087-6303-4fa5-82cd-204d0123282b.png)

Hi. Thank you for the fast response. But... yeah... so, this is still very annoying. Are you sure about keeping this feature in the software? Can I help to work on an alternative?

**Comment by ccbogel** [comment]
I need a really good understanding of what you want to do. the work flow etc

**Comment by ccbogel** [comment]
OK closing issue.
