### ISSUE TITLE
Manage Journals like files (add attributes, etc)

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#812]
**Is your feature request related to a problem? Please describe.**
I am now manually sorting journal-like notes into QualCoder's Journal Management. I am happy I can edit & revise names. I am frustrated that I cannot change the Date.

**Describe the solution you'd like**
Ideally the Date would be editable.

**Describe alternatives you've considered**
Rename "Date" to "last modified"

**Comment by ccbogel** [comment]
OK I have a couple of questions. 
Yes the Date displays the last modified date. I can change the Header to Modified.
Making the date editable - when the journal was edited, the date would change again ?
Would it be better or useful to have journal attributes (such as is used in files and cases) ?

**Comment by ccbogel** [comment]
I have made the journal table more modifiable. order by name or Modified asc or descending. 
Show only rows by a specific coder.
Show only journal names that contain a text match.

**Comment by ccbogel** [comment]
Further updated to fix some errors that popped up.

**Comment by ilippert** [comment]
Sorry, took me a while to get back. Thank you so much for immediately reacting.

Just pulled the newest version and reinstalled.

I find the date field changed to `Modified`. Great!

I like the idea of the consistency of managing journals like files. However, I cannot yet find a trace of this. For instance, no blue `+` button to add attributes.

**Comment by ccbogel** [comment]
Yes I will add that in. Currently you can add attributes using the Manage attributes menu.

**Comment by ilippert** [comment]
Thank you so much. Found it. That works well. I opened https://github.com/ccbogel/QualCoder/issues/814 for a follow up on the attributes per se.

**Comment by ccbogel** [comment]
updated with add attribute button in manage journals
