### ISSUE TITLE
Adding attributes of date/time type

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#814]
**appreciation**
I enjoy the possibility to generate new attributes with the `Manage attributes menu`.

**suggested feature**
I would love to be able to add an attribute that represents a data `DD/MM/YYYY`  and another of date/time `DD/MM/YYYY hh:mm` range. Ideally I would be able to enter data for this content manually or with a data/time picker.

**Comment by ccbogel** [comment]
OK. Add attribute button added to Manage Journals.
I have added the option to enter a calendar date - in the format yyyy-mm-dd _only_. As this format is easier to manage for sorting. 
The dates are stored as characters - so you must have a character attribute. I have restricted this further - so your attribute must contain the word 'date'  in the attribute name and it must be a character attribute.

Once the attribute is present - right click on the cell to then select 'Enter date' and then a calendar will appear.
I will not add date and time - there are many time format options with hours or hours +mins or hours+mins+secs, and it also requires a separate widget to appear apart from a date picker. So I feel it is too much complexity.

FYI: The sqlite database does not have a specific date or time field (unlike MySQL), it stores the information as character text or as a number. I choose character text as it is easy to interpret.

**Comment by ilippert** [comment]
Thanks, I just pulled the code and reinstalled QualCoder. I am now at git commit e44fc0e735034b3c2c8203a9edf6e6b0c17f5fbb.

I was not immediately able to reproduce the solution; sorry, did not follow your description precisely enough. Will try again with `date` rather than `DATE` as the attribute name, once [the other bug](https://github.com/ccbogel/QualCoder/issues/815) is out of the way.

**Comment by ilippert** [comment]
Ok, perfectly works, thanks a lot!

**Comment by ccbogel** [comment]
I am going to do one more update in a minute. A minor fix to ordering journals by attributes. A numeric attribute is ordered as a text string, not as a number.
So: 1 10 2 22  instead of 1 2 10 22
