### ISSUE TITLE
Merging a code onto itself and then choosing "no" at the confirm prompt causes a crash

### ISSUE THREAD

**Issue by RobHayden** [ccbogel/QualCoder#817]
**Describe the bug**
IN the code list, when you try to merge a code onto itself (for lack of a better place to drop it after dragging it by mistake) you still get prompted if you really want to merge "code title A" with "code title A", If you hit No, the application crashes.

**To Reproduce**
As above

**Expected behavior**
Do not prompt for a confirm if the code is dropped back onto itself

**Desktop (please complete the following information):**
Ubuntu 
 - Version 22.04.3

**Additional context**
Running under Hyper-V on windows 10

**Comment by ccbogel** [comment]
I cannot recreate this issue with 3.3 or 3.4 version on Windows 11.

**Comment by RobHayden** [comment]
I am using the 3.3 release executable. Just tested it again and selected Yes this time and that also causes the application to exit. Is there anything I can add to debug/log to get more detail for you?

**Comment by ccbogel** [comment]
Is there anything I can add to debug/log to get more detail for you?
There is a log file under .qualcoder in your home directory - this might shed some light on it. Delete the log file first to empty it. Secondly, a short video might help - in case something is happening that i am not aware of in how you are doing this.

**Comment by RobHayden** [comment]
Nothing in the log file, completely empty.
video attached

https://github.com/ccbogel/QualCoder/assets/16787240/cf486cd6-194d-4e59-bb35-fa460be14aa6

**Comment by ccbogel** [comment]
OK, that's interesting. 
I don't have Ubuntu at the moment to test. It does not happen on Windows. I have added code to the dev branch that will catch this before an error occurs.

**Comment by ccbogel** [comment]
fairly sure I have fixed this
