### ISSUE TITLE
Doesn't integrate with OneDrive on windows.

### ISSUE THREAD

**Issue by rcdemuth** [ccbogel/QualCoder#818]
**Describe the bug**
I had some oral histories stored in a one drive folder, I tried to navigate to the folder in QualCoder and opening up the main onedrive folder instigated a complete download of my OneDrive folder.  I suspect that it would behave similarly with any cloud-first storage solution (such as box or Google Drive).

**To Reproduce**
Try to add/import a file, and open the Onedrive folder on your pc/desktop.

**Expected behavior**
It would just load the one drive file tree without downloading all of the files I have stored there.

**Screenshots**
Can provide later if you would like?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22h2
 
**Additional context**
Is this related at all to the fact that QualCoder uses its own file browser instead of calling the system one?

**Comment by ccbogel** [comment]
Hi. I tested this out on a Windows 10 computer using OneDrive. 
This issue of loading everything in the OneDrive tree did not occur. 
I could navigate and select individual files for importation into QualCoder.

I also tried this with Google Drive. 
Similarly I could import and load the file I selected, without everything being imported.

This was using the QualCoder 3.4 version (for importing it would be the same as the 3.3 version as the software has not changed 
for this section)

Im not sure what version 22h2 is - did you use and older QC version?

**Comment by rcdemuth** [comment]
Sorry I was using version 3.3 of qualcoder, mis-understood the bug report template and gave you the version of windows 11 that I was using.

Go ahead and mark this as closed, I cannot recreate the error today.  I'm not sure why it wanted to download everything on my machine yesterday.  Today everything is working as expected (and as you described).

**Comment by ccbogel** [comment]
ok. maybe an accidental select all key press. I know sometimes in a rush I press unknown key combinatins that do unexpected things.
