### ISSUE TITLE
Translate manuel

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#82]
Hello,

I have beginning a (non official) translation of the manual in french. I don't know how it can be integrate in the project.

Qwerty

**Comment by ccbogel** [comment]
I will upload the manual in the original odt format.
I use LibreOffice to edit it.

**Comment by ccbogel** [comment]
@qwertygc Should  I close this issue? As  idont know how much progression as been made.

**Comment by qwertygc** [comment]
Yes i close i don't have the time now for translate :/

**Comment by ccbogel** [comment]
Thanks for offering

________________________________
