### ISSUE TITLE
Divide by Zero when running a Coder Comparison 

### ISSUE THREAD

**Issue by RyanCollis** [ccbogel/QualCoder#821]
When trying to run a Coder Comparison an uncaught exception error occurs, 

![image](https://github.com/ccbogel/QualCoder/assets/145690602/a7d69eb2-c1e7-4bec-9d58-61e4a957570b)

This occurred on both my PC (Win 11) and my co-author's Mac (12.6). 

We have been passing the directory back and forth for coding, each using our own names to separate the codes. 

Coder Comparison also fails with a "KeyError: 'type'" 
![image](https://github.com/ccbogel/QualCoder/assets/145690602/810ec09a-cdd7-427f-956d-802805ed9cfd)

but Code Frequency works with no issues, so it seems to be able to find, identify, and count the codes from each user.

**Comment by ccbogel** [comment]
Thanks for letting me know. I have fixed the Zero Division error and I am sure I have also fixed the Key Error. The code is in the dev branch not the master branch, for now. If you want to download and use that. (Left hand side combo box - select Dev not Master then the Green Code button to download the files zip).

**Comment by RyanCollis** [comment]
Thank you for the fast reply. The key error is fixed, but the divide by 0 error has changed to a key error:
![Screenshot 2023-09-22 090137](https://github.com/ccbogel/QualCoder/assets/145690602/dfa47df6-fcd6-4d86-a599-9968411a6d45)

**Comment by ccbogel** [comment]
Sorry, a spelling error.
I had total['disgreement'] instead of total['disagreement'] in the calculate method, when fixing the Zero div error.
Fixed now.

**Comment by ccbogel** [comment]
Ok I have tested and fixed this. Please confirm.

**Comment by RyanCollis** [comment]
Everything seems to be working now. Thank you so much for your help.

**Comment by ccbogel** [comment]
Great.
