### ISSUE TITLE
When codes are merged "same text" to show up only once

### ISSUE THREAD

**Issue by amru39** [ccbogel/QualCoder#823]
When codes are merged if the same text has been coded for both it shows up twice. If possible can the text show up only once so the count of number of times the code is used is more accurate.

**Comment by ccbogel** [comment]
Thanks.  I found an error around this code merge issue. I have updated so this should not happen in the future. Let me know.

**Comment by amru39** [comment]
Thank you. With the latest code the issue is not occurring.
