### ISSUE TITLE
Allow sorting of tabular entries

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#824]
**Is your feature request related to a problem? Please describe.**
I am currently using QualCoder 3.4 and work with journals. I would love to view the entries in different orders depending on my specific search situation.

**Describe the solution you'd like**
it would be amazing of QualCoder would allow sorting columns, alphabetically or numerically. A click on the column should activate/reverse ordering. This should be doable for any column, including [self-defined columns, like for a date attribute](https://github.com/ccbogel/QualCoder/issues/815#issuecomment-1689891268).

Of course, that solution would ideally also be implemented for other instances of such tables across QualCoder.

**Describe alternatives you've considered**
Export data and sort there...

**Comment by ccbogel** [comment]
You can already do this now in Journals, right click on a cell in the column:
![Screenshot 2023-09-29 123823](https://github.com/ccbogel/QualCoder/assets/5834638/0ff93138-acb2-4a39-95ac-9bff442745a8)

**Comment by ilippert** [comment]
ah, now I got it. I think this is slightly non-intuitive. if possible, allow it by left-clicking on the column top, too. But of course I understand if this takes too much time.

**Comment by ccbogel** [comment]
OK i added ascending/descending to the column header - by right-click

**Comment by ilippert** [comment]
yeah, works perfectly, thanks a lot!
