### ISSUE TITLE
When creating a journal entry with a name with illegal characters, name information is lost

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#825]
**Describe the bug**
I want to create a Journal entry. Information on the entry name is lost.

**To Reproduce**
I am creating a journal entry, with an `,`.

![Screenshot from 2023-09-28 11-01-15](https://github.com/ccbogel/QualCoder/assets/20518297/ea2f471e-d372-41f2-900d-a38d4d8eadd1)

Then I click `OK`.

I get this 

![Screenshot from 2023-09-28 11-01-28](https://github.com/ccbogel/QualCoder/assets/20518297/79d40ec5-ca14-4df1-b507-fbaf48470a67)

I can only click `OK`.

Then I get back to the main window. So, my formulation effort for a wonderful name of the journal entry is lost.

**Expected behavior**
After the information window, get back to naming the entry, which would fit my original objective of creating the entry.

**Comment by ccbogel** [comment]
OK. I have added a validator to the name entry so invalid characters cannot be typed in.
