### ISSUE TITLE
Journal, volume, and issue

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#826]
In "Manage files" also add title of journal, number of volume, and number of issue as attributes (important in literature review). 

Moreover, it would be also nice for right-click option for realoading these reference attributes if one is accidentally deleted.

**Comment by AndrzejWawa** [comment]
And name of journal, volume, and issue in three independent columns to allow filtering or searching files by name of journal, number of volume or issue.

**Comment by ccbogel** [comment]
HI. In Manage files I don't want to add too many columns. As it becomes unwieldy. Specially if you add a range of your own attributes. One Librarian in USA does this and had 20 or so attributes to files.
You can right click within the column multiple times to filter.
e.g. right click to filter for 'Journal of Law' to get a short list,
then right click in the same column and filter for ' 40'  for volume 40
and /or '(1)' for issue 1

In manage refernces - yes  I can add those columns

**Comment by AndrzejWawa** [comment]
Ok, thank you for the guidance!

**Comment by ccbogel** [comment]
So for this column, I have collated the journal name, then a space, then the number, then a space then bracket '(' then issue number then bracket ')'
