### ISSUE TITLE
add feature dark mode

### ISSUE THREAD

**Issue by Parth4git** [ccbogel/QualCoder#835]
**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by AndrzejWawa** [comment]
Project -> settings -> style: select dark. Reopen the QC.

**Comment by ccbogel** [comment]
thx AW!

**Comment by Parth4git** [comment]
I want to add a dark mode button in the website as it is in Nodejs and many other websites have this feature in navbar. @ccbogel

**Comment by ccbogel** [comment]
Hi, its not easily possible. it is not a website its desktop app.

**Comment by Parth4git** [comment]
https://qualcoder.wordpress.com/ I want to add a dark mode button navbar that switches from light to dark mode, this feature I am referring to. @ccbogel

**Comment by ccbogel** [comment]
No, thank you
