### ISSUE TITLE
Auto comment 

### ISSUE THREAD

**Issue by shraddha761** [ccbogel/QualCoder#842]
**Is your feature request related to a problem? Please describe.**  
An auto comment workflow add comment while issue is open, pr is opened or closed

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**  
Assign this issue to me if you like this ides

**Comment by shraddha761** [comment]
@ccbogel if you like this feature request to assign this issue to me

**Comment by ccbogel** [comment]
Huh?

**Comment by shraddha761** [comment]
![image](https://github.com/ccbogel/QualCoder/assets/106100728/fe904a13-7338-4cfd-bd10-147647ddd380)
Something like this, The message can be customized
