### ISSUE TITLE
fix typo in readme

### ISSUE THREAD

**Issue by DevanshKyada27** [ccbogel/QualCoder#847]
**Describe the bug**
The error in the installation instructions for MacOS is a missing space between "pdfminer.six" and "plotly," and "pyqt6" should be a separate module name. The corrected command in the description is:

pip3 install chardet ebooklib openpyxl pandas pillow ply pdfminer.six plotly pydub pyqt6 python-vlc rispy six SpeechRecognition wordcloud xmlschema

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ccbogel** [comment]
there is no error. Blocked
