### ISSUE TITLE
Requirements.txt instead of listing all modules

### ISSUE THREAD

**Issue by Paulie-Aditya** [ccbogel/QualCoder#849]
The readme states that I need to download so and so modules manually. This looks shabby and hard to understand for users too.

**Describe the solution you'd like**  
A Requirements.txt file so that people can easily install the required packages with a simple line and get on with developing using this repo.

**Comment by ilippert** [comment]
For which operation OS do you like this?

**Comment by ccbogel** [comment]
added requirements file
