### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [ccbogel/QualCoder#852]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/ccbogel/QualCoder/assets/147402107/de9ac5b8-cb3a-452a-9c47-f85ac4b2209d)

**Comment by Kalyanimhala** [comment]
@ccbogel  kindly assign me this issue, I want to work on it. Thank You!

**Comment by ccbogel** [comment]
It is not needed. Contributors ae shown on the page
