### ISSUE TITLE
File date/time stamp off by one hour compared to Windows Explorer 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#86]
The 'select file' dialogue when importing files shows the wrong modified date compared to Windows Explorer (off by an hour, GMT rather than BST). 

Windows 10 x64, QualCoder 1.9, Python 3.8 32 bit

**Comment by ccbogel** [comment]
This issue is going to be challenging:
https://stackoverflow.com/questions/15910181/elegant-way-to-adjust-date-timezones-in-python

**Comment by ccbogel** [comment]
For future python 3.9 implementations: a new module
The zoneinfo module brings support for the IANA time zone database to the standard library. It adds zoneinfo.ZoneInfo, a concrete datetime.tzinfo implementation backed by the system’s time zone data.

>>> from zoneinfo import ZoneInfo
>>> from datetime import datetime, timedelta

>>> # Daylight saving time
>>> dt = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo("America/Los_Angeles"))

**Comment by ccbogel** [comment]
Added a timezone function which might resolve this issue.

**Comment by glocalglocal** [comment]
The timestamps in the Open File dialogue and Windows Explorer are now consistent. Not sure what happens on other systems though. I discovered that Windows historically records the time of the clock, which means that in many countries there is a difference between winter and summer times. Some applications (eg 7-zip and Freecommander that I use), use UTC. This creates inconsistencies, particularly when comparing eg for backup purposes.

**Comment by ccbogel** [comment]
Ok. Will close this issue now.
