### ISSUE TITLE
Windows: wrong documents folder

### ISSUE THREAD

**Issue by kaixxx** [ccbogel/QualCoder#863]
**Describe the bug :**

The issue https://github.com/ccbogel/QualCoder/issues/861 also reveals a more general problem: 
**On windows, the user directory is not the right place to look for documents. This would be the "documents"-folder.** 

```os.path.expanduser('~')``` points to the user-profile-folder which also includes all the user specific settings, temporary/cached files and even some program binaries that are installed only for this particular user. By default, the "documents" folder is a subdirectory of the user profile. But even this is not always the case. The user may change the default location, i.e., to move their documents to a bigger harddrive. 
This problem affects not only the search for missing file links. Whenever qualcoder opens a file dialog to select a document name for import or export, a windows user (like me) would expect the "documents"-folder to be the starting point (or the last used dir). 

**Expected behavior :**

I would suggest adding the following function to "helpers.py" and call it not only in ```find_filepaths``` but whenever a file dialog is opened:
```
import ctypes
import platform

def get_documents_folder():
    if platform.system() == 'Windows':
        # Get the path to the Documents folder using SHGetFolderPath
        CSIDL_PERSONAL= 5       # My Documents
        SHGFP_TYPE_CURRENT= 0   # Want current, not default value
        buf= ctypes.create_unicode_buffer(ctypes.wintypes.MAX_PATH)
        ctypes.windll.shell32.SHGetFolderPathW(0, CSIDL_PERSONAL, 0, SHGFP_TYPE_CURRENT, buf)
        return buf.value
    else: 
        return os.path.expanduser('~')
```
(Inspired by: https://stackoverflow.com/questions/3858851/how-to-get-windows-special-folders-for-currently-logged-in-user)

One could even return '~/Documents' on macOS, but this might fail on machines set to another language than english.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 3.4

**Comment by ccbogel** [comment]
Thank you. I have added the code in. but I am not convinced it is the best approach yet. As some items would be in Videos, Music, Images or Pictures folders - these are not subfolders of the Documents folder. I have also so far updated \_\_main\_\_.py to us this now.

**Comment by ccbogel** [comment]
updated in a few places now.

**Comment by kaixxx** [comment]
> I am not convinced it is the best approach yet

I see your point. It depends on how people organize their files. I would collect all my field notes, audio recordings, transcripts, photos, etc. belonging to a particular research project in a folder under my documents. "Pictures" and "videos" only contain private holiday photos and such. But other people might handle this differently. 
I think the cleanest apporach would be to use the native file dialogs all throughout the app. This would make it very easy to access your documents, pictures, video... folders:

![grafik](https://github.com/ccbogel/QualCoder/assets/3353272/b2682918-208c-44bb-8928-8b2d7f623c39)

There is also another reason why I would prefer native dialogs: I see many of my students using cloud services (like MS Onedrive) to manage their data. These cloud folders are also nicely integrated into the native file dialogs (see the arrow above) but rather awkward to use with the Qt-dialogs. I am personally not a big fan of cloud services. But I think we have to accept that people use them anyway...
(btw: "Open project" is already using the native dialog, "Manage files" and others are not.)

**Comment by ccbogel** [comment]
@kaixxx 
I use this in file open dialogs:
options=QtWidgets.QFileDialog.Option.DontUseNativeDialog

Because on some operating systems using native dialogs causes errors. I didn't note which or the specific error. However it did happend.. So I won't revert to native for now. You are welcome to edit your own copy of QC by removing that exact code above, when you find it.

**Comment by kaixxx** [comment]
>  on some operating systems using native dialogs causes errors

Ok, so no native dialogs for now. 

> I have reverted that change as it caused errors on some Windows platforms.

Sorry for the trouble. Can you tell me a little more about the error and on which platform? 
I'm also curious to know because I wanted to use this exact code in my own app. I'm the autor of noScribe, the ai-based transcription tool we talked about a few weeks back.

**Comment by ccbogel** [comment]
ah ok yes I remember. On this windows I am using now, with the ctypes import there was no wintypes attribute on Win11 home python 3.11. On another Windows 10, this error did not occur.

**Comment by ccbogel** [comment]
yes true.
