### ISSUE TITLE
minor change: change infobox title

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#867]
I love the new info window that you implemented in reaction to https://github.com/ccbogel/QualCoder/issues/827.

![Screenshot from 2023-11-14 14-05-25](https://github.com/ccbogel/QualCoder/assets/20518297/5adfc91f-2319-4cfe-96b1-ec26f3572112)

I suggest to not call this a `warning`, but an `information`, if easily possible.

**Comment by ccbogel** [comment]
updated
