### ISSUE TITLE
Overlapping highlights in coded text

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#87]
Overlapping highlights in coded text make it impossible to tell when a snippet is coded for more than one code. This is particularly problematic when, say, a coded sentence is part of a differently coded paragraph. There is no way to tell that that sentence is coded differently. Possibly a reserved colour could be used as a visual cue for overlaps. There is already a mouse pointer tooltip showing which codes are applied.

**Comment by ccbogel** [comment]
Hi - check again my edited response to the coded text not showing, as I updated my response there.
Re this issue with overlaps - I have partly corrected by mouse hover showing the full text for each code - which is a small improvement - check it to let me know what you think.

**Comment by glocalglocal** [comment]
Re overlaps, with the update I am getting the error below when I hover over any highlighted area. 

2020/07/07 02:59 ERROR select_file.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\code_text.py", line 1150, in eventFilter
    displayText = '<p style="background-color:' + item['color'] + '"><em>' + item['name'] + "</em><br />" + item['seltext'] + "</p>"

TypeError: can only concatenate str (not "NoneType") to str

**Comment by ccbogel** [comment]
OK I have added code to catch this exception. This exception shouldnt occur, and I suspect that the import or original rqda data  has some blanks (i.e. not text at all) coded.

**Comment by glocalglocal** [comment]
I got the latest updates and tried the file I imported earlier -- the one with the black bands. I received the error below. It may work fine when the database is nicely corrected on import, and I will check, but there is still something wrong there. 

2020/07/07 11:44 ERROR select_file.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\code_text.py", line 1150, in eventFilter
    displayText = '<p style="background-color:' + item['color'] + '"><em>' + item['name'] + "</em><br />" + item['seltext'] + "</p>"

TypeError: can only concatenate str (not "NoneType") to str
2020/07/07 11:44 ERROR select_file.exception_handler Uncaught exception: Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\code_text.py", line 1150, in eventFilter
    displayText = '<p style="background-color:' + item['color'] + '"><em>' + item['name'] + "</em><br />" + item['seltext'] + "</p>"

TypeError: can only concatenate str (not "NoneType") to str

**Comment by ccbogel** [comment]
@glocalglocal  Yes I understand. If you are using the rqda file that you imported with the 'incorrect ' colour names this will happen. 
If you have not done any 'real' work with the imported file yet - can you please try re-importing the rqda file.
then let me know if this issue occurs again - I suspect it will not, as I have added code to put in random colours for the codes, rather than the error-causing blanks that occurred in the earlier import.

**Comment by glocalglocal** [comment]
The re-imported file works. This method of displaying overlapping codings works reasonably well. Interestingly, I can see now certain overlapping snippets were coded twice with the same code -- I think because it doesn't look like a qualcoder glitch.  

This method can get confusing with multiple overlaps but I am not familiar with a better alternative -- even the big guys, like NVivo, use coloured lines that are no less confusing. What will happen if there is so much text in the tooltips, the screen won't be big enough to accommodate it? 

(a) the tooltip times-out after a while (b) it pops up constantly and a big tooltip can cover potentially useful text -- could this be triggered only with ctrl? And could each tooltip snippet be reduced to [Beginning]... [End]? (c) unmark is unpredictable. I think it removes the most recent 'layer' which is not known to the user. Could the tooltip be used to enable the user to unmark for a selected code? 

To increase variability, why not show allow the user to specify foreground/background? It's difficult to tell the difference between several reds, but adding a font colour would increase the range.

**Comment by ccbogel** [comment]
Thanks for the feedback on this. I'm not keen on changing the foreground colours as well, add confusion I think. I think ideally the same text should not have much repeated overlapped coding (e.g. more than 2 or 3 overlaps indicates maybe a choice of codes is not ideal - Im not sure).
I cant control tooltip timeouts. Tooltips cannot be used to mark/unmark text.
Yes tooltip snippets could be reduced in size - good idea, on the TODO list.
Yes unmark is unpredictable in an overlap section - I will put this on the TODO list also :)

**Comment by glocalglocal** [comment]
This is literally academic but there are situations where multiple overlaps may be necessary, particularly if a long piece of coded text contains several small snippets that are differently coded. 

For me the real usability issue now is unmarking overlapping codings. 

Another thing, I tried to re-import the rdqa file and I accidentally specified a project name that was already used. Qualcoder correctly complained but then cancelled the operation. I think it should ask for another name. 

Also, Qualcoder now handles correctly properly formed rqda files, but shouldn't it handle gracefully corrupted files?

**Comment by ccbogel** [comment]
yes - will work on the multiple overlaps unmarking.
Re asking for another name  - ok will consider this
Handling corrupted files - not sure - do you mean a corrupted rqda database? this may be difficult as  I would need to have some idea of what the corruption is. If the entire database is corrupted it would not be readable.

**Comment by glocalglocal** [comment]
unmarking: in addition to the Code dialogue, another dialogue that could also offer unmarking is the codings report. But I think proper unmarking should be possible mainly in the Code dialogue.  

Corrupted files: what I meant was that if qualcoder sees there is something wrong in the imported file, it should say so, try to handle it if possible or cancel the operation if not possible (eg in the case of blanks in the rdqa file earlier). 

I think I pretty much reached the bottom of my list of observations for now. I may have more to say when I do some real-life coding.

**Comment by ccbogel** [comment]
ok thank you!!

**Comment by ccbogel** [comment]
I think I have address a fair bit of issues here, including some handling of corrupted rqda data.
I will create a new issue re the overlaps
