### ISSUE TITLE
Does not load VLC on Windows 11

### ISSUE THREAD

**Issue by yetiinabox** [ccbogel/QualCoder#870]
**Describe the bug :**
<br/>
When launching qualcoder on a Windows 11 machine with VLC installed, qualcoder throws the following error: "Could not find module 'C:\Users\will\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax." It also cannot load VLC when one tries to annotate a audio file.

**To Reproduce :**
<br/>
On a fresh install of Windows 11
- install scoop
- use scoop to install vlc and ffmpeg (OR: install VLC as a system admin)
- install qualcoder according to directions using venv. 
- Activate venv. Run qualcoder. 
- Qualcoder throws the error above.

The same behaviour happens if 
(1) libvlc.dll is copied to the directory mentioned 
(2) the user or system path is adjusted to include VLC

**Expected behavior :**
<br/>
qualcoder runs without complaint and is able to load and annotate mp4 files (this was the behaviour under Windows 10).

**Screenshots :**
<br/>
If applicable, add screenshots that helps to explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context :**
<br/>

**Comment by ccbogel** [comment]
I tested by downloaded the latest QualCoder-master zip. Unzipped to Downloads. Created a venv. Ran the software. I did not get these errors. For this test I used my Windows 11-Home. 
The VLC dll was located in C: Program Files / VideoLan / VLC  / libvlc.dll
The VLC version is 3.0.20 Vetinari  for Windows 64-bit

Will this information help you with it?

**Comment by yetiinabox** [comment]
Thank you for responding so quickly!  Yes, your information is helpful. See especially 5 and 6 below.

(1) The machine I'm working on is a corporate laptop with Windows 11 Pro - I installed VLC through scoop and can use it that way, but qualcoder can't find it. 

(2) Qualcoder did, I think, find VLC installed this way on my previous machine (Windows 10)). - the path is C:Users/(username)/scoop/apps/VLC/current/ with an alias at .../scoop/shims/ and (see (6)) PATH references this correctly.

(3) When I asked IT support to install VLC at the system level, the VLC installer put it into C:Program Files (x86)/VideoLan/VLC/ . So there is a difference between your reference install and the install that the VLC installer put onto this machine.

(4) Yes, this means that the IT support people left me with two installations of VLC while trying to fix this. So far as I can tell, that hasn't changed anything, though I want to fix that once I understand how to get qualcoder working.

(5) Does the routine that seeks VLC in Qualcoder look in both of those directory trees (C: Program Files/ and C: Program Files (x86) )? 

(6) If it is relevant - PATH on this machine includes both C: Users/(username)/scoop/shims  and a direct reference to C:Program Files (x86)/VideoLan/VLC/  - and calling VLC from the commandline (Powershell) works. It calls the scoop VLC.

I'm *not* a Windows person at all, I use Linux by choice, but I have to use this work laptop for this analysis. 

Again, thank you for your help.

**Comment by ccbogel** [comment]
Funny that, I have only recently returned to Windows also after 10+ years of Ubuntu, after laptop died. With Windows I can make the exe file for QualCoder. Though I find Windows a bit more cumbersome to use. So will probably again get Ubuntu as well at some stage.

You can download and read the vlc.py file from here: [https://pypi.org/project/python-vlc/](https://pypi.org/project/python-vlc/)  I did this just now. In the findlib method (starts at line 122) it is, amongst other places, looking for the ProgramFiles folder (line 159). 
So if you open python in the command line and run this code: 
import os
programfiles = os.environ["ProgramFiles"]
print(programfiles)

For me the output is  C:\\Program Files

I presume it will do the same for you. The best and simplest solution is to get your tech person to install the VLC software (64 bit version) into the Program Files folder.

======
The less easy and untested alternative, would be to change the line in the vlc.py file from:
programfiles = os.environ["ProgramFiles"]
replace with:
program files = "C:\\Program Files (x86)"
Keep the exact spaces at the start of this line, as spacing is important.

In the qualcoder \_\_main\_\_.py file line 88
replace
import vlc
with 
import .vlc
Make sure that there are 4 spaces before the import vlc wording. Spacing is important in python.
This change would have to be replicated in the qualcoder view_av.py, manage_files.py, helpers.py files also

Then copy the vlc.py file into the inner qualcoder folder.

Then remove when setting up the venv, do not install use pip to install vlc
=======

Apart from this, I am glad you have found QC useful. and if you have any public publications, please let me know and I can add to my Wordpress Studies using QualCoder page.

**Comment by yetiinabox** [comment]
I persuaded tech support to do the right thing. It works beautifully now.
> Apart from this, I am glad you have found QC useful. and if you have any public publications, please let me know and I can add to my Wordpress Studies using QualCoder page.

I certainly will do. This will eventually wind up being part of the research and analysis supporting the 3rd New Scots refugee integration policy, at which point I will make sure you can reference it formally. This is a much better tool than RQDA. 

Thank you again!

---WBTD.
Will Tuladhar-Douglas

**Comment by ccbogel** [comment]
@yetiinabox Wonderful. I will be glad to know when you publish.
p.s. I will probably release a 3.5 version soonish. Although, if you have downloaded the latest code rather than from the 3.4 release, you will be up to date with QualCoder anyway.
