### ISSUE TITLE
Missing requirement py2exe dependency with Python 3.12.1 on Windows

### ISSUE THREAD

**Issue by sabinammm** [ccbogel/QualCoder#878]
**Describe the bug :**
<br/>
Qualcoder 3.4 cannot be installed in Windows virtual environment due to missing python requirement **py2exe**. 

**To Reproduce :**
<br/>
I followed all instructions with installation in a Windows virtual env. Upon running `py -m pip install .` within the Qualcoder-3.4 folder, the following output was generated:
```
Processing c:\users\smollenhauer\downloads\qualcoder-3.4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      ERROR: Ignored the following yanked versions: 0.9.2.0, 0.9.2.2, 0.10.0.2
      ERROR: Ignored the following versions that require a different python version: 0.10.1.0 Requires-Python >=3.6, <3.10; 0.10.2.0 Requires-Python >=3.6, <3.10; 0.10.2.1 Requires-Python >=3.6, <3.10; 0.10.3.0 Requires-Python >=3.6, <3.10; 0.10.3.1 Requires-Python >=3.6, <3.10; 0.10.4.0 Requires-Python >=3.6, <3.10; 0.10.4.1 Requires-Python >=3.6, <3.10; 0.11.0.0 Requires-Python >=3.6, <3.11; 0.11.0.1 Requires-Python >=3.6, <3.11; 0.11.1.0 Requires-Python >=3.7, <3.11; 0.11.1.1 Requires-Python >=3.7, <3.11; 0.12.0.0 Requires-Python >=3.7, <3.11; 0.12.0.1 Requires-Python >=3.7, <3.11; 0.12.0.2 Requires-Python >=3.7, <3.11
      ERROR: Could not find a version that satisfies the requirement py2exe (from versions: none)
      ERROR: No matching distribution found for py2exe
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Since **py2exe** seemed not to be installed and wasn't listed in the instruction dependencies to be installed, I attempted to install it following the error with the following input and output
`py -m pip install py2exe
ERROR: Ignored the following yanked versions: 0.9.2.0, 0.9.2.2, 0.10.0.2
ERROR: Ignored the following versions that require a different python version: 0.10.1.0 Requires-Python >=3.6, <3.10; 0.10.2.0 Requires-Python >=3.6, <3.10; 0.10.2.1 Requires-Python >=3.6, <3.10; 0.10.3.0 Requires-Python >=3.6, <3.10; 0.10.3.1 Requires-Python >=3.6, <3.10; 0.10.4.0 Requires-Python >=3.6, <3.10; 0.10.4.1 Requires-Python >=3.6, <3.10; 0.11.0.0 Requires-Python >=3.6, <3.11; 0.11.0.1 Requires-Python >=3.6, <3.11; 0.11.1.0 Requires-Python >=3.7, <3.11; 0.11.1.1 Requires-Python >=3.7, <3.11; 0.12.0.0 Requires-Python >=3.7, <3.11; 0.12.0.1 Requires-Python >=3.7, <3.11; 0.12.0.2 Requires-Python >=3.7, <3.11
ERROR: Could not find a version that satisfies the requirement py2exe (from versions: none)
ERROR: No matching distribution found for py2exe`

**Expected behavior :**
<br/>
I expect to be able to easily install the program if all the requirmenets are met. Again, my Python version is Python 3.12.1, which seems to be contradictory when attempting to install **py2exe**, so I cannot figure out immediately how to solve this issue and instead have to figure out how to downgrade Python to 3.10 in Windows first. It would be great if the installation process made sure that I had the correct Python version installed from the beginning or alternatively that there isn't a dependency that requires an older Python version than everything else. I hope you can fix it by fixing the requirements, perhaps with a requirements.txt as has been suggested.
**Screenshots :**
<br/>
If applicable, add screenshots that helps to explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11 Enterprise

**Additional context :**
<br/>

**Comment by ccbogel** [comment]
@sabinammm Thank you for raising the issue. I am still using python3.11. The latest python 3.12 does not use py2exe. I have updated the commands - so it should now work if you read again through steps 1 to 9 for Windows.

Also I recommend that you use the latest 3.5 release, it fixes some errors in 3.4 and also uses its own wordcloud which was sometimes an install problem on the 3.3 and 3.4 versions: [https://github.com/ccbogel/QualCoder/releases/tag/3.5](https://github.com/ccbogel/QualCoder/releases/tag/3.5)
Also if you prefer to use the self contained exe for windows you could download and run that instead.
