### ISSUE TITLE
Case files not visible

### ISSUE THREAD

**Issue by angie1379** [ccbogel/QualCoder#880]
**Describe the bug:**
<br/>
I am new to QualCoder and hope this is the correct place to seek assistance. According to the Wiki and YouTube videos, the list of files associated with a given case should show up to the right of the case list when a case is selected. However, that is not happening. I cannot see which files I tagged for each case. I tried moving the screen divider, but it did not reveal the files. The case isn't registering as selected. Any help would be greatly appreciated. 

**Screenshots :**
<br/>
From the Wiki: 
![image](https://github.com/ccbogel/QualCoder/assets/156710756/f28dd20d-a915-4765-ae2a-7eda989c4370)

From my project:

![image](https://github.com/ccbogel/QualCoder/assets/156710756/42d065e2-493d-41a5-b40a-f31c2a9ca426)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 365
 

**Additional context :**
<br/>

**Comment by ccbogel** [comment]
@angie1379 HI, I removed that visual case display, as it annoyed some people when they had lots of attributes. Also it was hard to implement well. I have updated the wiki image.
So, now open the case file manage for that case, then click on the text file to display the text there for each file that is assigned.

**Comment by angie1379** [comment]
Thank you for the clarification. So am I correct in understanding the best way to see all of the coded text associated with a case is by running a report?

**Comment by ccbogel** [comment]
The best way is to go to the case-file manager and view the text file for that case.
Using the coded text report will only show the coded text, not the fill text file.
![image](https://github.com/ccbogel/QualCoder/assets/5834638/008d6f61-1b30-43a9-aa01-7fb43f593eb2)
