### ISSUE TITLE
Does not start on Windows, cannot load QtGui DLL

### ISSUE THREAD

**Issue by yetiinabox** [ccbogel/QualCoder#882]
**Describe the bug :**
<br/>
On a fresh re-install of qualcoder under Windows Pro 11, done using the source download and pyenv method, the launch of qualcoder fails with the error
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.

**To Reproduce :**
<br/>
Follow the instructions on the website/readme to install qualcoder on Windows. Set up a venv, use pip to install all the prerequisites (including PyQt6). CD to a fresh, unzipped qualcoder download directory. Either (a) run qualcoder directly or (b) install qualcoder using python3 -m pip install .  - using either method, if one then tries to run qualcoder, the following happens:

```
(Qualcoder_venv) PS C:\Users\will\hardhat\QualCoder-master> python3 -m qualcoder
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\will\hardhat\QualCoder-master\qualcoder\__main__.py", line 47, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
```

**Expected behavior :**
<br/>
Qualcoder should run normally.

**Screenshots :**
<br/>
If applicable, add screenshots that helps to explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows Pro
 - Version 11 22H2

**Additional context :**
<br/>
This error first showed up after running pip install --upgrade for all the prerequisites for qualcoder, as qualcoder was not loading a file type I expected it to load (.odt). When this error occurred, I deinstalled qualcoder completely and reinstalled it, and the error persists. My suspicion is that PyQt6 has changed somehow, but I have not sought to verify this.

**Comment by ccbogel** [comment]
Yes I suspect PyQt6 has changed. No quick fix, but you could try running under a different version of python, e.g. 3.10 or 3.11 instead of 3.12. this means downloading the version (don't add to path if it asks during installation). Then using the specific version in the commands like this: python3.10  ...
Alternatively use the exe

**Comment by ccbogel** [comment]
Is this OK now, I will close the issue soon.

**Comment by yetiinabox** [comment]
On Monday, 29 July 2024 00:30:41 BST QualCoder Developer wrote:
> Is this OK now, I will close the issue soon.

Yep, all sorted. Sorry!  I should have closed it.


Be well,

—WBTD.
- - -- --- ----- -------- -------------
Will Tuladhar-Douglas
***@***.***
