### ISSUE TITLE
Headings, bold and italics visible in right-hand panel

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#883]
Hi,

I have started my empirical analysis and created system of memos, including definitions, anchor examples, coding rules etc. - they are required by the Qualitative Content Analysis.

The right-hand panel in coding mode is very useful for this. Is it possible for this panel to display headings, bold and italics that have been used during writing codes and project memos? Now, they differ:

![obraz](https://github.com/ccbogel/QualCoder/assets/77200214/7d33fe84-e1df-4ab6-899e-8db5358332bf)

**Comment by ccbogel** [comment]
done

**Comment by AndrzejWawa** [comment]
Hi,

This upgrade is very useful. Is it also possible to introduce this then displaying:
1) coded text memo preview in code text mode,
2) coded text memo and other memos in coding report?

**Comment by ccbogel** [comment]
1 coded text memo preview in code text mode. This is when you mouse hover over the memo?
I think I can see a way to do this.
