### ISSUE TITLE
Right click context menu in Audio/Video Coding doesn't show

### ISSUE THREAD

**Issue by ht-commer** [ccbogel/QualCoder#884]
**Describe the bug :**
<br/>
V. 3.5 in an English Windows 11 environment
After audio/video segments are identified, it is not possible to see the right click context menu - a window briefly flashes and quickly disappears. 

**To Reproduce :**
<br/>

Click on audio/video segment, right click on segment, menu doesn't show.

**Expected behavior :**
<br/>
Right click should cause a context menu to appear, where the user should be able to see play segment, delete segment, link text to segment, and other options.

**Screenshots :**
<br/>
See attached

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit
 - Version: 22H2, 16GB Ram, 12th Gen Intel Core i7-1260P 2.10 GHz

**Additional context :**
<br/> 
![Screenshot 2024-02-13 085514](https://github.com/ccbogel/QualCoder/assets/159937443/3de1e2ff-9d66-4af9-97ce-eae58e1152f5)

**Comment by ccbogel** [comment]
It appears to be an issue with the exe. I don't know how to fix the exe.
I downloaded the source code zip, and ran that. Under this option the context menu works fine. 
I will put a note on the 3.5 release info.

**Comment by ht-commer** [comment]
I also tried the virtual environment , and the context menu works. Only issue is, after a video segment is played, there is an error message like the following appears in the console (but not in the GUI): 
[000002b07adb13c0] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4 
The linked text segment cannot be displayed after checking the option "scroll transcript while playing".

**Comment by ccbogel** [comment]
You should be able to ignore that thumbnail error without affecting how QC works. I get various ignorable errors when using VLC with python.

Regards this:
The linked text segment cannot be displayed after checking the option "scroll transcript while playing".
I did not have a problem. The checkbox was checked and in the context menu I selected play segment, and it played the segment.  So I dont know what happened there - unless the log file has some error noted?
I gues the easy fix is not to check that box.

**Comment by ht-commer** [comment]
Thank you for the feedback!

**Comment by ccbogel** [comment]
@ht-commer OK. I am working on an additional solution to this problem. Click on the Segment label text at the top of the screen will allow you to select a segment from a list. Then this will show a context menu for memo, delete, play.
It is under development right now, so I will work on it over the next week to fixit a lot more.
This will be something that works with segments when the code is packaged into an exe with pyinstaller.

**Comment by ccbogel** [comment]
@ht-commer OK now updated so:
right-click on the segment label will allow you to select a segment.
Then a menu pops up for play, delete, or memo the segment.
![image](https://github.com/ccbogel/QualCoder/assets/5834638/99e04cef-0005-428b-9d18-9af5f3541340)

**Comment by ht-commer** [comment]
Thanks for the update. On my Windows 11 system I can now select the segments on top to see and execute the menu items, and in the corresponding transcription/text segments, I can "play text" after right-clicking the coded text.

**Comment by ccbogel** [comment]
will close issue when checked by using a pyinstaller exe version

**Comment by ccbogel** [comment]
OK, now I have added a button. Hover over to see the tooltip comment.
This works by pressing the button, then select a segment, then the menu opens for : play, delete, memo
