### ISSUE TITLE
ERROR report time is off by 12 hours 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#89]
ERROR reports quote the wrong time. Eg just now: 2020/07/07 01:50. The time was 13:50 here.

**Comment by ccbogel** [comment]
hmm OK is this happening all the time?

**Comment by glocalglocal** [comment]
yes

**Comment by ccbogel** [comment]
OK,
The log is reset on opening the program, because otherwise it becomes large if a lot of text goes into it. So if there is an issue - you can view/save the log befor re-opening the program.

**Comment by glocalglocal** [comment]
How about a rolling log, or multiple log files up to a certain number of files? Only saying because the user can accidentally delete valuable debugging info by opening a project.

**Comment by ccbogel** [comment]
Thanks good idea. OK I have found the code to do this and uploaded a new version that supports rollover.
Also have changed the date format to 24 hour time.
