### ISSUE TITLE
version numbering

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#891]
I just have removed

/usr/local/lib/python3.12/site-packages/Qualcoder-3.4-py3.12.egg and then have freshly reinstalled QualCoder. The folder `Qualcoder-3.4-py3.12.egg` then reappears.

Though I have the 3.5 code.

**Comment by ccbogel** [comment]
Ahh. yes. the setup.py file still says 3.4 
I forgot to update to 3.5

**Comment by ccbogel** [comment]
I have updated the latest code to 3.6
