### ISSUE TITLE
Difference between a memo and an annotation?

### ISSUE THREAD

**Issue by maphouse** [ccbogel/QualCoder#895]
They seem to do the same thing. What's the difference? [Wiki guide](https://github.com/ccbogel/QualCoder/wiki/07-Coding-Text) doesn't say

**Comment by ccbogel** [comment]
For text coding, a memo is linked to a coded text segment. An annotation is a memo that is not linked to a coded test segment.
There might be times when you analyse coded text that the coded text memo is useful. These memos can be displayed associated with the coded text in a text report. 
An annotation might be useful for explaining or expressing some wording in more depth - such as expanding an acronym or explaining some slang
.

**Comment by maphouse** [comment]
I see, thanks. So annotations have nothing to do with the codes (attached to the text). Memos can give context to codes, why something was coded a certain way, etc. ok

**Comment by ccbogel** [comment]
Yes, that's correct.
