### ISSUE TITLE
Alphabetical order issue with multi-level categories

### ISSUE THREAD

**Issue by FP1404** [ccbogel/QualCoder#897]
Hello,
I think there is a potential bug concerning the alphabetical ordering of categories when it extends beyond the second level (see attached).

Has anybody experienced the same issue?

Best wishes,
<img width="109" alt="Alphabetical_order" src="https://github.com/ccbogel/QualCoder/assets/142088862/ccb42e4d-e35a-4070-93c5-1d7a3ff6dbf0">

**Comment by ccbogel** [comment]
I will look into it and see if I can fix it thank you. It does seem odd, the first The power entry is out of order but the later ones are ok

**Comment by FP1404** [comment]
I think the first subcategory you input (i.e. the power) gets "locked" and
cannot be ordered anymore.

Thank you

Federico Pendenza

**Comment by FP1404** [comment]
I think the first subcategory you input (i.e. the power) gets "locked" and
cannot be ordered anymore.

Thank you

**Comment by ccbogel** [comment]
that would work only up to 9. 10 up would look odd, unless you added a preceeding 0.
01
02
03
etc

1
10
2
etc

**Comment by ccbogel** [comment]
OK, I think this is fixed now. I have applied this in the Code Text section. I used a sort function for the QTreeWidget. Please let me know, then I can apply the same solution in other sections of QualCoder.

**Comment by FP1404** [comment]
That's fantastic - thank you. I guess I need to re-install QC through the source, which has been updated. I usually run it through the Windows executable, which I don't think has been updated. Anyway, regarding your question about how I am finding it QualCoder, it's fantastic software. In the past, I used to work on NVivo and MAXQDA but it's been almost 8 months I have been using QualCoder for my research projects (there will be an article coming up where I will be mentioning this software). It's light, powerful, and comprehensive. An undo or sort of history function would be useful but I know it may not be feasible. Thanks for all your work!

**Comment by FP1404** [comment]
<img width="49" alt="Screenshot 2024-04-09 090535" src="https://github.com/ccbogel/QualCoder/assets/142088862/12cb3c0c-5cd9-41ec-a2c2-d8671ffafe87">
<img width="71" alt="Screenshot 2024-04-09 090749" src="https://github.com/ccbogel/QualCoder/assets/142088862/c4387b72-f137-4b96-bd6e-51f752448695">

I have installed QualCoder through the source but I don't think the function you applied is working with current projects: actually, the order is all over the place now (see attached)

**Comment by FP1404** [comment]
<img width="49" alt="Screenshot 2024-04-09 090535" src="https://github.com/ccbogel/QualCoder/assets/142088862/1de7c6c8-cf30-42f5-b63c-5c8252db4b5c">
<img width="71" alt="Screenshot 2024-04-09 090749" src="https://github.com/ccbogel/QualCoder/assets/142088862/25201009-c861-4286-b66b-28261f691872">

I don't think it seems to work. Ordering is now all over the place at all levels :(

**Comment by FP1404** [comment]
Finally managed to run QualCoder from source - I am currently on a university-managed device - and the solution doesn't seem to work (see attached); actually, ordering is not all over the place across different levels. (You may have noticed that I deleted a couple of messages. I thought I had done something wrong and didn't want to create any confusion)

<img width="49" alt="Screenshot 2024-04-09 090535" src="https://github.com/ccbogel/QualCoder/assets/142088862/82bdbe19-918d-441d-b4b8-de75c70dda65">
<img width="71" alt="Screenshot 2024-04-09 090749" src="https://github.com/ccbogel/QualCoder/assets/142088862/3e588a46-0a3a-41e0-8e87-8e3d83dac4dd">

**Comment by kaixxx** [comment]
> ordering is not all over the place across different levels

Sorting is in descending order. That should be changed to `QtCore.Qt.SortOrder.AscendingOrder` (line 677). Other than that, your examples looks fine to me. Or am I missing something?

However, one problem is still left: The sorting is currently only applied when the code tree is loaded initially. We also need to add it to other functions like `add_code()` and `merge_category()`.

**Comment by FP1404** [comment]
> Sorting is in descending order. That should be changed to QtCore.Qt.SortOrder.AscendingOrder (line 677). Other than that, your examples look fine to me. Or am I missing something?

No, you are right. Thank you for checking it

> However, one problem is still left: The sorting is currently only applied when the code tree is loaded initially. We also need to add it to other functions like add_code() and merge_category().

I trust your judgement - I am not a programming/coding specialist, just a regular QualCoder user :)

**Comment by ccbogel** [comment]
Yes sure. I have time tonight to fix this.

**Comment by kaixxx** [comment]
> add code and merge categories etc. They will be updated anyway

You are right, fill_tree() is called in update_dialog_codes_and_categories() which is called in add_code()... Missed that, my bad.
For me, everything is working fine now! 

Nice to see that you also corrected the small error in save_backup().

**Comment by ccbogel** [comment]
OK closing issue now. I think I updated the code tree display everywhere. let me know if not. Luckily an easy fix.
@kaixxx Re the collab branch. Is it able t obe merged now? I am thinking there will be some conflicts in some files eg main.py and code text.py

**Comment by FP1404** [comment]
Everything seems to work. I am wondering whether not sorted/not arranged codes could be forced down the categories as it used to be (see attached). 

Thank you,
![unarranged-codes](https://github.com/ccbogel/QualCoder/assets/142088862/f6568610-2031-4d89-b8d6-382e225122b0)

**Comment by kaixxx** [comment]
@ccbogel 
>the collab branch. Is it able t obe merged now?

Let me have a final look. It should be ready, but I have a cold right now and need a clear mind for some final checks. I will also resolve any conflicts with the master branch.

**Comment by ccbogel** [comment]
@kaixxx OK, whenever you feel good, and are ready. Its an exciting update. 9My good supporter of QC in Poland is almost ready to do his final PhD paper. He has used QC in a different way from most Qual approaches, involving analysing legal documents.)

**Comment by ccbogel** [comment]
@FP1404  I am wondering whether not sorted/not arranged codes could be forced down the categories as it used to be (see attached).
This is now a very difficult request to do.
