### ISSUE TITLE
'Show coded text and media' error

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#90]
After the update 'Show coded text and media' in Code Text shows either the About page or the error below. I am guessing which one happens is to do with whether there is coded content to show. 

TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "C:\Other programs\QualCoder-master\qualcoder\code_text.py", line 394, in tree_menu
    self.coded_media(found)

  File "C:\Other programs\QualCoder-master\qualcoder\helpers.py", line 46, in coded_media
    title = '<span style=\"background-color:' + row[COLOR] + '\">'

TypeError: can only concatenate str (not "NoneType") to str

**Comment by ccbogel** [comment]
occurs from the blank colours imported from rqda, should be fixed now

**Comment by glocalglocal** [comment]
'Show coded text and media' now shows the About page when there are no codings to show for the selected code, or a peculiarly formatted report consisting of File: filename, Coder: codername, num1-num2File: Filename, .... 
All instances of 'File: filename' are highlighted in the code colour
'About QualCoder' is now misaligned. Not sure why the About page follows.

**Comment by ccbogel** [comment]
Thank - I will fix.

**Comment by ccbogel** [comment]
ok fixed
