### ISSUE TITLE
Qualcoder 3.4 wont run

### ISSUE THREAD

**Issue by kamalkotecha** [ccbogel/QualCoder#905]
**Describe the bug :**
<br/>
When I run py -m qualcoder , i get the following error message (screenshot attached)

**To Reproduce :**
<br/>
Ive tried installing Qualcoder 3.5 and different version of Python but still get the same error

**Expected behavior :**
<br/>
Ive installed it on another laptop and I get the GUI

**Screenshots :**
<br/>
<img width="657" alt="Screenshot 2024-04-25 161224" src="https://github.com/ccbogel/QualCoder/assets/54396686/493b4127-1880-4930-8fb1-6ec1370be4ef">

**Desktop (please complete the following information):**
 - OS:Windows 11 
 - Business 

**Additional context :**
<br/>
Can you help?

**Comment by ccbogel** [comment]
Try redound step 7 again from within the virtual environment.
that is , upgrading pip and installing all the modules. I kind of think that pyqt6 was not installed.
You could try download and run the exe file instead, as all the required modules are packed inside the exe.

This is an answer from [StackOverflow](https://stackoverflow.com/questions/73893299/dll-load-failed-while-importing-qtgui):

Uninstall all modules related to PyQt6, within the virtual environment.
`pip uninstall -y PyQt6 pyqt6-plugins PyQt6-Qt6 PyQt6-sip pyqt6-tools qt6-applications qt6-tools

Reinstall PyQt6.
`pip install PyQt6`

**Comment by kamalkotecha** [comment]
Thank you
That worked

I get the following error about vibvlc. But Qualcoder GUI still starts
Shall I just ignore it ?

***@***.***

Kamal Kotecha | Head of IT | Learning and Work Institute
e. ***@***.*** ***@***.*** > | m: |
www.learningandwork.org.uk<http://www.learningandwork.org.uk/> | @LearnWorkUK

**Comment by ccbogel** [comment]
Hi, I did not see what you posted with the libvlc error. But the main thing is QualCoder works.
If there is an issue with libvlc, it may mean that vlc is not installed or that the python-vlc module is not installed. 
That does not matter if you are only going to do analysis using text or images. So you can ignore that.

**Comment by kamalkotecha** [comment]
Brilliant.
Thank you so much for your help


Kamal Kotecha | Head of IT | Learning and Work Institute
e. ***@***.*** ***@***.*** > | m: |
www.learningandwork.org.uk<http://www.learningandwork.org.uk/> | @LearnWorkUK
