### ISSUE TITLE
UnicodeEncodeError: 'charmap' can't encode characters in position 26-27: character maps to <undefined>

### ISSUE THREAD

**Issue by ecofriiendly** [ccbogel/QualCoder#907]
**Describe the bug :**
<br/>
Project doesn't start and this is the error that appears: "UnicodeEncodeError: 'charmap' can't encode characters in position 26-27: character maps to _undefined_"

**To Reproduce :**
<br/>
When I create a project and try to open it this error appears.

**Expected behavior :**
<br/>
I expected to start a project.

**Screenshots :**
<br/>
![qualcoder](https://github.com/ccbogel/QualCoder/assets/169166054/021e270b-f9a9-48ad-9681-0e575dbf58d6)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 Pro 64bit

**Comment by ccbogel** [comment]
@ecofriiendly 
OK. I have updated the latest code which will force the recent_projects.txt file to read and write using the utf-8 character encoding. You will need to delete the existing recent_projects.txt file. It is automatically recreated when QualCoder is run.
This is located in the folder here: Users\\username\\.qualcoder

**Comment by ecofriiendly** [comment]
@ccbogel I deleted the file and tried to start a new project and received the same error. Should I have re-downloaded QualCoder from here?: https://github.com/ccbogel/QualCoder/releases/tag/3.5
Bests,

**Comment by ccbogel** [comment]
@ecofriiendly Each release will never change. I made a change to the current code, which can be downloaded as a zip from the main page. Using the Green Code button (top right hand side). You then after unzipping have to follow the manual install instructions.
With the 3.5 release version did you use the exe or the manual install method?

**Comment by ecofriiendly** [comment]
@ccbogel I did download the current code however I use the exe to download. I am not familiar with using Python. I guess then, I will not be able to update my software's code.

**Comment by ccbogel** [comment]
Well the update will be in the next exe release. 
Does it work when you simply delete that file, then run the exe.
Delete is from here: C:Users\\username\\.qualcoder\\recent_rpojects.txt

**Comment by ecofriiendly** [comment]
@ccbogel it does not, unfortunately, work like that. I look forward to the new release!
