### ISSUE TITLE
File structure on disk and backups 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#91]
QualCoder saves a *.qda file and a complete set of subfolders for audio, video, documents and images. When you only work with text (like I do) all the data are saved in the *.qda file and, for simplicity, the rest of the folders could be omitted. 

The number of backups could be optionally limited to a number specified by the user. I already have 19 backup files in less than a day (because I started the application a lot for testing). 

If I open and close a project with the backup setting on, a new identical and unnecessary copy of the previous backup file is created. 

We can of course easily delete redundant files ourselves.

**Comment by ccbogel** [comment]
I will keep the folder structure as is - it's not simple for me to omit them, as a lot of code searches through these in lots of places.
Yes when opening and closing a project, an identical copy is created. I do this because there is not undo function if you choose to code or change things once that project is opened. So its for safety.
Yes OK will look at automatically keeping only a few backups - perhaps the 3 most recent, to keep this issue manageable.

**Comment by glocalglocal** [comment]
On the identical copies, just to be clear, I understand why a new copy is created on open. But if the user doesn't edit the file and just closes it, perhaps that identical copy should be deleted on exit. It's not just about reducing clutter or elegance. If you open/close a project a few times without editing it, you may end up with lots if identical backups. If there is a max number of backups, the really useful restore point may be pushed out the other end.

**Comment by ccbogel** [comment]
Yes thats a good point that I did not think about. OK I will have to think about this one. Perhaps I can keep a variable like a yes/no for changes and then on closing the project - delete the backup if no changes have occurred.
Yes this is do-able but will take a bit of work.

**Comment by ccbogel** [comment]
OK. A backup will be created, however, on closing the project, the backup will be deleted if no changes occur. Occasionally this will not work and a backup will be kept - this will occur when viewing some memos, as it was difficult to code around whether a change had occurred within a memo.

**Comment by glocalglocal** [comment]
I see the backup is a copy of the whole folder and subfolders including irrelevant files I may have put in there. Shouldn't qualcoder only back up its own files? 

I am wondering what will happen if I delete all those empty subfolders in the main and backup folders. Will qualcoder complain and/or crash? I only ever work with text and it looks very messy that I have lots of empty folders where a single qda file would do.

**Comment by ccbogel** [comment]
Hi.You should not directly put files into the qualcoder folders - use the import files option. That way it can keep a record of original documents.
You can try deleting the empty folders - it may be OK and not crash, as it will not look through them if you only have text. However, that is the structure I have made for keeping the original files whether they be text, or other formats.  I guess you could view it in the same way as a Word document - which is a zipped folder containing sub-folders for text and images and other things.

**Comment by glocalglocal** [comment]
Not sure if replying to a closed issue is bad etiquette. Hmm. 

I know you are not supposed to fiddle with these subfolders but if there is a way users can break things, they will find it :) 

I will check stability when the empty folders are removed and I may practice my very basic python coding skills to write code that deletes empty folders before it runs qualcoder. I will most probably install qualcoder on my Linux Mint system, so there may be more issues to report later.
