### ISSUE TITLE
change branch name master to main

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#912]
may I suggest, following conversations more broadly, the switch the main branch from the name `master` to `main`?
See e.g. https://bud.agency/rename-master-branch-main-git-gitlab/

happy to provide argumentative resources :)

**Comment by ccbogel** [comment]
I think I will keep with what is done routinely in Github.

**Comment by ilippert** [comment]
> I think I will keep with what is done routinely in Github.

Lovely, as in https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/ ?

**Comment by ccbogel** [comment]
Its not a newly created repository so, master
