### ISSUE TITLE
Can't install, keep on hitting errors with python that are too complicated for me to solve, what happened to the exe ? (solved)

### ISSUE THREAD

**Issue by Arman-AI** [ccbogel/QualCoder#919]
**Is your feature request related to a problem? Please describe.**  

I remember installing this software a few months back and I was very happy with what it could do. It seems there was an update since then and now I cannot find the exe and the cmd keeps  on giving me errors related to python. I uninstalled, reistalled, restarted, even tried solving it with chatGPT but nothing worked. I have no coding background so the error code doesn't mean anything to me.

Here is the error I get:

Microsoft Windows [version 10.0.22631.3737]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\arman>cd Downloads\QualCoder-master

C:\Users\arman\Downloads\QualCoder-master>pip install virtualenv
Requirement already satisfied: virtualenv in c:\users\arman\appdata\local\programs\python\python312\lib\site-packages (20.26.2)
Requirement already satisfied: distlib<1,>=0.3.7 in c:\users\arman\appdata\local\programs\python\python312\lib\site-packages (from virtualenv) (0.3.8)
Requirement already satisfied: filelock<4,>=3.12.2 in c:\users\arman\appdata\local\programs\python\python312\lib\site-packages (from virtualenv) (3.15.0)
Requirement already satisfied: platformdirs<5,>=3.9.1 in c:\users\arman\appdata\local\programs\python\python312\lib\site-packages (from virtualenv) (4.2.2)

C:\Users\arman\Downloads\QualCoder-master>virtualenv env
RuntimeError: failed to build image pip because:
Traceback (most recent call last):
  File "C:\Users\arman\AppData\Local\Programs\Python\Python312\Lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 54, in _install
    with parent.non_reentrant_lock_for_key(wheel_img.name):
  File "C:\Users\arman\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\arman\AppData\Local\Programs\Python\Python312\Lib\site-packages\virtualenv\util\lock.py", line 142, in non_reentrant_lock_for_key
    with _CountedFileLock(str(self.path / f"{name}.lock")):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arman\AppData\Local\Programs\Python\Python312\Lib\site-packages\virtualenv\util\lock.py", line 22, in __init__
    super().__init__(lock_file)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

Exception ignored in: <function BaseFileLock.__del__ at 0x0000023BA8B54540>
Traceback (most recent call last):
  File "C:\Users\arman\AppData\Local\Programs\Python\Python312\Lib\site-packages\filelock\_api.py", line 365, in __del__
    self.release(force=True)
  File "C:\Users\arman\AppData\Local\Programs\Python\Python312\Lib\site-packages\virtualenv\util\lock.py", line 34, in release
    with self.thread_safe:
         ^^^^^^^^^^^^^^^^
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'

**Describe the solution you'd like**  
I have no idea how to solve this, could you provide an exe ? At least dont remove the old exe before creating the new one so that we, the pleb, can still use the software, I wouldn't mind using an older version as long as it works.

**Describe alternatives you've considered**  
I have considered using Taguette but Qualcoder has better features... Paid alternatives are too expensive for my budget.

**Additional context**  
I have no coding background but I believe this is the most appropriate tool for me because it is open source/free and relatively easy to use and relevant.

Thank you for your hard work in making such a tool available to us.

**Comment by Arman-AI** [comment]
Alright, after about an hour of fumbling around I managed to make it work by asking repeatedly chatGPT for solutions.

The solution was to use:
python -m venv env

Instead of:
virtualenv env

Good luck.

**Comment by ccbogel** [comment]
OK good that you solved it. That command is on step 6 for Windows of the Readme.
Also all the exes for Windows 10/11 are listed in the releases:
https://github.com/ccbogel/QualCoder/releases
