### ISSUE TITLE
Suggestion: Recent projects and default project directory 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#92]
The project menu could offer a list of recently opened projects for easy opening. Also, the user could be able to specify the default directory (or should that be 'folder' for Windows?) for projects. These two features would make locating and opening projects less frustrating. Currently, I have to navigate from the default system user folder to the folder where I keep my projects every time.

**Comment by ccbogel** [comment]
Recently opened projects list - sure will consider this.

The default directory (AKA folder) for projects. 
1 Can you set your default directory in the Settings - using the Default project directory button? Is this not working correctly for you.  
2 Maybe some of my coding for other functions is not making use of the default directory that you set.

Can you get back to me on this

**Comment by glocalglocal** [comment]
I changed the default dir in settings. This is remembered as expected. Then, Create new project takes me to the directory I set. Open Project takes me to my C:\users folder instead.

**Comment by ccbogel** [comment]
ok the default directory when Opening project should be recognised now

**Comment by glocalglocal** [comment]
I set the default folder, restarted qualcoder and it automatically opened the most recent project in the default directory but I never asked for that. I closed the project, selected Open Project. The title bar now displays 'QualCoderOpen Project' [sic] and I get the Open dialogue but it's pointing to my C:\users again. The settings info displayed in the main window still refers to my other directory as the default.

**Comment by ccbogel** [comment]
yes opening the last project is automatic. Generally use one project at a time and it works fine for many, this way.
ok will check on the default issue again - I thought i had fixed that.

**Comment by glocalglocal** [comment]
Opening the last project is not a bad idea. I was wondering if that was intentional.

**Comment by ccbogel** [comment]
fixed the default directory issue

**Comment by glocalglocal** [comment]
Yes, working now. Thanks.

**Comment by ccbogel** [comment]
recent projects list for selection of a prject is now possible

**Comment by glocalglocal** [comment]
It only shows one project, the most recent one.

**Comment by ccbogel** [comment]
Have you opened up several different qualcoder projects?
I have a list of 10 to choose from - most being various test projects

If you look in the .qualcoder folder and see how many recent projects are listed there in the recent_project.txt  file

**Comment by glocalglocal** [comment]
I have opened three projects so far, but there is always only one project listed in recent_project.txt -- the most recent one. 

I just realised you can open a project without closing the previous one. I believe the previous one is essentially closed. Then I realised you can keep dialogues for the previous project open, open a new project, and then open dialogues for the new project. Then I realised I can open multiple Code Text dialogues for the same project. Does that mean I can work, say, with two+ Code Text dialogues for the same and/or different projects at the same time? Wouldn't that cause problems? If it doesn't, perhaps each dialogue title bar should state the name of the project (eg Codes: Project1). I don't think multiple copies of the same dialogues for the same project is useful or a good idea.

**Comment by ccbogel** [comment]
Yes you can open multiple code dialogs. Although it can only be done for one project. 
 I can restrict it so that only one code dialog appears at a time.
When a project is opened, the previous project is closed.
