### ISSUE TITLE
QualCoder doesn't find VLC

### ISSUE THREAD

**Issue by mhechthz** [ccbogel/QualCoder#920]
I have VLC (as well as ffmpeg) in my path variable on Windows 11 and can start it (and ffmpeg) via commandline, so path is working. On running QualCoder 3.5 and trying to code audio/video I get the message: VLC is not installed.

What to do?

**Comment by ccbogel** [comment]
Hmm ok. This can be tricky to fix sometimes.
Firstly, make sure the VLC version is a 64 bit version, not a 32 bit version. And is VLC in a standard location for the python vlc module to find.
On my Windows 11 it is here: C:\Program Files\VideoLAN\VLC\vlc.exe
The version I am using is 3.0.20 Vetinari

Note: the qualcdoer 3.5 exe has a problem with right clicking on A/V segments and not opening menu options for the segments, but not a problem if it is installed manually.

**Comment by mhechthz** [comment]
Ok, for a reason I cannot comprehend anymore, I had the 32-bit version of VLC, even if I always take 64-bit for all programs - strange. By installing the 64-bit version, it is working now. Thank you.

**Comment by ccbogel** [comment]
Glad its working for you
Regards the remark - I am using the python-vlc module and not editing that module. I think it might 'look around' for VLC
