### ISSUE TITLE
Display of verbatim for codes in the "View Graph" Report

### ISSUE THREAD

**Issue by apar5070** [ccbogel/QualCoder#922]
### Discussed in https://github.com/ccbogel/QualCoder/discussions/921

<div type='discussions-op-text'>

<sup>Originally posted by **apar5070** June 17, 2024</sup>
As I was working in the QualCoder, as I created list of codes, sub-category and category; I was unable to present the list of verbatim for each of the codes/sub-category/category. It could also be that we could have selective verbatim to support it. Is it doable in QualCoder???</div>

**Comment by ccbogel** [comment]
I am not sure what you mean exactly.
In the view graph report there is a button (four coloured squares) to display the coded segments of text files - selecting the files, then the codes then the colour.

**Comment by ccbogel** [comment]
Closing, as no response.
