### ISSUE TITLE
Impossible to import REFI-QDA codebook

### ISSUE THREAD

**Issue by Jakcor** [ccbogel/QualCoder#934]
Hi, 
qualcoder 3.4 and 3.5 for windows
Codebook exported with the same installation as REFI-QDA qdx can't be reimported in another project.

**Comment by ccbogel** [comment]
Hi I have tested on 3.5 and on the current 3.6 code. The REFI-QDA codebook export and import works without error.

![image](https://github.com/user-attachments/assets/36612ffd-d5d0-4b50-b2f8-45f95c2ac90c)


The export file is has the .qdc ending: projectname.qdc

And to import:
![image](https://github.com/user-attachments/assets/091eccb8-58a2-4d43-9d65-b694c4e0af91)

The only other issue  I can think of is - there might be characters in the category and code names or memos, in the exported .qdc file that are causing a problem. e.g. <  or >  ?

**Comment by ccbogel** [comment]
Further testing and < and > do not cause problems in category or code names or memos.
Maybe it is due to other characters? 
Without seeing the .qdc file I cannot test it to see the proble,

**Comment by Jakcor** [comment]
Hi Colin, thanks a lot for this so quick reply.
I suppose you're right, as I work in France, I use accented characters.
I'll try to rename codes to avoid these characters.
I attached the qdc file

I very much appreciate your commitment to providing an outstanding tool to "poor" ! researchers
Very soon will I provide you with the description of our study.

Have a great day

Jacques
________________________________
De : QualCoder Developer ***@***.***>
Envoyé : dimanche 8 septembre 2024 09:34
À : ccbogel/QualCoder ***@***.***>
Cc : Jakcor ***@***.***>; Author ***@***.***>
Objet : Re: [ccbogel/QualCoder] Impossible to import REFI-QDA codebook (Issue #934)


Further testing and < and > do not cause problems in category or code names or memos.
Maybe it is due to other characters?
Without seeing the .qdc file I cannot test it to see the proble,

**Comment by ccbogel** [comment]
Hello Jakcor, 
Please attach the qdc file so I can test and improve the way the codebook export and import works.
If github is not happy with the .qdc ending change it to .txt

**Comment by Jakcor** [comment]
Here you are
[Codebook-test1.txt](https://github.com/user-attachments/files/16939704/Codebook-test1.txt)

thx
Jacques

**Comment by ccbogel** [comment]
OK. I have updated the code. This should now work with the latest 3.6 software.
Yes, the character accents in French were an issue. It was an easy fix in the code.

Alternatively, for older versions, 3.5 or 3.4, if you export a codebook.qdc file. 
Open it with Notepad. Then select 'Save As'
Ensure the encoding is 'UTF-8'
![image](https://github.com/user-attachments/assets/511667bc-eac7-4ff5-8d63-5664dced1294)

This will then import without problem into your next project.

**Comment by Jakcor** [comment]
Thanks a looooot !
Where may I find the 3.6 version?

**Comment by ccbogel** [comment]
I guess you want an exe version for Windows?
I will create one and file share with you
________________________________

**Comment by Jakcor** [comment]
Indeed, my main laptop runs windows.
I still have to install Qualcoder on my collega's linux and mac computers.
I know R but not Python.
I can collaborate to revise the French translation (which is actually great)
thx one more time

**Comment by ccbogel** [comment]
Thank you. The French translation - I used DeepL translator - online. At the moment I do not have an up to date Linux (Ubuntu) to develop the translations. I have now a Windows computer and, I am not able to create any newer translation files in Windows, but I used to be able to do this with Ubuntu. 
Can you send me an email and I can provide assistance with an up to date exe.

**Comment by Jakcor** [comment]
Sure,
jcorillon@hotmail.com

**Comment by Jakcor** [comment]
thx  Colin,
I get an error : 
Traceback (most recent call last):
  File "qualcoder\__main__.py", line 2674, in <module>
  File "qualcoder\__main__.py", line 2539, in gui
  File "qualcoder\__main__.py", line 285, in get_most_recent_projectpath
  File "qualcoder\__main__.py", line 213, in read_previous_project_paths
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 466: invalid continuation byte

![image](https://github.com/user-attachments/assets/07097bcb-d518-4e3c-9d61-1de8ff43dea2)
