### ISSUE TITLE
Colour selector and code colours 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#94]
Double-clicking on a colour in the Colour selector allows me to input text and displays the word 'colour' in the selected colour at the top. 

It would be useful to indicate in the colour selector the colour already associated with a code when you are trying to change the current colour. 

Selecting a code in the tree changes its colour and makes locating it in the text confusingly difficult. Perhaps another way to indicate the selected code that doesn't interfere with its colour would be better -- eg an arrow, a frame, bold text etc. 

In the code text dialogue I think it would be really great if selecting a code in the tree somehow made the associated coded snippets  on the right stand out (eg underlined text or something better) and vice versa -- ie clicking on the text on the right would make the associated code(s) on the left stand out. This would make a huge difference with 30+ codes where similar codes blend into each other.

**Comment by ccbogel** [comment]
The input text in the colour selector table cell - I had never noticed before - Now fixed.
OK - I prefill with the existing colour.
Selecting the code in tree changes its colour - yes and I wont be able to change this in this location, but I can change the background colour at the top of the dialog, where it shows the selected code. - Fixed enough.

The last idea of making the text stand out when selecting a code or coded text. This will be a challenge - I will think it over.

**Comment by glocalglocal** [comment]
'I prefill with the existing colour': I don't see that. When I select to change the colour, the colour selector dialogue opens and the 'colour' appears at the top against the grey background.

**Comment by ccbogel** [comment]
sorry, I was working late last night and uploaded the unedited file (9am here now). OK this is now fixed.

**Comment by glocalglocal** [comment]
It's working OK now. I think ideally there would be two colours at the top: the currently applied colour and the newly selected colour. Personally, I am happy with my colour scheme already. (it's past midnight here)

**Comment by ccbogel** [comment]
LOL, working late. Do you work for a university also?
OK will consider showing both old an new colors.

**Comment by glocalglocal** [comment]
Yes, I am an academic but things are a bit funny at the moment, social distancing and all.
