### ISSUE TITLE
install requirements chromadb==0.5.0

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#941]
**Describe the bug :**
<br/>
ERROR: Cannot install -r requirements.txt (line 20) and chromadb==0.5.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested chromadb==0.5.0
    langchain-chroma 0.1.0 depends on chromadb<0.5.0 and >=0.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

**To Reproduce :**
<br/>
in (env) installing requirements.txt
python3 -m pip install requirments.txt

**Expected behavior :**
<br/>
No conflict

**Screenshots :**
<br/>
![image](https://github.com/user-attachments/assets/bf978675-0457-457b-9e6e-b2893015261b)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by ccbogel** [comment]
Fixed by changing to:
chromadb>0.4.0

**Comment by kaixxx** [comment]
There is a problem with the current version 0.5.4 of chroma on Windows: https://github.com/chroma-core/chroma/issues/2513
To make sure that this is not used, I would suggest changing the requirements to:
`chromadb>=0.4.0,<=0.5.0`

**Comment by kaixxx** [comment]
> langchain-chroma 0.1.0 depends on chromadb<0.5.0 and >=0.4.0

In trying to solve the other problem you've got, I've realized that you are using a quite old version of langchain-chroma (0.1.0). I am using 0.1.2, the latest version is 0.1.4 (tested, works too). Chromadb 0.4.0 on the other hand gave me several issues. 
So I would suggest upgrading to langchain-chroma 0.1.2 and chromadb 0.5.0
