### ISSUE TITLE
Wiki: Info About New AI Features

### ISSUE THREAD

**Issue by kaixxx** [ccbogel/QualCoder#953]
I'm going to use this issue to track the changes I make to the wiki with regard to the newly added AI features in version 3.6.

**Comment by kaixxx** [comment]
Added the page "07b AI Assisted Coding" (renamed from: "07b Coding with AI"): 
https://github.com/ccbogel/QualCoder/wiki/07b-AI-Assisted-Coding

I had a little help from DeepL Write, so I hope my English is not too bad. 

TODO: Create a page about prompt editing and update the link on this page.

**Comment by kaixxx** [comment]
I have reorganized the wiki into a new hierarchical structure and added a table of contents to the sidebar: https://github.com/ccbogel/QualCoder/wiki The internal cross-links are adjusted accordingly; everything should work as before. 

I've also added a helper script to generate the TOC in the sidebar (which is saved in '_Sidebar.md') automatically from the filenames. The section titles are hardcoded into the script. See: https://raw.githubusercontent.com/wiki/ccbogel/QualCoder/generate_toc.py

**Comment by kaixxx** [comment]
Added info about the AI features to [Home.md](https://github.com/ccbogel/QualCoder/wiki), the landing page of the wiki.

**Comment by ccbogel** [comment]
Thats really nice, thank you. I will have to go through and edit the help URLs on the pages within the software.

**Comment by kaixxx** [comment]
Thanks. I wasn't even aware that there are individual help links within different parts of the software... But now I found the icon. I'll update the URLs tomorrow. Searching for the base URL in the source code makes them easy to find.

**Comment by kaixxx** [comment]
Added info about AI setup and data security: https://github.com/ccbogel/QualCoder/wiki/2.3.-AI-Setup

**Comment by kaixxx** [comment]
Added page about prompts and the prompt library: https://github.com/ccbogel/QualCoder/wiki/6.2.-AI-Prompt-Library

**Comment by ccbogel** [comment]
Great that will be helpful for people. I still find it fairly new to myself. I feel like I personally need to learn more about it.

**Comment by ccbogel** [comment]
I am interested in the symbols you have used in the AI chat section - the start, document, tag, etc. Where do they come from and how to enact them.

**Comment by kaixxx** [comment]
> I am interested in the symbols you have used in the AI chat section

I am using [QtAwesome](https://pypi.org/project/QtAwesome/) with the [Material Design Icons version 6](https://pictogrammers.com/library/mdi/). 

With QtAwesome, the symbols are not distributed as images, but in a font file (like the old WingDings) included in the library. This makes it very easy to package them with PyInstaller since you don't need to include any additional files, only the library.

Generating an icon is as simple as this:
```
import qtawesome as qta
icon = qta.icon('mdi6.help')  # "mdi6" is the Material Design 6 icon pack, "help" the name of the icon 
```

The icons are monochrome, but you can also add a color. I have added the function `app.highlight_color()`, which returns a color depending on the current theme (and light/dark mode). So you can do `qta.icon('mdi6.help', color=self.app.highlight_color())` to get a themed icon. 

It might be worth considering QtAwesome for other areas in QualCoder as well. The Material Design package includes over 7000 high-quality icons. Using them throughout would give QualCoder a more consistent UI (as requested here: https://github.com/ccbogel/QualCoder/issues/719).

**Comment by kaixxx** [comment]
I moved the info about creating a new project from [Settings](https://github.com/ccbogel/QualCoder/wiki/2.2.-Settings) to a new, dedicated page, [Creating a new project](https://github.com/ccbogel/QualCoder/wiki/3.1.-Creating-a-New-Project). 

The main reason was that I had to add some info about why it is important for the interaction with the AI to write a proper project memo and what information should be included there.

**Comment by kaixxx** [comment]
Added information to [Files](https://github.com/ccbogel/QualCoder/wiki/3.2.-Files) about the AI reading newly imported documents into its local memory.

**Comment by kaixxx** [comment]
Ok, that's all I wanted to do with the wiki for now. One thing is still open: Adding some technical information about the AI implementation to the "Development" page (or elsewhere). I will do that at a later date. 

Is there anything else that you want me to add to the wiki, @ccbogel? Otherwise, we can close this issue.

**Comment by ccbogel** [comment]
This is great thank you. Closing issue
