### ISSUE TITLE
Small UI issue in ui_dialog_view_text

### ISSUE THREAD

**Issue by kaixxx** [ccbogel/QualCoder#958]
**Describe the bug :**
![grafik](https://github.com/user-attachments/assets/e5fa7c52-876f-4f9e-ad81-78c06cc9d2cf)
There is some kind of widget on the top left behind the main text edit, which is probably not supposed to be there. Is this for the search feature?

**To Reproduce :**
Manage > files > view text

**Expected behavior :**
clean ui

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context :**
QualCoder 3.6, directly from source

**Comment by ccbogel** [comment]
Ah yes. I made a change the othe day to a widget, I didnt think it would affect the presentation.  I will fix that as soon as I can

**Comment by ccbogel** [comment]
fixed
