### ISSUE TITLE
code tree frequencies 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#97]
Could the code tree show frequencies for the text displayed in that window? The user may have to scroll the tree pane to see the memo and freq column, but that's even better -- out of view until needed.

**Comment by ccbogel** [comment]
done

**Comment by glocalglocal** [comment]
And we can swap Memo and Count around. Nice! It would be even better if we could change the width of the columns eg to truncate the names of codes if so desired. Not crucial of course.

**Comment by glocalglocal** [comment]
Similarly, why not show the frequencies column in the codlings report dialogue. Also, I am not sure how the code ID column is useful there, except for analysing the SQL data elsewhere.

**Comment by ccbogel** [comment]
Yes will add frequencies to coding report.
Code ids should be visible or not depending on the settings. If always visible, i will fix.
Re changing column widths,  will look into it and see if i can make thrm adjustable.

**Comment by glocalglocal** [comment]
IDs: They are always visible. So, that's what that tick box is supposed to do.

**Comment by ccbogel** [comment]
done

**Comment by glocalglocal** [comment]
I swap the memo and frequencies columns and this is not remembered. If possible I would want to make this change (and width setups when/if implemented) permanent and global across projects and dialogues.

**Comment by ccbogel** [comment]
This might be quite challenging, but will keep it in mind
