### ISSUE TITLE
Rich text/document formats

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#99]
Probably too difficult, but just in case, it would be useful to allow some simple text formatting in the text. Bold, underline etc can be semantically important -- eg emphasis in an interview or document. 

Incidentally, why wouldn't qualcoder import RTF and html?

**Comment by ccbogel** [comment]
I think RTF is uncommon now. That then means I have to find a conversion library for a proprietary format to make it plain text. I think the end user can do this themselves before importing. I can do so much but not wanting to do too much.
html is a bit complicated - particularly if there are lots of divs and positioning. e.g. from a webpage. But I can look for html to text code.

**Comment by ccbogel** [comment]
I actually forgot -  the ability to import text from html is there - if you download a page with a .htm or .html ending and import the file.
I will have to update the manual on this.
